using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine.SceneManagement;using TMPro;using IndianOceanAssets.ShooterSurvival;using Object=UnityEngine.Object;
public static class ApplyStreetDetail {
 const string ScenePath="Assets/ShooterSurvival/Scenes/Tools/Jamsil.unity",Models="Assets/ShooterSurvival/Prefabs/MeshyRestStop20260925/",Mall="Assets/ShooterSurvival/Models/Chapters/Chapters45/DetailedMall-20261003T092859667/";
 static Chapter45Director d;static Transform root,archive;static string assets;static TMP_FontAsset font;static Material ink,ivory,metal,amber;static EnemySO enemyData;static int actorNumber;static List<Chapter45Encounter> encounters;static List<Chapter45Hazard> hazards;
 static Transform Group(Transform p,string n){var g=new GameObject(n);g.transform.SetParent(p,false);return g.transform;}
 static GameObject Primitive(Transform p,string n,PrimitiveType type,Vector3 pos,Vector3 scale,Material m,bool trigger=false){var g=GameObject.CreatePrimitive(type);g.name=n;g.transform.SetParent(p,false);g.transform.localPosition=pos;g.transform.localScale=scale;g.GetComponent<Renderer>().sharedMaterial=m;g.GetComponent<Renderer>().shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;if(trigger)g.GetComponent<Collider>().isTrigger=true;else Object.DestroyImmediate(g.GetComponent<Collider>());return g;}
 static GameObject Model(Transform p,string id,Vector3 pos,float height,float yaw=0){var src=AssetDatabase.LoadAssetAtPath<GameObject>(Models+id+".prefab");if(src==null)throw new Exception("Missing existing model "+id);var g=(GameObject)PrefabUtility.InstantiatePrefab(src);g.transform.SetParent(p,false);g.transform.localPosition=Vector3.zero;g.transform.localRotation=Quaternion.Euler(0,yaw,0);var rr=g.GetComponentsInChildren<Renderer>(true).Where(x=>!(x is TrailRenderer)).ToArray();var b=rr[0].bounds;foreach(var x in rr)b.Encapsulate(x.bounds);g.transform.localScale*=height/Mathf.Max(.01f,b.size.y);b=rr[0].bounds;foreach(var x in rr)b.Encapsulate(x.bounds);var offset=p.InverseTransformVector(new Vector3(g.transform.position.x-b.center.x,g.transform.position.y-b.min.y,g.transform.position.z-b.center.z));g.transform.localPosition=pos+offset;foreach(var c in g.GetComponentsInChildren<Collider>(true))c.enabled=false;foreach(var a in g.GetComponentsInChildren<Animator>(true)){var ctrl=AssetDatabase.LoadAssetAtPath<RuntimeAnimatorController>(Mall+"Animation/"+id+".controller");if(ctrl!=null)a.runtimeAnimatorController=ctrl;a.applyRootMotion=false;}return g;}
 static void Place(Transform t,float distance,float lane=0,int branch=-1){d.route.Sample(distance,out var p,out var f);if(branch>=0)lane+=d.choices[0].Offset(distance,branch);t.SetPositionAndRotation(p+Vector3.Cross(Vector3.up,f)*lane,Quaternion.LookRotation(f));}
 static EnemyScript_space Actor(Chapter45Encounter e,string id,float at,float lane,Chapter45RoleAction.Role role,int index,int branch=-1){var g=Group(e.transform,"Street role "+actorNumber++ +" "+role);Place(g,at,lane,branch);g.position+=Vector3.up*.05f;g.rotation*=Quaternion.Euler(0,180,0);g.gameObject.tag="EnemyTag";Model(g,id,Vector3.zero,1.8f);Group(g,"Walker-HitPos").localPosition=Vector3.up*1.1f;var col=g.gameObject.AddComponent<CapsuleCollider>();col.center=Vector3.up*.9f;col.height=1.8f;col.radius=.42f;col.isTrigger=true;g.gameObject.AddComponent<AudioSource>().playOnAwake=false;var combat=g.gameObject.AddComponent<EnemyScript_space>();var so=new SerializedObject(combat);so.FindProperty("enemyData").objectReferenceValue=enemyData;so.ApplyModifiedPropertiesWithoutUndo();combat.ConfigureRewards(false,3);g.gameObject.AddComponent<Chapter45Deck>().floor=0;var evt=g.gameObject.AddComponent<EnemyEventController>();evt.HideWhileWaiting=false;evt.enabled=false;var b=g.gameObject.AddComponent<Chapter45RoleAction>();b.role=role;b.encounter=e;b.director=d;b.actionDamage=role==Chapter45RoleAction.Role.Preacher?3:2;b.cooldown=4.2f;b.moveSpeed=role==Chapter45RoleAction.Role.PhoneShopper?1.8f:2.3f;b.phaseOffset=index*.6f;
  var mark=Primitive(root,g.name+" warned action",PrimitiveType.Cylinder,Vector3.zero,new Vector3(2.5f,.012f,2.5f),amber);mark.SetActive(false);b.warningMarker=mark.transform;
  b.warningText=role==Chapter45RoleAction.Role.Preacher?"예수를 믿으세요! · 뻗는 손을 피하세요":role==Chapter45RoleAction.Role.Promoter?"시향지와 명함을 뿌립니다 · 빈 틈으로 피하세요":"촬영하는 손님 사이를 지나가세요";
  if(role==Chapter45RoleAction.Role.PhoneShopper){var phone=Primitive(g,"Provisional phone action prop",PrimitiveType.Cube,new Vector3(-.32f,1.3f,.3f),new Vector3(.09f,.17f,.018f),ink);Primitive(phone.transform,"Phone screen",PrimitiveType.Cube,new Vector3(0,0,-.55f),new Vector3(.8f,.85f,.04f),ivory);b.heldProp=phone.transform;}
  if(role==Chapter45RoleAction.Role.Promoter){var card=Primitive(g,"Inactive sample card projectile",PrimitiveType.Cube,new Vector3(.4f,1.2f,.2f),new Vector3(.24f,.13f,.012f),ivory,true);card.AddComponent<SimpleProjectile>();card.SetActive(false);b.projectileTemplate=card;b.heldProp=Primitive(g,"Provisional sample cards",PrimitiveType.Cube,new Vector3(.4f,1.2f,.2f),new Vector3(.24f,.13f,.04f),ivory).transform;}
  g.gameObject.SetActive(false);return combat;
 }
 static void Replace(Chapter45Encounter e,Chapter45RoleAction.Role role,string[] models,float hp,string label){float at=e.stopDistance+9;int branch=e.choiceIndex<0?-1:e.requiredChoice;foreach(var old in e.actors){old.gameObject.SetActive(false);old.transform.SetParent(archive,true);}e.health=hp;e.damage=2;e.statPrefix="c4_detail_"+role;e.announcement=label;e.coinReward=3;e.requiredToProceed=false;e.actors=models.Select((id,i)=>Actor(e,id,at,(i-(models.Length-1)*.5f)*2.2f,role,i,branch)).ToArray();}
 static Chapter45Encounter Queue(float at){var e=Group(root,"Left shopping queue "+at).gameObject.AddComponent<Chapter45Encounter>();e.activationDistance=at-35;e.stopDistance=at-7;e.floor=0;e.choiceIndex=0;e.requiredChoice=0;e.health=8;e.damage=2;e.statPrefix="c4_left_queue";e.coinReward=2;e.announcement="사람이 많은 쇼핑 골목";e.actors=Enumerable.Range(0,6).Select(i=>Actor(e,i%2==0?"A05_student":"A02_mom",at+(i/3)*7,(i%3-1)*2.2f,Chapter45RoleAction.Role.PhoneShopper,i,0)).ToArray();encounters.Add(e);return e;}
 static Chapter45Hazard Hazard(string n,float at,float lane,Vector3 size,Vector3 from,Vector3 to,float warningTime,float operation,float dwell,string label,int branch=-1,bool fatal=false,bool hole=false){var t=Group(root,n);Place(t,at,0,branch);var h=t.gameObject.AddComponent<Chapter45Hazard>();h.distance=at;h.floor=0;h.warningDistance=30;h.warningSeconds=warningTime;h.operationSeconds=operation;h.lingerSeconds=dwell;h.choiceIndex=branch<0?-1:0;h.requiredChoice=branch;h.safeLane=lane>=0?-2.8f:2.8f;h.safeHalfWidth=1.4f;h.damageFraction=.06f;h.fatalContact=fatal;h.fallIntoHole=hole;h.damageCause=hole?PlayerDamageCause.Hole:fatal?PlayerDamageCause.Roadblock:PlayerDamageCause.Traffic;h.warning=label;h.sweepFrom=from;h.sweepTo=to;var body=Group(t,n+" moving collision body");body.localPosition=new Vector3(lane,hole ? .08f : 1,0);var c=body.gameObject.AddComponent<BoxCollider>();c.size=size;c.isTrigger=true;h.body=body;h.footprint=Primitive(t,n+" warning footprint",PrimitiveType.Cylinder,new Vector3(lane,.035f,0),new Vector3(size.x+1,.015f,size.z+1),amber);hazards.Add(h);return h;}
 static void Bike(Chapter45Hazard h,bool kickboard){var p=h.body;Primitive(p,"Provisional vehicle frame",PrimitiveType.Cube,new Vector3(0,-.4f,0),new Vector3(.42f,.18f,1.5f),metal);foreach(float z in new[]{-.6f,.6f})Primitive(p,"Provisional wheel",PrimitiveType.Cylinder,new Vector3(0,-.7f,z),new Vector3(.4f,.08f,.4f),ink).transform.localRotation=Quaternion.Euler(0,0,90);Primitive(p,"Provisional handle stem",PrimitiveType.Cube,new Vector3(0,.2f,.55f),new Vector3(.07f,1.2f,.07f),metal);Primitive(p,"Provisional handlebar",PrimitiveType.Cube,new Vector3(0,.8f,.55f),new Vector3(.65f,.05f,.06f),ink);if(!kickboard)Primitive(p,"Provisional delivery box",PrimitiveType.Cube,new Vector3(0,.05f,-.65f),new Vector3(.7f,.75f,.7f),ivory);var rider=Model(p,"A05_student",new Vector3(0,-.4f,0),1.65f);foreach(var a in rider.GetComponentsInChildren<Animator>(true))a.enabled=false;}
 static int Stores(){var accepted=d.transform.Find("Scenery/Jamsil_ReferenceStreet_20261002");if(accepted==null)throw new Exception("Existing Astra street missing");var bays=accepted.GetComponentsInChildren<Transform>(true).Where(t=>t.name.StartsWith("Shop bay")&&t.gameObject.activeInHierarchy).ToArray();string[] names={"오늘커피","라임케어 · DRUG STORE","온길부동산","벙커버거","하루24 편의점","모노웨어","불빛떡볶이","데일리 라이프"};int changed=0;
  foreach(var bay in bays){int index=changed%names.Length;foreach(var sign in bay.GetComponentsInChildren<TMP_Text>(true)){sign.font=font;sign.fontSharedMaterial=font.material;sign.text=sign.transform.parent==bay?names[index]:index switch{0=>"COFFEE",1=>"CARE",2=>"부동산",3=>"BURGER",4=>"24",6=>"떡볶이",_=>"SHOP"};}
   if(index==4)Model(bay,"I02_drink_fridge",new Vector3(-2,0,0),1.9f);if(index==6)Model(bay,"P03_fishcake_stall",new Vector3(0,0,0),2.2f);changed++;
  }return changed;
 }
 public static object Main(){if(EditorApplication.isPlayingOrWillChangePlaymode||EditorApplication.isCompiling)throw new Exception("Idle required");for(int i=0;i<SceneManager.sceneCount;i++)if(SceneManager.GetSceneAt(i).isDirty)throw new Exception("Dirty scene");EditorSceneManager.OpenScene(ScenePath);d=Object.FindFirstObjectByType<Chapter45Director>();if(d.transform.Find("DetailedStreet_20261003")!=null)throw new Exception("Already applied");File.Copy(ScenePath,"outputs/chapter45-detailed-design-2026-10-03/scene-recovery/Jamsil-before-detail.unity",false);assets="Assets/ShooterSurvival/Models/Chapters/Chapters45/DetailedStreet-"+DateTime.UtcNow.ToString("yyyyMMddTHHmmssfff");Directory.CreateDirectory(assets);AssetDatabase.Refresh();AssetDatabase.CopyAsset(Mall+"DetailedMall font.asset",assets+"/Street detail font.asset");font=AssetDatabase.LoadAssetAtPath<TMP_FontAsset>(assets+"/Street detail font.asset");font.atlasPopulationMode=AtlasPopulationMode.Dynamic;string missing;font.TryAddCharacters("오늘커피라임케어온길부동산벙커버거하루편의점모노웨어불빛떡볶이데일리라이프DRUG STORECAREBURGERCOFFEE24SHOP0123456789 ·",out missing);font.atlasPopulationMode=AtlasPopulationMode.Static;AssetDatabase.SaveAssetIfDirty(font);
  ink=AssetDatabase.LoadAssetAtPath<Material>(Mall+"Ink graphite.mat");ivory=AssetDatabase.LoadAssetAtPath<Material>(Mall+"Porcelain.mat");metal=AssetDatabase.LoadAssetAtPath<Material>(Mall+"Satin champagne metal.mat");amber=AssetDatabase.LoadAssetAtPath<Material>(Mall+"Warning amber.mat");enemyData=AssetDatabase.LoadAssetAtPath<EnemySO>(AssetDatabase.GUIDToAssetPath("540a5d24ed1af08488d38a3679c240cb"));root=Group(d.transform,"DetailedStreet_20261003");archive=Group(d.transform,"Preserved pre-detail street actors and hazards");archive.gameObject.SetActive(false);encounters=d.GetComponentsInChildren<Chapter45Encounter>(true).Where(e=>e.gameObject.activeInHierarchy).ToList();hazards=d.hazards.ToList();actorNumber=0;
  foreach(var e in encounters){if(e.name.StartsWith("RiskRouteGuards")){Replace(e,Chapter45RoleAction.Role.PhoneShopper,new[]{"A05_student"},8,"차량 많은 길 · 빠르게 통과하세요");continue;}int at; if(!e.name.StartsWith("Encounter_")||!int.TryParse(e.name.Substring(10),out at)||at<215||at>=1570)continue;var role=at==315||at==1050?Chapter45RoleAction.Role.Preacher:at==420||at==1130?Chapter45RoleAction.Role.Promoter:Chapter45RoleAction.Role.PhoneShopper;var ids=role==Chapter45RoleAction.Role.Preacher?new[]{"A01_dad"}:role==Chapter45RoleAction.Role.Promoter?new[]{"A05_student"}:new[]{"A05_student","A02_mom"};Replace(e,role,ids,role==Chapter45RoleAction.Role.PhoneShopper?8:16,role==Chapter45RoleAction.Role.Preacher?"낯선 전도자가 손을 뻗습니다":role==Chapter45RoleAction.Role.Promoter?"향수 샘플과 명함을 피하세요":"놀란 손님들이 휴대폰을 꺼냅니다");}
  Queue(630);Queue(720);var fork=d.choices[0];fork.leftName="쇼핑 인파 골목";fork.rightName="택시·배달 골목";fork.riskDescription="사람 적음 · 차량 많음";fork.riskAttackPercent=10;fork.coinReward=120;fork.coinKey="c4_detail_riskCoins";
  foreach(var old in hazards.Where(h=>h.choiceIndex==0&&h.requiredChoice==1).ToArray()){hazards.Remove(old);old.transform.SetParent(archive,true);old.gameObject.SetActive(false);}
  var hole=Hazard("Open manhole",1085,1.8f,new Vector3(2.1f,.4f,2.1f),Vector3.zero,Vector3.zero,1.5f,.5f,15,"열린 맨홀 · 검은 구멍을 피하세요",-1,true,true);Primitive(hole.body,"Open dark void",PrimitiveType.Cylinder,Vector3.zero,new Vector3(2.1f,.025f,2.1f),ink);Primitive(hole.body,"Displaced manhole cover",PrimitiveType.Cylinder,new Vector3(1.7f,.12f,.5f),new Vector3(1.8f,.07f,1.8f),metal).transform.localRotation=Quaternion.Euler(0,0,25);
  var rebar=Hazard("Falling rebar shadow",1360,1.7f,new Vector3(2,3.8f,1.4f),new Vector3(0,10,0),Vector3.zero,2.2f,.65f,3,"철근 낙하 · 그림자가 없는 왼쪽으로",-1,true);for(int i=0;i<5;i++)Primitive(rebar.body,"Rebar bundle",PrimitiveType.Cylinder,new Vector3((i-2)*.32f,.7f,0),new Vector3(.085f,2,.085f),metal);
  var kick=Hazard("Wrong way kickboard",940,-1.3f,new Vector3(1,2.2f,1.8f),new Vector3(0,0,13),new Vector3(0,0,-13),1.5f,3,0,"역주행 킥보드 · 오른쪽으로 피하세요");kick.body.localRotation=Quaternion.Euler(0,180,0);Bike(kick,true);
  foreach(float at in new[]{650f,735f,1180f}){int branch=at<800?1:-1;var bike=Hazard("Side delivery motorcycle "+at,at,1.4f,new Vector3(1,2.2f,2),new Vector3(7,0,0),new Vector3(-.2f,0,0),1.6f,1.8f,.8f,"배달 오토바이 진입 · 왼쪽 차로가 열려 있습니다",branch);Bike(bike,false);}
  foreach(float at in new[]{610f,695f,775f}){var taxi=Hazard("Risk route taxi "+at,at,1.7f,new Vector3(2.1f,1.5f,4),new Vector3(6,0,0),new Vector3(-.1f,0,0),1.6f,1.8f,.8f,"골목 택시 진입 · 왼쪽 빈 차로로",1);Model(taxi.body,"V07_taxi",new Vector3(0,-.7f,0),1.5f);}
  int shops=Stores();d.encounters=encounters.OrderBy(e=>e.activationDistance).ToArray();d.hazards=hazards.ToArray();d.useExplicitRegistrations=true;if(d.goals.Length==0)d.goals=d.GetComponentsInChildren<Chapter45Goal>(true).Where(g=>g.gameObject.activeInHierarchy).ToArray();if(d.lifts.Length==0)d.lifts=d.GetComponentsInChildren<Chapter45Lift>(true).Where(g=>g.gameObject.activeInHierarchy).ToArray();EditorSceneManager.MarkSceneDirty(d.gameObject.scene);if(!EditorSceneManager.SaveScene(d.gameObject.scene))throw new Exception("Save failed");return new{assets,encounters=d.encounters.Length,roleActors=actorNumber,hazards=d.hazards.Select(h=>h.name).ToArray(),shops,missingFontCharacters=missing,oldActorArchive=archive.name,routeLength=d.route.Length,goals=d.goals.Length,targets=d.targets.Length,art="Existing verified Meshy actors reused provisionally; phone/cards/kickboard/motorcycle are authored action proxies. Paid role bodies/motions and final vehicle art pending. No new paid generation.",generation="Two earlier new local TRELLIS environment models remain applied in Ch5"};
 }
}
