using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEngine.Rendering;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine.SceneManagement;using TMPro;using IndianOceanAssets.ShooterSurvival;using Object=UnityEngine.Object;
public static class ApplyContent16 {
 const string Q="outputs/chapter45-detailed-design-2026-10-03/validation-cycle16/", Art="Assets/ShooterSurvival/Models/Chapters/Chapters45/Content20261004Cycle16",Owner="ContentCycle16";
 static string Json(object v)=>(string)AppDomain.CurrentDomain.GetAssemblies().First(a=>a.GetName().Name=="Newtonsoft.Json").GetType("Newtonsoft.Json.JsonConvert").GetMethod("SerializeObject",new[]{typeof(object)}).Invoke(null,new[]{v});
 static string P(Transform t)=>t.parent==null?t.name:P(t.parent)+"/"+t.name;
 static Transform G(Transform p,string n){var t=new GameObject(n).transform;t.SetParent(p,false);return t;}
 static bool In(Vector3 p)=>p.x>=-6.65f&&p.x<=6.65f&&p.y>=-.1f&&p.y<=18&&p.z>=-1.5f&&p.z<=6.6f;
 static string State(Scene scene){var records=new List<string>();foreach(var c in scene.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Component>(true))){if(c==null||P(c.transform).Contains(Owner))continue;if(!(c is Collider||c is Rigidbody||c is Camera||c is MonoBehaviour&&!(c is TMP_Text)))continue;var it=new SerializedObject(c).GetIterator();var f=new List<string>();bool descend=true;while(it.Next(descend)){descend=it.propertyType==SerializedPropertyType.Generic;if(c is Chapter45RoleAction&&c.name=="Actor 23 A01_dad"&&it.propertyPath=="projectileOrigin")continue;f.Add(it.propertyPath+"="+(it.propertyType==SerializedPropertyType.ObjectReference?(it.objectReferenceValue==null?"null":GlobalObjectId.GetGlobalObjectIdSlow(it.objectReferenceValue).ToString()):it.propertyType==SerializedPropertyType.Generic?"":it.propertyType==SerializedPropertyType.Float?it.doubleValue.ToString("R"):it.propertyType==SerializedPropertyType.Integer?it.longValue.ToString():it.propertyType==SerializedPropertyType.Boolean?it.boolValue.ToString():it.propertyType==SerializedPropertyType.String?it.stringValue:it.propertyType==SerializedPropertyType.Enum?it.intValue.ToString():it.propertyType==SerializedPropertyType.Vector3?it.vector3Value.ToString("R"):it.propertyType==SerializedPropertyType.Vector2?it.vector2Value.ToString("R"):it.propertyType==SerializedPropertyType.Quaternion?it.quaternionValue.ToString("R"):it.propertyType.ToString()));}records.Add(P(c.transform)+":"+c.GetType().Name+":"+c.transform.localToWorldMatrix.ToString("R")+":"+string.Join("|",f));}return string.Join("\n",records.OrderBy(x=>x,StringComparer.Ordinal));}
 static List<(Mesh mesh,Material mat)> Extract(Transform scope,Transform origin,string label){var result=new List<(Mesh,Material)>();int n=0;foreach(var filter in scope.GetComponentsInChildren<MeshFilter>(true)){var source=filter.sharedMesh;if(source==null)continue;var matrix=origin.worldToLocalMatrix*filter.transform.localToWorldMatrix;var sourceV=source.vertices;var sourceN=source.normals;var sourceUV=source.uv;var vs=sourceV.Select(matrix.MultiplyPoint3x4).ToArray();for(int s=0;s<source.subMeshCount;s++){var st=source.GetTriangles(s);var keep=new List<int>();for(int i=0;i<st.Length;i+=3)if(In(vs[st[i]])&&In(vs[st[i+1]])&&In(vs[st[i+2]]))keep.AddRange(new[]{st[i],st[i+1],st[i+2]});if(keep.Count==0)continue;var map=new Dictionary<int,int>();var v=new List<Vector3>();var norm=new List<Vector3>();var uv=new List<Vector2>();var tr=new List<int>();foreach(int k in keep){if(!map.TryGetValue(k,out int j)){j=v.Count;map.Add(k,j);v.Add(vs[k]);norm.Add(matrix.inverse.transpose.MultiplyVector(sourceN[k]).normalized);uv.Add(sourceUV.Length==sourceV.Length?sourceUV[k]:Vector2.zero);}tr.Add(j);}var mesh=new Mesh{name=label+" copied part "+n};mesh.SetVertices(v);mesh.SetNormals(norm);mesh.SetUVs(0,uv);mesh.SetTriangles(tr,0);mesh.RecalculateBounds();AssetDatabase.CreateAsset(mesh,Art+"/"+label+"-"+(n++)+".asset");result.Add((mesh,filter.GetComponent<Renderer>().sharedMaterials[s]));}}if(result.Sum(x=>x.Item1.triangles.Length)<300)throw new Exception("Empty extraction "+label);return result;}
 static object Street(Chapter45Director d){var root=G(d.transform.Find("Scenery"),Owner+" shopping fork infill");var hero=d.transform.Find("Scenery/EnvironmentArt_20261003/Hero storefront architecture v2");var shops=d.transform.Find("Scenery/Jamsil_ReferenceStreet_20261002").GetComponentsInChildren<Transform>(true).Where(t=>t.name.StartsWith("Shop bay ")).ToArray();var ids=new[]{22,24,27};var sources=ids.Select(id=>hero.Cast<Transform>().Single(t=>t.name.StartsWith("Hero "+id+" type "))).ToArray();var modules=sources.Select((t,i)=>Extract(hero,t,"ReusedHero"+ids[i])).ToArray();var placements=new List<object>();
 for(int i=0;i<21;i++){float station=571.2f+i*12.8f;int family=i%3;var t=G(root,"Reused shop "+i+" source "+ids[family]);d.route.Sample(station,out var pos,out var forward);var right=Vector3.Cross(Vector3.up,forward);t.SetPositionAndRotation(pos-right*32,Quaternion.LookRotation(forward)*Quaternion.Euler(0,-90,0));var visibility=t.gameObject.AddComponent<Chapter45SceneryGroup>();visibility.floor=0;visibility.startDistance=station-6.4f;visibility.endDistance=station+6.4f;
 foreach(var part in modules[family]){var f=G(t,part.mesh.name);f.gameObject.AddComponent<MeshFilter>().sharedMesh=part.mesh;var r=f.gameObject.AddComponent<MeshRenderer>();r.sharedMaterial=part.mat;r.shadowCastingMode=ShadowCastingMode.Off;}
 var label=shops[ids[family]].GetComponentsInChildren<TMP_Text>(true).Last();var copy=Object.Instantiate(label.gameObject,t,false);copy.name="Reused storefront sign";copy.transform.localPosition=label.transform.localPosition;copy.transform.localRotation=label.transform.localRotation;copy.transform.localScale=label.transform.localScale;
 placements.Add(new{station,source=P(sources[family]),position=t.position.ToString("R"),renderers=t.GetComponentsInChildren<Renderer>(true).Length,triangles=modules[family].Sum(x=>x.mesh.triangles.Length/3),offset=32f});}
 if(root.GetComponentsInChildren<Collider>(true).Length!=0)throw new Exception("Decorative collider");return new{shops=placements,sourceMeshesUnchanged=true,reusedModules=3,addedColliders=0,minimumFacadeOffset=30.5f,branchHalfWidth=3.5f,maximumBranchOffset=18f};}
 static object Queue(Chapter45Director d){var actor=d.transform.Find("DetailedMall_20261003/B1 식당 대기줄/Actor 23 A01_dad");var role=actor.GetComponent<Chapter45RoleAction>();if(role.role!=Chapter45RoleAction.Role.CalledQueue)throw new Exception("Wrong role");var old=actor.Cast<Transform>().Single(t=>t.name=="Generated role CH09 CalledQueue");var archive=G(d.transform,Owner+" preserved queue visual");archive.gameObject.SetActive(false);old.SetParent(archive,true);old.gameObject.SetActive(false);
 string path="Assets/ShooterSurvival/Models/Chapters/Chapters45/DetailedCharacters20261003/CH05/";var visual=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>(path+"CH05.prefab"),actor);visual.name="Generated role CH05 CalledQueue reused Cycle16";var animator=visual.GetComponentInChildren<Animator>(true);animator.runtimeAnimatorController=AssetDatabase.LoadAssetAtPath<RuntimeAnimatorController>(path+"character.controller");var hand=animator.GetComponentsInChildren<Transform>(true).Single(t=>t.name=="RightHand");role.projectileOrigin=G(hand,"Role projectile release");if(actor.GetComponentsInChildren<Animator>(true).Length!=1||visual.GetComponentsInChildren<Collider>(true).Length!=0)throw new Exception("Rig contract changed");return new{actor=P(actor),from="CH09",to="CH05",newPaidRequests=0,ownRigReused=true,oldVisualPreservedOutsideActor=true,projectileOriginRebound=true,queueRoleUnchanged=true};}
 public static object Main(string sceneName){if(sceneName!="Jamsil"&&sceneName!="ShoeTower")throw new Exception("Scene scope");if(EditorApplication.isPlayingOrWillChangePlaymode||EditorApplication.isCompiling)throw new Exception("Idle required");for(int i=0;i<SceneManager.sceneCount;i++)if(SceneManager.GetSceneAt(i).isDirty)throw new Exception("Dirty scene");string output=Q+sceneName+"-content-installation.json";if(File.Exists(output))throw new Exception("Already recorded");var setup=EditorSceneManager.GetSceneManagerSetup();try{var scene=EditorSceneManager.OpenScene("Assets/ShooterSurvival/Scenes/Tools/"+sceneName+".unity");var d=Object.FindFirstObjectByType<Chapter45Director>();if(d.GetComponentsInChildren<Transform>(true).Any(t=>t.name.StartsWith(Owner)))throw new Exception("Already applied");string before=State(scene);File.WriteAllText(Q+sceneName+"-protected-before.txt",before);Directory.CreateDirectory(Art);AssetDatabase.Refresh();var result=sceneName=="Jamsil"?Street(d):Queue(d);string after=State(scene);File.WriteAllText(Q+sceneName+"-protected-pending.txt",after);if(before!=after)throw new Exception("Protected configuration changed; review before save");EditorSceneManager.MarkSceneDirty(scene);if(!EditorSceneManager.SaveScene(scene))throw new Exception("Save failed");scene=EditorSceneManager.OpenScene(scene.path);after=State(scene);File.WriteAllText(Q+sceneName+"-protected-after.txt",after);if(before!=after)throw new Exception("Reopen protected state differs");var report=new{scene=sceneName,saved=true,protectedComponentsUnchanged=true,details=result,utc=DateTime.UtcNow};File.WriteAllText(output,Json(report));return report;}finally{EditorSceneManager.RestoreSceneManagerSetup(setup);}}
}
