using System;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine.SceneManagement;using IndianOceanAssets.ShooterSurvival;using Object=UnityEngine.Object;
public static class AuditReleaseAssets {
 const string Characters="Assets/ShooterSurvival/Models/Chapters/Chapters45/DetailedCharacters20261003/";
 public static object Main(){if(EditorApplication.isPlayingOrWillChangePlaymode||EditorApplication.isCompiling)throw new Exception("Idle required");for(int i=0;i<SceneManager.sceneCount;i++)if(SceneManager.GetSceneAt(i).isDirty)throw new Exception("Dirty scene");var setup=EditorSceneManager.GetSceneManagerSetup();var scenes=new List<object>();var prefabs=new List<object>();
  try{foreach(string name in new[]{"Jamsil","ShoeTower"}){var scene=EditorSceneManager.OpenScene("Assets/ShooterSurvival/Scenes/Tools/"+name+".unity");var d=Object.FindFirstObjectByType<Chapter45Director>();var actors=d.encounters.SelectMany(e=>e.actors).Distinct().ToArray();var roles=actors.Select(a=>a.GetComponent<Chapter45RoleAction>()).Where(r=>r!=null).ToArray();var props=roles.SelectMany(r=>r.GetComponentsInChildren<Chapter45HandProps>(true)).ToArray();if(props.Any(p=>p.GetComponentsInChildren<Collider>(true).Length>0))throw new Exception("Hand prop collision");if(actors.Any(a=>a.GetComponentsInChildren<Animator>(true).Length!=1))throw new Exception("Ambiguous actor Animator");int ownActors=actors.Count(a=>a.GetComponentsInChildren<Animator>(true).Any(b=>AssetDatabase.GetAssetPath(b.runtimeAnimatorController).StartsWith(Characters)));var camera=Camera.main;var stable=camera.GetComponent<StableGameplayCamera>();var meshes=d.GetComponentsInChildren<MeshFilter>(true);var towel=meshes.Where(m=>AssetDatabase.GetAssetPath(m.sharedMesh).Contains("RetailTowelMeshy")).ToArray();scenes.Add(new{scene=name,routeMetres=d.route.Length,routeSegments=d.route.segments.Length,floors=d.route.segments.Select(s=>s.floor).Distinct().ToArray(),encounters=d.encounters.Length,actors=actors.Length,ownRigActors=ownActors,roles=roles.Length,handProps=props.Length,handPropColliders=props.Sum(p=>p.GetComponentsInChildren<Collider>(true).Length),couples=d.GetComponentsInChildren<Chapter45CouplePose>(true).Length,riders=d.GetComponentsInChildren<Chapter45RiderPose>(true).Length,lifts=d.lifts.Length,escalators=d.lifts.Count(l=>l.escalator),goals=d.goals.Length,hazards=d.hazards.Length,ownRigAnimators=d.GetComponentsInChildren<Animator>(true).Count(a=>a.runtimeAnimatorController!=null&&AssetDatabase.GetAssetPath(a.runtimeAnimatorController).StartsWith(Characters)&&a.gameObject.activeInHierarchy),cameraOffset=new[]{stable.yawRelativeOffset.x,stable.yawRelativeOffset.y,stable.yawRelativeOffset.z},camera.fieldOfView,camera.useOcclusionCulling,activeTowelMeshRenderers=towel.Count(t=>t.gameObject.activeInHierarchy),preservedTowelMeshRenderers=towel.Count(t=>!t.gameObject.activeInHierarchy),scene.isDirty});}
  }finally{EditorSceneManager.RestoreSceneManagerSetup(setup);}
  foreach(string id in new[]{"CH01","CH02","CH03","CH04R","CH05","CH06R","CH07","CH08","CH09","CH10"}){var prefab=AssetDatabase.LoadAssetAtPath<GameObject>(Characters+id+"/"+id+".prefab");var a=prefab.GetComponentInChildren<Animator>(true);var skins=prefab.GetComponentsInChildren<SkinnedMeshRenderer>(true);var mat=AssetDatabase.LoadAssetAtPath<Material>(Characters+id+"/character.mat");var tex=mat.GetTexture("_BaseMap");var ti=(TextureImporter)AssetImporter.GetAtPath(AssetDatabase.GetAssetPath(tex));var android=ti.GetPlatformTextureSettings("Android");bool valid=a.avatar!=null&&a.avatar.isValid&&!a.avatar.isHuman&&skins.All(s=>s.quality==SkinQuality.Bone4)&&prefab.GetComponentsInChildren<Collider>(true).Length==0&&mat.shader.name=="FlatKit/Stylized Surface"&&!ti.mipmapEnabled&&!ti.isReadable&&android.format==TextureImporterFormat.ASTC_4x4; if(!valid)throw new Exception("Character budget/rig mismatch: "+id);prefabs.Add(new{id,triangles=skins.Sum(s=>s.sharedMesh.triangles.Length/3),ownGenericAvatar=true,avatarPath=AssetDatabase.GetAssetPath(a.avatar),skinQuality="Bone4",clips=a.runtimeAnimatorController.animationClips.Select(c=>c.name).Distinct().ToArray(),colliders=0,shader=mat.shader.name,texture=AssetDatabase.GetAssetPath(tex),ti.maxTextureSize,ti.mipmapEnabled,ti.isReadable,androidFormat=android.format.ToString(),runtimeTextureBytes=UnityEngine.Profiling.Profiler.GetRuntimeMemorySizeLong(tex)});}
  return new{scenes,prefabs,claims="Saved scene registrations and own-rig import budget audit; no physical-phone FPS or process-relaunch persistence claim."};
 }
}
