using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEngine.Rendering;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine.SceneManagement;using TMPro;using IndianOceanAssets.ShooterSurvival;using Object=UnityEngine.Object;

// Extends the existing ShoeTower scene. Old presentation/encounters are retained
// under an inactive archive; only this new authored registry runs the new route.
public static class BuildDetailedMall {
 const string ScenePath="Assets/ShooterSurvival/Scenes/Tools/ShoeTower.unity";
 const string Retail="Assets/ShooterSurvival/Models/Chapters/Chapters45/RetailProduction20261003/";
 const string Models="Assets/ShooterSurvival/Prefabs/MeshyRestStop20260925/";
 const string Record="outputs/chapter45-detailed-design-2026-10-03";
 static string assets;static Transform root;static Chapter45Director d;static TMP_FontAsset font;static EnemySO enemyData;
 static readonly List<Chapter45Route.Segment> segments=new();static readonly List<Chapter45Encounter> encounters=new();static readonly List<Chapter45Lift> lifts=new();
 static readonly Dictionary<int,int> first=new(),last=new();static readonly Dictionary<int,float> starts=new(),ends=new();static readonly Dictionary<int,Transform> floors=new();
 static readonly List<UnityEngine.Object> createdAssets=new();static readonly Dictionary<string,Material> mats=new();static RestStopHoldout cinema;static int actorIndex;
 static readonly int[] order={1,2,3,4,8,5,6,7};
 static float Y(int floor)=>floor==8?-9:(floor-1)*9;
 static string Label(int f)=>f==8?"B1":f+"F";
 static string Theme(int f)=>f switch{1=>"명품 · LUXURY",2=>"의류 · FASHION",3=>"스포츠 · SPORTS",4=>"리빙 · LIVING",8=>"식당가 · FOOD COURT",5=>"영화관 · TICKETS",6=>"상영관 · SCREEN",_=>"신발 · SHOE GALLERY"};
 static Transform Group(Transform parent,string name){var g=new GameObject(name);g.transform.SetParent(parent,false);return g.transform;}
 static Material Mat(string name,Color color,float smooth=.25f){if(mats.TryGetValue(name,out var m))return m;m=new Material(Shader.Find("Universal Render Pipeline/Lit")){name=name,enableInstancing=true};m.SetColor("_BaseColor",color);m.SetFloat("_Smoothness",smooth);AssetDatabase.CreateAsset(m,assets+"/"+name+".mat");createdAssets.Add(m);mats[name]=m;return m;}
 static Material Glass(){var m=Mat("Clear blue glass",new Color(.53f,.77f,.86f,.17f),.85f);m.SetFloat("_Surface",1);m.SetFloat("_Blend",0);m.SetInt("_SrcBlend",(int)BlendMode.SrcAlpha);m.SetInt("_DstBlend",(int)BlendMode.OneMinusSrcAlpha);m.SetInt("_ZWrite",0);m.SetInt("_Cull",(int)CullMode.Off);m.renderQueue=3000;m.EnableKeyword("_SURFACE_TYPE_TRANSPARENT");return m;}
 static Material stone,ivory,wood,dark,glass,metal,warm,blue,coral;
 static GameObject Box(Transform parent,string name,Vector3 local,Vector3 size,Material mat,bool solid=false){var g=GameObject.CreatePrimitive(PrimitiveType.Cube);g.name=name;g.transform.SetParent(parent,false);g.transform.localPosition=local;g.transform.localScale=size;g.GetComponent<Renderer>().sharedMaterial=mat;g.GetComponent<Renderer>().shadowCastingMode=ShadowCastingMode.Off;if(!solid)Object.DestroyImmediate(g.GetComponent<Collider>());return g;}
 static GameObject Cylinder(Transform parent,string name,Vector3 local,Vector3 size,Material mat){var g=GameObject.CreatePrimitive(PrimitiveType.Cylinder);g.name=name;g.transform.SetParent(parent,false);g.transform.localPosition=local;g.transform.localScale=size;g.GetComponent<Renderer>().sharedMaterial=mat;Object.DestroyImmediate(g.GetComponent<Collider>());return g;}
 static TMP_Text Sign(Transform parent,string name,string text,Vector3 local,float width,float size,Color color){var g=Group(parent,name);g.localPosition=local;var t=g.gameObject.AddComponent<TextMeshPro>();t.font=font;t.text=text;t.fontSize=size;t.color=color;t.alignment=TextAlignmentOptions.Center;t.rectTransform.sizeDelta=new Vector2(width,3);t.textWrappingMode=TextWrappingModes.NoWrap;return t;}
 static GameObject Model(Transform parent,string path,Vector3 local,float height,float yaw=0){var src=AssetDatabase.LoadAssetAtPath<GameObject>(path);if(src==null)throw new FileNotFoundException(path);var g=(GameObject)PrefabUtility.InstantiatePrefab(src);g.transform.SetParent(parent,false);g.transform.localPosition=Vector3.zero;g.transform.localRotation=Quaternion.Euler(0,yaw,0)*src.transform.localRotation;var rr=g.GetComponentsInChildren<Renderer>(true).Where(x=>!(x is TrailRenderer)).ToArray();if(rr.Length==0)throw new Exception("No model bounds: "+path);var b=rr[0].bounds;foreach(var r in rr)b.Encapsulate(r.bounds);g.transform.localScale*=height/Mathf.Max(.001f,b.size.y);b=rr[0].bounds;foreach(var r in rr)b.Encapsulate(r.bounds);var offset=parent.InverseTransformVector(new Vector3(-b.center.x+g.transform.position.x,-b.min.y+g.transform.position.y,-b.center.z+g.transform.position.z));g.transform.localPosition=local+offset;foreach(var c in g.GetComponentsInChildren<Collider>(true))c.enabled=false;foreach(var r in rr){r.shadowCastingMode=ShadowCastingMode.Off;r.receiveShadows=true;}return g;}
 static GameObject RetailModel(Transform parent,string name,Vector3 local,float height,float yaw=0){var g=Model(parent,Retail+name+".fbx",local,height,yaw);var mat=AssetDatabase.LoadAssetAtPath<Material>(Retail+name+".mat");if(mat!=null)foreach(var r in g.GetComponentsInChildren<Renderer>(true))r.sharedMaterial=mat;g.name=name+" reused verified model";return g;}
 static void Beam(Transform parent,string name,Vector3 a,Vector3 b,float width,Material mat){var g=Box(parent,name,(a+b)*.5f,new Vector3(width,Vector3.Distance(a,b),width),mat);g.transform.localRotation=Quaternion.FromToRotation(Vector3.up,b-a);}
 static Vector3 Polar(float radius,float angle,float y=0){float a=angle*Mathf.Deg2Rad;return new Vector3(Mathf.Cos(a)*radius,y,Mathf.Sin(a)*radius);}
 static Mesh RingMesh(float inner,float outer,float height){var v=new List<Vector3>();var uv=new List<Vector2>();var tri=new List<int>();for(int i=0;i<=120;i++){float a=i*3;foreach(float radius in new[]{inner,outer}){var p=Polar(radius,a,height);v.Add(p);uv.Add(new Vector2(p.x*.12f,p.z*.12f));}}for(int i=0;i<120;i++){int n=i*2;tri.AddRange(new[]{n,n+2,n+1,n+1,n+2,n+3});}var m=new Mesh{name="Curved atrium slab"};m.SetVertices(v);m.SetUVs(0,uv);m.SetTriangles(tri,0);m.RecalculateNormals();m.RecalculateBounds();return m;}
 static void MeshObject(Transform parent,string name,Mesh mesh,Material mat,bool solid){AssetDatabase.CreateAsset(mesh,assets+"/"+name+".asset");createdAssets.Add(mesh);var g=Group(parent,name);g.gameObject.AddComponent<MeshFilter>().sharedMesh=mesh;g.gameObject.AddComponent<MeshRenderer>().sharedMaterial=mat;if(solid)g.gameObject.AddComponent<MeshCollider>().sharedMesh=mesh;}
 static void AddSegment(Vector3 a,Vector3 b,int floor){segments.Add(new Chapter45Route.Segment{start=a,end=b,length=Vector3.Distance(a,b),floor=floor,label=Label(floor)+" "+Theme(floor)});}
 static void BuildRoutes(){segments.Clear();first.Clear();last.Clear();starts.Clear();ends.Clear();float cumulative=0;
  foreach(int floor in order){first[floor]=segments.Count;starts[floor]=cumulative;
   if(floor==6){AddSegment(new Vector3(15,Y(6),26),new Vector3(15,Y(6),-12),6);AddSegment(new Vector3(15,Y(6),-12),new Vector3(15,Y(6),26),6);}
   else{float angle=floor switch{1=>-90,2=>240,3=>570,4=>900,8=>1200,5=>1200,_=>1500};for(int i=0;i<60;i++)AddSegment(Polar(30,angle+i*5,Y(floor)),Polar(30,angle+(i+1)*5,Y(floor)),floor);}
   last[floor]=segments.Count-1;cumulative=segments.Sum(s=>s.Length);ends[floor]=cumulative;
  }d.route.segments=segments.ToArray();
 }
 static void Architecture(){floors.Clear();var scenery=Group(root,"Scenery");
  foreach(int floor in order){var f=Group(scenery,Label(floor)+" "+Theme(floor));f.localPosition=Vector3.up*Y(floor);floors[floor]=f;var vis=f.gameObject.AddComponent<Chapter45SceneryGroup>();vis.floor=floor;vis.alwaysVisible=true;vis.startDistance=starts[floor];vis.endDistance=ends[floor];
   if(floor==6)Box(f,"Cinema supported floor",new Vector3(7,-.2f,0),new Vector3(75,.4f,80),dark,true);
   else MeshObject(f,Label(floor)+" curved supported floor",RingMesh(19.5f,56,0),stone,true);
   for(int i=0;i<48;i++){float a=i*7.5f;var p=Polar(20,a,.6f);var railing=Box(f,"Curved glass balustrade",p,new Vector3(2.63f,1.2f,.035f),glass);railing.transform.localRotation=Quaternion.Euler(0,-a,0);Beam(f,"Brushed rail",Polar(20,a-3.75f,1.24f),Polar(20,a+3.75f,1.24f),.055f,metal);}
   for(int i=0;i<12;i++){float a=i*30;Box(f,"Warm walkway tile seam",Polar(35,a,.012f),new Vector3(.025f,.018f,27),wood).transform.localRotation=Quaternion.Euler(0,-a+90,0);}
   var title=Group(f,"Arrival wayfinding");var start=d.route.segments[first[floor]];title.localPosition=start.start-Vector3.up*Y(floor)+new Vector3(0,4.8f,0);title.rotation=Quaternion.LookRotation(start.end-start.start);Sign(title,"Floor sign",Label(floor)+"   "+Theme(floor),Vector3.zero,16,3.5f,new Color(.15f,.2f,.22f));
   if(floor!=6)for(int shop=0;shop<8;shop++)Shop(f,floor,shop);
  }
  var atrium=Group(scenery,"Shared skylit atrium structure");var common=atrium.gameObject.AddComponent<Chapter45SceneryGroup>();common.floor=-1;common.alwaysVisible=true;
  foreach(int f in order){float y=Y(f);for(int i=0;i<48;i++){float a=i*7.5f;var fascia=Box(atrium,"Visible balcony fascia "+Label(f),Polar(19.7f,a,y-.2f),new Vector3(2.65f,.4f,.18f),ivory);fascia.transform.localRotation=Quaternion.Euler(0,-a,0);}}
  for(int i=0;i<12;i++){float a=i*30;Beam(atrium,"Atrium vertical louver",Polar(18.9f,a,-9),Polar(18.9f,a,64),.14f,wood);Beam(atrium,"Skylight ribs",Polar(20,a,64),Polar(20,a+180,64),.12f,metal);}
  MeshObject(atrium,"Glazed roof daylight",RingMesh(0,20,64),glass,false);
 }
 static void Shop(Transform floorRoot,int floor,int index){float a=index*45;var shop=Group(floorRoot,Theme(floor)+" storefront "+index);shop.localPosition=Polar(47,a);shop.localRotation=Quaternion.LookRotation(-Polar(1,a));
  Box(shop,"Shop floor",new Vector3(0,.018f,0),new Vector3(18,.036f,13),ivory);Box(shop,"Warm recessed back wall",new Vector3(0,2.4f,-5),new Vector3(18,4.8f,.25f),floor==3?blue:floor==5?dark:ivory);Box(shop,"Timber portal left",new Vector3(-8.9f,2.4f,.3f),new Vector3(.4f,4.8f,11),wood);Box(shop,"Timber portal right",new Vector3(8.9f,2.4f,.3f),new Vector3(.4f,4.8f,11),wood);Box(shop,"Brass lintel",new Vector3(0,4.8f,5.7f),new Vector3(18,.45f,.3f),metal);
  Box(shop,"Warm interior strip",new Vector3(0,4.5f,-4.7f),new Vector3(17,.14f,.1f),warm);
  string[] luxury={"MAISON SOL","누아르","ATELIER 07","로에나"},clothes={"모노웨어","DAY FORM","오브제 의류","SEASON"},sports={"COURT 3","RUN FIELD","그린 스포츠","BALL CLUB"},living={"룸 앤 데이","LIVING LAB","홈 아틀리에","라움"},food={"한상 · 한식","용화 · 중식","PASTA TABLE · 양식","미소 · 일식"},ticket={"CINE SEVEN","예매 · TICKETS","POPCORN BAR","입장 안내"},shoes={"SHOE MARKET","STEP DAILY","SOLE STUDIO","AERO SEVEN"};
  var names=floor switch{1=>luxury,2=>clothes,3=>sports,4=>living,8=>food,5=>ticket,_=>shoes};string name=names[index%4];Sign(shop,"Fictional store name",name,new Vector3(0,4.2f,5.51f),16,3.8f,floor==5?Color.white:new Color(.12f,.17f,.18f));
  if(floor==8){Model(shop,Models+"I03_food_counter.prefab",new Vector3(0,0,1),2.3f);Model(shop,Models+"I04_dining_set.prefab",new Vector3(-5,0,1),1.5f);Sign(shop,"Four cuisine menu",names[index%4],new Vector3(0,2.8f,-4.7f),12,2.5f,new Color(.18f,.18f,.18f));}
  else if(floor==5){RetailModel(shop,"RetailCounter",new Vector3(0,0,2),1.1f);for(int k=-1;k<=1;k++){Box(shop,"Ticket touchscreen",new Vector3(k*2.3f,1.7f,2),new Vector3(1.5f,1.1f,.1f),blue);Sign(shop,"Ticket screen",k==0?"TICKET":"CINE",new Vector3(k*2.3f,1.7f,2.07f),1.4f,.7f,Color.white);} }
  else if(floor==2){for(int k=-2;k<=2;k++){float x=k*2.8f;Beam(shop,"Garment rail",new Vector3(x-.9f,2.1f,1),new Vector3(x+.9f,2.1f,1),.06f,metal);Beam(shop,"Rack left",new Vector3(x-.9f,0,1),new Vector3(x-.9f,2.1f,1),.07f,metal);Beam(shop,"Rack right",new Vector3(x+.9f,0,1),new Vector3(x+.9f,2.1f,1),.07f,metal);for(int j=-1;j<=1;j++){var cloth=Box(shop,"Garment silhouette awaiting TRELLIS clothing",new Vector3(x+j*.42f,1.4f,1),new Vector3(.38f,1.25f,.32f),j==0?blue:ivory);}}}
  else if(floor==3){for(int k=-2;k<=2;k++){var stand=Box(shop,"Sports display plinth",new Vector3(k*2.7f,.35f,1),new Vector3(1.8f,.7f,1.8f),wood);RetailModel(shop,"RetailSneaker",new Vector3(k*2.7f,.7f,1),.35f);}}
  else if(floor==4){RetailModel(shop,"RetailCounter",new Vector3(-4,0,1),1);RetailModel(shop,"RetailVase",new Vector3(-4,1,1),.6f);RetailModel(shop,"RetailBench",new Vector3(3,0,1),.8f);for(int k=0;k<5;k++)Cylinder(shop,"Living ceramic plate",new Vector3(0,.4f+k*.06f,2),new Vector3(.75f,.025f,.75f),ivory);}
  else {for(int k=-1;k<=1;k++){RetailModel(shop,"RetailCaseBase",new Vector3(k*4.6f,0,1.5f),.8f);var good=RetailModel(shop,floor==7?"RetailSneaker":"RetailTote",new Vector3(k*4.6f,.82f,1.5f),floor==7?.38f:.6f);Box(shop,"Clear display glazing",new Vector3(k*4.6f,1.22f,1.5f),new Vector3(2.3f,.85f,1.8f),glass);}}
  RetailModel(shop,"RetailPlanter",new Vector3(7,0,4),1.4f);
 }
 static EnemyScript_space Actor(Transform parent,string model,float distance,float lane,int floor,float height=1.8f){d.route.Sample(distance,out var pos,out var forward);var g=Group(parent,"Actor "+actorIndex++ +" "+model);g.position=pos+Vector3.Cross(Vector3.up,forward)*lane+Vector3.up*.06f;g.rotation=Quaternion.LookRotation(-forward);g.gameObject.tag="EnemyTag";
  Model(g,Models+model+".prefab",Vector3.zero,height);var hit=Group(g,"Walker-HitPos");hit.localPosition=Vector3.up*height*.6f;var col=g.gameObject.AddComponent<CapsuleCollider>();col.center=Vector3.up*height*.5f;col.height=height;col.radius=.45f;col.isTrigger=true;g.gameObject.AddComponent<AudioSource>().playOnAwake=false;
  var combat=g.gameObject.AddComponent<EnemyScript_space>();var so=new SerializedObject(combat);so.FindProperty("enemyData").objectReferenceValue=enemyData;so.ApplyModifiedPropertiesWithoutUndo();combat.ConfigureRewards(false,4);g.gameObject.AddComponent<Chapter45Deck>().floor=floor;var evt=g.gameObject.AddComponent<EnemyEventController>();evt.HideWhileWaiting=false;evt.EventMode=EnemyEventMode.AttackLoop;
  g.gameObject.SetActive(false);return combat;
 }
 static void Encounter(int floor,float fraction,string role,string[] models,float health,bool required,int branch=-1){float distance=Mathf.Lerp(starts[floor],ends[floor],fraction);var g=Group(root,Label(floor)+" "+role);var encounter=g.gameObject.AddComponent<Chapter45Encounter>();encounter.floor=floor;encounter.activationDistance=distance-24;encounter.stopDistance=distance-7;encounter.health=health;encounter.damage=2;encounter.statPrefix="c5_detailed_"+role.Replace(" ","_");encounter.coinReward=4;encounter.requiredToProceed=required;encounter.announcement=role;encounter.choiceIndex=branch<0?-1:0;encounter.requiredChoice=branch;
  encounter.announcement=role.Replace(" 기존 모델","").Replace(" 행동 대기","").Replace(" 복장 생성 대기","").Replace(" 모델 생성 대기","");
  encounter.actors=models.Select((m,i)=>Actor(g,m,distance,models.Length==1?0:(i-(models.Length-1)*.5f)*2.1f,floor,m=="A03_kid"?1.25f:1.8f)).ToArray();encounters.Add(encounter);
 }
 static Chapter45Lift Connection(int from,int to,bool escalator,int branch=-1){var g=Group(root,Label(from)+" to "+Label(to)+(escalator?" escalator":" elevator"));var l=g.gameObject.AddComponent<Chapter45Lift>();l.afterSegment=last[from];l.destinationSegment=first[to];l.choiceIndex=branch<0?-1:0;l.requiredChoice=branch;l.duration=escalator?5:6;l.exactDuration=true;l.escalator=escalator;l.destinationLabel=Label(to)+" "+Theme(to);l.minimumFloorSeconds=from==1?30:0;l.requireFloorClear=from!=1;lifts.Add(l);
  Vector3 a=d.route.segments[last[from]].end,b=d.route.segments[first[to]].start;var vis=g.gameObject.AddComponent<Chapter45SceneryGroup>();vis.floor=from;vis.alwaysVisible=true;
  if(escalator){Vector3 side=Vector3.Cross(Vector3.up,(b-a).normalized).normalized;for(int i=0;i<32;i++){float t=(float)i/31;var p=Vector3.Lerp(a,b,t);Box(g,"Metal escalator tread",p-Vector3.up*.08f,new Vector3(5,.16f,.55f),metal).transform.rotation=Quaternion.LookRotation(Vector3.ProjectOnPlane(b-a,Vector3.up));}foreach(int sign in new[]{-1,1}){Beam(g,"Black moving handrail",a+side*sign*2.7f+Vector3.up*1.15f,b+side*sign*2.7f+Vector3.up*1.15f,.12f,dark);Beam(g,"Clear escalator side",a+side*sign*2.7f+Vector3.up*.7f,b+side*sign*2.7f+Vector3.up*.7f,.5f,glass);}}
  else{var cabin=Group(g,"Elevator moving cabin");cabin.position=a;l.platform=cabin;Box(cabin,"Elevator visible cabin floor",-Vector3.up*.12f,new Vector3(9,.24f,9),metal);Box(cabin,"Cabin rear",new Vector3(0,2.1f,4.4f),new Vector3(9,4.2f,.12f),glass);var left=Box(g,"Elevator door L",a+new Vector3(-2,2,-4),new Vector3(2,4,.15f),glass);var right=Box(g,"Elevator door R",a+new Vector3(2,2,-4),new Vector3(2,4,.15f),glass);l.doors=new[]{left.transform,right.transform};}
  return l;
 }
 static void Gameplay(){encounters.Clear();lifts.Clear();actorIndex=0;
  Encounter(1,.2f,"관광객",new[]{"A01_dad","A02_mom"},8,false);Encounter(1,.5f,"관광객",new[]{"A05_student","A01_dad"},8,false);Encounter(1,.82f,"가드 기존 모델",new[]{"C01_patrol_police","C07_riot_police"},12,false);
  Encounter(2,.22f,"쇼핑백 여성",new[]{"A02_mom","A02_mom"},12,false);Encounter(2,.52f,"커플 행동 대기",new[]{"A01_dad","A02_mom"},12,true);Encounter(2,.82f,"의류 매장",new[]{"A05_student","A02_mom"},16,true);
  Encounter(3,.23f,"스포츠 고객",new[]{"A05_student","A01_dad"},14,false);Encounter(3,.52f,"학생 복장 생성 대기",new[]{"A05_student","A05_student","A05_student"},16,true);Encounter(3,.82f,"농구 중보스 모델 생성 대기",new[]{"C05_truck_driver"},90,true);
  Encounter(4,.28f,"리빙 고객",new[]{"A01_dad","A02_mom"},16,false);Encounter(4,.57f,"접시 투척 행동 대기",new[]{"C06_snack_clerk"},24,true);Encounter(4,.78f,"TV 코너",new[]{"A01_dad","A05_student"},18,true);
  Encounter(8,.18f,"식당 대기줄",new[]{"A01_dad","A02_mom","A06_grandma"},14,true,0);Encounter(8,.42f,"혼합 손님",new[]{"A05_student","A02_mom","C06_snack_clerk"},16,true,0);Encounter(8,.67f,"혼합 스포츠",new[]{"C05_truck_driver","A05_student"},22,true,0);Encounter(8,.87f,"배식 출구",new[]{"C06_snack_clerk","A01_dad"},18,true,0);
  Encounter(5,.2f,"영화관 아이들",new[]{"A03_kid","A05_student","A03_kid"},8,false,1);Encounter(5,.5f,"매표소 커플",new[]{"A01_dad","A02_mom"},14,true,1);Encounter(5,.8f,"직원과 청소부",new[]{"A10_cashier","A09_street_cleaner"},18,true,1);
  Encounter(6,.13f,"상영관 입장 대기",new[]{"A05_student","A01_dad"},10,false,1);
  Encounter(7,.2f,"저가 매장 매니저",new[]{"C01_patrol_police"},24,true);Encounter(7,.48f,"전문 매장 매니저",new[]{"C01_patrol_police","C07_riot_police"},30,true);Encounter(7,.77f,"최종 전시 매니저",new[]{"C07_riot_police","C01_patrol_police","C07_riot_police"},36,true);
  var cg=Group(root,"4F B1 or cinema actual floor choice");var choice=cg.gameObject.AddComponent<Chapter45Choice>();choice.kind=Chapter45Choice.ChoiceKind.FloorRoute;choice.floor=4;choice.distance=ends[4]-16;choice.endDistance=ends[4];choice.rewardDistance=ends[4];choice.leftName="B1 식당가";choice.rightName="5F 영화관";d.route.Sample(choice.distance-10,out var cp,out var cf);cg.position=cp+Vector3.up*4;cg.rotation=Quaternion.LookRotation(cf);choice.previewLabel=Sign(cg,"Actual destination choice",choice.leftName+"   |   "+choice.rightName,Vector3.zero,25,3.5f,Color.white);d.choices=new[]{choice};
  Connection(1,2,true);Connection(2,3,true);Connection(3,4,true);Connection(4,8,false,0);Connection(4,5,false,1);Connection(8,7,false,0);Connection(5,6,false,1);var cinemaExit=Connection(6,7,false,1);
  Cinema();cinemaExit.requiredHoldout=cinema;
  var goal=Group(root,"7F museum physical shoe pickup");var finish=d.route.segments[last[7]];goal.position=finish.end-finish.end.normalized*.1f+Vector3.up*1;goal.rotation=Quaternion.LookRotation(finish.end-finish.start);var trigger=goal.gameObject.AddComponent<BoxCollider>();trigger.size=new Vector3(8,4,4);trigger.isTrigger=true;var claim=goal.gameObject.AddComponent<Chapter45Goal>();claim.floor=7;claim.offering=true;
  var museum=Group(floors[7],"Museum glass shoe exhibition");museum.position=finish.end;museum.rotation=goal.rotation;Box(museum,"White museum pedestal",new Vector3(0,.45f,0),new Vector3(3,.9f,2.2f),ivory);claim.collectionVisual=RetailModel(museum,"RetailSneaker",new Vector3(0,.92f,0),.7f).transform;Box(museum,"Museum glass left",new Vector3(-1.65f,1.5f,0),new Vector3(.03f,1.4f,2.5f),glass);Box(museum,"Museum glass right",new Vector3(1.65f,1.5f,0),new Vector3(.03f,1.4f,2.5f),glass);Box(museum,"Museum glass rear",new Vector3(0,1.5f,1.2f),new Vector3(3.3f,1.4f,.03f),glass);Sign(museum,"Final exhibit","AERO SEVEN · THE WHITE SOLE",new Vector3(0,3,1),12,2,Color.white);
  d.encounters=encounters.ToArray();d.targets=Array.Empty<Chapter45Target>();d.hazards=Array.Empty<Chapter45Hazard>();d.lifts=lifts.ToArray();d.goals=new[]{claim};
 }
 static void Cinema(){var g=Group(root,"6F thirty second audience survival");cinema=g.gameObject.AddComponent<RestStopHoldout>();cinema.chapter45Owner=d;cinema.requiredFloor=6;cinema.choiceIndex=0;cinema.requiredChoice=1;cinema.hud=d.hud;cinema.center=Group(g,"Screen front survival position");cinema.center.position=new Vector3(15,Y(6),-12);cinema.center.rotation=Quaternion.Euler(0,180,0);var crowd=new List<EnemyEventController>();for(int i=0;i<24;i++){var actor=Actor(g,i%3==0?"A02_mom":i%3==1?"A05_student":"A01_dad",starts[6]+25,(i%3-1)*2,6);var evt=actor.GetComponent<EnemyEventController>();var target=Group(g,"Audience target "+i);target.position=cinema.center.position;evt.TargetPoint=target;crowd.Add(evt);}cinema.police=crowd.ToArray();cinema.entrances=new Transform[4];cinema.entranceSignals=new Renderer[4];for(int i=0;i<4;i++){var door=Group(g,"Audience entrance "+i);door.position=cinema.center.position+new Vector3(i%2==0?-12:12,0,i<2?-13:13);cinema.entrances[i]=door;cinema.entranceSignals[i]=Box(floors[6],"Audience entrance warning light",floors[6].InverseTransformPoint(door.position)+Vector3.up*.03f,new Vector3(3,.04f,3),coral).GetComponent<Renderer>();}
  Box(floors[6],"Large cinema screen",new Vector3(15,7,-31),new Vector3(38,14,.25f),ivory);Box(floors[6],"Screen lower frame",new Vector3(15,.25f,-30.8f),new Vector3(39,.5f,.3f),metal);Sign(floors[6],"Survival instructions","30초 생존 · SURVIVE",new Vector3(15,6,-30.7f),28,4,dark.color);
  // Seats are installed after local TRELLIS output passes inspection; reserve
  // generous central and side aisles instead of calling blockout chairs final.
 }
 public static object Main(){if(EditorApplication.isPlayingOrWillChangePlaymode||EditorApplication.isCompiling)throw new Exception("Idle edit mode required");for(int i=0;i<SceneManager.sceneCount;i++)if(SceneManager.GetSceneAt(i).isDirty)throw new Exception("Preserve dirty scene first");EditorSceneManager.OpenScene(ScenePath);d=Object.FindFirstObjectByType<Chapter45Director>();if(d.transform.Find("DetailedMall_20261003")!=null)throw new Exception("Already applied: inspect instead of duplicate");
  Directory.CreateDirectory(Record+"/scene-recovery");File.Copy(ScenePath,Record+"/scene-recovery/ShoeTower-before-detailed.unity",false);string stamp=DateTime.UtcNow.ToString("yyyyMMddTHHmmssfff");assets="Assets/ShooterSurvival/Models/Chapters/Chapters45/DetailedMall-"+stamp;Directory.CreateDirectory(assets);AssetDatabase.Refresh();
  font=AssetDatabase.LoadAssetAtPath<TMP_FontAsset>("Assets/ShooterSurvival/Resources/UI/GmarketHarbor SDF.asset");enemyData=AssetDatabase.LoadAssetAtPath<EnemySO>(AssetDatabase.GUIDToAssetPath("540a5d24ed1af08488d38a3679c240cb"));mats.Clear();createdAssets.Clear();stone=Mat("Warm limestone",new Color(.79f,.78f,.73f));ivory=Mat("Porcelain",new Color(.91f,.90f,.85f));wood=Mat("Warm oak",new Color(.37f,.23f,.12f));dark=Mat("Ink graphite",new Color(.075f,.095f,.11f));metal=Mat("Satin champagne metal",new Color(.61f,.55f,.39f),.55f);warm=Mat("Warm shop light",new Color(1,.82f,.5f));warm.EnableKeyword("_EMISSION");warm.SetColor("_EmissionColor",new Color(1,.69f,.3f)*1.4f);blue=Mat("Sports teal",new Color(.12f,.4f,.45f));coral=Mat("Warning amber",new Color(1,.45f,.1f));glass=Glass();
  var archive=Group(d.transform,"Preserved_PreDetailed_58F_118F_20261003");foreach(var child in d.transform.Cast<Transform>().Where(x=>x!=archive).ToArray())child.SetParent(archive,true);archive.gameObject.SetActive(false);root=Group(d.transform,"DetailedMall_20261003");
  BuildRoutes();Architecture();Gameplay();
  var player=Object.FindFirstObjectByType<PlayerScript>();var firstRoute=d.route.segments[0];Vector3 forward=(firstRoute.end-firstRoute.start).normalized;player.transform.SetPositionAndRotation(firstRoute.start+Vector3.up*.12f,Quaternion.LookRotation(forward));var cam=Camera.main;cam.transform.SetPositionAndRotation(player.transform.position-forward*23+Vector3.up*13,Quaternion.LookRotation(forward)*Quaternion.Euler(22,0,0));cam.farClipPlane=400;cam.GetComponent<StableGameplayCamera>()?.Configure(player.transform);
  var aura=Group(root,"Shield aura preserved use");if(d.shieldAura!=null){var copy=Object.Instantiate(d.shieldAura.gameObject,aura);copy.name="Shield aura";d.shieldAura=copy.transform;copy.SetActive(false);}
  var progress=Object.FindFirstObjectByType<ChapterProgression>();progress.nextChapterTitle="최고의 신발";progress.nextChapterCaption="7층 유리 전시실에서 최고의 신발을 찾았다.";
  foreach(var a in createdAssets)AssetDatabase.SaveAssetIfDirty(a);EditorSceneManager.MarkSceneDirty(SceneManager.GetActiveScene());if(!EditorSceneManager.SaveScene(SceneManager.GetActiveScene()))throw new Exception("Save failed");
  var result=new{scene=ScenePath,archive=archive.name,assets,floors=order,segments=segments.Count,encounters=d.encounters.Length,actors=actorIndex,lifts=d.lifts.Length,physicalShoe=true,oldCaptainRegistered=d.targets.Any(t=>t.captain),artStatus="structural installation; several role models/behaviors and local generated props pending",newPaidGeneration=false};
  var json=AppDomain.CurrentDomain.GetAssemblies().First(a=>a.GetName().Name=="Newtonsoft.Json").GetType("Newtonsoft.Json.JsonConvert");File.WriteAllText(Record+"/mall-structure-applied.json",(string)json.GetMethod("SerializeObject",new[]{typeof(object)}).Invoke(null,new object[]{result}));return result;
 }
}
