"""Build the same local gallery around individually generated object assets."""
from pathlib import Path
import csv,hashlib,html,json,sys,zipfile
ROOT=Path.cwd();DOC=ROOT/'map-concepts/reststop-atomic-assets-2026-09-23';G=ROOT/'tmp/image-previews/reststop-trellis-images-2026-09-23';REC=G/'atomic/records'
sys.path.insert(0,str(ROOT/'tmp/ten-run-review-2026-09-22/pythonlib'))
from PIL import Image
catalog=json.loads((DOC/'catalog.json').read_text(encoding='utf8'));assets=[];completed=[];bad=[]
for base in catalog:
 p=REC/(base['id']+'.json');revisions=sorted(REC.glob(base['id']+'-r*.json'));p=revisions[-1] if revisions else p;r={**base,**(json.loads(p.read_text(encoding='utf8')) if p.exists() else {})};r['layout_reference']=base['reference'];file=G/r['file'];r['available']=file.exists() and r.get('status')!='needs_revision'
 if r['available']:
  im=Image.open(file);im.load();r['width'],r['height']=im.size;r['mode']=im.mode;r['sha256']=hashlib.sha256(file.read_bytes()).hexdigest()
  if im.mode=='RGBA':
   a=im.getchannel('A');r['opaque_bbox']=a.point(lambda v:255 if v>204 else 0).getbbox();r['alpha_extrema']=a.getextrema()
   if r['opaque_bbox'] and (r['opaque_bbox'][0]==0 or r['opaque_bbox'][1]==0 or r['opaque_bbox'][2]==im.width or r['opaque_bbox'][3]==im.height):bad.append(r['id'])
  if r.get('status')=='complete':completed.append(r)
 assets.append(r)
public=[{k:r.get(k) for k in ('id','title','category','zones','file','available','status','visual_review','width','height','mode','sha256','opaque_bbox')} for r in assets]
(G/'atomic/manifest.json').write_text(json.dumps(public,ensure_ascii=False,indent=2),encoding='utf8');(DOC/'status.json').write_text(json.dumps({'total':len(assets),'completed':len(completed),'new_completed':sum(r['kind']=='new_image' for r in completed),'bbox_review_flags':bad},indent=2))
with (G/'atomic/asset-map.csv').open('w',newline='',encoding='utf-8-sig') as f:
 w=csv.writer(f);w.writerow(['ID','이름','분류','사용 구간','파일','상태'])
 for r in assets:w.writerow([r['id'],r['title'],r['category'],' / '.join(r['zones']),r['file'],r.get('status','pending')])
archive=G/'reststop-atomic-assets-69png.zip'
if len(completed)==len(assets) and not archive.exists():
 with zipfile.ZipFile(archive,'x',compression=zipfile.ZIP_DEFLATED,compresslevel=1) as z:
  for r in completed:z.write(G/r['file'],Path(r['file']).name)
 with zipfile.ZipFile(archive) as z:assert z.testzip() is None and len(z.namelist())==69
esc=html.escape
categories=list(dict.fromkeys(r['category'] for r in assets));zone_names={'01':'진입','02':'주차','03':'휴식·간식','04':'입구','05':'중앙 홀','06':'식당','07':'편의점','08':'화장실','09':'주유소','10':'출구'}
cards=[]
for r in assets:
 available=r['available'];title=r['id']+' '+r['title'];image=(f'<button class="picture" data-src="{esc(r["file"])}" data-title="{esc(title)}" aria-label="{esc(title)} 크게 보기"><img src="{esc(r["file"])}" alt="{esc(title)}" loading="lazy"></button>' if available else '<div class="pending">제작 중</div>')
 download=f'<a href="{esc(r["file"])}" download="{esc(title)}.png">PNG ↓</a>' if available else ''
 cards.append(f'<article data-zone="{" ".join(r["zones"])}" data-category="{esc(r["category"])}" data-ready="{str(available).lower()}">{image}<div class="caption"><h3><span>{r["id"]}</span> {esc(r["title"])}</h3>{download}</div><p class="zones">사용 구간 {" · ".join(r["zones"])} <a href="{esc(Path(r["layout_reference"]).relative_to(G).as_posix())}" target="_blank">참고 시안 ↗</a></p></article>')
css='''*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#eeeee6;color:#24382c;font:16px/1.6 system-ui,"Malgun Gothic",sans-serif}main{max-width:1550px;margin:auto;padding:38px 30px}.eyebrow{font-size:12px;letter-spacing:.16em;color:#5d7054}h1{font-size:clamp(30px,4vw,47px);margin:9px 0 15px;line-height:1.25}header p{color:#52654c}.links{display:flex;gap:22px;flex-wrap:wrap;margin:20px 0}a{color:#315e42;text-underline-offset:4px}a:hover{color:#8a5910}.filters{display:flex;gap:15px;flex-wrap:wrap;align-items:center;padding:18px 0;border-block:1px solid #c4ccb8;margin:25px 0}select{font:inherit;background:#fff;border:1px solid #b9c3ad;padding:7px 12px;color:#23382a}.count{margin-left:auto;font-size:14px}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:26px 20px}article{min-width:0}.picture{display:block;border:0;padding:12px;background:#fff;width:100%;cursor:zoom-in}.picture img{display:block;width:100%;height:auto;aspect-ratio:1;object-fit:contain}.pending{aspect-ratio:1;display:grid;place-items:center;background:#e0e4d9;color:#6b775f}.caption{display:flex;align-items:baseline;gap:8px;margin-top:9px}.caption h3{font-size:15px;line-height:1.45;margin:0}.caption span{font-weight:500;color:#927033}.caption a{font-size:13px;white-space:nowrap;margin-left:auto}.zones{font-size:12px;color:#617258;margin:6px 0}.zones a{margin-left:10px}footer{margin-top:40px;border-top:1px solid #c4ccb8;padding-top:18px;font-size:13px;color:#596e4f}button:focus-visible,a:focus-visible,select:focus-visible{outline:3px solid #986715;outline-offset:4px}dialog{max-width:95vw;max-height:96vh;border:0;padding:16px 22px;background:white}dialog::backdrop{background:#142319dc}.dialogbar{display:flex;gap:22px;align-items:center;margin-bottom:10px}.dialogbar button{margin-left:auto;padding:5px 14px;background:#fff;border:1px solid #aaa;cursor:pointer}dialog img{display:block;max-width:88vw;max-height:82vh;width:auto;height:auto;margin:auto}[hidden]{display:none!important}@media(max-width:1100px){.grid{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:760px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}main{padding:25px 14px}.caption h3{font-size:14px}.count{margin-left:0}}@media(max-width:440px){.grid{grid-template-columns:1fr}}'''
ready=len(completed);new_ready=sum(r['kind']=='new_image' for r in completed);download=f'<a href="{archive.name}" download>단독 PNG 69종 모두 받기 ↓</a>' if archive.exists() else '<span>완성된 파일은 각 이미지 아래에서 받을 수 있습니다.</span>'
if (G/'audit/index.html').exists():download+='<a href="audit/">Blender 소품 누락 검토 ↗</a>'
page=f'<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>휴게소 · 개별 소품 69종</title><style>{css}</style><main><header><div class="eyebrow">REST STOP / INDIVIDUAL ASSETS</div><h1>한 이미지에, 한 개의 에셋</h1><p>신규 {new_ready}/63종 · 단독 차량 6종 재사용 · 전체 {ready}/69종 완료</p><p>테이블·의자·판매대·진열장·구조 부품을 각각 분리했습니다. 같은 물체는 원본 하나를 복제해서 사용합니다.</p><div class="links">{download}<a href="atomic/asset-map.csv" download>구간별 소품 목록 CSV ↓</a><a href="layout-reference.html">이전 공간 배치 시안 ↗</a></div></header><div class="filters"><label>구간 <select id="zone"><option value="">모든 구간</option>'+''.join(f'<option value="{k}">{k} {v}</option>' for k,v in zone_names.items())+'</select></label><label>분류 <select id="category"><option value="">모든 분류</option>'+''.join(f'<option>{esc(c)}</option>' for c in categories)+'</select></label><label><input id="ready" type="checkbox" checked> 이미지가 있는 항목만</label><span class="count" id="shown"></span></div><div class="grid">'+''.join(cards)+'</div><footer>한 PNG는 독립 물체 또는 연결된 단순 구조 부품 하나입니다. 벽·기둥·가구를 조합한 공간 전체 이미지는 입력 세트에 포함하지 않습니다.<br>이미지 제작·분해 단계입니다. TRELLIS 변환 결과와 게임용 메시·충돌은 아직 검증하지 않았습니다. 나사·부착 손잡이 등은 해당 물체에 포함됩니다.</footer></main><dialog id="viewer"><div class="dialogbar"><strong id="vtitle"></strong><a id="vdownload" download>PNG 저장 ↓</a><button aria-label="닫기" id="close">닫기 ×</button></div><img id="vimage" alt=""></dialog><script>const zone=document.querySelector("#zone"),category=document.querySelector("#category"),ready=document.querySelector("#ready"),all=[...document.querySelectorAll("article")];function filter(){let count=0;all.forEach(a=>{const visible=(!zone.value||a.dataset.zone.split(" ").includes(zone.value))&&(!category.value||a.dataset.category===category.value)&&(!ready.checked||a.dataset.ready==="true");a.hidden=!visible;if(visible)count++});document.querySelector("#shown").textContent="표시 "+count+"종"}zone.onchange=category.onchange=ready.onchange=filter;filter();const d=document.querySelector("#viewer"),im=document.querySelector("#vimage");document.querySelectorAll(".picture").forEach(b=>b.onclick=()=>{im.src=b.dataset.src;im.alt=b.dataset.title;document.querySelector("#vtitle").textContent=b.dataset.title;document.querySelector("#vdownload").href=b.dataset.src;d.showModal()});document.querySelector("#close").onclick=()=>d.close();d.onclick=e=>{if(e.target===d)d.close()};</script></html>'
(G/'index.html').write_text(page,encoding='utf8');(G/'atomic-gallery.html').write_text(page,encoding='utf8');print(json.dumps({'completed':ready,'total':69,'new_completed':new_ready,'bbox_flags':bad}),flush=True)
