using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.Animations;using Object=UnityEngine.Object;
public static class BuildRoleCharacterPrefabs {
 const string Base="Assets/ShooterSurvival/Models/Chapters/Chapters45/DetailedCharacters20261003/", Outline="Assets/JH/Model/Enemy/Garden_Spear/Material.001.mat";
 static string State(string file,string take){
  if(file=="walk"||file=="run")return file;
  if(new[]{"throw","charge","grab","popcorn"}.Contains(file))return take=="retarget_clip"?"attack_once":null;
  if(new[]{"dribble","mop","kickride","bikeride"}.Contains(file))return take=="retarget_clip"?file:null;
  var n=take.ToLowerInvariant();return n.Contains("dead")?"die":n.Contains("hit_reaction")?"hit":n.Contains("idle")?"idle":n.Contains("golf_drive")?"attack_once":n.Contains("texting")?"phone":n.Contains("handbag")?"handbag":n.Contains("wave")?"wave":n.Contains("right_jab")?"guard":null;
 }
 static float Height(string id)=>id switch{"CH02"=>2.05f,"CH04R"=>1.7f,"CH05"=>1.76f,"CH06R"=>1.68f,"CH08"=>1.67f,"CH09"=>1.5f,_=>1.8f};

 static bool Loop(string s)=>s=="idle"||s=="walk"||s=="run"||s=="dribble"||s=="attack_loop"||s=="phone"||s=="handbag"||s=="kickride"||s=="bikeride";
 static Bounds BoundsOf(Transform model,Transform space){var b=new Bounds();bool first=true;foreach(var r in model.GetComponentsInChildren<SkinnedMeshRenderer>(true)){var m=new Mesh();r.BakeMesh(m,false);foreach(var v in m.vertices){var p=space.InverseTransformPoint(r.transform.TransformPoint(v));if(first){b=new Bounds(p,Vector3.zero);first=false;}else b.Encapsulate(p);}Object.DestroyImmediate(m);}if(first)throw new Exception("No skins");return b;}
 static float[] V(Vector3 p)=>new[]{p.x,p.y,p.z};
 public static object Main(string ids){if(EditorApplication.isPlayingOrWillChangePlaymode||EditorApplication.isCompiling)throw new Exception("Idle required");var reports=new List<object>();foreach(var id in ids.Split(',')){
  var folder=Base+id;string prefabPath=folder+"/"+id+".prefab";if(AssetDatabase.LoadAssetAtPath<GameObject>(prefabPath)!=null)throw new Exception("Already built "+id);var body=folder+"/body.fbx";var avatar=AssetDatabase.LoadAllAssetsAtPath(body).OfType<Avatar>().First();var clips=new Dictionary<string,AnimationClip>();
  foreach(var file0 in Directory.GetFiles(folder,"*.fbx")){string file=file0.Replace('\\','/'),key=Path.GetFileNameWithoutExtension(file);if(key=="body")continue;var ai=(ModelImporter)AssetImporter.GetAtPath(file);var chosen=new List<ModelImporterClipAnimation>();foreach(var take in ai.defaultClipAnimations){var state=State(key,take.takeName);if(state==null)continue;chosen.Add(new ModelImporterClipAnimation{name=state,takeName=take.takeName,firstFrame=take.firstFrame,lastFrame=take.lastFrame,loopTime=Loop(state),lockRootRotation=true,lockRootHeightY=true,lockRootPositionXZ=true,keepOriginalOrientation=true,keepOriginalPositionY=true,keepOriginalPositionXZ=true});}ai.clipAnimations=chosen.ToArray();ai.SaveAndReimport();
   foreach(var source in AssetDatabase.LoadAllAssetsAtPath(file).OfType<AnimationClip>().Where(c=>!c.name.StartsWith("__preview"))){if(!chosen.Any(c=>c.name==source.name))continue;var copy=new AnimationClip();EditorUtility.CopySerialized(source,copy);copy.name=source.name;foreach(var binding in AnimationUtility.GetCurveBindings(copy))if(binding.propertyName.StartsWith("m_LocalScale"))AnimationUtility.SetEditorCurve(copy,binding,null);AssetDatabase.CreateAsset(copy,folder+"/"+copy.name+".anim");clips.Add(copy.name,copy);}
  }
  if(!clips.ContainsKey("attack_once")&&clips.ContainsKey("wave")){var fallback=Object.Instantiate(clips["wave"]);fallback.name="attack_once";AssetDatabase.CreateAsset(fallback,folder+"/attack_once.anim");clips.Add("attack_once",fallback);}
  foreach(var state in new[]{"idle","walk","run","die","hit","attack_once"})if(!clips.ContainsKey(state))throw new Exception("Missing "+id+"/"+state);
  var loop=Object.Instantiate(clips["attack_once"]);loop.name="attack_loop";var settings=AnimationUtility.GetAnimationClipSettings(loop);settings.loopTime=true;AnimationUtility.SetAnimationClipSettings(loop,settings);AssetDatabase.CreateAsset(loop,folder+"/attack_loop.anim");clips.Add("attack_loop",loop);
  var texture=Directory.GetFiles(folder).Where(f=>new[]{".png",".jpg",".jpeg"}.Contains(Path.GetExtension(f))).OrderByDescending(f=>new FileInfo(f).Length).First().Replace('\\','/');var ti=(TextureImporter)AssetImporter.GetAtPath(texture);ti.sRGBTexture=true;ti.maxTextureSize=2048;ti.mipmapEnabled=true;ti.textureCompression=TextureImporterCompression.Compressed;ti.SetPlatformTextureSettings(new TextureImporterPlatformSettings{name="Android",overridden=true,maxTextureSize=1024,format=TextureImporterFormat.ASTC_6x6,compressionQuality=50});ti.SaveAndReimport();var mat=new Material(AssetDatabase.LoadAssetAtPath<Material>(Outline)){name=id+" outlined source texture",enableInstancing=true};mat.SetTexture("_BaseMap",AssetDatabase.LoadAssetAtPath<Texture2D>(texture));mat.SetColor("_BaseColor",Color.white);AssetDatabase.CreateAsset(mat,folder+"/character.mat");
  var controller=AnimatorController.CreateAnimatorControllerAtPath(folder+"/character.controller");var sm=controller.layers[0].stateMachine;foreach(var pair in clips){var state=sm.AddState(pair.Key);state.motion=pair.Value;if(pair.Key=="idle")sm.defaultState=state;if(pair.Key=="die")state.speed=pair.Value.length/.48f;}
  var root=new GameObject(id+" Meshy role character");try{var fit=new GameObject("Fit").transform;fit.SetParent(root.transform,false);var model=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>(body),fit);model.name="Model";var animator=model.GetComponent<Animator>()??model.AddComponent<Animator>();animator.avatar=avatar;animator.runtimeAnimatorController=controller;animator.applyRootMotion=false;animator.cullingMode=AnimatorCullingMode.CullUpdateTransforms;animator.enabled=false;foreach(var r in model.GetComponentsInChildren<SkinnedMeshRenderer>(true)){r.sharedMaterials=Enumerable.Repeat(mat,r.sharedMaterials.Length).ToArray();r.shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;r.updateWhenOffscreen=false;}
   clips["idle"].SampleAnimation(model,0);var b=BoundsOf(model.transform,root.transform);float height=Height(id);for(int i=0;i<8&&Mathf.Abs(b.size.y-height)>.002f;i++){fit.localScale*=Mathf.Sqrt(height/b.size.y);b=BoundsOf(model.transform,root.transform);}fit.localPosition-=new Vector3(b.center.x,b.min.y,b.center.z);var samples=new List<object>();var right=model.GetComponentsInChildren<Transform>(true).Single(t=>t.name=="RightHand");
   foreach(var pair in clips)foreach(float phase in new[]{0f,.25f,.5f,.75f,.99f}){pair.Value.SampleAnimation(model,pair.Value.length*phase);b=BoundsOf(model.transform,root.transform);samples.Add(new{state=pair.Key,phase,height=b.size.y,bottom=b.min.y,center=V(b.center),rightHand=V(root.transform.InverseTransformPoint(right.position))});}
   clips["idle"].SampleAnimation(model,0);animator.enabled=true;PrefabUtility.SaveAsPrefabAsset(root,prefabPath);reports.Add(new{id,prefabPath,clips=clips.Select(c=>new{name=c.Key,length=c.Value.length}).ToArray(),scale=V(fit.localScale),samples});
  }finally{Object.DestroyImmediate(root);}
 }AssetDatabase.SaveAssets();return new{items=reports};}
}
