"""Package the selected generated PNGs unchanged; no 3D generation or image edits."""
from pathlib import Path
import hashlib,html,json,sys,zipfile,shutil
ROOT=Path.cwd();DOC=ROOT/'map-concepts/reststop-trellis-images-2026-09-23';G=ROOT/'tmp/image-previews/reststop-trellis-images-2026-09-23'
sys.path.insert(0,str(ROOT/'tmp/ten-run-review-2026-09-22/pythonlib'))
from PIL import Image
records=json.loads((DOC/'selected.json').read_text(encoding='utf8'));assert len(records)==16;manifest=[]
for r in records:
 p=G/r['file'];im=Image.open(p);im.load();assert im.mode=='RGBA';alpha=im.getchannel('A');hist=alpha.histogram();bbox=alpha.point(lambda v:255 if v>204 else 0).getbbox();assert bbox and hist[0]>0 and hist[255]>0
 assert bbox[0]>0 and bbox[1]>0 and bbox[2]<im.width and bbox[3]<im.height,(p.name,bbox,im.size)
 manifest.append({'id':r['id'],'title':r['title'],'group':r['group'],'file':r['file'],'width':im.width,'height':im.height,'mode':im.mode,'opaque_bbox':bbox,'transparent_fraction':hist[0]/(im.width*im.height),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'generation_id':r['generation_id']})
for entry in manifest:
 entry['usage']='layout_reference_requires_asset_decomposition' if int(entry['id'])<=10 else 'single_vehicle_candidate_unverified'
(G/'manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2),encoding='utf8');shutil.copy2(G/'manifest.json',DOC/'manifest.json')
archive=G/'reststop-reference-images-16png.zip'
if not archive.exists():
 with zipfile.ZipFile(archive,'x',compression=zipfile.ZIP_DEFLATED,compresslevel=1) as z:
  for r in records:z.write(G/r['file'],r['file'])
with zipfile.ZipFile(archive) as z:assert z.testzip() is None and len(z.namelist())==16
def cards(items):
 return ''.join(f'<article><button class="picture" data-src="{html.escape(r["file"])}" data-title="{r["id"]} {html.escape(r["title"])}" aria-label="{r["id"]} {html.escape(r["title"])} 크게 보기"><img src="{html.escape(r["file"])}" alt="{r["id"]} {html.escape(r["title"])}" width="1254" height="1254"></button><div class="caption"><h3><span>{r["id"]}</span> {html.escape(r["title"])}</h3><a href="{html.escape(r["file"])}" download>PNG ↓</a></div></article>' for r in items)
css='''*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#eeeee6;color:#24382c;font:16px/1.6 system-ui,"Malgun Gothic",sans-serif}main{max-width:1500px;margin:auto;padding:40px 30px}.eyebrow{font-size:12px;letter-spacing:.16em;color:#586d50}h1{font-size:clamp(30px,4vw,48px);line-height:1.25;margin:12px 0 15px}header p{color:#53634c;margin-bottom:22px}nav{display:flex;gap:25px;flex-wrap:wrap;border-block:1px solid #c5cdbb;margin:27px 0;padding:17px 0}a{color:#315e42;text-underline-offset:4px}a:hover{color:#8a5910}.download{font-weight:650}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:28px 23px}article{min-width:0}.picture{display:block;width:100%;padding:12px;border:0;background:#fff;cursor:zoom-in}.picture img{display:block;width:100%;height:auto;aspect-ratio:1;object-fit:contain}.caption{display:flex;align-items:baseline;gap:10px;margin-top:9px}.caption h3{font-size:16px;font-weight:600;margin:0}.caption span{color:#8f6628;font-weight:500;margin-right:4px}.caption a{font-size:13px;white-space:nowrap;margin-left:auto}section{margin:36px 0 48px}h2{font-size:25px;font-weight:650;margin-bottom:18px}footer{font-size:14px;color:#53644c;border-top:1px solid #c5cdbb;padding-top:18px}button:focus-visible,a:focus-visible{outline:3px solid #9c702b;outline-offset:4px}dialog{border:0;padding:16px 22px;background:#fff;max-width:95vw;max-height:96vh}dialog::backdrop{background:#16201ad9}.dialogbar{display:flex;gap:24px;align-items:center;margin-bottom:10px}.dialogbar strong{font-size:16px}.close{margin-left:auto;border:1px solid #bbb;background:#fff;padding:5px 13px;cursor:pointer}dialog img{display:block;max-width:89vw;max-height:82vh;width:auto;height:auto;margin:auto}@media(max-width:850px){.grid{grid-template-columns:1fr 1fr}main{padding:25px 15px}.caption h3{font-size:14px}}@media(max-width:500px){.grid{grid-template-columns:1fr}}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}}'''
page=f'<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>휴게소 · TRELLIS 입력용 이미지</title><style>{css}</style><main><header><div class="eyebrow">REST STOP / IMAGE ASSETS</div><h1>TRELLIS 입력용 이미지</h1><p>공간 모듈 10장 + 차량 6장 · 개별 투명 PNG</p><a class="download" href="{archive.name}" download>선택된 16장 모두 받기 ↓</a></header><nav><a href="#environment">01–10 공간 모듈</a><a href="#vehicles">11–16 차량</a></nav><section id="environment"><h2>01–10 공간 모듈</h2><div class="grid">'+cards(records[:10])+'</div></section><section id="vehicles"><h2>11–16 차량 단독 이미지</h2><div class="grid">'+cards(records[10:])+'</div></section><footer>이미지를 누르면 크게 볼 수 있습니다. 다운로드한 개별 PNG를 한 장씩 사용하면 됩니다.<br>이번 결과는 ImageGen으로 제작한 이미지입니다. TRELLIS 변환은 실행하지 않았습니다.</footer></main><dialog id="viewer"><div class="dialogbar"><strong id="viewer-title"></strong><a id="viewer-download" download>PNG 저장 ↓</a><button class="close" aria-label="닫기">닫기 ×</button></div><img id="viewer-image" alt=""></dialog><script>const d=document.querySelector("#viewer"),im=document.querySelector("#viewer-image"),t=document.querySelector("#viewer-title"),a=document.querySelector("#viewer-download");document.querySelectorAll(".picture").forEach(b=>b.addEventListener("click",()=>{im.src=b.dataset.src;im.alt=b.dataset.title;t.textContent=b.dataset.title;a.href=b.dataset.src;d.showModal()}));document.querySelector(".close").addEventListener("click",()=>d.close());d.addEventListener("click",e=>{if(e.target===d)d.close()});</script></html>'
page=page.replace('TRELLIS 입력용 이미지','휴게소 배치 시안 · 단독 차량')
page=page.replace('공간 모듈 10장 + 차량 6장 · 개별 투명 PNG','01–10 공간 배치 참고 · 11–16 단독 차량 후보')
page=page.replace('01–10 공간 모듈','01–10 공간 배치 시안')
page=page.replace('<nav>','<p><strong>정정:</strong> 01–10은 공간 전체의 배치 참고 시안입니다. TRELLIS에 한 번에 넣을 제작용 입력으로 안내한 것은 잘못이었습니다. 가구·판매대·구조물을 개별 에셋 단위로 다시 분리해야 합니다. 차량도 실제 변환 결과는 아직 검증하지 않았습니다.</p><nav>',1)
page=page.replace('다운로드한 개별 PNG를 한 장씩 사용하면 됩니다.','공간 시안은 조립 배치 참고용이며, 직접 변환할 입력 이미지는 별도로 분해·제작해야 합니다.')
(G/'index.html').write_text(page,encoding='utf8');(G/'gallery-status.json').write_text(json.dumps({'selected_images':16,'dimensions':[1254,1254],'alpha_preserved':True,'zip_files':16,'trellis_executed':False,'environment_status':'layout_reference_only_requires_asset_decomposition','vehicle_status':'single_asset_candidates_unverified'},indent=2));print('IMAGE_GALLERY_READY',json.dumps({'images':16,'archive_bytes':archive.stat().st_size,'path':str(G)}),flush=True)
