using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections.Generic;using UnityEngine;using UnityEditor;using IndianOceanAssets.ShooterSurvival;using Object=UnityEngine.Object;
public static class CaptureMallOcclusion05 {
 static string folder;static Chapter45Director d;static PlayerScript p;static Camera cam;static StableGameplayCamera stable;static Queue<(int floor,float offset,string view)> jobs;static List<object> rows;static int frame=-1,wait=-1;static bool oldRunning;
 const BindingFlags P=BindingFlags.Instance|BindingFlags.NonPublic;
 static string Json(object o)=>(string)AppDomain.CurrentDomain.GetAssemblies().First(a=>a.GetName().Name=="Newtonsoft.Json").GetType("Newtonsoft.Json.JsonConvert").GetMethod("SerializeObject",new[]{typeof(object)}).Invoke(null,new[]{o});
 static void Set(object o,string n,object v)=>o.GetType().GetProperty(n).GetSetMethod(true).Invoke(o,new[]{v});
 public static object Main(string output){if(!EditorApplication.isPlaying)throw new Exception("Play required");folder=output;Directory.CreateDirectory(folder);d=Object.FindFirstObjectByType<Chapter45Director>();p=Object.FindFirstObjectByType<PlayerScript>();Object.FindFirstObjectByType<CanvasScript>().PlayerPressedStartButton();d.enabled=false;p.movement=false;oldRunning=TimeManager.isGameRunning;TimeManager.isGameRunning=false;cam=Camera.main;stable=cam.GetComponent<StableGameplayCamera>();jobs=new();rows=new();foreach(var point in new[]{(1,0f),(1,60f),(2,0f),(2,30f),(3,40f),(4,50f),(8,50f),(5,60f),(7,60f)})foreach(var view in new[]{"A","B"})jobs.Enqueue((point.Item1,point.Item2,view));EditorApplication.update+=Tick;return new{folder,pending=true,frames=jobs.Count};}
 static void Tick(){if(frame==Time.frameCount)return;frame=Time.frameCount;try{if(jobs.Count==0){Finish(null);return;}var job=jobs.Peek();if(wait<0){int first=Array.FindIndex(d.route.segments,s=>s.floor==job.floor);float distance=d.route.SegmentStart(first)+job.offset;int segment=d.route.SegmentAt(distance);Set(d,"CurrentSegment",segment);Set(d,"Distance",distance);d.route.SampleSegment(segment,distance,out var position,out var forward);p.ApplyContinuousRoutePose(position+Vector3.up*d.footOffset,forward,0);typeof(Chapter45Director).GetMethod("RefreshVisibility",P).Invoke(d,null);stable.yawRelativeOffset=new Vector3(0,5.8f,-12);stable.yawRelativeRotation=Quaternion.Euler(19,0,0);cam.fieldOfView=68;cam.useOcclusionCulling=job.view=="B";stable.SnapToTarget();wait=Time.frameCount+4;return;}if(Time.frameCount<wait)return;string name=$"{job.floor}F-{job.offset:F0}-{job.view}.png";var rt=new RenderTexture(720,1560,24);var old=cam.targetTexture;var active=RenderTexture.active;cam.targetTexture=rt;cam.Render();RenderTexture.active=rt;var tex=new Texture2D(720,1560,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,720,1560),0,0);tex.Apply();File.WriteAllBytes(Path.Combine(folder,name),tex.EncodeToPNG());cam.targetTexture=old;RenderTexture.active=active;Object.DestroyImmediate(tex);rt.Release();Object.DestroyImmediate(rt);var vp=cam.WorldToViewportPoint(p.transform.position+Vector3.up*1.5f);rows.Add(new{job.floor,job.offset,job.view,file=name,viewport=new[]{vp.x,vp.y,vp.z},camera=new[]{cam.transform.position.x,cam.transform.position.y,cam.transform.position.z},visibleRetailLights=Object.FindObjectsByType<Light>(FindObjectsSortMode.None).Count(l=>l.enabled&&l.name=="Warm retail downlight")});jobs.Dequeue();wait=-1;}catch(Exception e){Finish(e.ToString());}}
 static void Finish(string error){EditorApplication.update-=Tick;TimeManager.isGameRunning=oldRunning;File.WriteAllText(Path.Combine(folder,"result.json"),Json(new{completed=error==null,error,frames=rows,conditions="Directed native Unity Play architecture/camera fixture; actual saved meshes/materials and player, no ordinary-route claim. Both views=(0,5.8,-12), FOV68, pitch19. A: baked occlusion disabled; B: baked occlusion enabled. Diagnostic only, no saved scene changes."}));}
}
