using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Reflection;using UnityEngine;using UnityEditor;using UnityEngine.Localization.Settings;using IndianOceanAssets.ShooterSurvival;
public static class ChargeQa09 {
 const BindingFlags F=BindingFlags.Instance|BindingFlags.NonPublic;
 static Chapter45Director d;static PlayerScript p;static Chapter45RoleAction role;static string folder;static bool active,react,pauseTest,paused,pauseDone,sawWarning,sawActing;static float begin,firstWarning,next,initialHp;static double pauseBegan;static Vector3 pausedRole,pausedPlayer;static Vector3[] pausedVertices;static float pausedElapsed;static int frame,index,coverageFrames;static bool expectedContact;static float minStrikeDistance;static Dictionary<Chapter45RoleAction,Mesh> otherMeshes;static Mesh authoredMesh;static Material authoredMaterial;static string collidersBefore;static readonly List<string> passes=new(),fails=new(),errors=new();static readonly List<object> frames=new();
 static readonly MethodInfo Move=typeof(PlayerScript).GetMethod("PlayerMove",F);
 static string Json(object x)=>(string)AppDomain.CurrentDomain.GetAssemblies().First(a=>a.GetName().Name=="Newtonsoft.Json").GetType("Newtonsoft.Json.JsonConvert").GetMethod("SerializeObject",new[]{typeof(object)}).Invoke(null,new[]{x});
 static void Set(object o,string key,object value)=>o.GetType().GetField("<"+key+">k__BackingField",F).SetValue(o,value);
 static void Check(bool v,string s){(v?passes:fails).Add(s);}
 static float[] V(Vector3 v)=>new[]{v.x,v.y,v.z};
 static Vector3[] WorldVertices()=>role.warningMarker.GetComponent<MeshFilter>().sharedMesh.vertices.Select(v=>role.warningMarker.TransformPoint(v)).ToArray();
 static bool Inside(Vector3 point,Vector3[] poly){float sign=0;for(int i=0;i<poly.Length;i++){var a=poly[i];var b=poly[(i+1)%poly.Length];float cross=(b.x-a.x)*(point.z-a.z)-(b.z-a.z)*(point.x-a.x);if(Mathf.Abs(cross)<.002f)continue;if(sign==0)sign=Mathf.Sign(cross);else if(Mathf.Sign(cross)!=sign)return false;}return true;}
 public static object Begin(float distance,bool dodge,bool verifyPause,string output,bool expectContact){
  if(!EditorApplication.isPlaying||active||Directory.Exists(output))throw new Exception("Fresh Play and output required");Directory.CreateDirectory(output);folder=output;
  d=UnityEngine.Object.FindFirstObjectByType<Chapter45Director>();p=d.Player;UnityEngine.Object.FindFirstObjectByType<CanvasScript>().PlayerPressedStartButton();
  var h=UnityEngine.Object.FindFirstObjectByType<CombatHarness>();if(h!=null)typeof(CombatHarness).GetField("overlayVisible",F).SetValue(h,false);
  foreach(var e in d.encounters)if(e.stopDistance<distance){e.Retire();Set(e,"Complete",true);}foreach(var hazard in d.hazards)if(hazard.distance<distance){Set(hazard,"Triggered",true);hazard.Cancel();}
  foreach(var choice in d.choices)if(choice.distance<distance){int cs=Array.FindIndex(d.route.segments,s=>s.floor==choice.floor);if(cs>=0)Set(d,"CurrentSegment",cs);choice.Commit(-3);}
  Set(d,"Distance",distance);Set(d,"CurrentSegment",d.route.SegmentAt(distance));d.SampleOnCurrentDeck(distance,out var center,out var forward);p.ApplyContinuousRoutePose(center+Vector3.up*d.footOffset,forward,0);Physics.SyncTransforms();typeof(Chapter45Director).GetMethod("RefreshVisibility",F).Invoke(d,null);
  role=d.encounters.Where(e=>e.floor==d.CurrentFloor&&e.stopDistance>=distance).SelectMany(e=>e.actors).Select(a=>a.GetComponent<Chapter45RoleAction>()).First(r=>r!=null&&r.role==Chapter45RoleAction.Role.Basketball);
  expectedContact=expectContact;minStrikeDistance=float.PositiveInfinity;otherMeshes=d.encounters.SelectMany(e=>e.actors).Select(a=>a.GetComponent<Chapter45RoleAction>()).Where(r=>r!=null&&r.role!=Chapter45RoleAction.Role.Basketball&&r.warningMarker!=null).ToDictionary(r=>r,r=>r.warningMarker.GetComponent<MeshFilter>().sharedMesh);
  authoredMesh=role.warningMarker.GetComponent<MeshFilter>().sharedMesh;authoredMaterial=role.warningMarker.GetComponent<Renderer>().sharedMaterial;collidersBefore=Json(role.GetComponentsInChildren<Collider>(true).Select(c=>EditorJsonUtility.ToJson(c)).ToArray());
  passes.Clear();fails.Clear();errors.Clear();frames.Clear();Check(p.MaxHealth==60&&p.ResolvedAttackDamage==8,"ordinary starting stats 60HP/8ATK");
  string ko="돌진 예고 · 주황 경로 옆으로 피하세요";LocalizationSettings.SelectedLocale=LocalizationSettings.AvailableLocales.Locales.Single(l=>l.Identifier.Code=="ko-KR");Check(Chapter45PresentationText.Localize(ko)==ko,"Korean warning matches the marked path");LocalizationSettings.SelectedLocale=LocalizationSettings.AvailableLocales.Locales.Single(l=>l.Identifier.Code=="en-US");Check(Chapter45PresentationText.Localize(ko)=="Charge incoming · Move beside the orange path","English warning matches the marked path");
  begin=d.Elapsed;next=0;firstWarning=-1;initialHp=p.currentHealth;frame=-1;index=coverageFrames=0;react=dodge;pauseTest=verifyPause;paused=pauseDone=sawWarning=sawActing=false;active=true;
  Application.logMessageReceived+=Log;EditorApplication.update+=Tick;File.WriteAllText(Path.Combine(folder,"conditions.json"),Json(new{initialPlacementOnly=true,ordinaryPlaythrough=false,distance,dodge,verifyPause,expectContact,authoredFloor=d.CurrentFloor,input="native PlayerMove; starts 350ms after observed warning",manualDamage=false,manualRoleTick=false,statsOverridden=false}));return new{started=true,folder,target=role.name};
 }
 static void Log(string m,string tr,LogType type){if(type==LogType.Error||type==LogType.Exception||type==LogType.Assert)errors.Add(m);}
 static void Tick(){
  if(!active||!EditorApplication.isPlaying)return;EditorApplication.QueuePlayerLoopUpdate();if(frame==Time.frameCount)return;frame=Time.frameCount;
  float t=d.Elapsed-begin;
  if(role.Phase==Chapter45RoleAction.ActionPhase.Warning&&!sawWarning){sawWarning=true;firstWarning=t;Check(role.warningMarker.GetComponent<MeshFilter>().sharedMesh!=authoredMesh&&WorldVertices().Length==4,"charge displays a ground corridor before acting");Check(role.warningMarker.GetComponent<Renderer>().sharedMaterial==authoredMaterial,"existing warning material reused");Check(role.warningMarker.GetComponentsInChildren<Collider>(true).Length==0,"warning visual has no collider");}
  if(pauseTest&&sawWarning&&!pauseDone&&!paused&&t-firstWarning>=.16f){paused=true;pauseBegan=EditorApplication.timeSinceStartup;pausedRole=role.transform.position;pausedPlayer=p.transform.position;pausedElapsed=d.Elapsed;pausedVertices=WorldVertices();TimeManager.isGameRunning=false;}
  if(paused){if(EditorApplication.timeSinceStartup-pauseBegan<.35)return;Check(role.transform.position==pausedRole&&p.transform.position==pausedPlayer&&d.Elapsed==pausedElapsed&&WorldVertices().SequenceEqual(pausedVertices),"pause freezes actor, player, warning and active clock");TimeManager.isGameRunning=true;paused=false;pauseDone=true;}
  if(react&&sawWarning&&t-firstWarning>=.35f&&Mathf.Abs(d.Lane-3)>.08f)Move.Invoke(p,new object[]{Mathf.Clamp((3-d.Lane)*6,-15,15)});
  if(role.Phase==Chapter45RoleAction.ActionPhase.Acting){sawActing=true;var polygon=WorldVertices();var forward=Vector3.ProjectOnPlane(role.transform.forward,Vector3.up).normalized;var side=Vector3.Cross(Vector3.up,forward);var strike=role.transform.position+forward*(1.55f*.55f);float radius=1.55f*.55f+.45f;minStrikeDistance=Mathf.Min(minStrikeDistance,Vector3.ProjectOnPlane(strike-p.transform.position,Vector3.up).magnitude);bool covered=Inside(strike+side*radius,polygon)&&Inside(strike-side*radius,polygon)&&Inside(strike+forward*radius,polygon)&&Inside(strike-forward*radius,polygon);if(!covered&&!fails.Contains("actual strike disk stays inside warning corridor"))fails.Add("actual strike disk stays inside warning corridor");coverageFrames++;}
  if(t>=next){next=t+.12f;string file=(index++).ToString("D3")+".png";ScreenCapture.CaptureScreenshot(Path.Combine(folder,file));frames.Add(new{file,t,phase=role.Phase.ToString(),lane=d.Lane,health=p.currentHealth,actor=V(role.transform.position),player=V(p.transform.position),marker=role.warningMarker.gameObject.activeInHierarchy,vertices=WorldVertices().Select(V).ToArray()});}
  if(t<7.2f&&p.currentHealth>0)return;
  Check(sawWarning&&sawActing&&role.Actions>0,"native warning advances to a real charge");Check(coverageFrames>=5,"actual charge collision extent sampled throughout movement");if(!fails.Contains("actual strike disk stays inside warning corridor"))passes.Add("actual strike disk stays inside warning corridor");
  if(react)Check(role.Contacts==0,"350ms delayed right movement avoids the charge");else if(!expectedContact)Check(role.Contacts==0&&minStrikeDistance>1.55f*.55f+.45f,"B1 curved route outside strike disk causes no charge contact");else Check(role.Contacts==1,"straight approach receives exactly one real charge contact");
  Check(otherMeshes.All(kv=>kv.Key.warningMarker.GetComponent<MeshFilter>().sharedMesh==kv.Value),"all other role warning meshes preserved");
  int contacts=role.Contacts,actions=role.Actions;float health=p.currentHealth;Check(collidersBefore==Json(role.GetComponentsInChildren<Collider>(true).Select(c=>EditorJsonUtility.ToJson(c)).ToArray()),"actor collider properties preserved");
  role.enabled=false;Check(role.warningMarker.GetComponent<MeshFilter>().sharedMesh==authoredMesh&&!role.warningMarker.gameObject.activeSelf,"disable restores authored marker and hides warning");role.enabled=true;Check(role.Phase==Chapter45RoleAction.ActionPhase.Moving&&role.Contacts==0&&!role.warningMarker.gameObject.activeSelf,"reenable resets action and warning state");
  active=false;EditorApplication.update-=Tick;Application.logMessageReceived-=Log;
  File.WriteAllText(Path.Combine(folder,"result.json"),Json(new{complete=true,passed=passes.Count,failed=fails.Count,passes,fails,errors,actions,contacts,health,initialHp,safe=react,coverageFrames,minStrikeDistance,otherRoleMarkers=otherMeshes.Count,elapsed=t,frames=frames.ToArray(),timeline=d.Timeline.ToArray(),manualDamage=false,manualRoleTick=false,actualPhysicalContacts=true}));
 }
 public static object Stop(){if(paused)TimeManager.isGameRunning=true;paused=active=false;EditorApplication.update-=Tick;Application.logMessageReceived-=Log;return new{stopped=true};}
}
