using System;using System.IO;using System.Linq;using System.Reflection;using UnityEngine;using UnityEditor;using TMPro;using IndianOceanAssets.ShooterSurvival;using Object=UnityEngine.Object;
public static class CompareCinemaPitch {
 const BindingFlags Private=BindingFlags.Instance|BindingFlags.NonPublic;static Chapter45Director d;static RestStopHoldout h;static PlayerScript p;static string folder;static bool active;static int stage,frame;static float frozen;static double stageAt;static object pairs;static double began;static void Set(object o,string property,object value)=>o.GetType().GetProperty(property).GetSetMethod(true).Invoke(o,new[]{value});
 static string Json(object value)=>(string)AppDomain.CurrentDomain.GetAssemblies().First(a=>a.GetName().Name=="Newtonsoft.Json").GetType("Newtonsoft.Json.JsonConvert").GetMethod("SerializeObject",new[]{typeof(object)}).Invoke(null,new[]{value});
 public static object Main(string output){if(!EditorApplication.isPlaying)throw new Exception("Fresh prepared Play required");folder=output;Directory.CreateDirectory(folder);if(File.Exists(Path.Combine(folder,"conditions.json")))throw new Exception("Preserve existing capture");d=Object.FindFirstObjectByType<Chapter45Director>();p=Object.FindFirstObjectByType<PlayerScript>();Object.FindFirstObjectByType<CanvasScript>().PlayerPressedStartButton();h=d.GetComponentsInChildren<RestStopHoldout>(true).Single(x=>x.chapter45Owner==d);int choiceSegment=Array.FindIndex(d.route.segments,s=>s.floor==4);Set(d,"CurrentSegment",choiceSegment);Set(d,"Distance",d.choices[0].distance);d.choices[0].Commit(1);if(!d.choices[0].Selected||d.choices[0].Selection!=1)throw new Exception("Fixture floor4 choice did not commit");int segment=Array.FindIndex(d.route.segments,s=>s.floor==6);Set(d,"CurrentSegment",segment);Set(d,"Distance",d.route.SegmentStart(segment)+37.4f);p.ApplyContinuousRoutePose(h.center.position+Vector3.up*d.footOffset,h.center.forward,0);Physics.SyncTransforms();File.WriteAllText(Path.Combine(folder,"conditions.json"),Json(new{ordinaryPlaythrough=false,directedPlacement=true,statOverrides=false,comparison="same frozen scene/frame, camera policy only; current seat/material layout in both images",width=1080,height=2340}));active=true;began=EditorApplication.timeSinceStartup;stage=0;frame=-1;EditorApplication.update+=Tick;return new{folder,active};}
 static string Title()=>string.Join(" | ",d.hud.GetComponentsInChildren<TMP_Text>(true).Where(t=>t.gameObject.activeInHierarchy).Select(t=>t.text));
 static void Render(Camera camera,string name){var prior=camera.targetTexture;var activeRT=RenderTexture.active;var rt=RenderTexture.GetTemporary(1080,2340,24,RenderTextureFormat.ARGB32);var tex=new Texture2D(1080,2340,TextureFormat.RGB24,false);try{camera.targetTexture=rt;camera.Render();RenderTexture.active=rt;tex.ReadPixels(new Rect(0,0,1080,2340),0,0);tex.Apply();File.WriteAllBytes(Path.Combine(folder,name),tex.EncodeToPNG());}finally{camera.targetTexture=prior;RenderTexture.active=activeRT;RenderTexture.ReleaseTemporary(rt);Object.DestroyImmediate(tex);}}
 static void Tick(){if(!active||frame==Time.frameCount)return;frame=Time.frameCount;try{File.WriteAllText(Path.Combine(folder,"status.json"),Json(new{stage,h.Active,h.Completed,h.OnChapterFloor,h.Elapsed,d.Running,d.CurrentFloor,d.Distance,TimeManager.isGameRunning,TimeManager.timeFactor,position=new[]{p.transform.position.x,p.transform.position.y,p.transform.position.z},hp=p.currentHealth,choice=d.choices[0].Selection}));if(EditorApplication.timeSinceStartup-began>28)throw new Exception("Fixture did not reach capture/resume stage");if(stage==0){if(!h.Active||h.Elapsed<6)return;frozen=h.Elapsed;TimeManager.isGameRunning=false;var camera=Camera.main;var position=camera.transform.position;var rotation=camera.transform.rotation;float fov=camera.fieldOfView;string title=Title();if(!title.Contains("생존")||!title.Contains("초"))throw new Exception("Cinema countdown missing: "+title);Render(camera,"pitch-before-62-same-state.png");var proposed=Quaternion.Euler(48,h.center.eulerAngles.y,0);float distance=(float)typeof(RestStopHoldout).GetMethod("CinemaCameraDistance",Private).Invoke(h,new object[]{proposed});camera.transform.SetPositionAndRotation(h.LockedPosition+Vector3.up*1.1f-proposed*Vector3.forward*distance,proposed);camera.fieldOfView=45;Render(camera,"pitch-after-48-same-state.png");var points=h.entrances.Select(t=>camera.WorldToViewportPoint(t.position+Vector3.up*1.2f)).ToArray();if(points.Any(v=>v.z<=0||v.x<.04f||v.x>.96f||v.y<.06f||v.y>.82f))throw new Exception("Approach outside usable viewport");pairs=new{frame=Time.frameCount,elapsed=frozen,title,approachViewport=points.Select(v=>new[]{v.x,v.y,v.z}).ToArray(),sameActorsAndWorld=true};stage=1;stageAt=EditorApplication.timeSinceStartup;return;}if(stage==1){if(EditorApplication.timeSinceStartup-stageAt<1.2)return;if(Mathf.Abs(h.Elapsed-frozen)>.001f)throw new Exception("Paused countdown advanced");TimeManager.isGameRunning=true;stage=2;stageAt=EditorApplication.timeSinceStartup;return;}if(stage==2){if(h.Elapsed<frozen+1.5f)return;Finish(new{passed=true,pairs,resumedElapsed=h.Elapsed,resumedTitle=Title(),pauseFreezesClock=true,restorationStillRequired=true});}}catch(Exception e){Finish(new{passed=false,error=e.ToString(),restorationStillRequired=true});}}
 static void Finish(object result){active=false;EditorApplication.update-=Tick;File.WriteAllText(Path.Combine(folder,"result.json"),Json(result));}
}
