using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine.SceneManagement;using Object=UnityEngine.Object;
public static class DeepenEntryWindows {
 const string Mall="Assets/ShooterSurvival/Models/Chapters/Chapters45/DetailedMall-20261003T092859667/";
 const string Retail="Assets/ShooterSurvival/Models/Chapters/Chapters45/RetailProduction20261003/";
 static Transform root;static int geometry,reused;static string assets;static Material stone,wood,metal,warm,glass,dark;
 static void Box(string n,Vector3 p,Vector3 size,Material mat){var g=GameObject.CreatePrimitive(PrimitiveType.Cube);g.name=n;g.transform.SetParent(root,false);g.transform.localPosition=p;g.transform.localScale=size;g.GetComponent<Renderer>().sharedMaterial=mat;g.GetComponent<Renderer>().shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;Object.DestroyImmediate(g.GetComponent<Collider>());geometry++;}
 static void Model(string name,Vector3 local,float height,float yaw){var holder=new GameObject("Reused "+name+" entry exhibit").transform;holder.SetParent(root,false);holder.localPosition=local;holder.localRotation=Quaternion.Euler(0,yaw,0);var source=AssetDatabase.LoadAssetAtPath<GameObject>(Retail+name+".fbx");var g=(GameObject)PrefabUtility.InstantiatePrefab(source);g.transform.SetParent(holder,false);var rr=g.GetComponentsInChildren<Renderer>(true);var b=rr[0].bounds;foreach(var r in rr.Skip(1))b.Encapsulate(r.bounds);holder.localScale=Vector3.one*(height/b.size.y);b=rr[0].bounds;foreach(var r in rr.Skip(1))b.Encapsulate(r.bounds);g.transform.position+=holder.position-new Vector3(b.center.x,b.min.y,b.center.z);foreach(var r in rr){r.sharedMaterial=AssetDatabase.LoadAssetAtPath<Material>(Retail+name+".mat");r.shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;}if(g.GetComponentsInChildren<Collider>(true).Length>0)throw new Exception("Unexpected reused collider");reused++;}
 public static object Main(){if(EditorApplication.isPlayingOrWillChangePlaymode||EditorApplication.isCompiling)throw new Exception("Idle required");for(int i=0;i<SceneManager.sceneCount;i++)if(SceneManager.GetSceneAt(i).isDirty)throw new Exception("Dirty scene");EditorSceneManager.OpenScene("Assets/ShooterSurvival/Scenes/Tools/Jamsil.unity");var d=Object.FindFirstObjectByType<Chapter45Director>();var entrance=d.transform.Find("Scenery/DepartmentStore_20261002/Tower department store entrance");if(entrance==null)throw new Exception("Expected existing entrance");if(entrance.Find("Entry display depth revision")!=null)throw new Exception("Already applied");File.Copy(d.gameObject.scene.path,"outputs/chapter45-detailed-design-2026-10-03/scene-recovery/Jamsil-before-entry-depth.unity",false);
  assets=Retail+"EntryDepth-"+DateTime.UtcNow.ToString("yyyyMMddTHHmmssfff");Directory.CreateDirectory(assets);AssetDatabase.Refresh();stone=AssetDatabase.LoadAssetAtPath<Material>(Mall+"Ivory shop porcelain.mat");if(stone==null)stone=AssetDatabase.LoadAssetAtPath<Material>(Mall+"Pearl stone.mat");
  // Resolve authored materials already assigned to this scene instead of mutating shared sources.
  var mats=d.GetComponentsInChildren<Renderer>(true).SelectMany(r=>r.sharedMaterials).Where(m=>m!=null).Distinct().ToArray();stone=mats.First(m=>m.name=="Ivory porcelain");wood=AssetDatabase.LoadAssetAtPath<Material>(Mall+"Warm oak.mat");metal=AssetDatabase.LoadAssetAtPath<Material>(Mall+"Satin champagne metal.mat");warm=AssetDatabase.LoadAssetAtPath<Material>(Mall+"Warm shop light.mat");dark=AssetDatabase.LoadAssetAtPath<Material>(Mall+"Ink graphite.mat");glass=new Material(AssetDatabase.LoadAssetAtPath<Material>(Mall+"Clear blue glass.mat")){name="Entry display low tint glass"};glass.SetColor("_BaseColor",new Color(.66f,.85f,.9f,.065f));glass.SetFloat("_Smoothness",.45f);AssetDatabase.CreateAsset(glass,assets+"/Entry display low tint glass.mat");
  root=new GameObject("Entry display depth revision").transform;root.SetParent(entrance,false);geometry=reused=0;
  foreach(float x in new[]{-25f,-14f,14f,25f}){
   Box("Display alcove floor",new Vector3(x,.16f,-1.5f),new Vector3(6,.3f,3),stone);Box("Display warm back",new Vector3(x,2.15f,-.05f),new Vector3(6,4,.15f),wood);Box("Display recessed ceiling",new Vector3(x,4.22f,-1.5f),new Vector3(6,.18f,3),dark);
   foreach(int side in new[]{-1,1}){Box("Window depth return",new Vector3(x+side*2.93f,2.15f,-1.5f),new Vector3(.14f,4,3),stone);Box("Window front metal stile",new Vector3(x+side*2.88f,2.15f,-3.04f),new Vector3(.085f,4,.075f),metal);}
   Box("Window overhead warm strip",new Vector3(x,4.05f,-1.8f),new Vector3(5.7f,.07f,.1f),warm);Box("Clear entry display glass",new Vector3(x,2.16f,-3.03f),new Vector3(5.68f,3.96f,.025f),glass);
   foreach(int side in new[]{-1,1}){Box("Retail merchandise pedestal",new Vector3(x+side*1.25f,.63f,-1.65f),new Vector3(1.7f,.95f,1.3f),stone);Model(x<0?"RetailTote":"RetailSneaker",new Vector3(x+side*1.25f,1.11f,-1.65f),x<0?.85f:.5f,x<0?180:side*20);}
  }
  if(root.GetComponentsInChildren<Collider>(true).Length!=0)throw new Exception("Decorative collision");EditorSceneManager.MarkSceneDirty(d.gameObject.scene);if(!EditorSceneManager.SaveScene(d.gameObject.scene))throw new Exception("Save failed");AssetDatabase.SaveAssets();return new{windows=4,displayDepthMeters=3,nativeStructuralObjects=geometry,reusedGeneratedGoods=reused,newAiModels=0,addedColliders=0,centralOpeningMeters=18,goalAndTowerUnchanged=true,validation="Requires native entry approach replay; original entrance geometry retained"};
 }
}
