using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine.SceneManagement;using Object=UnityEngine.Object;
public static class FinishStreetMerge {
 static Chapter45Director d;static Transform root;static string assets;static Material brick,stone,cream;static int meshes;
 static void MeshObject(string name,List<Vector3> v,List<Vector2> uv,List<int> tri,Material mat){var mesh=new Mesh{name=name};mesh.SetVertices(v);mesh.SetUVs(0,uv);mesh.SetTriangles(tri,0);mesh.RecalculateNormals();mesh.RecalculateBounds();AssetDatabase.CreateAsset(mesh,assets+"/"+name+".asset");var g=new GameObject(name);g.transform.SetParent(root,false);g.AddComponent<MeshFilter>().sharedMesh=mesh;var rr=g.AddComponent<MeshRenderer>();rr.sharedMaterial=mat;rr.shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;meshes++;}
 static void Strip(string name,int side,float begin,float end,int band,Material mat,float y){var v=new List<Vector3>();var uv=new List<Vector2>();var tri=new List<int>();int count=Mathf.CeilToInt((end-begin)/2);for(int i=0;i<=count;i++){float distance=Mathf.Lerp(begin,end,(float)i/count);d.route.Sample(distance,out var center,out var forward);float blend=Mathf.Max(1-Mathf.SmoothStep(0,1,Mathf.InverseLerp(500,550,distance)),Mathf.SmoothStep(0,1,Mathf.InverseLerp(820,960,distance)));float road=Mathf.Lerp(4.15f,8.25f,blend),inner=Mathf.Lerp(4.2f,8.4f,blend),outer=Mathf.Lerp(7.8f,14.5f,blend);float a=band==0?-road:band==1?-outer:band==2?inner:band==3?-inner-.05f:inner-.07f;float b=band==0?road:band==1?-inner:band==2?outer:band==3?-inner+.07f:inner+.05f;float offset=side<0?0:d.choices[0].Offset(distance,side);var right=Vector3.Cross(Vector3.up,forward);v.Add(center+right*(offset+a)+Vector3.up*y);v.Add(center+right*(offset+b)+Vector3.up*y);uv.Add(new Vector2((offset+a)*.12f,distance*.12f));uv.Add(new Vector2((offset+b)*.12f,distance*.12f));if(i<count){int n=i*2;tri.AddRange(new[]{n,n+2,n+1,n+1,n+2,n+3});}}MeshObject(name,v,uv,tri,mat);}
 static void Median(){var v=new List<Vector3>();var uv=new List<Vector2>();var tri=new List<int>();for(int i=0;i<=115;i++){float distance=575+i*2;d.route.Sample(distance,out var center,out var forward);var right=Vector3.Cross(Vector3.up,forward);float width=Mathf.Max(.04f,Mathf.Abs(d.choices[0].Offset(distance,0))-5.8f);v.Add(center-right*width+Vector3.up*.11f);v.Add(center+right*width+Vector3.up*.11f);uv.Add(new Vector2(-width*.12f,distance*.12f));uv.Add(new Vector2(width*.12f,distance*.12f));if(i<115){int n=i*2;tri.AddRange(new[]{n,n+2,n+1,n+1,n+2,n+3});}}MeshObject("Central paved pocket plaza",v,uv,tri,stone);}
 static void ReuseModel(string model,float distance,float height,float offset){d.route.Sample(distance,out var center,out var forward);var holder=new GameObject("Reused "+model+" median display").transform;holder.SetParent(root,false);holder.SetPositionAndRotation(center+Vector3.Cross(Vector3.up,forward)*offset+Vector3.up*.12f,Quaternion.LookRotation(forward));var source=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/ShooterSurvival/Models/Chapters/Chapters45/RetailProduction20261003/"+model+".fbx");var g=(GameObject)PrefabUtility.InstantiatePrefab(source);g.transform.SetParent(holder,false);var rr=g.GetComponentsInChildren<Renderer>(true);var b=rr[0].bounds;foreach(var r in rr.Skip(1))b.Encapsulate(r.bounds);holder.localScale=Vector3.one*(height/b.size.y);b=rr[0].bounds;foreach(var r in rr.Skip(1))b.Encapsulate(r.bounds);g.transform.position+=holder.position-new Vector3(b.center.x,b.min.y,b.center.z);var mat=AssetDatabase.LoadAssetAtPath<Material>("Assets/ShooterSurvival/Models/Chapters/Chapters45/RetailProduction20261003/"+model+".mat");foreach(var r in rr){r.sharedMaterial=mat;r.shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;}foreach(var c in g.GetComponentsInChildren<Collider>(true))c.enabled=false;}
 public static object Main(){if(EditorApplication.isPlayingOrWillChangePlaymode||EditorApplication.isCompiling)throw new Exception("Idle required");for(int i=0;i<SceneManager.sceneCount;i++)if(SceneManager.GetSceneAt(i).isDirty)throw new Exception("Dirty scene");EditorSceneManager.OpenScene("Assets/ShooterSurvival/Scenes/Tools/Jamsil.unity");d=Object.FindFirstObjectByType<Chapter45Director>();var old=d.transform.Find("DetailedStreet_20261003/Continuous fork paving");if(old.Find("Revision01 preserved")!=null)throw new Exception("Already applied");File.Copy(d.gameObject.scene.path,"outputs/chapter45-detailed-design-2026-10-03/scene-recovery/Jamsil-before-merge-finish.unity",false);var archive=new GameObject("Revision01 preserved").transform;archive.SetParent(old,false);foreach(var t in old.Cast<Transform>().Where(t=>t!=archive).ToArray())t.SetParent(archive,true);archive.gameObject.SetActive(false);root=new GameObject("Tapered merges and planted plaza").transform;root.SetParent(old,false);old.GetComponent<Chapter45SceneryGroup>().endDistance=990;
  assets="Assets/ShooterSurvival/Models/Chapters/Chapters45/ForkMerge-"+DateTime.UtcNow.ToString("yyyyMMddTHHmmssfff");Directory.CreateDirectory(assets);AssetDatabase.Refresh();var mats=archive.GetComponentsInChildren<Renderer>(true).Select(r=>r.sharedMaterial).Distinct().ToArray();brick=mats.Single(m=>m.name=="Clay pavers");stone=mats.Single(m=>m.name=="Pavement");cream=mats.Single(m=>m.name=="Warm limestone");meshes=0;
  foreach(var section in new[]{(side:-1,start:500f,end:560f,label:"Entry"),(side:0,start:560f,end:820f,label:"Left"),(side:1,start:560f,end:820f,label:"Right"),(side:-1,start:820f,end:970f,label:"Merge")})for(int band=0;band<5;band++)Strip(section.label+" surface "+band,section.side,section.start,section.end,band,band==0?brick:band<3?stone:cream,band<3?.145f:.15f);
  Median();foreach(float distance in new[]{620f,660,700,740}){ReuseModel("RetailPlanter",distance,.85f,0);ReuseModel("RetailBench",distance+5,.65f,0);}
  EditorSceneManager.MarkSceneDirty(d.gameObject.scene);EditorSceneManager.SaveScene(d.gameObject.scene);return new{assets,newVisualMeshes=meshes,reusedPlanters=4,reusedBenches=4,addedColliders=0,retainedOriginalMeshes=true,mergeExtendsTo=970,normalCurb=8.4f,normalPavementOuter=14.5f,routeAndCombatChanged=false,validation="native end/merge capture and route recheck required"};}
}
