using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Object=UnityEngine.Object;
public static class FitCouplesAndRoleProps {
 const string Base="Assets/ShooterSurvival/Models/Chapters/Chapters45/DetailedCharacters20261003/";
 static Transform Bone(Animator a,string name)=>a.GetComponentsInChildren<Transform>(true).Single(t=>t.name==name);
 public static object Main(){if(EditorApplication.isPlayingOrWillChangePlaymode)throw new Exception("Edit required");EditorSceneManager.OpenScene("Assets/ShooterSurvival/Scenes/Tools/ShoeTower.unity");var d=Object.FindFirstObjectByType<Chapter45Director>();string backup="outputs/chapter45-detailed-design-2026-10-03/scene-recovery/ShoeTower-before-adjacent-couples.unity";File.Copy(d.gameObject.scene.path,backup,false);var rows=new List<object>();foreach(var follower in d.encounters.SelectMany(e=>e.actors).Select(a=>a.GetComponent<Chapter45RoleAction>()).Where(b=>b!=null&&b.linkedLeader!=null)){if(follower.GetComponent<Chapter45CouplePose>()!=null)throw new Exception("Pair already fitted");var leader=follower.linkedLeader;float before=Vector3.Distance(follower.transform.position,leader.transform.position);var delta=follower.transform.position-leader.transform.position;var direction=delta.normalized;var center=(follower.transform.position+leader.transform.position)*.5f;leader.transform.position=center-direction*.31f;follower.transform.position=center+direction*.31f;follower.linkedOffset=direction*.62f;var a=follower.GetComponentInChildren<Animator>(true);var partner=leader.GetComponentInChildren<Animator>(true);var pose=follower.gameObject.AddComponent<Chapter45CouplePose>();pose.follower=follower;pose.leader=leader;pose.animator=a;bool left=Vector3.Dot(leader.transform.position-follower.transform.position,follower.transform.right)<0;pose.upper=Bone(a,left?"LeftArm":"RightArm");pose.lower=Bone(a,left?"LeftForeArm":"RightForeArm");pose.hand=Bone(a,left?"LeftHand":"RightHand");pose.partnerElbow=Bone(partner,left?"RightForeArm":"LeftForeArm");EditorUtility.SetDirty(follower);rows.Add(new{follower=follower.name,leader=leader.name,before,after=.62f,centerPreserved=true,healthAndCollidersUnchanged=true});}
 var ballPath=Base+"basketball-orange.mat";var mat=AssetDatabase.LoadAssetAtPath<Material>(ballPath);if(mat==null){mat=new Material(Shader.Find("Universal Render Pipeline/Lit")){name="Basketball orange leather"};mat.SetColor("_BaseColor",new Color(.83f,.27f,.065f));mat.SetFloat("_Smoothness",.12f);AssetDatabase.CreateAsset(mat,ballPath);}foreach(var role in d.encounters.SelectMany(e=>e.actors).Select(a=>a.GetComponent<Chapter45RoleAction>()).Where(b=>b!=null&&b.role==Chapter45RoleAction.Role.Basketball)){role.heldProp.Find("Basketball").GetComponent<Renderer>().sharedMaterial=mat;}
 // The TV originally inherited the cart's cosmetic children. Keep the moving
 // trigger and warning, but give it a thin black display face and metal back.
 var tv=d.hazards.First(h=>h.name=="4F falling television");var archive=new GameObject("Preserved old TV cosmetic cart children");archive.transform.SetParent(d.transform,false);archive.SetActive(false);foreach(var old in tv.body.Cast<Transform>().ToArray())old.SetParent(archive.transform,true);var rear=tv.body.GetComponent<Renderer>();if(rear!=null)rear.sharedMaterial=AssetDatabase.LoadAssetAtPath<Material>("Assets/ShooterSurvival/Models/Chapters/Chapters45/DetailedMall-20261003T092859667/Ink graphite.mat");var screen=GameObject.CreatePrimitive(PrimitiveType.Cube);screen.name="Television dark glass display";screen.transform.SetParent(tv.body,false);screen.transform.localPosition=new Vector3(0,0,-.51f);screen.transform.localScale=new Vector3(.93f,.87f,.018f);Object.DestroyImmediate(screen.GetComponent<Collider>());screen.GetComponent<Renderer>().sharedMaterial=rear.sharedMaterial;
 EditorSceneManager.MarkSceneDirty(d.gameObject.scene);EditorSceneManager.SaveScene(d.gameObject.scene);AssetDatabase.SaveAssets();return new{couples=rows,reason="Move each pair symmetrically around its existing center so the authored arm link is physically possible; preserve encounter, health, rewards and colliders.",ballMaterial="Orange leather",tvVisualCorrected=true};}
}
