using System;using System.IO;using System.Linq;using System.Reflection;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using TMPro;using IndianOceanAssets.ShooterSurvival;using Object=UnityEngine.Object;
public static class FixPopcornCaption16 {
 const string Q="outputs/chapter45-detailed-design-2026-10-03/validation-cycle16/",Dir="Assets/ShooterSurvival/Models/Chapters/Chapters45/Content20261004Cycle16/Popcorn/";
 static string Json(object v)=>(string)AppDomain.CurrentDomain.GetAssemblies().First(a=>a.GetName().Name=="Newtonsoft.Json").GetType("Newtonsoft.Json.JsonConvert").GetMethod("SerializeObject",new[]{typeof(object)}).Invoke(null,new[]{v});
 static string Glyph(char c){switch(c){case 'P':return "11110100011000111110100001000010000";case 'O':return "01110100011000110001100011000101110";case 'C':return "01111100001000010000100001000001111";case 'R':return "11110100011000111110101001001010001";case 'N':return "10001110011010110011100011000110001";default:throw new Exception("Unexpected glyph");}}
 static void Word(Texture2D tex,string word,int bottom){int scale=8,left=(256-(word.Length*6-1)*scale)/2;for(int k=0;k<word.Length;k++){var bits=Glyph(word[k]);for(int y=0;y<7;y++)for(int x=0;x<5;x++)if(bits[y*5+x]=='1')for(int iy=0;iy<scale;iy++)for(int ix=0;ix<scale;ix++)tex.SetPixel(left+(k*6+x)*scale+ix,bottom+(6-y)*scale+iy,new Color(.68f,.04f,.04f));}}
 public static object Main(){if(EditorApplication.isPlayingOrWillChangePlaymode||EditorApplication.isCompiling)throw new Exception("Idle required");if(File.Exists(Q+"popcorn-caption-fix.json"))throw new Exception("Already fixed");var setup=EditorSceneManager.GetSceneManagerSetup();try{var scene=EditorSceneManager.OpenScene("Assets/ShooterSurvival/Scenes/Tools/ShoeTower.unity");File.Copy(scene.path,Q+"recovery/ShoeTower-before-caption-fix.unity",false);var state=AppDomain.CurrentDomain.GetAssemblies().Select(a=>a.GetType("ApplyContent16")).First(t=>t!=null).GetMethod("State",BindingFlags.Static|BindingFlags.NonPublic);string before=(string)state.Invoke(null,new object[]{scene});File.WriteAllText(Q+"caption-protected-before.txt",before);
 var role=Object.FindFirstObjectByType<Chapter45Director>().GetComponentsInChildren<Chapter45RoleAction>(true).Single(r=>r.role==Chapter45RoleAction.Role.PopcornThrower);var holder=role.heldProp.Find("ContentCycle16 generated popcorn container");var texts=holder.GetComponentsInChildren<TextMeshPro>(true);var old=texts.Select(t=>new{name=t.name,scale=t.transform.localScale.ToString(),fontSize=t.fontSize,bounds=t.GetComponent<Renderer>().bounds.size.ToString()}).ToArray();if(texts.Length!=4)throw new Exception("Expected four captions");foreach(var t in texts)t.gameObject.SetActive(false);
 var tex=new Texture2D(256,192,TextureFormat.RGBA32,false);tex.SetPixels(Enumerable.Repeat(Color.white,256*192).ToArray());Word(tex,"POP",108);Word(tex,"CORN",28);tex.Apply();string asset=Dir+"NativePrintedCaption.png";File.WriteAllBytes(asset,tex.EncodeToPNG());Object.DestroyImmediate(tex);AssetDatabase.ImportAsset(asset);var ti=(TextureImporter)AssetImporter.GetAtPath(asset);ti.mipmapEnabled=true;ti.maxTextureSize=256;ti.textureCompression=TextureImporterCompression.Uncompressed;ti.wrapMode=TextureWrapMode.Clamp;ti.SaveAndReimport();var mat=AssetDatabase.LoadAssetAtPath<Material>(Dir+"PaperCaption.mat");mat.SetTexture("_BaseMap",AssetDatabase.LoadAssetAtPath<Texture2D>(asset));EditorUtility.SetDirty(mat);AssetDatabase.SaveAssets();string after=(string)state.Invoke(null,new object[]{scene});if(before!=after)throw new Exception("Gameplay contract changed");EditorSceneManager.MarkSceneDirty(scene);if(!EditorSceneManager.SaveScene(scene))throw new Exception("Save failed");scene=EditorSceneManager.OpenScene(scene.path);after=(string)state.Invoke(null,new object[]{scene});File.WriteAllText(Q+"caption-protected-after.txt",after);if(before!=after)throw new Exception("Reopened contract changed");var report=new{saved=true,observedProblem="Oversized world TMP lettering obscured actual Play; failed images retained in exact-popcorn",resolution="Four authored paper panels now share a 256x192 native printed POP CORN texture; old text objects retained inactive",oldText=old,nativeOnly=true,newPaidCalls=0,gameplayComponentsUnchanged=true,utc=DateTime.UtcNow};File.WriteAllText(Q+"popcorn-caption-fix.json",Json(report));return report;}finally{EditorSceneManager.RestoreSceneManagerSetup(setup);}}
}
