using System;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Object=UnityEngine.Object;
public static class ImportDetailedModels {
 const string Dir="Assets/ShooterSurvival/Models/Chapters/Chapters45/DetailedMall-20261003T092859667/GeneratedModels";
 static GameObject Import(string name){
  string path=Dir+"/"+name+".fbx";var mi=AssetImporter.GetAtPath(path) as ModelImporter;if(mi==null)throw new Exception(path);mi.materialImportMode=ModelImporterMaterialImportMode.None;mi.animationType=ModelImporterAnimationType.None;mi.importAnimation=false;mi.isReadable=false;mi.SaveAndReimport();
  var texPath=Dir+"/"+name+"_M0_0.png";var ti=(TextureImporter)AssetImporter.GetAtPath(texPath);ti.textureType=TextureImporterType.Default;ti.sRGBTexture=true;ti.maxTextureSize=2048;ti.mipmapEnabled=true;ti.textureCompression=TextureImporterCompression.Compressed;ti.SetPlatformTextureSettings(new TextureImporterPlatformSettings{name="Android",overridden=true,maxTextureSize=1024,format=TextureImporterFormat.ASTC_6x6,compressionQuality=50});ti.SaveAndReimport();
  var mat=AssetDatabase.LoadAssetAtPath<Material>(Dir+"/"+name+".mat");if(mat==null){mat=new Material(Shader.Find("Universal Render Pipeline/Lit")){name=name+" generated base color",enableInstancing=true};AssetDatabase.CreateAsset(mat,Dir+"/"+name+".mat");}mat.SetTexture("_BaseMap",AssetDatabase.LoadAssetAtPath<Texture2D>(texPath));mat.SetColor("_BaseColor",Color.white);mat.SetFloat("_Smoothness",name.Contains("Washer")?.35f:.18f);
  var source=AssetDatabase.LoadAssetAtPath<GameObject>(path);var imported=(GameObject)PrefabUtility.InstantiatePrefab(source);var g=new GameObject(name);imported.transform.SetParent(g.transform,false);imported.transform.localPosition=Vector3.zero;var renderers=g.GetComponentsInChildren<MeshRenderer>();foreach(var renderer in renderers){renderer.sharedMaterial=mat;renderer.shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;}
  var b=renderers[0].bounds;foreach(var rr in renderers)b.Encapsulate(rr.bounds);if(Mathf.Abs(b.size.y-1)>.03f||Mathf.Abs(b.min.y)>.03f)throw new Exception("Unexpected native axes/pivot for "+name+": "+b);
  var prefab=PrefabUtility.SaveAsPrefabAsset(g,Dir+"/"+name+".prefab");Object.DestroyImmediate(g);return prefab;
 }
 public static object Main(){
  if(EditorApplication.isPlayingOrWillChangePlaymode||EditorApplication.isCompiling)throw new Exception("Idle required");EditorSceneManager.OpenScene("Assets/ShooterSurvival/Scenes/Tools/ShoeTower.unity");AssetDatabase.Refresh();var d=Object.FindFirstObjectByType<Chapter45Director>();var root=d.transform.Find("DetailedMall_20261003");if(root.GetComponentsInChildren<Transform>(true).Any(t=>t.name=="Generated cinema seat row"))throw new Exception("Already applied");
  var chair=Import("DetailedCinemaSeat");var washer=Import("DetailedWasher");var floors=root.Find("Scenery");var cinema=floors.Cast<Transform>().Single(t=>t.name.StartsWith("6F "));var living=floors.Cast<Transform>().Single(t=>t.name.StartsWith("4F "));int seats=0,washers=0;
  for(int row=0;row<4;row++)foreach(float x in new[]{-4f,0,4,26,30,34}){var g=(GameObject)PrefabUtility.InstantiatePrefab(chair);g.name="Generated cinema seat row";g.transform.SetParent(cinema,false);g.transform.localPosition=new Vector3(x,0,8+row*4);g.transform.localRotation=Quaternion.Euler(0,180,0);g.transform.localScale=Vector3.one*1.15f;seats++;}
  foreach(var shop in living.Cast<Transform>().Where(t=>t.name.Contains("storefront"))){foreach(float x in new[]{-1.4f,1.4f}){var g=(GameObject)PrefabUtility.InstantiatePrefab(washer);g.name="Generated washer wall-backed display";g.transform.SetParent(shop,false);g.transform.localPosition=new Vector3(x,0,-3.7f);g.transform.localRotation=Quaternion.identity;g.transform.localScale=Vector3.one*.88f;washers++;}}
  EditorSceneManager.MarkSceneDirty(d.gameObject.scene);EditorSceneManager.SaveScene(d.gameObject.scene);AssetDatabase.SaveAssets();
  return new{seats,washers,seatsTriangles=3584*seats,washerTriangles=3572*washers,colliders=0,centralAisleWidth=18,androidTexture="1024 ASTC6x6, shared mipmapped texture per model",generatedModels=2,washerAuthoredFinishing="door inset and bezel; generated body/texture retained; wall-backed display only",review="Native bounds/pivot/material import validated; saved-play visual review pending"};
 }
}
