using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine.SceneManagement;using Object=UnityEngine.Object;
public static class ImportGeneratedVehicles {
 const string Base="Assets/ShooterSurvival/Models/Chapters/Chapters45/DetailedMall-20261003T092859667/";
 const string Dir="Assets/ShooterSurvival/Models/Chapters/Chapters45/DetailedVehicles20261003";
 static readonly List<object> audit=new();
 static GameObject Import(string name){
  var mi=AssetImporter.GetAtPath(Dir+"/"+name+".fbx") as ModelImporter;if(mi==null)throw new Exception("Missing model "+name);mi.materialImportMode=ModelImporterMaterialImportMode.None;mi.animationType=ModelImporterAnimationType.None;mi.importAnimation=false;mi.isReadable=false;mi.SaveAndReimport();
  string texPath=Dir+"/"+name+"_M0_0.png";var ti=(TextureImporter)AssetImporter.GetAtPath(texPath);ti.textureType=TextureImporterType.Default;ti.sRGBTexture=true;ti.maxTextureSize=2048;ti.mipmapEnabled=true;ti.textureCompression=TextureImporterCompression.Compressed;ti.SetPlatformTextureSettings(new TextureImporterPlatformSettings{name="Android",overridden=true,maxTextureSize=1024,format=TextureImporterFormat.ASTC_6x6,compressionQuality=50});ti.SaveAndReimport();
  var mat=new Material(Shader.Find("Universal Render Pipeline/Lit")){name=name+" generated base color",enableInstancing=true};mat.SetTexture("_BaseMap",AssetDatabase.LoadAssetAtPath<Texture2D>(texPath));mat.SetColor("_BaseColor",Color.white);mat.SetFloat("_Smoothness",name.Contains("Vacuum")?.3f:.16f);AssetDatabase.CreateAsset(mat,Dir+"/"+name+".mat");
  var source=AssetDatabase.LoadAssetAtPath<GameObject>(Dir+"/"+name+".fbx");var g=new GameObject(name);var imported=(GameObject)PrefabUtility.InstantiatePrefab(source);imported.transform.SetParent(g.transform,false);imported.transform.localPosition=Vector3.zero;
  var rr=g.GetComponentsInChildren<MeshRenderer>(true);foreach(var r in rr){r.sharedMaterial=mat;r.shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;}var b=rr[0].bounds;foreach(var r in rr.Skip(1))b.Encapsulate(r.bounds);int triangles=g.GetComponentsInChildren<MeshFilter>(true).Sum(m=>(int)m.sharedMesh.GetIndexCount(0)/3);
  if(Mathf.Abs(b.size.y-1)>.03f||Mathf.Abs(b.min.y)>.03f||triangles>(name=="DetailedDeliveryBike"?16000:3600)||g.GetComponentsInChildren<Collider>(true).Length!=0)throw new Exception("Model native contract failed: "+name+" "+b+" tris"+triangles);
  audit.Add(new{name,triangles,height=b.size.y,bottom=b.min.y,size=new[]{b.size.x,b.size.y,b.size.z},sourceRotationPreserved=Quaternion.Angle(source.transform.localRotation,imported.transform.localRotation)<.01f,colliders=0,android="1024 ASTC6x6 mipmaps"});var prefab=PrefabUtility.SaveAsPrefabAsset(g,Dir+"/"+name+".prefab");Object.DestroyImmediate(g);return prefab;
 }
 static void Place(GameObject prefab,Transform parent,string label,Vector3 position,float height,float yaw=0){var g=(GameObject)PrefabUtility.InstantiatePrefab(prefab);g.name=label;g.transform.SetParent(parent,false);g.transform.localPosition=position;g.transform.localRotation=Quaternion.Euler(0,yaw,0);g.transform.localScale=Vector3.one*height;}
 static GameObject Box(Transform p,string n,Vector3 pos,Vector3 size,Material mat){var g=GameObject.CreatePrimitive(PrimitiveType.Cube);g.name=n;g.transform.SetParent(p,false);g.transform.localPosition=pos;g.transform.localScale=size;g.GetComponent<Renderer>().sharedMaterial=mat;g.GetComponent<Renderer>().shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;Object.DestroyImmediate(g.GetComponent<Collider>());return g;}
 public static object Main(){if(EditorApplication.isPlayingOrWillChangePlaymode||EditorApplication.isCompiling)throw new Exception("Idle required");AssetDatabase.Refresh(ImportAssetOptions.ForceSynchronousImport);audit.Clear();Import("DetailedKickboard");Import("DetailedDeliveryBike");AssetDatabase.SaveAssets();return new{models=audit.ToArray(),sceneApplied=false};}
}
