using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;
public static class InspectRoleCharacterImport {
 const string Base="Assets/ShooterSurvival/Models/Chapters/Chapters45/DetailedCharacters20261003/";
 public static object Main(string ids){if(EditorApplication.isPlayingOrWillChangePlaymode)throw new Exception("Edit Mode required");AssetDatabase.Refresh(ImportAssetOptions.ForceSynchronousImport);var rows=new List<object>();foreach(var id in ids.Split(',')){
  string folder=Base+id,body=folder+"/body.fbx";var mi=(ModelImporter)AssetImporter.GetAtPath(body);mi.animationType=ModelImporterAnimationType.Generic;mi.avatarSetup=ModelImporterAvatarSetup.CreateFromThisModel;mi.importAnimation=false;mi.importCameras=mi.importLights=mi.addCollider=false;mi.isReadable=true;mi.materialImportMode=ModelImporterMaterialImportMode.ImportStandard;mi.SaveAndReimport();mi.ExtractTextures(folder);AssetDatabase.Refresh(ImportAssetOptions.ForceSynchronousImport);var avatar=AssetDatabase.LoadAllAssetsAtPath(body).OfType<Avatar>().First();var root=AssetDatabase.LoadAssetAtPath<GameObject>(body);
  foreach(var path0 in Directory.GetFiles(folder,"*.fbx")){var path=path0.Replace('\\','/');if(path==body)continue;var ai=(ModelImporter)AssetImporter.GetAtPath(path);ai.animationType=ModelImporterAnimationType.Generic;ai.avatarSetup=ModelImporterAvatarSetup.CopyFromOther;ai.sourceAvatar=avatar;ai.importAnimation=true;ai.materialImportMode=ModelImporterMaterialImportMode.None;ai.animationCompression=ModelImporterAnimationCompression.Off;ai.importCameras=ai.importLights=ai.addCollider=false;ai.SaveAndReimport();rows.Add(new{id,file=Path.GetFileName(path),takes=ai.defaultClipAnimations.Select(c=>new{c.name,c.takeName,c.firstFrame,c.lastFrame}).ToArray(),clips=AssetDatabase.LoadAllAssetsAtPath(path).OfType<AnimationClip>().Where(c=>!c.name.StartsWith("__preview")).Select(c=>new{c.name,c.length,c.frameRate,bindings=AnimationUtility.GetCurveBindings(c).Select(b=>b.path).Distinct().Take(12).ToArray()}).ToArray()});}
  rows.Add(new{id,avatarValid=avatar.isValid,rootScale=new[]{root.transform.localScale.x,root.transform.localScale.y,root.transform.localScale.z},rootEuler=new[]{root.transform.localEulerAngles.x,root.transform.localEulerAngles.y,root.transform.localEulerAngles.z},bones=root.GetComponentsInChildren<Transform>(true).Select(t=>AnimationUtility.CalculateTransformPath(t,root.transform)).ToArray(),triangles=root.GetComponentsInChildren<SkinnedMeshRenderer>(true).Sum(r=>r.sharedMesh.triangles.Length/3)});
 }AssetDatabase.SaveAssets();return new{items=rows};}
}
