if(UnityEditor.EditorApplication.isPlayingOrWillChangePlaymode)throw new System.InvalidOperationException("Edit Mode required");
var scene=UnityEngine.SceneManagement.SceneManager.GetSceneByPath("Assets/ShooterSurvival/Scenes/Tools/Noryangjin_MapTool_Mode_SR18.unity");
var map=scene.GetRootGameObjects().Single(g=>g.name=="Noryangjin_MapTool").transform;
var defaults=UnityEditor.AssetDatabase.LoadAssetAtPath<NoryangjinMapToolPaletteDefaults>("Assets/ShooterSurvival/Editor/NoryangjinMapToolPaletteDefaults.asset");
var entries=(System.Collections.Generic.List<NoryangjinMapToolPalettePlacementEntry>)typeof(NoryangjinMapToolPaletteDefaults).GetField("entries",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).GetValue(defaults);
var paths=new[]{"Assets/JH/Model/Prefab/Enemy_OldMan.prefab","Assets/JH/Model/Prefab/Enemy_YllowMan_Net.prefab","Assets/JH/Model/Prefab/Enemy_YllowMan_Sword.prefab","Assets/JH/Model/Prefab/Enemy_Guard.prefab","Assets/JH/Model/Prefab/Enemy_FatMan.prefab","Assets/JH/Model/Prefab/Enemy_Woman.prefab","Assets/ShooterSurvival/Prefabs/Walls/New/Box_left.prefab","Assets/ShooterSurvival/Prefabs/Gameplay/Noryangjin_EnemyMovementTrigger.prefab"};
var prefabs=paths.Select(path=>{var go=UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.GameObject>(path);var e=entries.FirstOrDefault(x=>x.prefabPath==path);return new{path,rootScale=go.transform.localScale.ToString("F3"),paletteScale=e==null?"none":e.scale.ToString("F3"),height=e==null?0:e.heightOffset,rotation=e==null?0:e.yawOffset,colliders=go.GetComponentsInChildren<UnityEngine.Collider>(true).Select(c=>new{type=c.GetType().Name,c.name,scale=c.transform.lossyScale.ToString("F3"),serialized=UnityEditor.EditorJsonUtility.ToJson(c)}).ToArray()};}).ToArray();
var player=scene.GetRootGameObjects().Single(g=>g.name=="Noryangjin_Player");
return new{scene.isDirty,roots=scene.GetRootGameObjects().Select(g=>g.name),parts=map.Cast<UnityEngine.Transform>().Select(t=>new{t.name,t.childCount}),player=UnityEditor.EditorJsonUtility.ToJson(player.GetComponent<IndianOceanAssets.ShooterSurvival.PlayerScript>()),prefabs};
