using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.Animations;using UnityEditor.SceneManagement;using IndianOceanAssets.ShooterSurvival;using Object=UnityEngine.Object;
public static class InstallGeneratedRoleVisuals {
 const string Base="Assets/ShooterSurvival/Models/Chapters/Chapters45/DetailedCharacters20261003/", Mall="Assets/ShooterSurvival/Models/Chapters/Chapters45/DetailedMall-20261003T092859667/";
 static Transform archive;static int counter;static readonly List<object> report=new();
 static Transform Group(Transform p,string name){var g=new GameObject(name);g.transform.SetParent(p,false);return g.transform;}
 static Material Mat(string name)=>AssetDatabase.LoadAssetAtPath<Material>(Mall+name+".mat");
 static Transform Primitive(Transform p,string name,PrimitiveType type,Vector3 pos,Vector3 size,Material material){var g=GameObject.CreatePrimitive(type);g.name=name;g.transform.SetParent(p,false);g.transform.localPosition=pos;g.transform.localScale=size;Object.DestroyImmediate(g.GetComponent<Collider>());g.GetComponent<Renderer>().sharedMaterial=material;g.GetComponent<Renderer>().shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;return g.transform;}
 static Transform Bone(Animator a,string name)=>a.GetComponentsInChildren<Transform>(true).Single(t=>t.name==name);
 static void Preserve(Transform visual,string owner){visual.name=owner+" / "+visual.name;visual.SetParent(archive,true);visual.gameObject.SetActive(false);}
 static string Id(Chapter45RoleAction b,int index){switch(b.role){case Chapter45RoleAction.Role.Promoter:case Chapter45RoleAction.Role.Guard:case Chapter45RoleAction.Role.Manager:return "CH01";case Chapter45RoleAction.Role.Basketball:return "CH02";case Chapter45RoleAction.Role.Golfer:return "CH03";case Chapter45RoleAction.Role.StudentGrab:return "CH04R";case Chapter45RoleAction.Role.Preacher:return "CH05";case Chapter45RoleAction.Role.ShoppingBags:return "CH06R";case Chapter45RoleAction.Role.LinkedCouple:return b.linkedLeader==null?"CH07":"CH08";case Chapter45RoleAction.Role.Cleaner:case Chapter45RoleAction.Role.PlateThrower:case Chapter45RoleAction.Role.PopcornThrower:return "CH10";default:return new[]{"CH07","CH08","CH09"}[index%3];}}
 static AnimatorController Controller(string id,string variant,float warning=1.1f){string path=Base+id+"/role-"+variant+".controller";var existing=AssetDatabase.LoadAssetAtPath<AnimatorController>(path);if(existing!=null)return existing;var original=AssetDatabase.LoadAssetAtPath<AnimatorController>(Base+id+"/character.controller");var controller=AnimatorController.CreateAnimatorControllerAtPath(path);var sm=controller.layers[0].stateMachine;foreach(var child in original.layers[0].stateMachine.states){var source=child.state;var state=sm.AddState(source.name);string clip=source.motion.name;if(variant=="Guard"||variant=="Manager"){if(source.name.StartsWith("attack"))clip="guard";}if(variant=="Basketball"&&source.name=="walk")clip="dribble";if(variant=="Cleaner"&&source.name.StartsWith("attack"))clip="mop";if(variant=="ShoppingBags"&&(source.name=="walk"||source.name=="idle"))clip="handbag";if(variant=="PhoneShopper"&&(source.name=="idle"||source.name=="walk"))clip="phone";if(variant=="kickride"||variant=="bikeride")clip=variant;var motion=AssetDatabase.LoadAssetAtPath<AnimationClip>(Base+id+"/"+clip+".anim");if(motion==null)throw new Exception("Missing own rig motion "+id+"/"+clip);state.motion=motion;state.speed=source.speed;if(source.name=="attack_once"||source.name=="attack_loop")state.speed=motion.length/(warning+(variant=="Promoter"||variant=="PopcornThrower"||variant=="PlateThrower"?.25f:.65f));if(source.name=="idle")sm.defaultState=state;}return controller;}
 static GameObject Visual(Transform actor,string id,string variant,float warning=1.1f){var visual=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>(Base+id+"/"+id+".prefab"),actor);visual.name="Generated role "+id+" "+variant;var animator=visual.GetComponentInChildren<Animator>();animator.runtimeAnimatorController=Controller(id,variant,warning);return visual;}
 static Chapter45HandProps Hand(Transform actor,Animator a,Chapter45HandProps.Style style,Transform prop){var bind=prop.gameObject.AddComponent<Chapter45HandProps>();bind.actor=actor;bind.animator=a;bind.style=style;bind.rightHand=Bone(a,"RightHand");bind.rightForearm=Bone(a,"RightForeArm");bind.leftHand=Bone(a,"LeftHand");bind.leftForearm=Bone(a,"LeftForeArm");bind.leftUpperArm=Bone(a,"LeftArm");bind.prop=prop;bind.gripRotationOffset=Quaternion.Inverse(bind.rightHand.rotation)*actor.rotation;return bind;}
 static void Props(Chapter45RoleAction role,Animator animator){if(role.heldProp!=null)Preserve(role.heldProp,role.name);role.heldProp=null;role.propFollowsSkeleton=true;role.animationBeginsDuringWarning=true;var p=Group(role.transform,"Generated rig hand prop "+role.role);Chapter45HandProps binding=null;switch(role.role){
 case Chapter45RoleAction.Role.Basketball:
  Primitive(p,"Basketball",PrimitiveType.Sphere,Vector3.zero,Vector3.one*.42f,Mat("Warm oak"));binding=Hand(role.transform,animator,Chapter45HandProps.Style.Basketball,p);break;
 case Chapter45RoleAction.Role.Golfer:case Chapter45RoleAction.Role.Cleaner:
  bool mop=role.role==Chapter45RoleAction.Role.Cleaner;float length=mop?1.08f:.84f;Primitive(p,"Hand grip",PrimitiveType.Cylinder,new Vector3(0,-.07f,0),new Vector3(.025f,.10f,.025f),Mat("Ink graphite"));Primitive(p,"Brushed steel shaft",PrimitiveType.Cylinder,new Vector3(0,-length*.5f,0),new Vector3(.013f,length*.5f,.013f),Mat("Satin champagne metal"));Primitive(p,mop?"Cotton mop head":"Golf iron head",mop?PrimitiveType.Capsule:PrimitiveType.Cube,new Vector3(mop?0:.045f,-length,0),mop?new Vector3(.40f,.05f,.16f):new Vector3(.13f,.06f,.08f),Mat(mop?"Porcelain":"Satin champagne metal"));binding=Hand(role.transform,animator,Chapter45HandProps.Style.TwoHandTool,p);break;
 case Chapter45RoleAction.Role.PhoneShopper:
  Primitive(p,"Phone casing",PrimitiveType.Cube,Vector3.zero,new Vector3(.082f,.155f,.014f),Mat("Ink graphite"));Primitive(p,"Phone lit screen",PrimitiveType.Cube,new Vector3(0,0,-.009f),new Vector3(.070f,.132f,.003f),Mat("Porcelain"));binding=Hand(role.transform,animator,Chapter45HandProps.Style.Phone,p);binding.gripRotationOffset=Quaternion.Inverse(binding.rightHand.rotation)*role.transform.rotation*Quaternion.Euler(30,0,0);break;
 case Chapter45RoleAction.Role.Promoter:
  for(int i=0;i<5;i++)Primitive(p,"Sample card "+i,PrimitiveType.Cube,new Vector3((i-2)*.025f,0,-i*.006f),new Vector3(.11f,.17f,.003f),Mat(i%2==0?"Porcelain":"Warm oak")).localRotation=Quaternion.Euler(0,0,(i-2)*12);binding=Hand(role.transform,animator,Chapter45HandProps.Style.Palm,p);binding.useLeftHand=true;binding.gripRotationOffset=Quaternion.Inverse(binding.leftHand.rotation)*role.transform.rotation;break;
 case Chapter45RoleAction.Role.PopcornThrower:
  Primitive(p,"Popcorn paper cup",PrimitiveType.Cylinder,new Vector3(0,-.04f,0),new Vector3(.19f,.14f,.19f),Mat("Warm oak"));for(int i=0;i<7;i++)Primitive(p,"Popcorn kernel "+i,PrimitiveType.Sphere,new Vector3(Mathf.Cos(i*2.4f)*.06f,.11f+(i%2)*.02f,Mathf.Sin(i*2.4f)*.06f),Vector3.one*.08f,Mat("Porcelain"));binding=Hand(role.transform,animator,Chapter45HandProps.Style.Palm,p);binding.useLeftHand=true;binding.gripRotationOffset=Quaternion.Inverse(binding.leftHand.rotation)*role.transform.rotation;break;
 case Chapter45RoleAction.Role.PlateThrower:
  Primitive(p,"Porcelain plate",PrimitiveType.Cylinder,Vector3.zero,new Vector3(.32f,.014f,.32f),Mat("Porcelain"));Primitive(p,"Plate inset",PrimitiveType.Cylinder,new Vector3(0,.015f,0),new Vector3(.25f,.005f,.25f),Mat("Warm oak"));binding=Hand(role.transform,animator,Chapter45HandProps.Style.Palm,p);break;
 case Chapter45RoleAction.Role.ShoppingBags:
  var bag=Object.Instantiate(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/ShooterSurvival/Models/Chapters/Chapters45/RetailProduction20261003/RetailTote.fbx"),p);foreach(var r in bag.GetComponentsInChildren<Renderer>()){r.sharedMaterial=AssetDatabase.LoadAssetAtPath<Material>("Assets/ShooterSurvival/Models/Chapters/Chapters45/RetailProduction20261003/RetailTote.mat");r.shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;}var bounds=bag.GetComponentsInChildren<Renderer>().First().bounds;foreach(var r in bag.GetComponentsInChildren<Renderer>().Skip(1))bounds.Encapsulate(r.bounds);bag.transform.localScale*=.40f/bounds.size.y;bounds=bag.GetComponentsInChildren<Renderer>().First().bounds;foreach(var r in bag.GetComponentsInChildren<Renderer>().Skip(1))bounds.Encapsulate(r.bounds);bag.transform.position-=new Vector3(bounds.center.x-p.position.x,bounds.max.y-p.position.y,bounds.center.z-p.position.z);binding=Hand(role.transform,animator,Chapter45HandProps.Style.ShoppingBag,p);break;
 }
 if(binding!=null){role.heldProp=p;binding.ApplyPose();}else p.gameObject.SetActive(false);
 var socket=Group(Bone(animator,"RightHand"),"Role projectile release");socket.localPosition=Vector3.zero;role.projectileOrigin=socket;
 }
 static void Replace(EnemyScript_space actor,string id,string variant,Chapter45RoleAction role){var colliders=actor.GetComponents<Collider>().Select(c=>EditorJsonUtility.ToJson(c)).ToArray();var stats=EditorJsonUtility.ToJson(actor);var old=actor.transform.Cast<Transform>().Where(t=>t.GetComponentsInChildren<Animator>(true).Length>0).ToArray();if(old.Length!=1)throw new Exception("Expected one old visual "+actor.name);Preserve(old[0],actor.name);var visual=Visual(actor.transform,id,variant,role!=null?role.warningSeconds:1.1f);var animator=visual.GetComponentInChildren<Animator>();if(role!=null)Props(role,animator);if(actor.GetComponentsInChildren<Animator>(true).Length!=1)throw new Exception("Ambiguous animator "+actor.name);if(!colliders.SequenceEqual(actor.GetComponents<Collider>().Select(c=>EditorJsonUtility.ToJson(c)))||stats!=EditorJsonUtility.ToJson(actor))throw new Exception("Combat contract changed "+actor.name);report.Add(new{actor=actor.name,id,variant,oldVisual=old[0].name,collidersPreserved=true,statsPreserved=true,animators=1});}
 public static object Main(string scene){if(EditorApplication.isPlayingOrWillChangePlaymode||EditorApplication.isCompiling)throw new Exception("Idle required");string scenePath="Assets/ShooterSurvival/Scenes/Tools/"+scene+".unity";EditorSceneManager.OpenScene(scenePath);var d=Object.FindFirstObjectByType<Chapter45Director>();if(d.transform.Find("Preserved_PreOwnRig_20261003")!=null)throw new Exception("Already installed");string backup="outputs/chapter45-detailed-design-2026-10-03/scene-recovery/"+scene+"-before-own-role-rigs.unity";if(File.Exists(backup))throw new Exception("Backup exists; inspect before retry");File.Copy(scenePath,backup,false);archive=Group(d.transform,"Preserved_PreOwnRig_20261003");archive.gameObject.SetActive(false);counter=0;report.Clear();var actors=d.encounters.SelectMany(e=>e.actors).ToArray();foreach(var actor in actors){var role=actor.GetComponent<Chapter45RoleAction>();if(role==null)continue;if(actor.name.Contains("A03_kid"))continue;Replace(actor,Id(role,counter++),role.role.ToString(),role);}foreach(var holdout in d.GetComponentsInChildren<RestStopHoldout>(true)){foreach(var controller in holdout.police){var actor=controller.GetComponent<EnemyScript_space>();Replace(actor,new[]{"CH07","CH08","CH09"}[counter++%3],"Audience",null);}}EditorSceneManager.MarkSceneDirty(d.gameObject.scene);EditorSceneManager.SaveScene(d.gameObject.scene);AssetDatabase.SaveAssets();return new{scene,applied=report.Count,items=report,archive=archive.name,contract="Existing actor roots, health/reward components, colliders, encounter refs, floor routes and timings preserved; new visual children only."};}
}
