using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using Object=UnityEngine.Object;
public static class NormalizeRoleMotionClips {
 const string Base="Assets/ShooterSurvival/Models/Chapters/Chapters45/DetailedCharacters20261003/";
 static EditorCurveBinding B(string path,string name)=>EditorCurveBinding.FloatCurve(path,typeof(Transform),name);
 static void Write(AnimationClip clip,string path,string property,AnimationCurve curve){for(int i=0;i<curve.length;i++){AnimationUtility.SetKeyLeftTangentMode(curve,i,AnimationUtility.TangentMode.Linear);AnimationUtility.SetKeyRightTangentMode(curve,i,AnimationUtility.TangentMode.Linear);}AnimationUtility.SetEditorCurve(clip,B(path,property),curve);}
 static Bounds BoundsOf(Transform model,Transform space){bool first=true;var b=new Bounds();foreach(var r in model.GetComponentsInChildren<SkinnedMeshRenderer>(true)){var m=new Mesh();r.BakeMesh(m,false);foreach(var v in m.vertices){var p=space.InverseTransformPoint(r.transform.TransformPoint(v));if(first){b=new Bounds(p,Vector3.zero);first=false;}else b.Encapsulate(p);}Object.DestroyImmediate(m);}return b;}
 static float[] V(Vector3 p)=>new[]{p.x,p.y,p.z};
 public static object Main(string ids){if(EditorApplication.isPlayingOrWillChangePlaymode)throw new Exception("Edit required");var report=new List<object>();foreach(var id in ids.Split(',')){
  string folder=Base+id,backup="outputs/chapter45-detailed-design-2026-10-03/recovery/motion-units-"+id;if(Directory.Exists(backup))throw new Exception("Already normalized "+id);Directory.CreateDirectory(backup);var body=AssetDatabase.LoadAssetAtPath<GameObject>(folder+"/body.fbx");var armature=body.transform.Find("Armature");var clips=Directory.GetFiles(folder,"*.anim").Select(p=>AssetDatabase.LoadAssetAtPath<AnimationClip>(p.Replace('\\','/'))).ToArray();foreach(var clip in clips)File.Copy(AssetDatabase.GetAssetPath(clip),backup+"/"+clip.name+".anim",false);
  (string,string)[] custom=id switch {
   "CH01"=>new[]{("attack_once","throw"),("attack_loop","throw")},
   "CH02"=>new[]{("attack_once","charge"),("attack_loop","charge"),("dribble","dribble")},
   "CH04R" or "CH05"=>new[]{("attack_once","grab"),("attack_loop","grab")},
   "CH07"=>new[]{("kickride","kickride"),("bikeride","bikeride")},
   "CH10"=>new[]{("attack_once","popcorn"),("attack_loop","popcorn"),("mop","mop")},
   _=>Array.Empty<(string,string)>()};

  foreach(var pair in custom){var clip=clips.Single(c=>c.name==pair.Item1);var imported=AssetDatabase.LoadAssetAtPath<GameObject>(folder+"/"+pair.Item2+".fbx").transform.Find("Armature");var basis=Quaternion.Inverse(armature.localRotation)*imported.localRotation;float factor=imported.localScale.x/armature.localScale.x;if(Mathf.Abs(factor-.01f)>.00001f||Quaternion.Angle(basis,Quaternion.Euler(90,0,0))>.1f)throw new Exception("Unexpected source unit/basis "+id);
   foreach(var binding in AnimationUtility.GetCurveBindings(clip).Where(b=>b.propertyName.StartsWith("m_LocalPosition"))){var source=AnimationUtility.GetEditorCurve(clip,binding);var keys=source.keys;for(int k=0;k<keys.Length;k++){keys[k].value*=factor;keys[k].inTangent*=factor;keys[k].outTangent*=factor;}source.keys=keys;AnimationUtility.SetEditorCurve(clip,binding,source);}
   string hip="Armature/Hips";var pos="xyz".Select(a=>AnimationUtility.GetEditorCurve(clip,B(hip,"m_LocalPosition."+a))).ToArray();var rot="xyzw".Select(a=>AnimationUtility.GetEditorCurve(clip,B(hip,"m_LocalRotation."+a))).ToArray();if(pos.Any(c=>c==null)||rot.Any(c=>c==null))throw new Exception("Missing sampled hip transform");var pc=Enumerable.Range(0,3).Select(_=>new AnimationCurve()).ToArray();var rc=Enumerable.Range(0,4).Select(_=>new AnimationCurve()).ToArray();var rest=body.transform.Find(hip).localPosition;
   for(int frame=0;frame<=Mathf.CeilToInt(clip.length*30);frame++){float time=Mathf.Min(clip.length,frame/30f);Vector3 p=basis*new Vector3(pos[0].Evaluate(time),pos[1].Evaluate(time),pos[2].Evaluate(time));p.x=rest.x;p.y=rest.y;var q=basis*new Quaternion(rot[0].Evaluate(time),rot[1].Evaluate(time),rot[2].Evaluate(time),rot[3].Evaluate(time));for(int a=0;a<3;a++)pc[a].AddKey(time,p[a]);for(int a=0;a<4;a++)rc[a].AddKey(time,q[a]);}
   for(int a=0;a<3;a++)Write(clip,hip,"m_LocalPosition."+"xyz"[a],pc[a]);for(int a=0;a<4;a++)Write(clip,hip,"m_LocalRotation."+"xyzw"[a],rc[a]);
   for(int a=0;a<3;a++)Write(clip,"Armature","m_LocalPosition."+"xyz"[a],AnimationCurve.Constant(0,clip.length,armature.localPosition[a]));for(int a=0;a<4;a++)Write(clip,"Armature","m_LocalRotation."+"xyzw"[a],AnimationCurve.Constant(0,clip.length,armature.localRotation[a]));clip.EnsureQuaternionContinuity();EditorUtility.SetDirty(clip);
  }
  string prefabPath=folder+"/"+id+".prefab";var prefab=PrefabUtility.LoadPrefabContents(prefabPath);try{var animator=prefab.GetComponentInChildren<Animator>(true);animator.enabled=false;var model=animator.transform;var hips=model.Find("Armature/Hips");foreach(var clip in clips){var curves=new[]{new AnimationCurve(),new AnimationCurve(),new AnimationCurve()};for(int frame=0;frame<=Mathf.CeilToInt(clip.length*30);frame++){float time=Mathf.Min(clip.length,frame/30f);clip.SampleAnimation(model.gameObject,time);var b=BoundsOf(model,prefab.transform);var original=hips.localPosition;var unit=hips.parent.InverseTransformVector(prefab.transform.TransformVector(Vector3.up));hips.localPosition=original+unit*.1f;float response=(BoundsOf(model,prefab.transform).min.y-b.min.y)/.1f;hips.localPosition=original;if(response<.001f)throw new Exception("Invalid hips response");var p=original+unit*((.008f-b.min.y)/response);for(int a=0;a<3;a++)curves[a].AddKey(time,p[a]);}for(int a=0;a<3;a++)Write(clip,"Armature/Hips","m_LocalPosition."+"xyz"[a],curves[a]);EditorUtility.SetDirty(clip);}
   var samples=new List<object>();foreach(var clip in clips)foreach(float phase in new[]{0f,.25f,.5f,.75f,.99f}){clip.SampleAnimation(model.gameObject,clip.length*phase);var b=BoundsOf(model,prefab.transform);samples.Add(new{state=clip.name,phase,height=b.size.y,bottom=b.min.y,center=V(b.center),rightHand=V(prefab.transform.InverseTransformPoint(model.GetComponentsInChildren<Transform>(true).Single(t=>t.name=="RightHand").position))});if(b.size.y>3||b.size.y<.2f||b.min.y<-.04f||b.min.y>.05f)throw new Exception("Invalid normalized bounds "+id+"/"+clip.name+" "+b);}
   clips.Single(c=>c.name=="idle").SampleAnimation(model.gameObject,0);animator.enabled=true;PrefabUtility.SaveAsPrefabAsset(prefab,prefabPath);report.Add(new{id,customFiles=custom.Select(p=>p.Item2).Distinct().ToArray(),basisDegrees=90,positionScale=.01f,rootTravelRemoved=true,samples});
  }finally{PrefabUtility.UnloadPrefabContents(prefab);}
 }AssetDatabase.SaveAssets();return new{items=report};}
}
