using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine.SceneManagement;using TMPro;using Object=UnityEngine.Object;
public static class PolishMallPresentation07 {
 const string Base="Assets/ShooterSurvival/Models/Chapters/Chapters45/DetailedMall-20261003T092859667/",Dir=Base+"Presentation07/";
 static int added;static Material oak,warm,bronze,ink;static TMP_FontAsset font;
 static Transform Group(Transform p,string n){var g=new GameObject(n);g.transform.SetParent(p,false);return g.transform;}
 static GameObject Box(Transform p,string n,Vector3 pos,Vector3 scale,Material m){var g=GameObject.CreatePrimitive(PrimitiveType.Cube);g.name=n;g.transform.SetParent(p,false);g.transform.localPosition=pos;g.transform.localScale=scale;g.GetComponent<Renderer>().sharedMaterial=m;g.GetComponent<Renderer>().shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;Object.DestroyImmediate(g.GetComponent<Collider>());added++;return g;}
 static TMP_Text Sign(Transform p,string n,string content,Vector3 pos,float width,float size,Color color){var g=Group(p,n);g.localPosition=pos;var t=g.gameObject.AddComponent<TextMeshPro>();t.font=font;t.text=content;t.fontSize=size;t.color=color;t.alignment=TextAlignmentOptions.Center;t.rectTransform.sizeDelta=new Vector2(width,3);t.textWrappingMode=TextWrappingModes.NoWrap;return t;}
 static Material Mat(string n,Color c,bool unlit=false){var m=new Material(Shader.Find(unlit?"Universal Render Pipeline/Unlit":"Universal Render Pipeline/Lit")){name=n,enableInstancing=true};m.SetColor("_BaseColor",c);AssetDatabase.CreateAsset(m,Dir+n+".mat");return m;}
 // Original native graphic design, not a generated 3D asset or photograph.
 static Material Poster(string n,int variant,bool wide){int w=wide?1024:256,h=wide?512:512;var t=new Texture2D(w,h,TextureFormat.RGB24,false);var pixels=new Color[w*h];Color low=variant==0?new Color(.04f,.10f,.18f):variant==1?new Color(.13f,.06f,.19f):new Color(.05f,.19f,.18f),high=variant==0?new Color(.34f,.53f,.63f):variant==1?new Color(.75f,.32f,.26f):new Color(.72f,.59f,.35f);for(int y=0;y<h;y++)for(int x=0;x<w;x++){float u=(float)x/w,v=(float)y/h;Color c=Color.Lerp(low,high,v);float cx=wide?.73f:.68f,cy=.70f,dx=(u-cx)*(wide?2f:.5f),dy=v-cy;if(dx*dx+dy*dy<.085f*.085f)c=new Color(1,.88f,.60f);float ridge=.29f+.09f*Mathf.Sin(u*14+variant)+.025f*Mathf.Sin(u*49);if(v<ridge)c=Color.Lerp(low,new Color(.15f,.29f,.35f),.5f);int block=(int)(u*21);float skyline=.12f+((block*17+variant*11)%13)/80f;if(v<skyline)c=low*.65f;if(v<skyline&&v>.04f&&x%Mathf.Max(6,w/90)<2&&y%20<3)c=new Color(.86f,.60f,.28f)*.6f;pixels[y*w+x]=c;}t.SetPixels(pixels);t.Apply();string path=Dir+n+".png";File.WriteAllBytes(path,t.EncodeToPNG());Object.DestroyImmediate(t);AssetDatabase.ImportAsset(path);var ti=(TextureImporter)AssetImporter.GetAtPath(path);ti.mipmapEnabled=true;ti.isReadable=false;ti.maxTextureSize=1024;ti.textureCompression=TextureImporterCompression.CompressedHQ;ti.SaveAndReimport();var m=Mat(n,Color.white,true);m.SetTexture("_BaseMap",AssetDatabase.LoadAssetAtPath<Texture2D>(path));EditorUtility.SetDirty(m);return m;}
 public static object Main(){if(EditorApplication.isPlayingOrWillChangePlaymode||EditorApplication.isCompiling)throw new Exception("Idle required");for(int i=0;i<SceneManager.sceneCount;i++)if(SceneManager.GetSceneAt(i).isDirty)throw new Exception("Dirty scene");const string path="Assets/ShooterSurvival/Scenes/Tools/ShoeTower.unity";EditorSceneManager.OpenScene(path);var d=Object.FindFirstObjectByType<Chapter45Director>();var root=d.transform.Find("DetailedMall_20261003");if(root.Find("Presentation revision 07")!=null)throw new Exception("Already applied");File.Copy(path,"outputs/chapter45-detailed-design-2026-10-03/scene-recovery/ShoeTower-before-presentation07.unity",false);Directory.CreateDirectory(Dir);AssetDatabase.Refresh();oak=AssetDatabase.LoadAssetAtPath<Material>(Base+"Warm oak.mat");warm=AssetDatabase.LoadAssetAtPath<Material>(Base+"Warm shop light.mat");bronze=AssetDatabase.LoadAssetAtPath<Material>(Base+"Satin champagne metal.mat");ink=AssetDatabase.LoadAssetAtPath<Material>(Base+"Ink graphite.mat");font=root.GetComponentsInChildren<TMP_Text>(true).First().font;var scenery=root.Find("Scenery");var floors=scenery.Cast<Transform>().Where(t=>t.GetComponent<Chapter45SceneryGroup>()?.floor>=0&&t.Cast<Transform>().Any(c=>c.name.Contains("supported floor"))).ToArray();int slabs=0,glassPanels=0,posters=0;
  // Opaque destination slabs must not cross the camera while an elevator rises.
  foreach(var f in floors){int n=f.GetComponent<Chapter45SceneryGroup>().floor;if(!new[]{5,6,7,8}.Contains(n))continue;var visual=Group(scenery,n+"F floor slab transfer visibility");var vis=visual.gameObject.AddComponent<Chapter45SceneryGroup>();vis.floor=n;vis.alwaysVisible=true;vis.hideDuringTransfer=true;foreach(var c in f.Cast<Transform>().Where(t=>t.name.Contains("supported floor")||t.name=="Fine limestone circulation tiles").ToArray()){c.SetParent(visual,true);slabs++;}}
  Material cabinGlass=null;foreach(var l in d.lifts.Where(l=>!l.escalator)){var rear=l.platform.Find("Cabin rear");if(rear==null)throw new Exception("Cabin rear missing");var r=rear.GetComponent<Renderer>();if(cabinGlass==null){cabinGlass=new Material(r.sharedMaterial){name="Low tint cabin rear glass"};var c=cabinGlass.GetColor("_BaseColor");c.a=.045f;cabinGlass.SetColor("_BaseColor",c);AssetDatabase.CreateAsset(cabinGlass,Dir+"Low tint cabin rear glass.mat");}r.sharedMaterial=cabinGlass;glassPanels++;}
  var posterMats=new[]{Poster("Blue hour original graphic",0,false),Poster("City lights original graphic",1,false),Poster("Last train original graphic",2,false)};var screenMat=Poster("Midnight city original cinema graphic",0,true);var titles=new[]{"BLUE HOUR","CITY LIGHTS","LAST TRAIN"};
  var f5=floors.Single(f=>f.GetComponent<Chapter45SceneryGroup>().floor==5);int shopIndex=0;foreach(var shop in f5.Cast<Transform>().Where(t=>t.name.Contains("storefront"))){var backdrop=Box(shop,"Cinema warm ticket feature wall",new Vector3(0,2.4f,-4.70f),new Vector3(17,4.7f,.08f),shopIndex%2==0?oak:ink);for(int side=-1;side<=1;side+=2){int variant=(shopIndex+(side+1)/2)%3;Box(shop,"Backlit original film poster frame",new Vector3(side*5.4f,2.45f,-4.58f),new Vector3(3.7f,4.25f,.09f),bronze);Box(shop,"Original native film poster",new Vector3(side*5.4f,2.45f,-4.51f),new Vector3(3.48f,4.03f,.035f),posterMats[variant]);Sign(shop,"Original film title",titles[variant],new Vector3(side*5.4f,3.78f,-4.47f),3.2f,.78f,Color.white);posters++;}Sign(shop,"Screen schedule",shopIndex%2==0?"CINE SEVEN\nSCREEN 01 - 06":"POPCORN & COFFEE\nSWEET / SALT",new Vector3(0,3.1f,-4.54f),6.4f,1.05f,new Color(1,.89f,.65f));Box(shop,"Ticket counter overhead warm strip",new Vector3(0,4.58f,-4.4f),new Vector3(16,.06f,.06f),warm);shopIndex++;}
  var cinema=floors.Single(f=>f.GetComponent<Chapter45SceneryGroup>().floor==6);cinema.Find("Large cinema screen").GetComponent<Renderer>().sharedMaterial=screenMat;var title=cinema.Find("Survival instructions").GetComponent<TMP_Text>();title.text="MIDNIGHT CITY";title.fontSize=3.6f;title.color=new Color(1,.94f,.78f);title.transform.localPosition=new Vector3(15,10.9f,-30.80f);
  var seam=Mat("Cinema carpet fine weave",new Color(.21f,.13f,.16f));var vertices=new List<Vector3>();var triangles=new List<int>();void Line(Vector3 a,Vector3 b,float width){var side=Vector3.Cross(Vector3.up,b-a).normalized*width/2;int k=vertices.Count;vertices.AddRange(new[]{a-side,a+side,b-side,b+side});triangles.AddRange(new[]{k,k+2,k+1,k+2,k+3,k+1});}for(float z=-30;z<28;z+=2.2f)Line(new Vector3(-10,.025f,z),new Vector3(40,.025f,z),.022f);for(float x=-10;x<41;x+=2.2f)Line(new Vector3(x,.025f,-30),new Vector3(x,.025f,28),.022f);var mesh=new Mesh{name="Cinema fitted carpet weave"};mesh.SetVertices(vertices);mesh.SetTriangles(triangles,0);mesh.RecalculateNormals();mesh.RecalculateBounds();AssetDatabase.CreateAsset(mesh,Dir+mesh.name+".asset");var weave=Group(scenery.Find("6F floor slab transfer visibility"),"Cinema subtle carpet weave");weave.position=cinema.position;weave.gameObject.AddComponent<MeshFilter>().sharedMesh=mesh;weave.gameObject.AddComponent<MeshRenderer>().sharedMaterial=seam;
  for(int sign=-1;sign<=1;sign+=2){float x=15+sign*25.7f;for(int i=0;i<16;i++){float z=-29+i*3.6f;Box(cinema,"Acoustic wall timber rib",new Vector3(x,3.8f,z),new Vector3(.11f,7.2f,.17f),oak);if(i%3==0)Box(cinema,"Acoustic warm light reveal",new Vector3(x-sign*.065f,3.8f,z+.23f),new Vector3(.04f,5.8f,.04f),warm);}}
  var f7=floors.Single(f=>f.GetComponent<Chapter45SceneryGroup>().floor==7);shopIndex=0;foreach(var shop in f7.Cast<Transform>().Where(t=>t.name.Contains("storefront"))){Box(shop,"Shoe store warm feature backdrop",new Vector3(0,2.5f,-4.68f),new Vector3(16.9f,4.9f,.08f),shopIndex%2==0?oak:ink);for(int i=0;i<12;i++)Box(shop,"Shoe store fine vertical reveal",new Vector3(-8+i*.48f,2.5f,-4.59f),new Vector3(.045f,4.7f,.06f),bronze);Sign(shop,"Shoe collection wall title",shopIndex%2==0?"EVERYDAY MOVEMENT":"CRAFTED FOR MOTION",new Vector3(2.1f,3.7f,-4.55f),9.5f,1.25f,Color.white);Box(shop,"Shoe collection warm linear light",new Vector3(2.1f,4.52f,-4.52f),new Vector3(10,.055f,.04f),warm);shopIndex++;}
  new GameObject("Presentation revision 07").transform.SetParent(root,false);AssetDatabase.SaveAssets();EditorSceneManager.MarkSceneDirty(d.gameObject.scene);if(!EditorSceneManager.SaveScene(d.gameObject.scene))throw new Exception("Save failed");return new{slabs,glassPanels,posters,addedDecorativeObjects=added,newColliders=0,slabCollidersPreserved=true,newPaidGeneration=0,source="Original native cinema poster/screen graphics and architectural finishing; previously generated models preserved.",gameplayAndSpawnPositionsUnchanged=true};
 }
}
