using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine.SceneManagement;using Object=UnityEngine.Object;
public static class PolishMallPresentation04 {
 const string ScenePath="Assets/ShooterSurvival/Scenes/Tools/ShoeTower.unity", Base="Assets/ShooterSurvival/Models/Chapters/Chapters45/DetailedMall-20261003T092859667/", Plant="Assets/ShooterSurvival/Models/Chapters/Chapters45/DepartmentStore/Trellis20261003/";
 static Material ivory,wood,warm,soil,rug,carpet,screen;static int added;static Bounds BoundsOf(Transform t){var rr=t.GetComponentsInChildren<Renderer>(true);var b=rr[0].bounds;foreach(var r in rr.Skip(1))b.Encapsulate(r.bounds);return b;}
 static Vector3 Bottom(Bounds b)=>new Vector3(b.center.x,b.min.y,b.center.z);
 static GameObject Box(Transform p,string name,Vector3 pos,Vector3 size,Material mat){var g=GameObject.CreatePrimitive(PrimitiveType.Cube);g.name=name;g.transform.SetParent(p,false);g.transform.localPosition=pos;g.transform.localScale=size;g.GetComponent<Renderer>().sharedMaterial=mat;g.GetComponent<Renderer>().shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;Object.DestroyImmediate(g.GetComponent<Collider>());added++;return g;}
 static Material Mat(string name,Color c,bool unlit=false){var m=new Material(Shader.Find(unlit?"Universal Render Pipeline/Unlit":"Universal Render Pipeline/Lit")){name=name,enableInstancing=true};m.SetColor("_BaseColor",c);if(m.HasProperty("_Smoothness"))m.SetFloat("_Smoothness",.12f);AssetDatabase.CreateAsset(m,Base+"Presentation04/"+name+".mat");return m;}
 static void PlaceModel(GameObject asset,Transform parent,string name,Vector3 p,float h,Material mat=null,float yaw=0){var g=(GameObject)PrefabUtility.InstantiatePrefab(asset,parent);g.name=name;g.transform.localPosition=Vector3.zero;g.transform.localRotation=Quaternion.Euler(0,yaw,0)*asset.transform.localRotation;var b=BoundsOf(g.transform);g.transform.localScale*=h/b.size.y;b=BoundsOf(g.transform);g.transform.position+=parent.TransformPoint(p)-Bottom(b);if(mat!=null)foreach(var r in g.GetComponentsInChildren<Renderer>(true)){r.sharedMaterial=mat;r.shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;}added++;}
 public static object Main(){
  if(EditorApplication.isPlayingOrWillChangePlaymode||EditorApplication.isCompiling)throw new Exception("Idle required");for(int i=0;i<SceneManager.sceneCount;i++)if(SceneManager.GetSceneAt(i).isDirty)throw new Exception("Dirty scene");EditorSceneManager.OpenScene(ScenePath);var d=Object.FindFirstObjectByType<Chapter45Director>();var root=d.transform.Find("DetailedMall_20261003");if(root.Find("Presentation revision 04")!=null)throw new Exception("Already applied");
  File.Copy(ScenePath,"outputs/chapter45-detailed-design-2026-10-03/scene-recovery/ShoeTower-before-presentation04.unity",false);Directory.CreateDirectory(Base+"Presentation04");AssetDatabase.Refresh();ivory=AssetDatabase.LoadAssetAtPath<Material>(Base+"Warm ivory.mat");if(ivory==null)ivory=AssetDatabase.LoadAssetAtPath<Material>(Base+"Porcelain.mat");wood=AssetDatabase.LoadAssetAtPath<Material>(Base+"Warm oak.mat");warm=AssetDatabase.LoadAssetAtPath<Material>(Base+"Warm shop light.mat");soil=Mat("Planter soil",new Color(.085f,.065f,.044f));rug=Mat("Living woven sand",new Color(.48f,.43f,.36f));carpet=Mat("Cinema seating carpet",new Color(.072f,.041f,.058f));screen=Mat("Cinema soft illuminated screen",new Color(.72f,.81f,.84f),true);
  var plant=AssetDatabase.LoadAssetAtPath<GameObject>(Plant+"MallPlant.fbx");var plantMat=AssetDatabase.LoadAssetAtPath<Material>(Plant+"MallPlant.mat");if(plant==null||plantMat==null)throw new Exception("Verified TRELLIS plant missing");int panels=0,windows=0,planters=0,racks=0,livingGroups=0;added=0;
  foreach(var floor in root.Find("Scenery").Cast<Transform>().Where(t=>t.GetComponent<Chapter45SceneryGroup>()?.floor>=0)){
   int f=floor.GetComponent<Chapter45SceneryGroup>().floor;
   foreach(var t in floor.Cast<Transform>().Where(t=>t.name=="Enclosing clerestory wall"||t.name=="Upper daylight glazing")){
    float a=Mathf.Atan2(t.localPosition.z,t.localPosition.x)*Mathf.Rad2Deg;t.localRotation=Quaternion.Euler(0,90-a,0);var p=t.localPosition;
    if(t.name=="Enclosing clerestory wall"){p.y=2.4f;t.localScale=new Vector3(4.36f,4.8f,.22f);t.GetComponent<Renderer>().sharedMaterial=ivory;panels++;}
    else{p.y=5.6f;t.localScale=new Vector3(4.28f,1.6f,.05f);windows++;}t.localPosition=p;
   }
   foreach(var shop in floor.Cast<Transform>().Where(t=>t.name.Contains("storefront"))){
    var planter=shop.Cast<Transform>().Single(t=>t.name.StartsWith("RetailPlanter"));var b=BoundsOf(planter);planter.localScale*=.63f/b.size.y;b=BoundsOf(planter);planter.position+=shop.TransformPoint(new Vector3(7,.036f,-1.8f))-Bottom(b);b=BoundsOf(planter);var localWidth=b.size; // An upright, already axis-corrected imported planter.
    Box(shop,"Recessed planter soil",new Vector3(7,.61f,-1.8f),new Vector3(1.75f,.035f,.62f),soil);
    foreach(float x in new[]{6.42f,7.58f})PlaceModel(plant,shop,"Reused TRELLIS planter greenery",new Vector3(x,.42f,-1.8f),1.08f,plantMat);planters++;
    if(f==2&&(shop.name.Contains("storefront 7")||shop.name.Contains("storefront 3"))){
     var current=shop.Cast<Transform>().Single(t=>t.name=="Generated TRELLIS clothing rack");current.localPosition=new Vector3(-3.8f,.036f,-2.2f);var rackAsset=AssetDatabase.LoadAssetAtPath<GameObject>(Base+"GeneratedModels/DetailedClothingRack.prefab");PlaceModel(rackAsset,shop,"Generated TRELLIS clothing rack depth",new Vector3(3.8f,.036f,-2.2f),1.9f);PlaceModel(rackAsset,shop,"Generated TRELLIS clothing rack front",new Vector3(0,.036f,2.1f),1.9f);racks+=2;
     Box(shop,"Fashion oak display backdrop",new Vector3(0,1.4f,-4.72f),new Vector3(15,2.7f,.08f),wood);foreach(float y in new[]{.7f,1.6f,2.4f})Box(shop,"Fashion shallow shelf",new Vector3(0,y,-4.5f),new Vector3(14,.065f,.4f),ivory);
     Box(shop,"Fashion display table",new Vector3(-4.8f,.4f,2.5f),new Vector3(2.4f,.72f,1.45f),wood);var tote=AssetDatabase.FindAssets("RetailTote t:Model").Select(AssetDatabase.GUIDToAssetPath).First(p=>p.EndsWith("RetailTote.fbx"));var toteMat=AssetDatabase.LoadAssetAtPath<Material>(tote.Replace(".fbx",".mat"));PlaceModel(AssetDatabase.LoadAssetAtPath<GameObject>(tote),shop,"Reused generated bag display",new Vector3(-4.8f,.78f,2.5f),.65f,toteMat);
    }
    if(f==4){
     int wi=0;foreach(var w in shop.Cast<Transform>().Where(t=>t.name=="Generated washer wall-backed display"))w.localPosition=new Vector3(-5.4f+1.7f*wi++,.036f,-2.5f);
     shop.Find("Generated TRELLIS bed display").localPosition=new Vector3(3.2f,.066f,-.6f);shop.Find("Generated TRELLIS vacuum display").localPosition=new Vector3(6.5f,.036f,-1.5f);Box(shop,"Bedroom woven rug",new Vector3(3.2f,.047f,-.6f),new Vector3(5,.022f,4),rug);
     Box(shop,"Appliance oak backboard",new Vector3(-4.6f,1.4f,-3.5f),new Vector3(4.8f,2.7f,.12f),wood);Box(shop,"Appliance warm task strip",new Vector3(-4.6f,2.72f,-3.38f),new Vector3(4.6f,.055f,.04f),warm);
     foreach(var t in shop.Cast<Transform>().Where(t=>t.name.StartsWith("RetailCounter")||t.name.StartsWith("RetailVase"))) {var pos=t.localPosition;pos.x=-.8f;pos.z=2.3f;t.localPosition=pos;}
     foreach(var t in shop.Cast<Transform>().Where(t=>t.name=="Living ceramic plate"||t.name=="Low ceramic display table")){var pos=t.localPosition;pos.x=-4.8f;pos.z=2.3f;t.localPosition=pos;}livingGroups++;
    }
   }
   if(f==6){floor.Find("Large cinema screen").GetComponent<Renderer>().sharedMaterial=screen;foreach(float x in new[]{.7f,29.3f})Box(floor,"Front seating carpet zone",new Vector3(x,.023f,-3.55f),new Vector3(6.3f,.036f,9.5f),carpet);foreach(float x in new[]{7.7f,22.3f})Box(floor,"Rear seating carpet zone",new Vector3(x,.023f,10.45f),new Vector3(5.6f,.036f,9.5f),carpet);Box(floor,"Low cinema screen stage",new Vector3(15,.15f,-29.2f),new Vector3(39,.3f,2),wood);}
  }
  if(panels!=504||windows!=504||planters!=56||racks!=4)throw new Exception("Unexpected scene topology "+panels+"/"+windows+"/"+planters+"/"+racks);
  new GameObject("Presentation revision 04").transform.SetParent(root,false);EditorSceneManager.MarkSceneDirty(d.gameObject.scene);if(!EditorSceneManager.SaveScene(d.gameObject.scene))throw new Exception("Save failed");AssetDatabase.SaveAssets();return new{panels,windows,planters,addedRackInstances=racks,livingGroups,addedObjects=added,newColliders=0,combatAndRouteChanged=false,plantSource=Plant,rackTriangles=15945,scope="Tangent enclosure, human-scale planted boxes, grouped retail displays, cinema contrast. Native Play/independent art recheck pending."};
 }
}
