using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine.SceneManagement;using TMPro;using Object=UnityEngine.Object;
public static class PolishMallPresentation03 {
 const string ScenePath="Assets/ShooterSurvival/Scenes/Tools/ShoeTower.unity";
 static string assets;static Material dark,wood,metal,warm,carpet,white;static Transform revision;
 static GameObject Box(Transform p,string n,Vector3 pos,Vector3 scale,Material m){var g=GameObject.CreatePrimitive(PrimitiveType.Cube);g.name=n;g.transform.SetParent(p,false);g.transform.localPosition=pos;g.transform.localScale=scale;g.GetComponent<Renderer>().sharedMaterial=m;g.GetComponent<Renderer>().shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;Object.DestroyImmediate(g.GetComponent<Collider>());return g;}
 static Material Mat(string name,Color color){var m=new Material(Shader.Find("Universal Render Pipeline/Lit")){name=name,enableInstancing=true};m.SetColor("_BaseColor",color);m.SetFloat("_Smoothness",.3f);AssetDatabase.CreateAsset(m,assets+"/"+name+".mat");return m;}
 public static object Main(){if(EditorApplication.isPlayingOrWillChangePlaymode||EditorApplication.isCompiling)throw new Exception("Idle required");for(int i=0;i<SceneManager.sceneCount;i++)if(SceneManager.GetSceneAt(i).isDirty)throw new Exception("Dirty scene");EditorSceneManager.OpenScene(ScenePath);var d=Object.FindFirstObjectByType<Chapter45Director>();var root=d.transform.Find("DetailedMall_20261003");if(root.Find("Presentation revision 03")!=null)throw new Exception("Already applied");File.Copy(ScenePath,"outputs/chapter45-detailed-design-2026-10-03/scene-recovery/ShoeTower-before-presentation03.unity",false);revision=new GameObject("Presentation revision 03").transform;revision.SetParent(root,false);
  var src="Assets/ShooterSurvival/Models/Chapters/Chapters45/DetailedMall-20261003T092859667/";assets=src+"Presentation03";Directory.CreateDirectory(assets);AssetDatabase.Refresh();dark=AssetDatabase.LoadAssetAtPath<Material>(src+"Ink graphite.mat");wood=AssetDatabase.LoadAssetAtPath<Material>(src+"Warm oak.mat");metal=AssetDatabase.LoadAssetAtPath<Material>(src+"Satin champagne metal.mat");warm=AssetDatabase.LoadAssetAtPath<Material>(src+"Warm shop light.mat");carpet=Mat("Cinema woven burgundy",new Color(.115f,.052f,.067f));white=Mat("White sole exhibit porcelain",new Color(.94f,.95f,.94f));
  var scenery=root.Find("Scenery");var cinema=scenery.Cast<Transform>().Single(t=>t.name.StartsWith("6F "));var floor=cinema.Find("Cinema supported floor");floor.GetComponent<Renderer>().sharedMaterial=carpet;
  var seats=cinema.Cast<Transform>().Where(t=>t.name=="Generated cinema seat row").ToList();var source=seats[0].gameObject;while(seats.Count<64){var g=Object.Instantiate(source,cinema);g.name="Generated cinema seat row";seats.Add(g.transform);}
  int at=0;for(int section=0;section<2;section++)for(int side=0;side<2;side++)for(int row=0;row<4;row++)for(int col=0;col<4;col++){var seat=seats[at++];float x=section==0?-1+col*1.15f:6+col*1.15f;if(side==1)x=30-x;float z=section==0?-7+row*2.3f:7+row*2.3f;seat.localPosition=new Vector3(x,0,z);seat.localRotation=Quaternion.Euler(0,180,0);}
  // The front banks remain outside diagonal approaches. Rear banks sit behind
  // the rear spawn doors; central walking aisle remains at least 11m wide.
  foreach(float x in new[]{9.5f,20.5f})Box(cinema,"Low aisle edge lighting",new Vector3(x,.025f,13),new Vector3(.07f,.035f,19),warm);
  var screen=cinema.Find("Large cinema screen");screen.GetComponent<Renderer>().sharedMaterial=white;var instructions=cinema.Find("Survival instructions");instructions.GetComponent<TMP_Text>().text="CINE SEVEN";
  var goal=d.goals.Single(g=>g.offering);var museum=goal.collectionVisual.parent;foreach(var r in goal.collectionVisual.GetComponentsInChildren<Renderer>(true))r.sharedMaterial=white;
  Box(museum,"Exhibit dark backdrop",new Vector3(0,3.1f,3.7f),new Vector3(12,6.2f,.25f),dark);Box(museum,"Exhibit warm inset",new Vector3(0,3.1f,3.54f),new Vector3(8.8f,4.6f,.06f),wood);
  foreach(float x in new[]{-4.5f,4.5f})Box(museum,"Museum warm frame",new Vector3(x,3.1f,3.42f),new Vector3(.07f,4.8f,.04f),warm);foreach(float y in new[]{.7f,5.5f})Box(museum,"Museum warm frame",new Vector3(0,y,3.42f),new Vector3(9.1f,.07f,.04f),warm);
  Box(museum,"Museum dark inset floor",new Vector3(0,.025f,.5f),new Vector3(10,.045f,7),dark);Box(museum,"White gallery approach",new Vector3(0,.035f,-3.1f),new Vector3(3.8f,.045f,1.4f),white);
  var label=museum.Find("Final exhibit").GetComponent<TMP_Text>();label.transform.localPosition=new Vector3(0,5.05f,3.35f);label.text="AERO SEVEN · THE WHITE SOLE";label.fontSize=2.2f;
  EditorSceneManager.MarkSceneDirty(d.gameObject.scene);if(!EditorSceneManager.SaveScene(d.gameObject.scene))throw new Exception("Save failed");return new{assets,totalReusedGeneratedSeats=seats.Count,newSeatInstances=40,seatSource="existing local TRELLIS chair mesh/texture",newPaidGeneration=0,addedColliders=0,whiteShoe="existing sneaker geometry with scene-owned white material",cinemaAttackPositionsUnchanged=true,cinemaDamageUnchanged=true,goalColliderUnchanged=true,remainingArt="native replay and independent review required; role bodies and missing retail goods remain pending"};
 }
}
