using System;using System.IO;using System.Linq;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine.SceneManagement;using Object=UnityEngine.Object;
public static class PolishMallPresentation08 {
 public static object Main(){if(EditorApplication.isPlayingOrWillChangePlaymode||EditorApplication.isCompiling)throw new Exception("Idle required");for(int i=0;i<SceneManager.sceneCount;i++)if(SceneManager.GetSceneAt(i).isDirty)throw new Exception("Dirty scene");const string path="Assets/ShooterSurvival/Scenes/Tools/ShoeTower.unity",Base="Assets/ShooterSurvival/Models/Chapters/Chapters45/DetailedMall-20261003T092859667/";EditorSceneManager.OpenScene(path);var d=Object.FindFirstObjectByType<Chapter45Director>();var scenery=d.transform.Find("DetailedMall_20261003/Scenery");if(scenery.Find("6F cinema enclosing background")!=null)throw new Exception("Already applied");File.Copy(path,"outputs/chapter45-detailed-design-2026-10-03/scene-recovery/ShoeTower-before-presentation08.unity",false);
  var groups=scenery.Cast<Transform>().Where(t=>t.name.EndsWith("floor slab transfer visibility")).Select(t=>t.GetComponent<Chapter45SceneryGroup>()).ToArray();foreach(var g in groups){g.hideDuringTransfer=false;g.hideWhileArriving=true;EditorUtility.SetDirty(g);}
  var mat=AssetDatabase.LoadAssetAtPath<Material>(Base+"Presentation07/Low tint cabin rear glass.mat");File.Copy(AssetDatabase.GetAssetPath(mat),"outputs/chapter45-detailed-design-2026-10-03/recovery/CabinGlass-before-specular-fix.mat",false);mat.SetFloat("_BlendModePreserveSpecular",0);mat.SetFloat("_SrcBlend",(float)UnityEngine.Rendering.BlendMode.SrcAlpha);mat.SetFloat("_DstBlend",(float)UnityEngine.Rendering.BlendMode.OneMinusSrcAlpha);mat.SetFloat("_SpecularHighlights",0);mat.SetFloat("_EnvironmentReflections",0);mat.SetFloat("_Smoothness",.1f);mat.DisableKeyword("_ALPHAPREMULTIPLY_ON");mat.EnableKeyword("_SPECULARHIGHLIGHTS_OFF");mat.EnableKeyword("_ENVIRONMENTREFLECTIONS_OFF");EditorUtility.SetDirty(mat);
  var cinema=scenery.Cast<Transform>().Single(t=>t.GetComponent<Chapter45SceneryGroup>()?.floor==6&&t.Find("Large cinema screen")!=null);var group=new GameObject("6F cinema enclosing background");group.transform.SetParent(scenery,false);group.transform.position=cinema.position;var vis=group.AddComponent<Chapter45SceneryGroup>();vis.floor=6;vis.alwaysVisible=true;vis.hideDuringTransfer=true;var panel=GameObject.CreatePrimitive(PrimitiveType.Cube);panel.name="Dark cinema background behind screen";panel.transform.SetParent(group.transform,false);panel.transform.localPosition=new Vector3(15,45,-36);panel.transform.localScale=new Vector3(200,100,.25f);Object.DestroyImmediate(panel.GetComponent<Collider>());var dark=new Material(Shader.Find("Universal Render Pipeline/Unlit")){name="Cinema enclosed midnight",enableInstancing=true};dark.SetColor("_BaseColor",new Color(.035f,.045f,.059f));AssetDatabase.CreateAsset(dark,Base+"Presentation07/Cinema enclosed midnight.mat");panel.GetComponent<Renderer>().sharedMaterial=dark;panel.GetComponent<Renderer>().shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;
  AssetDatabase.SaveAssets();EditorSceneManager.MarkSceneDirty(d.gameObject.scene);if(!EditorSceneManager.SaveScene(d.gameObject.scene))throw new Exception("Save failed");return new{arrivalOnlySlabGroups=groups.Length,sourceFloorsRemainVisible=true,cabinGlassAlpha=.045f,preservedSpecularDisabled=true,backdropBehindScreen=true,newDecorativeColliders=0,routeAndCombatChanged=false};
 }
}
