using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine.SceneManagement;
public static class PolishStreetFork {
 static Chapter45Director d;static Transform root;static string assets;static Material brick,stone,cream;
 static void Strip(string name,int side,float inner,float outer,Material mat,float y){var v=new List<Vector3>();var uv=new List<Vector2>();var tri=new List<int>();for(int i=0;i<=190;i++){float distance=500+i*2.2f;d.route.Sample(distance,out var center,out var forward);float offset=d.choices[0].Offset(distance,side);var right=Vector3.Cross(Vector3.up,forward);v.Add(center+right*(offset+inner)+Vector3.up*y);v.Add(center+right*(offset+outer)+Vector3.up*y);uv.Add(new Vector2(inner*.12f,distance*.12f));uv.Add(new Vector2(outer*.12f,distance*.12f));if(i<190){int n=i*2;tri.AddRange(new[]{n,n+2,n+1,n+1,n+2,n+3});}}var mesh=new Mesh{name=name};mesh.SetVertices(v);mesh.SetUVs(0,uv);mesh.SetTriangles(tri,0);mesh.RecalculateNormals();mesh.RecalculateBounds();AssetDatabase.CreateAsset(mesh,assets+"/"+name+".asset");var g=new GameObject(name);g.transform.SetParent(root,false);g.AddComponent<MeshFilter>().sharedMesh=mesh;var renderer=g.AddComponent<MeshRenderer>();renderer.sharedMaterial=mat;renderer.shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;}
 public static object Main(){if(EditorApplication.isPlayingOrWillChangePlaymode||EditorApplication.isCompiling)throw new Exception("Idle required");for(int i=0;i<SceneManager.sceneCount;i++)if(SceneManager.GetSceneAt(i).isDirty)throw new Exception("Dirty scene");EditorSceneManager.OpenScene("Assets/ShooterSurvival/Scenes/Tools/Jamsil.unity");d=UnityEngine.Object.FindFirstObjectByType<Chapter45Director>();if(d.transform.Find("DetailedStreet_20261003/Continuous fork paving")!=null)throw new Exception("Already applied");File.Copy(d.gameObject.scene.path,"outputs/chapter45-detailed-design-2026-10-03/scene-recovery/Jamsil-before-fork-polish.unity",false);root=new GameObject("Continuous fork paving").transform;root.SetParent(d.transform.Find("DetailedStreet_20261003"),false);assets="Assets/ShooterSurvival/Models/Chapters/Chapters45/ForkPaving-"+DateTime.UtcNow.ToString("yyyyMMddTHHmmssfff");Directory.CreateDirectory(assets);AssetDatabase.Refresh();var source=d.transform.Find("Scenery/Jamsil_ReferenceStreet_20261002");var materials=source.GetComponentsInChildren<Renderer>(true).SelectMany(r=>r.sharedMaterials).Where(m=>m!=null).Distinct().ToArray();brick=materials.First(m=>m.name=="Clay pavers");stone=materials.First(m=>m.name=="Pavement");cream=materials.First(m=>m.name=="Warm limestone");
  foreach(int side in new[]{0,1}){Strip("Branch "+side+" continuous clay",side,-4.15f,4.15f,brick,.092f);Strip("Branch "+side+" left pavement",side,-7.8f,-4.2f,stone,.09f);Strip("Branch "+side+" right pavement",side,4.2f,7.8f,stone,.09f);Strip("Branch "+side+" left curb stripe",side,-4.22f,-4.08f,cream,.096f);Strip("Branch "+side+" right curb stripe",side,4.08f,4.22f,cream,.096f);}
  var group=root.gameObject.AddComponent<Chapter45SceneryGroup>();group.floor=0;group.startDistance=480;group.endDistance=950;
  int walkers=0;foreach(var life in source.GetComponentsInChildren<Chapter4StreetLife>(true)){bool branch=life.station>500&&life.station<910;foreach(var w in life.walkers){float sign=Mathf.Sign(w.origin.x);float alternate=Mathf.Abs(w.origin.x)>(branch?27.6f:9.8f)?1.1f:0;w.origin.x=sign*((branch?22.8f:6.2f)+alternate);w.body.localPosition=w.origin;walkers++;}}
  foreach(var choice in d.choices)if(choice.previewLabel!=null)choice.previewLabel.gameObject.SetActive(false);
  d.authoredForwardScale=.82f;foreach(var e in d.encounters){var role=e.actors.Select(a=>a.GetComponent<Chapter45RoleAction>()).FirstOrDefault(a=>a!=null);if(role==null)continue;if(role.role==Chapter45RoleAction.Role.Preacher){e.health=40;foreach(var a in e.actors)a.GetComponent<Chapter45RoleAction>().moveSpeed=3.5f;}if(role.role==Chapter45RoleAction.Role.Promoter)e.health=24;}
  foreach(var h in d.hazards.Where(h=>h.name.StartsWith("Risk route taxi")||h.name.StartsWith("Side delivery")))h.warningDistance=24;
  EditorSceneManager.MarkSceneDirty(d.gameObject.scene);if(!EditorSceneManager.SaveScene(d.gameObject.scene))throw new Exception("Save failed");return new{assets,visualOnlyPavingMeshes=10,addedColliders=0,movedExistingDecorativeWalkers=walkers,worldChoiceTextHidden=true,hudChoiceUnchanged=true,forwardScale=d.authoredForwardScale,expectedOrdinarySpeed=7.8f*d.authoredForwardScale,weakCrowdHealth=8,preacherHealth=40,promoterHealth=24,reason="246s native run was short of approximately300s; movement and encounter readability tuned before new replay"};}
}
