using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine.SceneManagement;using Object=UnityEngine.Object;
public static class PolishMallPresentation06 {
 const string Base="Assets/ShooterSurvival/Models/Chapters/Chapters45/DetailedMall-20261003T092859667/";
 static Vector3 Polar(float r,float a,float y){a*=Mathf.Deg2Rad;return new Vector3(r*Mathf.Cos(a),y,r*Mathf.Sin(a));}
 static void Quad(List<Vector3> v,List<int> t,Vector3 a,Vector3 b,Vector3 c,Vector3 d,bool down){int k=v.Count;v.AddRange(new[]{a,b,c,d});if(down)t.AddRange(new[]{k+2,k+1,k,k+3,k+1,k+2});else t.AddRange(new[]{k,k+1,k+2,k+2,k+1,k+3});}
 static Mesh Make(List<Vector3> v,List<int> t,string n){var m=new Mesh{name=n};m.SetVertices(v);m.SetTriangles(t,0);m.RecalculateNormals();m.RecalculateBounds();AssetDatabase.CreateAsset(m,Base+"Presentation06/"+n+".asset");return m;}
 static GameObject MeshObject(Transform p,string n,Mesh mesh,Material mat){var g=new GameObject(n);g.transform.SetParent(p,false);g.AddComponent<MeshFilter>().sharedMesh=mesh;var r=g.AddComponent<MeshRenderer>();r.sharedMaterial=mat;r.shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;return g;}
 static Material Mat(string name,Color c,bool unlit=false){var m=new Material(Shader.Find(unlit?"Universal Render Pipeline/Unlit":"Universal Render Pipeline/Lit")){name=name,enableInstancing=true};m.SetColor("_BaseColor",c);AssetDatabase.CreateAsset(m,Base+"Presentation06/"+name+".mat");return m;}
 public static object Main(){if(EditorApplication.isPlayingOrWillChangePlaymode||EditorApplication.isCompiling)throw new Exception("Idle required");for(int i=0;i<SceneManager.sceneCount;i++)if(SceneManager.GetSceneAt(i).isDirty)throw new Exception("Dirty scene");const string scene="Assets/ShooterSurvival/Scenes/Tools/ShoeTower.unity";EditorSceneManager.OpenScene(scene);var director=Object.FindFirstObjectByType<Chapter45Director>();var root=director.transform.Find("DetailedMall_20261003");if(root.Find("Presentation revision 06")!=null)throw new Exception("Already applied");File.Copy(scene,"outputs/chapter45-detailed-design-2026-10-03/scene-recovery/ShoeTower-before-presentation06.unity",false);Directory.CreateDirectory(Base+"Presentation06");AssetDatabase.Refresh();
  var ceiling=AssetDatabase.LoadAssetAtPath<Material>(Base+"Presentation05/Ceiling.mat");File.Copy(Base+"Presentation05/Ceiling.mat","outputs/chapter45-detailed-design-2026-10-03/recovery/Ceiling-before-presentation06.mat",false);ceiling.SetColor("_EmissionColor",new Color(.43f,.415f,.37f));EditorUtility.SetDirty(ceiling);
  var daylight=Mat("Diffused daylight panels",new Color(.87f,.94f,.94f),true);var mullion=Mat("Ceiling pale bronze mullions",new Color(.57f,.53f,.44f),true);var grout=Mat("Limestone fine joints",new Color(.59f,.58f,.54f));
  var v=new List<Vector3>();var t=new List<int>();for(int i=0;i<72;i++)Quad(v,t,Polar(24.6f,i*5+.12f,7.17f),Polar(24.6f,(i+1)*5-.12f,7.17f),Polar(33.7f,i*5+.12f,7.17f),Polar(33.7f,(i+1)*5-.12f,7.17f),true);var panels=Make(v,t,"Segmented daylight ceiling panels");v.Clear();t.Clear();
  for(int i=0;i<72;i++){Quad(v,t,Polar(24.5f,i*5-.055f,7.145f),Polar(24.5f,i*5+.055f,7.145f),Polar(33.8f,i*5-.055f,7.145f),Polar(33.8f,i*5+.055f,7.145f),true);foreach(float r in new[]{24.6f,29.15f,33.7f})Quad(v,t,Polar(r-.025f,i*5,7.14f),Polar(r-.025f,(i+1)*5,7.14f),Polar(r+.025f,i*5,7.14f),Polar(r+.025f,(i+1)*5,7.14f),true);}var ribs=Make(v,t,"Slender daylight ceiling frame");
  var scenery=root.Find("Scenery");int floors=0;foreach(var roof in scenery.Cast<Transform>().Where(c=>c.name.EndsWith("curved ceiling presentation"))){MeshObject(roof,"Daylight panels",panels,daylight);MeshObject(roof,"Daylight panel mullions",ribs,mullion);}
  foreach(var floor in scenery.Cast<Transform>().Where(c=>c.GetComponent<Chapter45SceneryGroup>()?.floor>=0&&c.Cast<Transform>().Any(s=>s.name.Contains("storefront")))){
   int f=floor.GetComponent<Chapter45SceneryGroup>().floor;var holes=director.lifts.Where(l=>l.escalator&&director.route.segments[l.Destination(l.afterSegment)].floor==f).Select(l=>(a:director.route.segments[l.afterSegment].end,b:director.route.segments[l.Destination(l.afterSegment)].start)).ToArray();
   bool Hole(Vector3 p){p=floor.TransformPoint(p);foreach(var h in holes){var a=h.a;var b=h.b;a.y=b.y=p.y;var ab=b-a;float phase=Vector3.Dot(p-a,ab)/ab.sqrMagnitude;if(phase>=-.10f&&phase<1.05f&&Vector3.Distance(p,a+ab*phase)<4.1f)return true;}return false;}
   v.Clear();t.Clear();void Line(Vector3 a,Vector3 b){if(Hole((a+b)*.5f))return;var side=Vector3.Cross(Vector3.up,b-a).normalized*.010f;int k=v.Count;v.AddRange(new[]{a-side,a+side,b-side,b+side});t.AddRange(new[]{k,k+2,k+1,k+2,k+3,k+1});}
   for(float r=20.5f;r<=35;r+=2.1f)for(int i=0;i<144;i++)Line(Polar(r,i*2.5f,.024f),Polar(r,(i+1)*2.5f,.024f));for(int i=0;i<72;i++)for(float r=20.5f;r<35;r+=1)Line(Polar(r,i*5,.024f),Polar(Mathf.Min(35,r+1),i*5,.024f));MeshObject(floor,"Fine limestone circulation tiles",Make(v,t,"Floor"+f+" fine tile joints"),grout);floors++;
  }
  var cam=Camera.main;bool before=cam.useOcclusionCulling;cam.useOcclusionCulling=false;EditorUtility.SetDirty(cam);new GameObject("Presentation revision 06").transform.SetParent(root,false);AssetDatabase.SaveAssets();EditorSceneManager.MarkSceneDirty(director.gameObject.scene);EditorSceneManager.SaveScene(director.gameObject.scene);return new{floors,addedRenderers=floors*3,newColliders=0,occlusionBefore=before,occlusionAfter=cam.useOcclusionCulling,reason="Same-pose native A/B proves inherited Noryangjin occlusion data incorrectly removes the newly authored mall. Keep the old bake asset intact; this camera uses frustum and Chapter45 floor visibility.",source="Native architectural finish; existing generated retail models unchanged."};
 }
}
