using System;using System.IO;using System.Linq;using UnityEngine;using UnityEditor;using IndianOceanAssets.ShooterSurvival;using Object=UnityEngine.Object;
public static class PopcornPair16 {
 static string Json(object v)=>(string)AppDomain.CurrentDomain.GetAssemblies().First(a=>a.GetName().Name=="Newtonsoft.Json").GetType("Newtonsoft.Json.JsonConvert").GetMethod("SerializeObject",new[]{typeof(object)}).Invoke(null,new[]{v});
 static void Shot(Camera c,string file,int w=720,int h=1560){var old=c.targetTexture;var prev=RenderTexture.active;var rt=RenderTexture.GetTemporary(w,h,24,RenderTextureFormat.ARGB32);Texture2D tex=null;try{c.targetTexture=rt;c.Render();RenderTexture.active=rt;tex=new Texture2D(w,h,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,w,h),0,0);tex.Apply();File.WriteAllBytes(file,tex.EncodeToPNG());}finally{c.targetTexture=old;RenderTexture.active=prev;RenderTexture.ReleaseTemporary(rt);if(tex!=null)Object.DestroyImmediate(tex);}}
 public static object Main(string folder){if(!EditorApplication.isPlaying||Directory.Exists(folder))throw new Exception("Fresh actual Play/output required");Directory.CreateDirectory(folder);var d=Object.FindFirstObjectByType<Chapter45Director>();var role=d.GetComponentsInChildren<Chapter45RoleAction>(true).Single(r=>r.role==Chapter45RoleAction.Role.PopcornThrower);if(!role.gameObject.activeInHierarchy)throw new Exception("Actor inactive");var prop=role.heldProp;var added=prop.Find("ContentCycle16 generated popcorn container");var old=prop.Find("Popcorn paper cup");var kernels=prop.Cast<Transform>().Where(t=>t.name.StartsWith("Popcorn kernel ")).ToArray();var positions=kernels.Select(t=>t.localPosition).ToArray();var rotations=kernels.Select(t=>t.localRotation).ToArray();var meshes=kernels.Select(t=>t.GetComponent<MeshFilter>().sharedMesh).ToArray();bool addedActive=added.gameObject.activeSelf,oldActive=old.gameObject.activeSelf;var c=Camera.main;var cp=c.transform.position;var cq=c.transform.rotation;int frame=Time.frameCount;float elapsed=d.Elapsed;var temp=GameObject.CreatePrimitive(PrimitiveType.Sphere);temp.SetActive(false);var sphere=temp.GetComponent<MeshFilter>().sharedMesh;
 try{added.gameObject.SetActive(false);old.gameObject.SetActive(true);for(int i=0;i<kernels.Length;i++){kernels[i].GetComponent<MeshFilter>().sharedMesh=sphere;kernels[i].localPosition=positions[i]-Vector3.up*.07f;kernels[i].localRotation=Quaternion.identity;}Shot(c,folder+"/before.png");c.transform.position=prop.position+role.transform.forward*.95f+role.transform.right*.45f+Vector3.up*.26f;c.transform.LookAt(prop.position+Vector3.up*.02f);Shot(c,folder+"/before-detail.png",720,960);added.gameObject.SetActive(addedActive);old.gameObject.SetActive(oldActive);for(int i=0;i<kernels.Length;i++){kernels[i].GetComponent<MeshFilter>().sharedMesh=meshes[i];kernels[i].localPosition=positions[i];kernels[i].localRotation=rotations[i];}Shot(c,folder+"/after-detail.png",720,960);c.transform.SetPositionAndRotation(cp,cq);Shot(c,folder+"/after.png");}
 finally{added.gameObject.SetActive(addedActive);old.gameObject.SetActive(oldActive);for(int i=0;i<kernels.Length;i++){kernels[i].GetComponent<MeshFilter>().sharedMesh=meshes[i];kernels[i].localPosition=positions[i];kernels[i].localRotation=rotations[i];}c.transform.SetPositionAndRotation(cp,cq);Object.DestroyImmediate(temp);}
 if(frame!=Time.frameCount||elapsed!=d.Elapsed)throw new Exception("Different frame");var report=new{frame,elapsed,d.Distance,d.CurrentFloor,role.Phase,role.Actions,exactSamePlayFrame=true,before="Preserved old cylinder and original builtin sphere fill rendered in place; simulation unchanged",after="Actual saved TRELLIS carton/native caption/kernel finishing",cameraRestored=true,screenSpaceOverlayUiExcluded=true,detailView="Temporary matching close-up camera in the same frame, not normal gameplay view",handBindingPreserved=true,projectileCount=Object.FindObjectsByType<SimpleProjectile>(FindObjectsSortMode.None).Count(x=>x.name.StartsWith("PopcornThrower"))};File.WriteAllText(folder+"/conditions.json",Json(report));return report;}
}
