using System;
using System.Linq;
using UnityEditor;
using UnityEngine;
using Object=UnityEngine.Object;
public static class S22Cameras
{
 public static object Focus(){EditorWindow.GetWindow(typeof(Editor).Assembly.GetType("UnityEditor.GameView")).Focus();return new{Screen.width,Screen.height,Application.isFocused};}
 public static object Render(){var c=Camera.main;var old=c.targetTexture;var active=RenderTexture.active;var r=new RenderTexture(540,1170,24);r.Create();c.targetTexture=r;c.Render();RenderTexture.active=r;var t=new Texture2D(540,1170);t.ReadPixels(new Rect(0,0,540,1170),0,0);t.Apply();System.IO.File.WriteAllBytes("tmp/image-previews/s22-polish-2026-10-01/camera-probe.png",t.EncodeToPNG());c.targetTexture=old;RenderTexture.active=active;r.Release();Object.Destroy(r);Object.Destroy(t);return new{c.targetDisplay,c.fieldOfView,c.nearClipPlane,c.farClipPlane,rotation=c.transform.eulerAngles.ToString(),rect=c.rect.ToString(),activeRenderTexture=active!=null?active.name:"none",capture=Time.captureFramerate};}
 public static object Reload(){if(EditorApplication.isPlaying)throw new Exception("Edit required");EditorUtility.RequestScriptReload();return "Domain reload requested";}
 public static object Reopen(){if(EditorApplication.isPlaying)throw new Exception("Edit required");for(int i=0;i<UnityEngine.SceneManagement.SceneManager.sceneCount;i++)if(UnityEngine.SceneManagement.SceneManager.GetSceneAt(i).isDirty)throw new Exception("Unsaved scene");AssetDatabase.DeleteAsset("Assets/tmp/image-previews/s22-polish-2026-10-01/pipeline-screen.png");EditorApplication.delayCall+=()=>EditorApplication.Exit(0);return "Closing clean Editor to reset render backbuffer";}
 public static object ViewTexture(){var type=typeof(Editor).Assembly.GetType("UnityEditor.GameView");var w=Resources.FindObjectsOfTypeAll(type).First();var r=(RenderTexture)type.GetField("m_RenderTexture",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).GetValue(w);var old=RenderTexture.active;RenderTexture.active=r;var t=new Texture2D(r.width,r.height);t.ReadPixels(new Rect(0,0,r.width,r.height),0,0);t.Apply();System.IO.File.WriteAllBytes("tmp/image-previews/s22-polish-2026-10-01/gameview-probe.png",t.EncodeToPNG());RenderTexture.active=old;Object.Destroy(t);return new{r.width,r.height,r.name};}
 public static object Views(){var type=typeof(Editor).Assembly.GetType("UnityEditor.GameView");var windows=Resources.FindObjectsOfTypeAll(type).Cast<EditorWindow>().ToArray();UnityEditorInternal.InternalEditorUtility.RepaintAllViews();foreach(var w in windows){w.Repaint();w.Focus();}EditorApplication.QueuePlayerLoopUpdate();return new{windows=windows.Select(w=>new{w.titleContent.text,position=w.position.ToString(),w.maximized,fields=type.GetFields(System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Public).Where(f=>f.Name.Contains("Target")||f.Name.Contains("Display")||f.Name.Contains("Render")||f.Name.Contains("Size")).Select(f=>new{name=f.Name,value=f.GetValue(w)?.ToString()}).ToArray()}).ToArray()};}
 public static object Main()=>new{play=EditorApplication.isPlaying,cameras=Resources.FindObjectsOfTypeAll<Camera>().Where(c=>c.gameObject.scene.IsValid()).Select(c=>new{c.name,c.enabled,active=c.gameObject.activeInHierarchy,c.depth,c.cullingMask,pos=c.transform.position.ToString(),target=c.targetTexture!=null,root=c.transform.root.name,flags=c.transform.root.hideFlags.ToString(),scene=c.gameObject.scene.name}).ToArray(),canvases=Object.FindObjectsByType<Canvas>(FindObjectsInactive.Include,FindObjectsSortMode.None).Where(c=>c.isRootCanvas).Select(c=>new{c.name,c.enabled,active=c.gameObject.activeInHierarchy,mode=c.renderMode.ToString()}).ToArray()};
 public static object Clean(){if(EditorApplication.isPlaying)throw new Exception("Edit Mode required");var temporary=Resources.FindObjectsOfTypeAll<Camera>().Where(c=>c.gameObject.scene.IsValid()&&c.name=="Cinematic camera").Select(c=>c.transform.root.gameObject).Distinct().ToArray();foreach(var root in temporary)Object.DestroyImmediate(root);return new{removed=temporary.Length};}
}
