"""Meshy production for the 2026-09-29 Noryangjin feedback (Claude Code).

N20_ajumma_boss: new final boss (user: the old boss looked stretched sideways; Meshy allowed).
N19_live_fish_tub: live-fish auction basin (user: the cold auction did not read as a live-fish auction).
Reference images were generated by Codex (project rule: Meshy only makes 3D models/textures).
Resume-safe: an existing task in the ledger is awaited, never re-submitted.
  py -3.11 -X utf8 tools/produce-noryangjin-claude.py [asset ...]
"""
from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).parent))
from meshy_client import Meshy

RUN = Path('outputs/meshy-noryangjin-claude-2026-09-29')
CAP = 150
PROPS = {'N19_live_fish_tub': 3000}
CHARACTERS = {'N20_ajumma_boss': 14000}
ACTIONS = {'idle': 0, 'attack_once': 51, 'hit': 178, 'die': 187}
TEXTURE = {
    'N20_ajumma_boss': 'Stylized cartoon Korean fish-market ajumma: curly dark-brown permed hair, orange T-shirt, white towel, glossy white rubber apron, black waist pouch with a won sign, navy flower-pattern baggy pants with pink flowers, pink rubber gloves, green rubber boots. Clean colours, no text.',
    'N19_live_fish_tub': 'Glossy blue plastic basin with clear sea water, a flounder, a rockfish and a red sea bream inside, white plastic lot tag. Clean stylized cartoon colours.',
}


def task(client, asset, kind, submit):
    client.refresh()
    previous = [e for e in client.ledger if e['asset'] == asset and e['kind'] == kind]
    entry = previous[-1] if previous else None
    if entry and entry['status'] not in ('PENDING', 'SUCCEEDED'):
        raise RuntimeError(f'Inspect existing paid task before retrying: {asset}/{kind}/{entry["status"]}')
    if entry is None:
        entry = submit()
        print(asset, kind, 'submitted', entry['task_id'], flush=True)
    result = client.wait(entry, poll=10, timeout=2700)
    if result['status'] != 'SUCCEEDED':
        raise RuntimeError(f'{asset}/{kind}: {result["status"]}')
    return entry, result


def produce(asset):
    client = Meshy(RUN, cap=CAP)
    out = RUN / 'models' / asset
    out.mkdir(parents=True, exist_ok=True)
    ref = RUN / 'concepts' / asset / f'{asset}.png'

    def download(url, path):
        if url and not path.exists():
            client.download(url, path)

    polycount = PROPS.get(asset) or CHARACTERS[asset]
    pose = 'a-pose' if asset in CHARACTERS else ''
    model_entry, model = task(client, asset, 'model', lambda: client.to_3d(
        asset, [ref], polycount, pose=pose, texture_prompt=TEXTURE[asset], note='User 2026-09-29 Noryangjin feedback'))
    for ext in ('glb', 'fbx'):
        download(model['model_urls'].get(ext), out / f'model1.{ext}')
    download(model.get('thumbnail_url'), out / 'thumb1.png')
    if asset in CHARACTERS:
        rig_entry, rig = task(client, asset, 'rig', lambda: client.rig(asset, model_entry['task_id'], 1.7, note='boss rig'))
        for ext in ('fbx', 'glb'):
            download(rig['result'].get(f'rigged_character_{ext}_url'), out / f'rigged.{ext}')
        for key, url in rig['result'].get('basic_animations', {}).items():
            if key.endswith('_fbx_url') and 'armature' not in key:
                download(url, out / f'anim_{key.replace("_fbx_url", "")}.fbx')
        for name, action in ACTIONS.items():
            _, anim = task(client, asset, f'anim{action}', lambda: client.animate(asset, rig_entry['task_id'], action, note=name))
            res = anim['result']
            download(res.get('processed_animation_fps_fbx_url') or res.get('animation_fbx_url'), out / f'anim_{name}.fbx')
    print(asset, 'READY', 'spent', client.spent(), flush=True)


if __name__ == '__main__':
    assets = sys.argv[1:] or list(PROPS) + list(CHARACTERS)
    failed = []
    for asset in assets:
        try:
            produce(asset)
        except Exception as error:  # keep going so one failure does not block the other asset
            failed.append(asset)
            print(asset, 'FAILED', error, flush=True)
    raise SystemExit(bool(failed))
