using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Reflection;using UnityEngine;using UnityEditor;using UnityEngine.Localization.Settings;using IndianOceanAssets.ShooterSurvival;
public static class ReadabilityWindow10 {
 const BindingFlags F=BindingFlags.Instance|BindingFlags.NonPublic;
 static Chapter45Director d;static PlayerScript p;static Chapter45RoleAction cleaner;static Chapter45Hazard vehicle;static string folder;static bool active,sawActing;static int mode,frame,index;static float begin,next,end,warningAt,endedAt;static bool startedDodge,startedReturn;static readonly List<object> frames=new(),events=new(),samples=new();static readonly List<string> errors=new();
 static float inputDelay;static Vector3 originalScale;static Mesh originalMesh;static Material originalMaterial;static string originalColliders;static Dictionary<Chapter45RoleAction,Mesh> otherMeshes;
 static readonly MethodInfo Move=typeof(PlayerScript).GetMethod("PlayerMove",F);
 static string Json(object x)=>(string)AppDomain.CurrentDomain.GetAssemblies().First(a=>a.GetName().Name=="Newtonsoft.Json").GetType("Newtonsoft.Json.JsonConvert").GetMethod("SerializeObject",new[]{typeof(object)}).Invoke(null,new[]{x});
 static void Set(object o,string key,object value)=>o.GetType().GetField("<"+key+">k__BackingField",F).SetValue(o,value);
 static float[] V(Vector3 v)=>new[]{v.x,v.y,v.z};
 public static object Begin(int scenario,string output)=>BeginWithDelay(scenario,output,.35f);
 public static object BeginWithDelay(int scenario,string output,float responseDelay){
  inputDelay=responseDelay;
  if(!EditorApplication.isPlaying||active||Directory.Exists(output))throw new Exception("Fresh Play and unused output required");Directory.CreateDirectory(output);folder=output;mode=scenario;float distance=mode<3?870:mode==3?606:888;float lane=mode<3?0:mode==3?-3:3;end=mode==0?8.5f:mode<3?11.5f:10;
  d=UnityEngine.Object.FindFirstObjectByType<Chapter45Director>();p=d.Player;UnityEngine.Object.FindFirstObjectByType<CanvasScript>().PlayerPressedStartButton();
  var h=UnityEngine.Object.FindFirstObjectByType<CombatHarness>();if(h!=null)typeof(CombatHarness).GetField("overlayVisible",F).SetValue(h,false);LocalizationSettings.SelectedLocale=LocalizationSettings.AvailableLocales.Locales.Single(l=>l.Identifier.Code=="en-US");
  foreach(var e in d.encounters)if(e.stopDistance<distance){e.Retire();Set(e,"Complete",true);}foreach(var hazard in d.hazards)if(hazard.distance<distance){Set(hazard,"Triggered",true);hazard.Cancel();}
  foreach(var choice in d.choices)if(choice.distance<distance){int cs=Array.FindIndex(d.route.segments,s=>s.floor==choice.floor);if(cs>=0)Set(d,"CurrentSegment",cs);choice.Commit(3);}
  Set(d,"Distance",distance);Set(d,"CurrentSegment",d.route.SegmentAt(distance));d.SampleOnCurrentDeck(distance,out var center,out var forward);p.ApplyContinuousRoutePose(center+Vector3.up*d.footOffset,forward,lane);Physics.SyncTransforms();typeof(Chapter45Director).GetMethod("RefreshVisibility",F).Invoke(d,null);
  cleaner=mode<3?d.encounters.Where(e=>e.floor==d.CurrentFloor&&e.stopDistance>=distance).SelectMany(e=>e.actors).Select(a=>a.GetComponent<Chapter45RoleAction>()).First(r=>r!=null&&r.role==Chapter45RoleAction.Role.Cleaner):null;
  vehicle=mode>=3?d.hazards.First(v=>mode==3?v.name.Contains("motorcycle 650"):v.name.Contains("Wrong way kickboard")):null;
  if(cleaner!=null){originalScale=cleaner.warningMarker.localScale;originalMesh=cleaner.warningMarker.GetComponent<MeshFilter>().sharedMesh;originalMaterial=cleaner.warningMarker.GetComponent<Renderer>().sharedMaterial;originalColliders=Json(cleaner.GetComponentsInChildren<Collider>(true).Select(c=>EditorJsonUtility.ToJson(c)).ToArray());otherMeshes=d.encounters.SelectMany(e=>e.actors).Select(a=>a.GetComponent<Chapter45RoleAction>()).Where(r=>r!=null&&r.role!=Chapter45RoleAction.Role.Cleaner&&r.warningMarker!=null).ToDictionary(r=>r,r=>r.warningMarker.GetComponent<MeshFilter>().sharedMesh);}
  if(p.MaxHealth!=60||p.ResolvedAttackDamage!=8||TimeManager.timeFactor!=1)throw new Exception("Expected ordinary 60HP/8ATK at 1x");
  begin=d.Elapsed;next=0;warningAt=endedAt=-1;frame=-1;index=0;startedDodge=startedReturn=sawActing=false;frames.Clear();events.Clear();samples.Clear();errors.Clear();active=true;Application.logMessageReceived+=Log;EditorApplication.update+=Tick;
  File.WriteAllText(Path.Combine(folder,"conditions.json"),Json(new{scenario,distance,lane,end,ordinaryPlaythrough=false,initialPoseDirected=true,earlierEncountersRetired=true,upcomingActorsUnmodified=true,nativeUpdate=true,manualDamage=false,manualRoleOrHazardTick=false,statsOverridden=false,cleanerDodgeDelay=inputDelay,returnDelay=.3f,target=cleaner!=null?cleaner.name:vehicle.name,vehicle=vehicle==null?null:new{vehicle.distance,vehicle.safeLane,vehicle.warningSeconds,vehicle.operationSeconds,sweepFrom=V(vehicle.sweepFrom),sweepTo=V(vehicle.sweepTo)}}));return new{started=true,folder,scenario};
 }
 static void Log(string msg,string trace,LogType type){if(type==LogType.Error||type==LogType.Exception||type==LogType.Assert)errors.Add(msg);}
 static void Tick(){
  if(!active||!EditorApplication.isPlaying)return;EditorApplication.QueuePlayerLoopUpdate();if(frame==Time.frameCount)return;frame=Time.frameCount;float t=d.Elapsed-begin;
  if(cleaner!=null){if(cleaner.Phase==Chapter45RoleAction.ActionPhase.Warning&&warningAt<0){warningAt=t;events.Add(new{t,kind="cleaner warning observed",lane=d.Lane});}if(cleaner.Phase==Chapter45RoleAction.ActionPhase.Acting)sawActing=true;if(sawActing&&cleaner.Phase==Chapter45RoleAction.ActionPhase.Recovering&&endedAt<0){endedAt=t;events.Add(new{t,kind="cleaner recovery observed",lane=d.Lane,contacts=cleaner.Contacts});}}
  else{if(vehicle.Triggered&&warningAt<0){warningAt=t;events.Add(new{t,kind="vehicle warning observed",lane=d.Lane});}if(vehicle.Active)sawActing=true;if(sawActing&&vehicle.Finished&&endedAt<0){endedAt=t;events.Add(new{t,kind="vehicle body and warning hidden",lane=d.Lane,contacts=vehicle.Contacts,bodyActive=vehicle.body.gameObject.activeInHierarchy,footprintActive=vehicle.footprint!=null&&vehicle.footprint.activeInHierarchy});}}
  float targetLane=d.Lane;
  if(mode==1||mode==2){if(warningAt>=0&&t-warningAt>=inputDelay){targetLane=mode==1?3:-3;if(!startedDodge){startedDodge=true;events.Add(new{t,kind="dodge input begins",targetLane});}}}
  if(mode!=0&&endedAt>=0&&t-endedAt>=.3f){targetLane=0;if(!startedReturn){startedReturn=true;events.Add(new{t,kind="return to center input begins",targetLane});}}
  if(Mathf.Abs(targetLane-d.Lane)>.06f)Move.Invoke(p,new object[]{Mathf.Clamp((targetLane-d.Lane)*6,-15,15)});
  Vector3 markerCenter=cleaner!=null?cleaner.warningMarker.position:Vector3.zero;float markerRadius=cleaner!=null?Mathf.Max(cleaner.warningMarker.GetComponent<Renderer>().bounds.extents.x,cleaner.warningMarker.GetComponent<Renderer>().bounds.extents.z):0;Vector3 strike=cleaner!=null?cleaner.transform.position+cleaner.transform.forward*(2.6f*.55f):Vector3.zero;
  samples.Add(new{t,warningCenter=V(markerCenter),warningRadius=markerRadius,strike=V(strike),strikeRadius=2.6f*.55f+.45f,markerDistance=Vector3.ProjectOnPlane(p.transform.position-markerCenter,Vector3.up).magnitude,strikeDistance=Vector3.ProjectOnPlane(p.transform.position-strike,Vector3.up).magnitude,lane=d.Lane,hp=p.currentHealth,rolePhase=cleaner?.Phase.ToString(),roleContacts=cleaner?.Contacts,vehicleActive=vehicle?.Active,vehicleContacts=vehicle?.Contacts,vehicleBodyActive=vehicle==null?(bool?)null:vehicle.body.gameObject.activeInHierarchy,returning=startedReturn});
  if(t>=3.4f&&t>=next){next=t+.12f;string file=(index++).ToString("D3")+".png";ScreenCapture.CaptureScreenshot(Path.Combine(folder,file));
   frames.Add(new{file,t,d.Distance,lane=d.Lane,health=p.currentHealth,player=V(p.transform.position),roles=d.encounters.Where(e=>e.Activated&&!e.Complete&&e.floor==d.CurrentFloor).SelectMany(e=>e.actors).Where(a=>a!=null&&a.gameObject.activeInHierarchy&&!a.IsDead).Select(a=>new{a.name,position=V(a.transform.position),role=a.GetComponent<Chapter45RoleAction>()?.role.ToString(),phase=a.GetComponent<Chapter45RoleAction>()?.Phase.ToString(),contacts=a.GetComponent<Chapter45RoleAction>()?.Contacts,marker=a.GetComponent<Chapter45RoleAction>()?.warningMarker!=null&&a.GetComponent<Chapter45RoleAction>().warningMarker.gameObject.activeInHierarchy}).ToArray(),vehicle=vehicle==null?null:new{vehicle.Active,vehicle.Finished,vehicle.Contacts,bodyActive=vehicle.body.gameObject.activeInHierarchy,body=V(vehicle.body.position),footprint=vehicle.footprint!=null&&vehicle.footprint.activeInHierarchy},allActiveHazards=d.hazards.Where(h=>h.Triggered&&!h.Finished).Select(h=>new{h.name,h.Active,h.Contacts}).ToArray()});
  }
  if(t<end&&p.currentHealth>0)return;active=false;EditorApplication.update-=Tick;Application.logMessageReceived-=Log;
  int? contacts=cleaner?.Contacts,actions=cleaner?.Actions;var checks=new Dictionary<string,bool>();
  if(cleaner!=null){checks["same existing mesh"]=cleaner.warningMarker.GetComponent<MeshFilter>().sharedMesh==originalMesh;checks["same existing material"]=cleaner.warningMarker.GetComponent<Renderer>().sharedMaterial==originalMaterial;checks["actor colliders unchanged"]=originalColliders==Json(cleaner.GetComponentsInChildren<Collider>(true).Select(c=>EditorJsonUtility.ToJson(c)).ToArray());checks["other role meshes unchanged"]=otherMeshes.All(kv=>kv.Key.warningMarker.GetComponent<MeshFilter>().sharedMesh==kv.Value);cleaner.enabled=false;checks["authored scale restored on disable"]=cleaner.warningMarker.localScale==originalScale;checks["authored mesh restored on disable"]=cleaner.warningMarker.GetComponent<MeshFilter>().sharedMesh==originalMesh;checks["marker hidden on disable"]=!cleaner.warningMarker.gameObject.activeSelf;cleaner.enabled=true;checks["reenable resets role and marker"]=cleaner.Phase==Chapter45RoleAction.ActionPhase.Moving&&cleaner.Contacts==0&&!cleaner.warningMarker.gameObject.activeSelf;}
  File.WriteAllText(Path.Combine(folder,"result.json"),Json(new{complete=true,scenario=mode,elapsed=t,health=p.currentHealth,sawActing,warningAt,endedAt,startedDodge,startedReturn,finalLane=d.Lane,roleContacts=contacts,roleActions=actions,checks,vehicleContacts=vehicle?.Contacts,frames=frames.ToArray(),events=events.ToArray(),samples=samples.ToArray(),errors=errors.ToArray(),timeline=d.Timeline.ToArray(),manualDamage=false,manualRoleOrHazardTick=false}));
 }
 public static object Stop(){active=false;EditorApplication.update-=Tick;Application.logMessageReceived-=Log;return new{stopped=true};}
}
