using System;using System.IO;using System.Linq;using System.Collections;using System.Collections.Generic;using System.Reflection;using UnityEngine;using UnityEditor;using UnityEngine.Localization.Settings;using TMPro;using IndianOceanAssets.ShooterSurvival;using Object=UnityEngine.Object;
public static class RegressionUiFixtureCycle08 {
 const BindingFlags Private=BindingFlags.Instance|BindingFlags.NonPublic;
 const string Root="outputs/chapter45-detailed-design-2026-10-03/regression-cycle08/";
 public sealed class Case{public string id,title,detail,enTitle,enDetail;}
 static Chapter45Director d;static CanvasScript canvas;static string output,phase;static Case[] cases;static List<object> checks;static int failed;static int wallet,jewels;
 static Type J=>AppDomain.CurrentDomain.GetAssemblies().First(a=>a.GetName().Name=="Newtonsoft.Json").GetType("Newtonsoft.Json.JsonConvert");
 static string Json(object o)=>(string)J.GetMethod("SerializeObject",new[]{typeof(object)}).Invoke(null,new[]{o});
 static void Set(object o,string name,object value)=>o.GetType().GetField("<"+name+">k__BackingField",Private).SetValue(o,value);
 static void Check(bool ok,string label){checks.Add(new{pass=ok,label});if(!ok)failed++;}
 static void Clear()=>((Chapter45NoticeQueue)typeof(Chapter45Director).GetField("notices",Private).GetValue(d)).Clear();
 static void Render()=>typeof(Chapter45Director).GetMethod("RenderAnnouncement",Private).Invoke(d,null);
 static object Measure(TMP_Text t){t.ForceMeshUpdate();var r=t.rectTransform.rect;var ch=t.textInfo.characterInfo.Take(t.textInfo.characterCount).Where(c=>c.isVisible).ToArray();return new{text=t.text,t.fontSize,lines=t.textInfo.lineCount,overflow=t.isTextOverflowing,outside=ch.Any(c=>c.bottomLeft.x<r.xMin-1||c.topRight.x>r.xMax+1||c.bottomLeft.y<r.yMin-1||c.topRight.y>r.yMax+1),missing=(t.text??"").Where(c=>!char.IsWhiteSpace(c)&&!t.font.HasCharacter(c,true,false)).Distinct().Select(c=>c.ToString()).ToArray()};}
 static void Capture(string id,bool screenshot=true){Canvas.ForceUpdateCanvases();var texts=new[]{d.hud.title,d.hud.description};foreach(var t in texts){t.ForceMeshUpdate();var r=t.rectTransform.rect;var ch=t.textInfo.characterInfo.Take(t.textInfo.characterCount).Where(c=>c.isVisible).ToArray();Check(!t.isTextOverflowing&&!ch.Any(c=>c.bottomLeft.x<r.xMin-1||c.topRight.x>r.xMax+1||c.bottomLeft.y<r.yMin-1||c.topRight.y>r.yMax+1)&&!(t.text??"").Any(c=>!char.IsWhiteSpace(c)&&!t.font.HasCharacter(c,true,false)),id+" fits "+t.name);}string file=Path.Combine(output,id);if(File.Exists(file+".json"))throw new Exception("Preserve evidence");File.WriteAllText(file+".json",Json(new{id,phase,locale=LocalizationSettings.SelectedLocale.Identifier.Code,width=Screen.width,height=Screen.height,measurements=texts.Select(Measure).ToArray(),coin=MoneyScript.S.Coin,jewel=MoneyScript.S.Jewel,presentationFixture=true}));if(screenshot)ScreenCapture.CaptureScreenshot(file+".png");}
 public static object Main(string targetPhase){if(!EditorApplication.isPlaying||targetPhase!="before-fix"&&targetPhase!="after-fix")throw new Exception("Play and explicit phase required");phase=targetPhase;output=Root+"focused-"+phase;if(Directory.Exists(output))throw new Exception("Preserve phase");Directory.CreateDirectory(output);cases=(Case[])J.GetMethod("DeserializeObject",new[]{typeof(string),typeof(Type)}).Invoke(null,new object[]{File.ReadAllText(Root+"translation-cases.json"),typeof(Case[])});checks=new List<object>();failed=0;d=Object.FindFirstObjectByType<Chapter45Director>();canvas=Object.FindFirstObjectByType<CanvasScript>();canvas.PlayerPressedStartButton();Time.timeScale=0;Set(d,"Running",false);wallet=MoneyScript.S.Coin;jewels=MoneyScript.S.Jewel;var overlay=Object.FindFirstObjectByType<CombatHarness>();if(overlay)typeof(CombatHarness).GetField("overlayVisible",Private).SetValue(overlay,false);canvas.StartCoroutine(Guarded(Run()));return new{started=true,phase,cases=cases.Length};}
 static IEnumerator Guarded(IEnumerator routine){while(true){object current;try{if(!routine.MoveNext())break;current=routine.Current;}catch(Exception e){failed++;checks.Add(new{pass=false,label=e.ToString()});break;}yield return current;}Check(MoneyScript.S.Coin==wallet&&MoneyScript.S.Jewel==jewels,"UI fixture does not pay or change wallet");File.WriteAllText(Path.Combine(output,"summary.json"),Json(new{phase,passed=checks.Count-failed,failed,checks,cases=cases.Length,fixtureOnly=true,gameplayRewardsInvoked=false}));}
 static IEnumerator Run(){foreach(string code in new[]{"ko-KR","en-US"}){LocalizationSettings.SelectedLocale=LocalizationSettings.AvailableLocales.Locales.Single(l=>l.Identifier.Code==code);yield return null;yield return null;foreach(var c in cases){Clear();d.Announce(c.title,c.detail,999);yield return null;bool en=code=="en-US";if(!en||phase=="after-fix")Check(d.hud.title.text==(en?c.enTitle:c.title)&&d.hud.description.text==(en?c.enDetail:c.detail),c.id+" "+code+" exact expected wording");Capture(code+"-"+c.id,c.id=="00"||c.id=="01"||c.id=="07"||c.id=="08"||c.id=="13"||c.id=="30");yield return new WaitForEndOfFrame();}
  Clear();Set(d,"Elapsed",100f);d.AnnounceReward("보상 획득","코인 +120 · 공격 +10%",3);d.AnnounceWarning("행동 예고","접시 투척 · 옆으로 이동하세요",1.1f);Set(d,"Elapsed",100.1f);d.AnnounceWarning("주문 034번","호출된 대기줄이 이동합니다",1.2f);yield return null;string plate=code=="en-US"?"Plate throw":"접시 투척",order=code=="en-US"?"Order 034":"주문 034번";Check(d.hud.description.text.Contains(plate)&&d.hud.description.text.Contains(order),code+" native two warnings coexist");Capture(code+"-warnings-two");yield return new WaitForEndOfFrame();d.AnnounceWarning("행동 예고","와 머야~!! · 손을 뻗기 전에 옆으로",1.2f);d.Announce("경비 구역","최종 전시 매니저",2);yield return null;Check(d.hud.description.text.Contains(plate)&&d.hud.description.text.Contains(order)&&d.hud.description.text.Contains(code=="en-US"?"Whoa":"와 머야"),code+" three warnings survive informational notice");Capture(code+"-warnings-three");yield return new WaitForEndOfFrame();Set(d,"Elapsed",102f);Render();yield return null;Check(d.hud.title.text==(code=="en-US"?"Reward received":"보상 획득")&&d.hud.description.text==(code=="en-US"?"Coins +120 · ATK +10%":"코인 +120 · 공격 +10%"),code+" interrupted reward returns after native warning expiry");Capture(code+"-reward-after-warnings");yield return new WaitForEndOfFrame();}}
}
