using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections.Generic;using UnityEngine;using UnityEngine.Localization.Settings;using UnityEngine.SceneManagement;using Object=UnityEngine.Object;
public static class RegressionObserveCycle08 {
 static string Json(object o)=>(string)AppDomain.CurrentDomain.GetAssemblies().First(a=>a.GetName().Name=="Newtonsoft.Json").GetType("Newtonsoft.Json.JsonConvert").GetMethod("SerializeObject",new[]{typeof(object)}).Invoke(null,new[]{o});
 public static object Main(string label){
  if(Path.GetFileName(label)!=label)throw new Exception("Basename required");string path="outputs/chapter45-detailed-design-2026-10-03/regression-cycle08/observer-"+label+".json";if(File.Exists(path))throw new Exception("Preserve evidence");
  var settings=LocalizationSettings.Instance;var array=typeof(LocalizationSettings).GetField("m_SelectedLocaleChanged",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(settings);var t=array.GetType();int length=(int)t.GetProperty("Length").GetValue(array);var delegates=new List<Delegate>();if(length==1)delegates.Add((Delegate)t.GetProperty("SingleDelegate").GetValue(array));else if(length>1)delegates.AddRange(((Array)t.GetProperty("MultiDelegates").GetValue(array)).Cast<Delegate>().Take(length));
  var relevant=delegates.Where(d=>d.Method.DeclaringType==typeof(Chapter45Choice)||d.Method.DeclaringType==typeof(Chapter45CompletionPresentation)).ToArray();int destroyed=relevant.Count(d=>d.Target is Object o&&o==null);int duplicate=relevant.GroupBy(d=>d).Count(g=>g.Count()>1);var director=Object.FindFirstObjectByType<Chapter45Director>();
  var rows=relevant.Select(d=>new{method=d.Method.DeclaringType.Name+"."+d.Method.Name,target=d.Target is Object o&&o!=null?o.name:"destroyed",scene=d.Target is Component c&&c!=null?c.gameObject.scene.name:"",enabled=d.Target is MonoBehaviour m&&m!=null&&m.isActiveAndEnabled}).ToArray();
  var result=new{utc=DateTime.UtcNow.ToString("o"),scene=SceneManager.GetActiveScene().name,locale=LocalizationSettings.SelectedLocale.Identifier.Code,selectedLocaleListeners=length,chapterListeners=rows,destroyedChapterListeners=destroyed,duplicateChapterListeners=duplicate,authoredEncounters=director==null?null:director.encounters.Select(e=>new{e.name,e.floor,e.announcement,e.Activated,e.Complete}).ToArray(),choices=director==null?null:director.choices.Select(c=>new{c.name,c.leftName,c.rightName,c.Selected,c.Selection,c.Rewarded}).ToArray(),readOnly=true};File.WriteAllText(path,Json(result));if(destroyed!=0||duplicate!=0)throw new Exception("Stale or duplicate new locale listener");return new{scene=SceneManager.GetActiveScene().name,chapterListeners=rows.Length,destroyedChapterListeners=destroyed,duplicateChapterListeners=duplicate,readOnly=true};
 }
}
