using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEngine;
using UnityEngine.Animations;
using UnityEngine.Playables;
using TMPro;
using IndianOceanAssets.ShooterSurvival;
using Object=UnityEngine.Object;

// Deterministic, actually animated native cinematics. Uses the installed hero
// and reviewed scene assets, not independently generated lookalike characters.
public static class S22Cinematics
{
 const string Out="outputs/s22-polish-2026-10-01/cinematics-v2";
 const string Pref="Assets/ShooterSurvival/Prefabs/MeshyRestStop20260925/";
 static readonly Vector3 Origin=new Vector3(10000,10000,10000);
 sealed class Actor
 {
  public Transform holder,model;public Animator animator;public bool isHero;public AnimationClip[] clips;public PlayableGraph graph;public AnimationClipPlayable playable;public AnimationClip current;
  public void Animate(string key,float time){if(animator==null)return;var clip=clips.FirstOrDefault(c=>c.name.ToLowerInvariant().Contains(key.ToLowerInvariant()))??clips.FirstOrDefault();if(clip==null)return;if(isHero){animator.speed=0;animator.Play(key.Equals("walk",StringComparison.OrdinalIgnoreCase)?"Walk":"Idle",0,(time/Mathf.Max(.01f,clip.length))%1);animator.Update(0);}else{if(current!=clip){if(graph.IsValid())graph.Destroy();current=clip;animator.runtimeAnimatorController=null;graph=PlayableGraph.Create("Native cinematic animation");playable=AnimationClipPlayable.Create(graph,clip);playable.SetSpeed(0);AnimationPlayableOutput.Create(graph,"Actor",animator).SetSourcePlayable(playable);graph.Play();}playable.SetTime(time%Mathf.Max(.01f,clip.length));graph.Evaluate(0);}foreach(var rig in model.GetComponentsInChildren<SharkTailFootRig>())rig.Synchronize();}
  public void Dispose(){if(graph.IsValid())graph.Destroy();}
 }
 sealed class Stage
 {
  public GameObject root;public Camera camera;public RenderTexture rt;public Texture2D pixels;public Actor hero,normal;public Transform shoe,better;public readonly List<Actor> people=new();public readonly List<Transform> cars=new(),sparkles=new();public readonly List<Material> materials=new();public int shot;
  public Vector3 W(Vector3 p)=>Origin+p;
  public Material Mat(string name,Color color){var m=new Material(Shader.Find("Universal Render Pipeline/Lit")){name=name};m.SetColor("_BaseColor",color);m.SetFloat("_Smoothness",name=="sacred gold"?.65f:.25f);m.SetFloat("_Metallic",name=="sacred gold"?.7f:0);materials.Add(m);return m;}
  public Transform Box(string name,Vector3 position,Vector3 size,Material material){var go=GameObject.CreatePrimitive(PrimitiveType.Cube);go.name=name;Object.Destroy(go.GetComponent<Collider>());go.transform.SetParent(root.transform,false);go.transform.localPosition=position;go.transform.localScale=size;go.layer=31;go.GetComponent<Renderer>().sharedMaterial=material;return go.transform;}
  public Transform Sphere(string name,Vector3 position,Vector3 size,Material material){var go=GameObject.CreatePrimitive(PrimitiveType.Sphere);go.name=name;Object.Destroy(go.GetComponent<Collider>());go.transform.SetParent(root.transform,false);go.transform.localPosition=position;go.transform.localScale=size;go.layer=31;go.GetComponent<Renderer>().sharedMaterial=material;return go.transform;}
  public Transform Prop(string path,Vector3 position,float height,float yaw=0){var prefab=AssetDatabase.LoadAssetAtPath<GameObject>(path);if(prefab==null)throw new Exception(path);var holder=new GameObject(prefab.name+" stage holder").transform;holder.SetParent(root.transform,false);holder.localPosition=position;holder.localRotation=Quaternion.Euler(0,yaw,0);var go=Object.Instantiate(prefab,holder);go.transform.localPosition=Vector3.zero;foreach(var t in go.GetComponentsInChildren<Transform>(true))t.gameObject.layer=31;foreach(var c in go.GetComponentsInChildren<Collider>(true))c.enabled=false;foreach(var b in go.GetComponentsInChildren<MonoBehaviour>(true))b.enabled=false;var bounds=Bounds(go);go.transform.localScale*=height/Mathf.Max(.00001f,bounds.size.y);bounds=Bounds(go);go.transform.position+=holder.position-new Vector3(bounds.center.x,bounds.min.y,bounds.center.z);return holder;}

  public void Text(Transform parent,string value,Vector3 pos,float size,float width){var go=new GameObject("Readable sign",typeof(TextMeshPro));go.transform.SetParent(parent,false);go.transform.localPosition=pos;go.layer=31;var t=go.GetComponent<TextMeshPro>();t.font=GameUIFont.Load();t.text=value;t.fontSize=size;t.alignment=TextAlignmentOptions.Center;t.color=new Color(1,.94f,.75f);t.rectTransform.sizeDelta=new Vector2(width,1.1f);t.textWrappingMode=TextWrappingModes.NoWrap;}
  public void Frame(Vector3 position,Vector3 target){camera.transform.SetPositionAndRotation(W(position),Quaternion.LookRotation(W(target)-W(position)));}
  public void SubjectFrame(Actor actor,Vector3 direction,float distance){var b=Bounds(actor.model.gameObject);camera.transform.SetPositionAndRotation(b.center+direction.normalized*distance,Quaternion.LookRotation(-direction));}
  public void Dispose(){hero?.Dispose();normal?.Dispose();foreach(var p in people)p.Dispose();camera.enabled=false;camera.targetTexture=null;rt.Release();Object.Destroy(root);Object.Destroy(rt);Object.Destroy(pixels);foreach(var m in materials)Object.Destroy(m);}
 }
 static Bounds Bounds(GameObject go){var rs=go.GetComponentsInChildren<Renderer>(true).Where(r=>!(r is ParticleSystemRenderer)).ToArray();if(rs.Length==0)return new Bounds(go.transform.position,Vector3.one);var b=rs[0].bounds;foreach(var r in rs.Skip(1))b.Encapsulate(r.bounds);return b;}
 static Actor MakeActor(Stage s,string path,bool hero){var parent=new GameObject(hero?"Canonical hero":"Actor").transform;parent.SetParent(s.root.transform,false);var go=Object.Instantiate(AssetDatabase.LoadAssetAtPath<GameObject>(path),parent);foreach(var t in go.GetComponentsInChildren<Transform>(true))t.gameObject.layer=31;foreach(var c in go.GetComponentsInChildren<Collider>(true))c.enabled=false;foreach(var b in go.GetComponentsInChildren<MonoBehaviour>(true))b.enabled=false;var a=go.GetComponentInChildren<Animator>();AnimationClip[] clips;
  if(hero){if(a==null)a=go.AddComponent<Animator>();a.avatar=AssetDatabase.LoadAllAssetsAtPath(path).OfType<Avatar>().FirstOrDefault();a.runtimeAnimatorController=AssetDatabase.LoadAssetAtPath<RuntimeAnimatorController>("Assets/JH/Anim/Shark/Original.controller");CosmeticAppearance.Apply(go.transform,Resources.Load<CosmeticVisualCatalog>("Cosmetics/Catalog"),"skin_original","shoes_original","hat_none");}
  if(path.Contains("Shark_White")){foreach(var r in go.GetComponentsInChildren<Renderer>()){var ms=r.sharedMaterials.Select(m=>{var replacement=s.Mat("natural shark",m.HasProperty("_Color")?m.color:Color.white);if(m.mainTexture!=null)replacement.SetTexture("_BaseMap",m.mainTexture);return replacement;}).ToArray();r.sharedMaterials=ms;}}
  clips=a!=null&&a.runtimeAnimatorController!=null?a.runtimeAnimatorController.animationClips.Distinct().ToArray():Array.Empty<AnimationClip>();if(a!=null){a.cullingMode=AnimatorCullingMode.AlwaysAnimate;a.applyRootMotion=false;}foreach(var r in go.GetComponentsInChildren<SkinnedMeshRenderer>(true))r.updateWhenOffscreen=true;
  return new Actor{holder=parent,model=go.transform,animator=a,clips=clips,isHero=hero};
 }
 static void Fit(Actor a,float size,bool length=false){var b=Bounds(a.model.gameObject);a.model.localScale*=size/Mathf.Max(.00001f,length?Mathf.Max(b.size.x,b.size.z):b.size.y);b=Bounds(a.model.gameObject);a.model.position+=a.holder.position-new Vector3(b.center.x,length?b.center.y:b.min.y,b.center.z);}
 static Stage Build(int shot){var s=new Stage{shot=shot};s.root=new GameObject("Temporary native cinematic"){hideFlags=HideFlags.DontSave};s.root.transform.position=Origin;var c=new GameObject("Cinematic camera");c.transform.SetParent(s.root.transform,false);s.camera=c.AddComponent<Camera>();s.camera.clearFlags=CameraClearFlags.SolidColor;s.camera.backgroundColor=new Color(.48f,.72f,.82f);s.camera.cullingMask=1<<31;s.camera.fieldOfView=42;s.camera.nearClipPlane=.1f;s.camera.farClipPlane=180;s.camera.allowHDR=false;s.camera.aspect=9f/16;s.rt=new RenderTexture(576,1024,24);s.rt.Create();s.camera.targetTexture=s.rt;s.pixels=new Texture2D(576,1024,TextureFormat.RGB24,false);
  var wood=s.Mat("harbor timber",new Color(.36f,.23f,.13f));var stone=s.Mat("warm granite",new Color(.49f,.52f,.51f));var water=s.Mat("harbor water",new Color(.03f,.45f,.58f));var navy=s.Mat("navy enamel",new Color(.025f,.12f,.21f));var gold=s.Mat("sacred gold",new Color(1,.67f,.08f));var purple=s.Mat("curse light",new Color(.52f,.19f,.86f));var white=s.Mat("lane paint",new Color(.92f,.94f,.9f));
  s.hero=MakeActor(s,AssetDatabase.GetAssetPath(Resources.Load<CosmeticVisualCatalog>("Cosmetics/Catalog").previewModel),true);s.hero.Animate("Idle",0);
  if(shot<3){s.normal=MakeActor(s,"Assets/polyperfect/Low Poly Animated Animals/- Prefabs/Animals/Shark_White.prefab",false);s.normal.Animate("Swim",0);s.Box("Sea",new Vector3(0,-.3f,-18),new Vector3(90,.2f,40),water);s.Box("Stone quay",new Vector3(0,-.3f,12),new Vector3(30,.6f,27),stone);
   s.Box("Offering platform",new Vector3(0,.3f,2),new Vector3(3,.6f,2.6f),stone);s.Box("Offering stone",new Vector3(0,1,2),new Vector3(1.7f,.65f,1.2f),stone);
   for(int i=0;i<7;i++)s.Sphere("Seonang stone cairn",new Vector3(-2,.3f+i*.32f,3),new Vector3(1.15f-i*.1f,.46f,.95f-i*.08f),stone);
   s.Box("Sacred tree trunk",new Vector3(-3.2f,2.3f,4),new Vector3(.4f,4.6f,.42f),wood);var leaves=s.Mat("pine crown",new Color(.1f,.31f,.21f));for(int i=0;i<3;i++)s.Sphere("Pine foliage",new Vector3(-3.2f+i*.6f,4.2f+i*.35f,4),new Vector3(3,1.5f,2.5f),leaves);
   for(int i=0;i<5;i++)s.Box("Ritual ribbon",new Vector3(-3.6f+i*.21f,2.8f,3.74f),new Vector3(.13f,1.1f,.025f),s.Mat("ribbon",new[]{Color.white,new Color(.83f,.15f,.12f),new Color(.95f,.73f,.12f),new Color(.07f,.33f,.58f),new Color(.12f,.18f,.2f)}[i]));
   s.shoe=s.Prop("Assets/ShooterSurvival/Prefabs/Cosmetics/Trellis/shoes_ruby.prefab",new Vector3(0,1.34f,2),.65f,90);foreach(var r in s.shoe.GetComponentsInChildren<Renderer>())r.sharedMaterials=Enumerable.Repeat(gold,r.sharedMaterials.Length).ToArray();
   s.better=s.Prop("Assets/ShooterSurvival/Prefabs/Cosmetics/Trellis/shoes_relic.prefab",new Vector3(2,.1f,10),.8f,0);
   for(int i=0;i<16;i++)s.sparkles.Add(s.Sphere("Spiritual light",Vector3.zero,Vector3.one*.08f,i%2==0?gold:purple));
   s.Frame(new Vector3(-6,4,-8),new Vector3(0,1.3f,1));
  }
  else if(shot==3){s.Box("Harbor boardwalk",new Vector3(0,-.25f,9),new Vector3(15,.5f,30),wood);for(int i=0;i<3;i++)foreach(int side in new[]{-1,1})s.Prop("Assets/ShooterSurvival/Prefabs/MeshyAI/Stage01_Noryangjin/014_STAGE01_NRY_BLD_001_Fish_market_storefront_facade/014_STAGE01_NRY_BLD_001_Fish_market_storefront_facade.prefab",new Vector3(side*3.6f,0,i*7),3.8f,side<0?90:-90);var sign=s.Box("Market entrance",new Vector3(0,4.3f,-2),new Vector3(10,1.2f,.3f),navy);s.Text(s.root.transform,"노량진 수산시장",new Vector3(0,4.3f,-1.8f),4.6f,7);s.Frame(new Vector3(7,4.5f,8),new Vector3(0,1.3f,3));}
  else if(shot==4){var asphalt=s.Mat("asphalt",new Color(.17f,.2f,.22f));s.Box("Highway",new Vector3(0,-.15f,5),new Vector3(20,.3f,90),asphalt);for(int lane=-1;lane<=1;lane++)for(int j=-8;j<10;j++)s.Box("Lane marking",new Vector3(lane*3.6f,.02f,j*5),new Vector3(.12f,.025f,2.7f),white);for(int side=-1;side<=1;side+=2)s.Box("Road edge",new Vector3(side*7.3f,.4f,5),new Vector3(.28f,.8f,90),stone);var green=s.Mat("distant hills",new Color(.23f,.41f,.24f));for(int i=0;i<8;i++)s.Sphere("Korean hillside",new Vector3((i%2==0?-1:1)*(36+i),1,10+i*8),new Vector3(18,6+i,24),green);for(int i=0;i<7;i++){string type=i%3==0?"V05_tour_bus":i%3==1?"V02_white_sedan":"V08_box_truck";s.cars.Add(s.Prop(Pref+type+".prefab",new Vector3((i%3-1)*3.6f,0,10+i*7),i%3==0?2.8f:1.8f,180));}s.Frame(new Vector3(-9,4,6),new Vector3(-4,1.3f,1));}
  else{s.Box("Rest stop plaza",new Vector3(0,-.15f,7),new Vector3(35,.3f,45),s.Mat("plaza paving",new Color(.58f,.65f,.65f)));s.Box("Food hall",new Vector3(0,3.5f,15),new Vector3(24,7,3),stone);s.Box("Teal canopy",new Vector3(0,6.5f,12),new Vector3(25,.45f,8),navy);s.Text(s.root.transform,"한울휴게소",new Vector3(0,5.1f,13.3f),7,18);var glass=s.Mat("window glazing",new Color(.12f,.32f,.4f));for(int i=-5;i<=5;i++)s.Box("Hall windows",new Vector3(i*2,2.6f,13.45f),new Vector3(1.75f,4,.12f),glass);for(int i=0;i<5;i++){var a=MakeActor(s,Pref+(i%2==0?"N13_merchant_male":"N14_merchant_female")+".prefab",false);s.people.Add(a);a.Animate("idle",0);}s.Frame(new Vector3(8,5,10),new Vector3(0,1.8f,5));}
  if(shot==3){s.root.transform.Find("Readable sign").localRotation=Quaternion.Euler(0,180,0);for(int i=-10;i<42;i++)s.Box("Boardwalk plank",new Vector3(0,.014f,i*.55f),new Vector3(15,.028f,.50f),wood);for(int side=-1;side<=1;side+=2)s.Box("Entrance post",new Vector3(side*4.8f,2.1f,-2),new Vector3(.18f,4.2f,.25f),navy);}
  if(shot==5){foreach(Transform t in s.root.transform.Cast<Transform>().Where(t=>t.name=="Food hall"||t.name=="Hall windows").ToArray())Object.Destroy(t.gameObject);const string prod="Assets/ShooterSurvival/Prefabs/RestStopProduction20260925/";for(int i=-4;i<=4;i++){if(i==0)continue;s.Prop(prod+"B05.prefab",new Vector3(i*2.6f,0,14),4.6f);if(i%2==0)s.Prop(prod+"B04.prefab",new Vector3(i*2.6f-1.3f,0,14),4.8f);}s.Prop(prod+"B06.prefab",new Vector3(0,0,13.8f),4.6f);}
  var keyLight=new GameObject("Cinematic key light");keyLight.transform.SetParent(s.root.transform,false);keyLight.transform.localRotation=Quaternion.Euler(48,-35,0);var lamp=keyLight.AddComponent<Light>();lamp.type=LightType.Directional;lamp.intensity=1.1f;lamp.color=new Color(1,.93f,.8f);lamp.cullingMask=1<<31;lamp.shadows=LightShadows.Soft;
  return s;
 }
 static float Ease(float t){t=Mathf.Clamp01(t);return t*t*(3-2*t);}
 static void Pose(Stage s,float time,float length){float u=time/length;
  if(s.shot==0){s.hero.holder.gameObject.SetActive(false);s.normal.holder.gameObject.SetActive(true);float take=Ease((u-.45f)/.55f);var pos=u<.45f?Vector3.Lerp(new Vector3(-4,.1f,-5),new Vector3(0,.1f,.1f),Ease(u/.45f)):Vector3.Lerp(new Vector3(0,.1f,.1f),new Vector3(-7,.1f,-8),take);pos.y+=Mathf.Sin(Mathf.PI*Mathf.Clamp01((u-.28f)/.38f))*1.4f;s.normal.holder.localPosition=pos;s.normal.holder.localRotation=Quaternion.LookRotation(u<.45f?new Vector3(4,0,5):new Vector3(-7,0,-8));s.normal.Animate(u>.36f&&u<.62f?"Attack":"Swim",time);s.shoe.position=u<.48f?s.W(new Vector3(0,1.34f,2)):s.normal.holder.position+s.normal.holder.forward*1.7f+Vector3.up*.05f;s.shoe.rotation=Quaternion.Euler(0,u<.48f?90:s.normal.holder.eulerAngles.y,0);foreach(var f in s.sparkles)f.gameObject.SetActive(false);s.better.gameObject.SetActive(false);s.Frame(new Vector3(-6,4,-8),Vector3.Lerp(new Vector3(0,1.1f,1),new Vector3(-3,1,-3),take));}
  else if(s.shot==1){bool changed=u>.43f;s.normal.holder.gameObject.SetActive(!changed);s.hero.holder.gameObject.SetActive(changed);s.normal.holder.localPosition=new Vector3(0,.5f,4);s.normal.Animate("Swim",time);s.hero.holder.localPosition=new Vector3(0,0,4);s.hero.holder.localRotation=Quaternion.Euler(0,180+Mathf.Sin(time*1.6f)*12,0);s.hero.Animate("Idle",time);s.shoe.localPosition=new Vector3(0,2.3f+Mathf.Sin(time)*.2f,2);s.shoe.localRotation=Quaternion.Euler(0,time*45,0);s.better.gameObject.SetActive(false);for(int i=0;i<s.sparkles.Count;i++){float a=time*3+i*Mathf.PI*2/s.sparkles.Count;s.sparkles[i].localPosition=new Vector3(Mathf.Cos(a)*2,1.1f+Mathf.Sin(a*1.3f)*.8f,4+Mathf.Sin(a)*2);s.sparkles[i].localScale=Vector3.one*(.09f+.12f*Mathf.Sin(Mathf.PI*u));}s.Frame(new Vector3(6,4.6f,10),new Vector3(0,1.5f,3.5f));}
  else if(s.shot==2){s.normal.holder.gameObject.SetActive(false);s.hero.holder.gameObject.SetActive(true);s.hero.holder.localPosition=new Vector3(-1,0,4);s.hero.holder.localRotation=Quaternion.Euler(0,25,0);s.hero.Animate("Idle",time);s.shoe.localPosition=new Vector3(0,4.2f+Mathf.Sin(time*1.1f)*.15f,6);s.shoe.localScale=Vector3.one*1.6f;s.shoe.localRotation=Quaternion.Euler(0,80+time*8,0);s.better.localPosition=new Vector3(2,1.25f,10);for(int i=0;i<s.sparkles.Count;i++){float a=time+i*Mathf.PI*2/s.sparkles.Count;s.sparkles[i].localPosition=Vector3.Lerp(new Vector3(0,4.2f,6),new Vector3(2,1.4f,10),i/(float)s.sparkles.Count)+new Vector3(Mathf.Sin(a)*.16f,Mathf.Cos(a)*.16f,0);}s.Frame(new Vector3(7-u*2,4.6f,1),new Vector3(.3f,2.8f,6));}
  else if(s.shot==3){s.hero.holder.localPosition=new Vector3(0,0,time*1.25f);s.hero.holder.localRotation=Quaternion.identity;s.hero.Animate("walk",time*1.35f);s.Frame(new Vector3(6,4.2f,time*1.25f+7),new Vector3(0,1.2f,time*1.25f+1));}
  else if(s.shot==4){s.hero.holder.localPosition=new Vector3(-5.4f,0,Mathf.Max(0,time-2)*.9f);s.hero.holder.localRotation=Quaternion.Euler(0,time<2?65:0,0);s.hero.Animate(time<2?"Idle":"walk",time*1.2f);for(int i=0;i<s.cars.Count;i++)s.cars[i].localPosition=new Vector3((i%3-1)*3.6f,0,28+i*6-time*(i%3==0?11:14));s.Frame(new Vector3(-10,4.2f,6+time*.3f),new Vector3(-4,1.3f,2+time*.4f));}
  else{s.hero.holder.localPosition=new Vector3(0,0,-1+time*.65f);s.hero.holder.localRotation=Quaternion.identity;s.hero.Animate("walk",time);for(int i=0;i<s.people.Count;i++){float side=i%2==0?-1:1;var p=s.people[i];p.holder.localPosition=new Vector3((i-2)*1.25f+side*Mathf.Max(0,time-1.2f)*1.6f,0,5.5f+(i%2)*1.4f);p.holder.localRotation=Quaternion.Euler(0,time<1.2f?180:side*75,0);p.Animate(time<1.2f?"call":"run",time*1.05f);}s.Frame(new Vector3(8,5.3f,10),new Vector3(0,1.8f,4));}
 }
 static void Ground(Actor a){if(a==null||!a.holder.gameObject.activeInHierarchy)return;var b=Bounds(a.model.gameObject);a.model.position+=Vector3.up*(a.holder.position.y+.03f-b.min.y);}
 static void Compose(Stage s){Ground(s.hero);Ground(s.normal);foreach(var p in s.people)Ground(p);if(s.shot==0)s.SubjectFrame(s.normal,new Vector3(-5,3,-7),12);else if(s.shot==1)s.SubjectFrame(s.hero,new Vector3(6,3,8),13);else if(s.shot==2){var center=Vector3.Lerp(Bounds(s.hero.model.gameObject).center,s.shoe.position,.45f);var delta=new Vector3(8,4,-10).normalized*16;s.camera.transform.SetPositionAndRotation(center+delta,Quaternion.LookRotation(-delta));}else if(s.shot==3)s.SubjectFrame(s.hero,new Vector3(3,3,8),12);else if(s.shot==4)s.SubjectFrame(s.hero,new Vector3(-6,3,6),12);else s.SubjectFrame(s.hero,new Vector3(2,5,-11),18);}
 public static object Preview()=>Begin(true);
 public static object PreviewEntries()=>Begin(true,3);
 public static object RecordEntries()=>Begin(false,3);
 public static object Record()=>Begin(false);
 static object Begin(bool preview,int firstShot=0){if(!EditorApplication.isPlaying||TimeManager.isGameRunning)throw new Exception("Fresh Play lobby required");foreach(var o in Object.FindObjectsByType<Transform>(FindObjectsSortMode.None).Where(t=>t.name=="Temporary native cinematic"))Object.Destroy(o.gameObject);Directory.CreateDirectory(Out);if(File.Exists(Out+"/error.txt"))File.Delete(Out+"/error.txt");Object.FindFirstObjectByType<OpeningStoryUI>(FindObjectsInactive.Include)?.Skip();Object.FindFirstObjectByType<CanvasScript>().StartCoroutine(Guard(Run(preview,firstShot)));return new{preview,folder=Out};}
 static IEnumerator Guard(IEnumerator work){while(true){bool next;object current;try{next=work.MoveNext();current=next?work.Current:null;}catch(Exception ex){File.WriteAllText(Out+"/error.txt",ex.ToString());yield break;}if(!next)yield break;yield return current;}}
 static IEnumerator Run(bool preview,int firstShot){var world=Camera.main;int worldMask=world.cullingMask;world.cullingMask=0;float[] durations={8,12,10,9,121f/24,121f/24};int oldCapture=Time.captureFramerate;Time.captureFramerate=24;
  try{for(int shot=firstShot;shot<6;shot++){Stage s=null;try{s=Build(shot);yield return null;yield return null;Fit(s.hero,shot==5?3.8f:2.75f);if(s.normal!=null)Fit(s.normal,3.8f,true);foreach(var person in s.people)Fit(person,1.85f);yield return null;
    int frames=preview?1:Mathf.RoundToInt(durations[shot]*24);string folder=Out+"/shot-"+shot;Directory.CreateDirectory(folder);
    for(int frame=0;frame<frames;frame++){float time=preview?durations[shot]*.7f:frame/24f;Pose(s,time,durations[shot]);yield return null;Compose(s);yield return new WaitForEndOfFrame();var old=RenderTexture.active;RenderTexture.active=s.rt;s.pixels.ReadPixels(new Rect(0,0,576,1024),0,0);s.pixels.Apply();RenderTexture.active=old;string file=preview?Out+"/preview-"+shot+".png":folder+"/frame-"+frame.ToString("D4")+".jpg";File.WriteAllBytes(file,preview?s.pixels.EncodeToPNG():s.pixels.EncodeToJPG(94));if(!preview&&frame%24==0)File.WriteAllText(Out+"/progress.txt",$"shot={shot} frame={frame}/{frames}");}
   }finally{s?.Dispose();}yield return null;}
   File.WriteAllText(Out+(preview?"/preview-complete.txt":"/record-complete.txt"),"Native animated selection completed;24fps;shot3=9s;entries121frames. Check selected directories.");
  }finally{world.cullingMask=worldMask;Time.captureFramerate=oldCapture;}
 }
}
