using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Reflection;using UnityEngine;using UnityEditor;using IndianOceanAssets.ShooterSurvival;
public static class TelegraphWindow11 {
 const BindingFlags F=BindingFlags.Instance|BindingFlags.NonPublic;
 static Chapter45Director d;static PlayerScript p;static Chapter45RoleAction role;static Chapter45Hazard hazard;static string folder;static bool active;static int frame,index;static float begin,next,end,warningAt,delay,dodge;static bool move;static readonly List<object> samples=new(),frames=new();static readonly List<string> errors=new();
 static readonly MethodInfo Move=typeof(PlayerScript).GetMethod("PlayerMove",F);
 static string Json(object x)=>(string)AppDomain.CurrentDomain.GetAssemblies().First(a=>a.GetName().Name=="Newtonsoft.Json").GetType("Newtonsoft.Json.JsonConvert").GetMethod("SerializeObject",new[]{typeof(object)}).Invoke(null,new[]{x});
 static void Set(object o,string key,object value)=>o.GetType().GetField("<"+key+">k__BackingField",F).SetValue(o,value);
 static float[] V(Vector3 v)=>new[]{v.x,v.y,v.z};
 static object B(Bounds b)=>new{center=V(b.center),size=V(b.size)};
 static object Shape(Transform t){if(t==null)return null;var f=t.GetComponent<MeshFilter>();return new{position=V(t.position),scale=V(t.lossyScale),active=t.gameObject.activeInHierarchy,bounds=t.GetComponent<Renderer>()==null?null:B(t.GetComponent<Renderer>().bounds),vertices=f?.sharedMesh==null?null:f.sharedMesh.vertices.Where((v,i)=>f.sharedMesh.vertexCount<=8||i%4==0).Select(v=>V(t.TransformPoint(v))).ToArray(),mesh=f?.sharedMesh?.name};}
 static object Col(Collider c)=>new{c.name,type=c.GetType().Name,c.isTrigger,c.enabled,active=c.gameObject.activeInHierarchy,bounds=B(c.bounds),serialized=EditorJsonUtility.ToJson(c)};
 public static object Begin(string target,float distance,float lane,float dodgeLane,float responseDelay,float duration,int branch,string output){
  if(!EditorApplication.isPlaying||active||Directory.Exists(output))throw new Exception("Fresh play and unused output required");Directory.CreateDirectory(output);folder=output;end=duration;delay=responseDelay;move=responseDelay>=0;dodge=dodgeLane;
  d=UnityEngine.Object.FindFirstObjectByType<Chapter45Director>();p=d.Player;UnityEngine.Object.FindFirstObjectByType<CanvasScript>().PlayerPressedStartButton();
  var h=UnityEngine.Object.FindFirstObjectByType<CombatHarness>();if(h!=null)typeof(CombatHarness).GetField("overlayVisible",F).SetValue(h,false);
  foreach(var e in d.encounters)if(e.stopDistance<distance){e.Retire();Set(e,"Complete",true);}foreach(var z in d.hazards)if(z.distance<distance){Set(z,"Triggered",true);z.Cancel();}
  foreach(var c in d.choices)if(c.distance<distance){int cs=Array.FindIndex(d.route.segments,s=>s.floor==c.floor);if(cs>=0)Set(d,"CurrentSegment",cs);c.Commit(branch==0?-3:3);}
  Set(d,"Distance",distance);Set(d,"CurrentSegment",d.route.SegmentAt(distance));d.SampleOnCurrentDeck(distance,out var center,out var forward);p.ApplyContinuousRoutePose(center+Vector3.up*d.footOffset,forward,lane);Physics.SyncTransforms();typeof(Chapter45Director).GetMethod("RefreshVisibility",F).Invoke(d,null);
  role=d.encounters.Where(e=>e.floor==d.CurrentFloor&&e.stopDistance>=distance).SelectMany(e=>e.actors).Select(a=>a.GetComponent<Chapter45RoleAction>()).FirstOrDefault(r=>r!=null&&(r.role.ToString()==target||r.name==target));hazard=role==null?d.hazards.FirstOrDefault(z=>z.name==target):null;if(role==null&&hazard==null)throw new Exception("Target missing "+target);
  if(p.MaxHealth!=60||p.ResolvedAttackDamage!=8||TimeManager.timeFactor!=1)throw new Exception("Ordinary 60HP/8ATK/1x required");
  var inventory=new{roles=d.encounters.SelectMany(e=>e.actors).Where(a=>a!=null).Select(a=>a.GetComponent<Chapter45RoleAction>()).Where(r=>r!=null).Select(r=>new{r.name,role=r.role.ToString(),r.encounter.floor,r.warningSeconds,r.actionDamage,marker=Shape(r.warningMarker),colliders=r.GetComponentsInChildren<Collider>(true).Select(Col).ToArray()}).ToArray(),hazards=d.hazards.Select(z=>new{z.name,z.distance,z.warningDistance,z.warningSeconds,z.operationSeconds,z.lingerSeconds,z.floor,z.fatalContact,z.fallIntoHole,position=V(z.transform.position),rotation=V(z.transform.eulerAngles),body=V(z.body.position),from=V(z.sweepFrom),to=V(z.sweepTo),marker=Shape(z.footprint?.transform),colliders=z.body.GetComponentsInChildren<Collider>(true).Select(Col).ToArray()}).ToArray(),playerColliders=p.GetComponentsInChildren<Collider>(true).Select(Col).ToArray()};
  File.WriteAllText(Path.Combine(folder,"inventory.json"),Json(inventory));File.WriteAllText(Path.Combine(folder,"conditions.json"),Json(new{target,distance,lane,dodgeLane,responseDelay,duration,branch,ordinaryPlaythrough=false,initialPoseDirected=true,earlierEncountersRetired=true,upcomingActorsUnmodified=true,nativeUpdate=true,manualDamage=false,manualRoleOrHazardTick=false,statsOverridden=false}));
  begin=d.Elapsed;next=0;warningAt=-1;frame=-1;index=0;samples.Clear();frames.Clear();errors.Clear();active=true;Application.logMessageReceived+=Log;EditorApplication.update+=Tick;return new{started=true,folder,target=role!=null?role.name:hazard.name};
 }
 static void Log(string msg,string trace,LogType type){if(type==LogType.Error||type==LogType.Exception||type==LogType.Assert)errors.Add(msg);}
 static object Role(Chapter45RoleAction r){float reach=r.role==Chapter45RoleAction.Role.Golfer||r.role==Chapter45RoleAction.Role.Cleaner?2.6f:1.55f;var strike=r.transform.position+r.transform.forward*reach*.55f;var marker=r.warningMarker;return new{r.name,role=r.role.ToString(),phase=r.Phase.ToString(),r.Contacts,r.Actions,r.CanAct,position=V(r.transform.position),forward=V(r.transform.forward),strike=V(strike),strikeRadius=reach*.55f+.45f,marker=Shape(marker),markerDistance=marker==null?0:Vector3.ProjectOnPlane(p.transform.position-marker.position,Vector3.up).magnitude,strikeDistance=Vector3.ProjectOnPlane(p.transform.position-strike,Vector3.up).magnitude,colliders=r.GetComponents<Collider>().Select(Col).ToArray()};}
 static void Tick(){
  if(!active||!EditorApplication.isPlaying)return;EditorApplication.QueuePlayerLoopUpdate();if(frame==Time.frameCount)return;frame=Time.frameCount;float t=d.Elapsed-begin;
  if(warningAt<0&&(role!=null?role.Phase==Chapter45RoleAction.ActionPhase.Warning:hazard.Triggered))warningAt=t;
  if(move&&warningAt>=0&&t-warningAt>=delay&&Mathf.Abs(dodge-d.Lane)>.04f)Move.Invoke(p,new object[]{Mathf.Clamp((dodge-d.Lane)*6,-15,15)});
  var projectiles=UnityEngine.Object.FindObjectsByType<SimpleProjectile>(FindObjectsSortMode.None).Where(q=>q.name.Contains("active projectile")).Select(q=>new{q.name,position=V(q.transform.position),colliders=q.GetComponents<Collider>().Select(Col).ToArray(),renderers=q.GetComponentsInChildren<Renderer>().Select(r=>new{r.name,bounds=B(r.bounds),r.enabled}).ToArray()}).ToArray();
  var actors=d.encounters.Where(e=>e.Activated&&!e.Complete&&e.floor==d.CurrentFloor).SelectMany(e=>e.actors).Where(a=>a!=null&&a.gameObject.activeInHierarchy&&!a.IsDead).Select(a=>a.GetComponent<Chapter45RoleAction>()).Where(r=>r!=null).Select(Role).ToArray();
  samples.Add(new{t,frame,d.Distance,d.CurrentFloor,lane=d.Lane,hp=p.currentHealth,player=V(p.transform.position),targetRole=role==null?null:Role(role),actors,projectiles,hazard=hazard==null?null:new{hazard.Triggered,hazard.Active,hazard.Finished,hazard.Contacts,bodyActive=hazard.body.gameObject.activeInHierarchy,body=V(hazard.body.position),marker=Shape(hazard.footprint?.transform),colliders=hazard.body.GetComponentsInChildren<Collider>(true).Select(Col).ToArray()}});
  if(t>=next){next=t+.18f;string file=(index++).ToString("D3")+".png";ScreenCapture.CaptureScreenshot(Path.Combine(folder,file));frames.Add(new{file,t,hp=p.currentHealth,phase=role?.Phase.ToString(),hazardActive=hazard?.Active});}
  if(t<end&&p.currentHealth>0)return;active=false;EditorApplication.update-=Tick;Application.logMessageReceived-=Log;File.WriteAllText(Path.Combine(folder,"result.json"),Json(new{complete=true,t,health=p.currentHealth,warningAt,roleContacts=role?.Contacts,roleActions=role?.Actions,hazardContacts=hazard?.Contacts,frames,samples,errors,timeline=d.Timeline.ToArray(),manualDamage=false,manualRoleOrHazardTick=false}));
 }
 public static object Stop(){active=false;EditorApplication.update-=Tick;Application.logMessageReceived-=Log;return new{stopped=true};}
}
