using System;using System.IO;using System.Linq;using System.Collections.Generic;using Microsoft.Win32;using UnityEngine;
public static class UiNativeRegistryCycle07 {
 public sealed class Snapshot{public string path;public bool exists;public Row[] rows;}
 public sealed class Row{public string name,kind;public object value;}
 static Snapshot[] Original(){var j=AppDomain.CurrentDomain.GetAssemblies().First(a=>a.GetName().Name=="Newtonsoft.Json").GetType("Newtonsoft.Json.JsonConvert");return (Snapshot[])j.GetMethod("DeserializeObject",new[]{typeof(string),typeof(Type)}).Invoke(null,new object[]{File.ReadAllText("outputs/chapter45-detailed-design-2026-10-03/ui-cycle07/original-native-registry.json"),typeof(Snapshot[])});}
 public static object VerifyGamePreferences(string receipt){
  if(UnityEditor.EditorApplication.isPlayingOrWillChangePlaymode)throw new Exception("Stop owned Play before restoring session metadata");
  if(Path.GetFileName(receipt)!=receipt)throw new Exception("Evidence basename required");string output="outputs/chapter45-detailed-design-2026-10-03/ui-cycle07/"+receipt;if(File.Exists(output))throw new Exception("Preserve prior restoration receipt");
  var original=Original()[0];using var key=Registry.CurrentUser.OpenSubKey(original.path,false);var names=key.GetValueNames().OrderBy(x=>x).ToArray();if(!names.SequenceEqual(original.rows.Select(r=>r.name)))throw new Exception("Native registry key set changed unexpectedly");
  var allowed=new[]{"unity.player_session_count","unity.player_sessionid","unity_connect.mega_session_id","unity_connect.session_id"};var changed=new List<string>();
  foreach(var r in original.rows){object value=key.GetValue(r.name);string encoded=value is byte[] bytes?Convert.ToBase64String(bytes):value.ToString();if(key.GetValueKind(r.name).ToString()==r.kind&&encoded==r.value.ToString())continue;string plain=r.name.Substring(0,r.name.LastIndexOf("_h",StringComparison.Ordinal));if(!allowed.Contains(plain)||r.kind!="Binary"||!(value is byte[] current))throw new Exception("Unexpected game preference change: "+r.name);string currentText=System.Text.Encoding.UTF8.GetString(current).TrimEnd('\0');if(!PlayerPrefs.HasKey(plain)||PlayerPrefs.GetString(plain,"missing")!=currentText)throw new Exception("Session key does not match native PlayerPrefs API");changed.Add(plain);}
  // Engine session identities belong to the live engine. The project recovery
  // guidance explicitly says not to rewind them merely to manufacture equality.
  var result=new{gamePreferencesPreserved=true,nativeValueCount=original.rows.Length,unchangedNonSessionValues=original.rows.Length-allowed.Length,retainedLiveEngineSessionKeys=changed.ToArray(),gamePreferenceKeysChanged=0,mismatchesOutsideEngineSessionKeys=0,noPreferenceWrites=true};File.WriteAllText(output,Json(result));return result;
 }
 static string Json(object o)=>(string)AppDomain.CurrentDomain.GetAssemblies().First(a=>a.GetName().Name=="Newtonsoft.Json").GetType("Newtonsoft.Json.JsonConvert").GetMethod("SerializeObject",new[]{typeof(object)}).Invoke(null,new[]{o});
 public static object Main()=>Capture("original-native-registry.json");
 public static object Capture(string filename){if(Path.GetFileName(filename)!=filename)throw new Exception("Evidence basename required");string file="outputs/chapter45-detailed-design-2026-10-03/ui-cycle07/"+filename;if(File.Exists(file))throw new Exception("Preserve registry evidence");var results=new List<object>();foreach(string path in new[]{@"Software\Unity\UnityEditor\DefaultCompany\tralalero Shooter",@"Software\DefaultCompany\tralalero Shooter"}){using var key=Registry.CurrentUser.OpenSubKey(path,false);if(key==null){results.Add(new{path,exists=false});continue;}var rows=key.GetValueNames().OrderBy(x=>x).Select(name=>new{name,kind=key.GetValueKind(name).ToString(),value=key.GetValue(name) is byte[] bytes?Convert.ToBase64String(bytes):key.GetValue(name)}).ToArray();results.Add(new{path,exists=true,rows});}File.WriteAllText(file,Json(results));return new{file,coin=PlayerPrefs.GetInt("coin"),jewel=PlayerPrefs.GetInt("jewel"),pid=System.Diagnostics.Process.GetCurrentProcess().Id};}
}
