using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Reflection;using UnityEngine;using UnityEditor;using UnityEngine.Localization.Settings;using TMPro;using IndianOceanAssets.ShooterSurvival;using Object=UnityEngine.Object;
// Presentation-only fixtures: no choice commit/reward, goal contact or chapter completion.
public static class UiProbeCycle07 {
 const BindingFlags Private=BindingFlags.Instance|BindingFlags.NonPublic;
 static string Json(object o)=>(string)AppDomain.CurrentDomain.GetAssemblies().First(a=>a.GetName().Name=="Newtonsoft.Json").GetType("Newtonsoft.Json.JsonConvert").GetMethod("SerializeObject",new[]{typeof(object)}).Invoke(null,new[]{o});
 static void Set(object o,string property,object value)=>o.GetType().GetField("<"+property+">k__BackingField",Private).SetValue(o,value);
 static string PathOf(Transform t)=>t.parent==null?t.name:PathOf(t.parent)+"/"+t.name;
 static Chapter45Director Director()=>Object.FindFirstObjectByType<Chapter45Director>();
 public static object Begin(){if(!EditorApplication.isPlaying)throw new Exception("Play required");var d=Director();OpeningStoryUI.Instance?.Skip();Object.FindFirstObjectByType<CanvasScript>().PlayerPressedStartButton();Time.timeScale=0;Set(d,"Running",false);var overlay=Object.FindFirstObjectByType<CombatHarness>();if(overlay)typeof(CombatHarness).GetField("overlayVisible",Private).SetValue(overlay,false);return new{running=d.Running,presentationOnly=true,coin=MoneyScript.S.Coin,jewel=MoneyScript.S.Jewel};}
 public static object SelectLocale(string code){var locale=LocalizationSettings.AvailableLocales.Locales.Single(l=>l.Identifier.Code==code);LocalizationSettings.SelectedLocale=locale;return new{locale=code,persistentLocaleSelectorConfigured=false};}
 static void Place(Chapter45Director d,int segment,float distance){Set(d,"CurrentSegment",segment);Set(d,"Distance",distance);d.Sample(distance,out var center,out var forward);d.Player.ApplyContinuousRoutePose(center+Vector3.up*d.footOffset,forward,0);typeof(Chapter45Director).GetMethod("RefreshVisibility",Private).Invoke(d,null);Physics.SyncTransforms();}
 public static object Show(string sample){var d=Director();((Chapter45NoticeQueue)typeof(Chapter45Director).GetField("notices",Private).GetValue(d)).Clear();var completion=Object.FindObjectsByType<Chapter45CompletionPresentation>(FindObjectsInactive.Include,FindObjectsSortMode.None).FirstOrDefault(c=>c.gameObject.scene==d.gameObject.scene);if(completion)completion.gameObject.SetActive(false);Set(d,"GoalClaimed",false);foreach(var g in d.goals)Set(g,"Claimed",false);
  if(sample=="choice"){var c=d.choices.First();Place(d,d.route.SegmentAt(c.distance-1),c.distance-1);d.Announce("길을 선택하세요",c.Description,999);}
  else if(sample=="student"){var a=Object.FindObjectsByType<Chapter45RoleAction>(FindObjectsInactive.Include,FindObjectsSortMode.None).First(x=>x.gameObject.scene==d.gameObject.scene&&x.role.ToString()=="StudentGrab");d.AnnounceWarning("행동 예고",a.warningText,999);}
  else if(sample=="reward"){var c=d.choices.First();d.AnnounceReward("보상 획득","코인 +"+c.ResolvedCoins+(c.riskAttackPercent>0?" · 공격 +"+c.riskAttackPercent.ToString("0")+"%":""),999);}
  else if(sample=="heal-reward"){var c=d.choices.First();d.AnnounceReward("보상 획득","체력 "+(c.healFraction*100).ToString("0")+"% 회복",999);}
  else if(sample=="danger"){foreach(var h in d.hazards.Where(h=>!string.IsNullOrEmpty(h.warning)).Take(3))d.AnnounceWarning("위험 예고",h.warning,999);}
  else if(sample.StartsWith("floor-")){int floor=int.Parse(sample.Substring(6));int segment=Array.FindIndex(d.route.segments,s=>s.floor==floor);Place(d,segment,d.route.SegmentStart(segment)+2);d.Announce(d.route.segments[segment].label,"문이 열렸습니다 · 앞으로 이동하세요",999);}
  else if(sample=="shoe"){Set(d,"GoalClaimed",true);Set(d.goals.First(),"Claimed",true);completion.gameObject.SetActive(true);d.hud.Clear(d);}
  else if(sample=="queue"){var plate=Object.FindObjectsByType<Chapter45RoleAction>(FindObjectsInactive.Include,FindObjectsSortMode.None).First(x=>x.gameObject.scene==d.gameObject.scene&&x.role==Chapter45RoleAction.Role.PlateThrower);d.AnnounceWarning("행동 예고",plate.warningText,999);d.AnnounceWarning("주문 2번","호출된 대기줄이 이동합니다",999);}
  else if(sample=="cinema"){var h=Object.FindObjectsByType<RestStopHoldout>(FindObjectsInactive.Include,FindObjectsSortMode.None).Single(x=>x.chapter45Owner==d);int segment=Array.FindIndex(d.route.segments,s=>s.floor==6);Set(d,"CurrentSegment",Array.FindIndex(d.route.segments,s=>s.floor==4));d.choices.First(c=>c.kind==Chapter45Choice.ChoiceKind.FloorRoute).Commit(3);Place(d,segment,d.route.SegmentStart(segment));d.Player.ApplyContinuousRoutePose(h.center.position+Vector3.up*d.footOffset,h.center.forward,0);Set(d,"Running",true);Physics.SyncTransforms();}
  else throw new Exception("Unknown sample "+sample);
  Canvas.ForceUpdateCanvases();EditorApplication.QueuePlayerLoopUpdate();return new{sample,locale=LocalizationSettings.SelectedLocale.Identifier.Code,scene=d.gameObject.scene.name,coin=MoneyScript.S.Coin,jewel=MoneyScript.S.Jewel,title=d.hud.title.text,detail=d.hud.description.text};
 }
 static object Measure(TMP_Text t){t.ForceMeshUpdate();var chars=t.textInfo.characterInfo.Take(t.textInfo.characterCount).Where(c=>c.isVisible).ToArray();var rect=t.rectTransform.rect;float minX=chars.Length==0?0:chars.Min(c=>c.bottomLeft.x),maxX=chars.Length==0?0:chars.Max(c=>c.topRight.x),minY=chars.Length==0?0:chars.Min(c=>c.bottomLeft.y),maxY=chars.Length==0?0:chars.Max(c=>c.topRight.y);return new{path=PathOf(t.transform),t.text,t.fontSize,t.enableAutoSizing,t.isTextOverflowing,lines=t.textInfo.lineCount,characters=t.textInfo.characterCount,rect=new{rect.xMin,rect.xMax,rect.yMin,rect.yMax},glyphBounds=new{minX,maxX,minY,maxY},outsideRect=chars.Length>0&&(minX<rect.xMin-1||maxX>rect.xMax+1||minY<rect.yMin-1||maxY>rect.yMax+1),missing=t.text.Where(c=>!char.IsWhiteSpace(c)&&!t.font.HasCharacter(c,true,false)).Distinct().Select(c=>c.ToString()).ToArray()};}
 public static object Capture(string folder,string sample){Directory.CreateDirectory(folder);string file=Path.Combine(folder,sample+".json");if(File.Exists(file))throw new Exception("Preserve evidence");var d=Director();var targets=new List<TMP_Text>{d.hud.title,d.hud.description};var completion=Object.FindObjectsByType<Chapter45CompletionPresentation>(FindObjectsInactive.Include,FindObjectsSortMode.None).FirstOrDefault(c=>c.gameObject.scene==d.gameObject.scene);if(completion&&completion.gameObject.activeInHierarchy){targets.Add(completion.title);targets.Add(completion.message);}var result=new{sample,scene=d.gameObject.scene.name,locale=LocalizationSettings.SelectedLocale.Identifier.Code,screen=new{Screen.width,Screen.height},coin=MoneyScript.S.Coin,jewel=MoneyScript.S.Jewel,measurements=targets.Where(t=>t!=null&&t.gameObject.activeInHierarchy).Select(Measure).ToArray(),activeOldFloorLabels=Object.FindObjectsByType<TMP_Text>(FindObjectsSortMode.None).Where(t=>t.gameObject.scene==d.gameObject.scene&&((t.text??"").Contains("58F")||(t.text??"").Contains("118F"))).Select(t=>new{path=PathOf(t.transform),t.text}).ToArray(),presentationOnly=true};File.WriteAllText(file,Json(result));ScreenCapture.CaptureScreenshot(Path.Combine(folder,sample+".png"));return new{file,scene=d.gameObject.scene.name,locale=LocalizationSettings.SelectedLocale.Identifier.Code};}
 public static object SettleCinema(){var d=Director();var h=Object.FindObjectsByType<RestStopHoldout>(FindObjectsInactive.Include,FindObjectsSortMode.None).Single(x=>x.chapter45Owner==d);if(!h.Active||h.Spawned!=0||Time.timeScale!=0)throw new Exception("Expected frozen pre-spawn cinema");Set(h,"Elapsed",.8f);return new{active=h.Active,elapsed=h.Elapsed,spawned=h.Spawned,presentationFixture=true};}
 public sealed class LocaleState{public string selected;}
 public static object AuthoredCoverage(string filename){var d=Director();if(!Chapter45PresentationText.English)throw new Exception("English locale required");var sources=d.hazards.Select(h=>h.warning).Concat(Object.FindObjectsByType<Chapter45RoleAction>(FindObjectsInactive.Include,FindObjectsSortMode.None).Where(a=>a.gameObject.scene==d.gameObject.scene).Select(a=>a.warningText)).Concat(d.lifts.Select(l=>l.destinationLabel)).Concat(d.chapter==5?d.route.segments.Select(s=>s.label):Enumerable.Empty<string>()).Where(s=>!string.IsNullOrEmpty(s)).Distinct().ToArray();var translated=sources.Select(s=>new{original=s,translated=Chapter45PresentationText.Localize(s)}).ToArray();var missing=translated.Where(r=>r.translated.Any(c=>c>='가'&&c<='힣')).ToArray();var result=new{scene=d.gameObject.scene.name,stringsChecked=translated.Length,missingCount=missing.Length,translated,missing};File.WriteAllText("outputs/chapter45-detailed-design-2026-10-03/ui-cycle07/"+filename,Json(result));return new{stringsChecked=translated.Length,missingCount=missing.Length};}
 public static object RestoreLocale(){const string file="outputs/chapter45-detailed-design-2026-10-03/ui-cycle07/original-locale.json";var json=AppDomain.CurrentDomain.GetAssemblies().First(a=>a.GetName().Name=="Newtonsoft.Json").GetType("Newtonsoft.Json.JsonConvert");var saved=(LocaleState)json.GetMethod("DeserializeObject",new[]{typeof(string),typeof(Type)}).Invoke(null,new object[]{File.ReadAllText(file),typeof(LocaleState)});string code=saved.selected;LocalizationSettings.SelectedLocale=LocalizationSettings.AvailableLocales.Locales.Single(l=>l.Identifier.Code==code);return new{restoredLocale=code};}
}
