using System;using System.Threading;using System.Collections.Concurrent;using System.IO;using System.Linq;using System.Collections.Generic;using System.Reflection;using System.Runtime.InteropServices;using UnityEngine;using UnityEngine.UI;using UnityEngine.EventSystems;using UnityEditor;using UnityEngine.SceneManagement;using IndianOceanAssets.ShooterSurvival;using Object=UnityEngine.Object;
public static class ValidationInput14 {
 const BindingFlags F=BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic|BindingFlags.Static|BindingFlags.FlattenHierarchy;
 [StructLayout(LayoutKind.Sequential)]struct Pt{public int x,y;}
 [StructLayout(LayoutKind.Sequential)]struct Mouse{public int dx,dy;public uint data,flags,time;public UIntPtr extra;}
 [StructLayout(LayoutKind.Sequential)]struct NativeInput{public uint type;public Mouse mouse;}
 [DllImport("user32.dll",SetLastError=true)]static extern uint SendInput(uint n,NativeInput[] events,int size);
 [DllImport("user32.dll")]static extern IntPtr GetForegroundWindow();
 [DllImport("user32.dll")]static extern uint GetWindowThreadProcessId(IntPtr h,out uint pid);
 [DllImport("user32.dll")]static extern bool GetCursorPos(out Pt p);
 [DllImport("user32.dll")]static extern IntPtr WindowFromPoint(Pt p);
 [DllImport("user32.dll")]static extern bool ClientToScreen(IntPtr h,ref Pt p);
 [DllImport("user32.dll")]static extern int GetSystemMetrics(int n);
 [DllImport("user32.dll")]static extern short GetAsyncKeyState(int n);
 static CanvasScript c;static PlayerScript p;static Chapter45Director d;static ChapterProgression cp;
 static EditorWindow view;static object zoom;static string folder,label;static bool active,held,slowOnly,burstOnly,burstStarted;static volatile bool burstActive,burstHeld;static readonly ConcurrentQueue<object> burstEvents=new();static readonly ConcurrentQueue<string> burstErrors=new();static AsyncOperation pendingScene;static int frame=-1,failed,step;static double began,at;static Pt expectedCursor;static Vector2 expectedGame,lastObserved;static Vector2 calibration;static int expectedHeight=2340;static string prefix="";static int handleBefore,loadsBefore,savedCoin,savedJewel;static float pausedElapsed,pausedDistance,pauseLane;static Chapter45Choice testedChoice;static readonly List<object> sceneLoads=new();static bool mousePrimed;
 static readonly List<object> checks=new(),observations=new(),sent=new(),inputDeferrals=new();static readonly List<string> errors=new();
 sealed class Step{public string name;public double delay;public Action action;}
 static readonly List<Step> steps=new();
 static Type J=>AppDomain.CurrentDomain.GetAssemblies().First(a=>a.GetName().Name=="Newtonsoft.Json").GetType("Newtonsoft.Json.JsonConvert");
 static string Json(object x)=>(string)J.GetMethod("SerializeObject",new[]{typeof(object)}).Invoke(null,new[]{x});
 static void Write(string n,object x)=>File.WriteAllText(Path.Combine(folder,n),Json(x));
 static object Get(object o,string n)=>o.GetType().GetProperty(n,F)?.GetValue(o)??o.GetType().GetField(n,F)?.GetValue(o);
 static void Bind(){c=Object.FindFirstObjectByType<CanvasScript>();p=Object.FindFirstObjectByType<PlayerScript>();d=Object.FindFirstObjectByType<Chapter45Director>();cp=Object.FindFirstObjectByType<ChapterProgression>();}
 static float[] V(Vector2 a)=>new[]{a.x,a.y};
 static object State()=>new{scene=SceneManager.GetActiveScene().name,handle=SceneManager.GetActiveScene().handle,screen=new[]{Screen.width,Screen.height},running=TimeManager.isGameRunning,factor=TimeManager.timeFactor,gameover=CanvasScript.isGameOver,elapsed=cp!=null?cp.Elapsed:-1,distance=d!=null?d.Distance:-1,transferring=d!=null&&d.IsTransferring,lane=d!=null?d.Lane:0,hp=p!=null?p.currentHealth:0,armed=p!=null?Get(p,"startGestureArmed"):null,triggered=p!=null?Get(p,"startGestureTriggered"):null,settings=c!=null&&c.settingsMenuUI.activeInHierarchy,coin=MoneyScript.S!=null?MoneyScript.S.Coin:0,jewel=MoneyScript.S!=null?MoneyScript.S.Jewel:0};
 static void Check(bool ok,string name,object evidence=null){checks.Add(new{pass=ok,name,evidence});Write("checks.json",checks);if(!ok){failed++;throw new Exception(name);}}
 static void Add(string n,double delay,Action a)=>steps.Add(new Step{name=n,delay=delay,action=a});
 static Rect RenderRect(){var target=(Vector2)Get(view,"targetSize");var v=(Rect)Get(view,"viewInWindow");var scale=(Vector2)Get(zoom,"scale");var shift=(Vector2)Get(zoom,"translation");return new Rect(view.position.x+v.x+shift.x-target.x*scale.x/2,view.position.y+v.y+shift.y-target.y*scale.y/2,target.x*scale.x,target.y*scale.y);}
 static void Guard(){GetWindowThreadProcessId(GetForegroundWindow(),out var pid);if(pid!=System.Diagnostics.Process.GetCurrentProcess().Id||EditorWindow.focusedWindow!=view)throw new Exception("Stop: Unity Game View lost foreground/focus");GetCursorPos(out var pos);if(Math.Abs(pos.x-expectedCursor.x)>1||Math.Abs(pos.y-expectedCursor.y)>1)throw new Exception("Stop: cursor changed outside owned input; expected "+expectedCursor.x+","+expectedCursor.y+" observed "+pos.x+","+pos.y+" lock="+Cursor.lockState);if((GetAsyncKeyState(2)&0x8000)!=0||(GetAsyncKeyState(4)&0x8000)!=0)throw new Exception("Stop: other mouse button held");}
 static void Send(uint flags,Vector2? game=null){Guard();if(Screen.width!=1080||Screen.height!=expectedHeight)throw new Exception("Unexpected Game View resolution during input");var pos=expectedCursor;var rect=RenderRect();rect.position+=calibration;if(game.HasValue){var s=game.Value;if(s.x<2||s.y<2||s.x>Screen.width-2||s.y>Screen.height-2)throw new Exception("Input outside rendered game");pos=new Pt{x=Mathf.RoundToInt(rect.x+s.x/Screen.width*rect.width),y=Mathf.RoundToInt(rect.y+(1-s.y/Screen.height)*rect.height)};if(!view.position.Contains(new Vector2(pos.x,pos.y)))throw new Exception("Input outside Game View");GetWindowThreadProcessId(WindowFromPoint(pos),out var pointPid);if(pointPid!=System.Diagnostics.Process.GetCurrentProcess().Id)throw new Exception("Input target occluded by another application");flags|=0xC001;expectedGame=s;mousePrimed=true;}
  int vx=GetSystemMetrics(76),vy=GetSystemMetrics(77),vw=GetSystemMetrics(78),vh=GetSystemMetrics(79);var e=new NativeInput{type=0,mouse=new Mouse{dx=Mathf.RoundToInt((pos.x-vx)*65535f/(vw-1)),dy=Mathf.RoundToInt((pos.y-vy)*65535f/(vh-1)),flags=flags,extra=new UIntPtr(0xC014)}};uint count=SendInput(1,new[]{e},Marshal.SizeOf<NativeInput>());if(count!=1)throw new Exception("SendInput failed: "+Marshal.GetLastWin32Error());expectedCursor=pos;SessionState.SetString("Chapter45.Validation14.Cursor",pos.x+","+pos.y);if((flags&2)!=0)held=true;if((flags&4)!=0)held=false;sent.Add(new{step=label,frame=Time.frameCount,flags,desktop=new[]{pos.x,pos.y},game=game.HasValue?V(game.Value):null,inserted=count,utc=DateTime.UtcNow.ToString("O")});Write("sent-input.json",sent);
 }
 static Vector2 Center(RectTransform rt){var canvas=rt.GetComponentInParent<Canvas>().rootCanvas;return RectTransformUtility.WorldToScreenPoint(canvas.renderMode==RenderMode.ScreenSpaceOverlay?null:canvas.worldCamera,rt.TransformPoint(rt.rect.center));}
 static Rect ScreenRect(RectTransform rt){var corners=new Vector3[4];rt.GetWorldCorners(corners);var canvas=rt.GetComponentInParent<Canvas>().rootCanvas;var cam=canvas.renderMode==RenderMode.ScreenSpaceOverlay?null:canvas.worldCamera;var a=RectTransformUtility.WorldToScreenPoint(cam,corners[0]);var b=RectTransformUtility.WorldToScreenPoint(cam,corners[2]);return Rect.MinMaxRect(a.x,a.y,b.x,b.y);}
 static Button ButtonAt(string path)=>c.transform.Find(path).GetComponent<Button>();
 static void InspectButton(Button b,string name){var r=ScreenRect((RectTransform)b.transform);var center=Center((RectTransform)b.transform);var ev=new PointerEventData(EventSystem.current){position=center};var hits=new List<RaycastResult>();EventSystem.current.RaycastAll(ev,hits);Check(b.isActiveAndEnabled&&b.interactable&&r.xMin>=0&&r.yMin>=0&&r.xMax<=Screen.width&&r.yMax<=Screen.height&&hits.Count>0&&hits[0].gameObject.GetComponentInParent<Button>()==b,"Visible button geometry: "+name,new{rect=new[]{r.x,r.y,r.width,r.height},center=V(center),top=hits.Count>0?hits[0].gameObject.name:null});}
 static void Click(string name,Func<Button> resolve,bool twice=false,bool cancel=false){Add(name+" position",.15,()=>{var b=resolve();InspectButton(b,name);Send(0,Center((RectTransform)b.transform));});Add(name+" down",.12,()=>Send(2));if(cancel)Add(name+" cancel drag outside",.12,()=>Send(0,new Vector2(35,Screen.height*.55f)));if(twice&&burstOnly){Add(name+" native background double click",.12,()=>BurstReleaseAndRepeat());return;}Add(name+" up",.12,()=>Send(4));if(twice){Add(name+" repeated down",.06,()=>Send(2));Add(name+" repeated up",.06,()=>Send(4));}}
 static Vector2 start;
 static void Gesture(string name,Vector2 delta,bool startInside=true){Add(name+" position",.15,()=>{start=startInside?Center(c.startAreaImg):new Vector2(40,Screen.height*.9f);Send(0,start);});Add(name+" down",.15,()=>Send(2));Add(name+" move",.18,()=>Send(0,start+delta));Add(name+" up",.18,()=>Send(4));}
 static void Shot(string n)=>ScreenCapture.CaptureScreenshot(Path.Combine(folder,prefix+n+".png"));
 static void Probe(){
  Add("calibration move",.5,()=>Send(0,new Vector2(Screen.width*.5f,Screen.height*.5f)));
  Add("calibration measure",.25,()=>{var observed=(Vector2)Input.mousePosition;var r=RenderRect();var diff=expectedGame-observed;calibration=new Vector2(diff.x/Screen.width*r.width,-diff.y/Screen.height*r.height);Write(prefix+"calibration.json",new{desired=V(expectedGame),observed=V(observed),offset=V(calibration),cursorLock=Cursor.lockState.ToString()});Send(0,new Vector2(Screen.width*.6f,Screen.height*.6f));});
  Add("calibration verify",.25,()=>Check(Vector2.Distance((Vector2)Input.mousePosition,expectedGame)<6,"Game/desktop coordinates independently verified",new{expected=V(expectedGame),actual=V(Input.mousePosition),offset=V(calibration)}));

  Add("fresh lobby",.6,()=>{Check(!TimeManager.isGameRunning&&c.IsStartAreaActive(),"Fresh lobby before OS input",State());Write(prefix+"geometry.json",new{render=RenderRect().ToString(),view=view.position.ToString(),screen=new[]{Screen.width,Screen.height},module=EventSystem.current.currentInputModule.GetType().FullName});Shot("01-lobby");});
  Gesture("tap",Vector2.zero);Add("tap rejected",.3,()=>Check(!TimeManager.isGameRunning,"Tap does not start",State()));
  Gesture("vertical cancelled gesture",new Vector2(0,70));Add("vertical rejected",.3,()=>Check(!TimeManager.isGameRunning,"Vertical-only drag does not start",State()));
  Gesture("outside start area",new Vector2(70,0),false);Add("outside rejected",.3,()=>Check(!TimeManager.isGameRunning,"Horizontal drag starting outside area does not start",State()));
  if(slowOnly){Add("slow gesture position",.2,()=>{start=Center(c.startAreaImg);Send(0,start);});Add("slow gesture down",.15,()=>Send(2));for(int i=1;i<=12;i++){int n=i;Add("slow gesture move "+n,.08,()=>Send(0,start+new Vector2(n*4,0)));}Add("slow gesture up",.15,()=>Send(4));}else Gesture("valid horizontal start",new Vector2(70,0));Add("horizontal accepted",.5,()=>{Check(TimeManager.isGameRunning&&cp.Elapsed>0,"Actual OS horizontal gesture starts game",State());Check(observations.Count>4,"Unity Input observations captured",observations.Count);Shot("02-real-gesture-start");});
 }

 static void SceneLoaded(Scene scene,LoadSceneMode mode)=>sceneLoads.Add(new{name=scene.name,scene.handle,frame=Time.frameCount,label});
 static void Prop(object o,string n,object value)=>o.GetType().GetProperty(n).GetSetMethod(true).Invoke(o,new[]{value});
 static void Fresh(){Bind();Check(!OpeningStoryUI.IsBlockingGameplay&&!TimeManager.isGameRunning&&!CanvasScript.isGameOver&&cp.Elapsed<.01f&&d.Distance==0&&c.IsStartAreaActive(),"Actual retry/return reaches fresh lobby",State());}
 static void ClearPrerequisites(){foreach(var e in d.encounters)Prop(e,"Complete",true);foreach(var x in d.targets){Prop(x,"Health",0f);typeof(Chapter45Target).GetField("opening",F).SetValue(x,1f);if(x.hitCollider!=null)x.hitCollider.enabled=false;if(x.panelCollider!=null)x.panelCollider.enabled=false;}}
 static void SeedBranch(){testedChoice=d.choices.Where(x=>!x.Selected).OrderBy(x=>x.distance).First();ClearPrerequisites();float distance=Mathf.Max(0,testedChoice.distance-16);int segment=0;while(segment<d.route.segments.Length-1&&d.route.SegmentEnd(segment)<distance)segment++;Prop(d,"CurrentSegment",segment);Prop(d,"Distance",distance);d.route.SampleSegment(segment,distance,out var center,out var forward);p.ApplyContinuousRoutePose(center+Vector3.up*d.footOffset,forward,0);Physics.SyncTransforms();Check(!testedChoice.Selected&&testedChoice.OnCurrentFloor&&Mathf.Abs(d.Lane)<.01f,"Directed branch fixture begins unselected with neutral lane",new{testedChoice.name,kind=testedChoice.kind.ToString(),testedChoice.distance,fixtureDistance=distance,realInputRequired=true});}
 static void SeedGoal(){Check(!d.IsTransferring,"Goal fixture begins outside any lift transfer",State());ClearPrerequisites();foreach(var choice in d.choices)if(!choice.Selected)choice.Commit(-1);var goal=d.goals.Single(g=>g.offering);var pc=p.GetComponent<Collider>();var gc=goal.GetComponent<Collider>();int seg=-1;float distance=0,best=float.PositiveInfinity,startAt=0;
  for(int i=0;i<d.route.segments.Length;i++){var r=d.route.segments[i];if(r.floor==goal.floor&&startAt+r.Length>=d.route.Length-40){var span=r.end-r.start;float f=Mathf.Clamp01(Vector3.Dot(gc.bounds.center-r.start,span)/Mathf.Max(.0001f,span.sqrMagnitude));float sq=Vector3.ProjectOnPlane(gc.bounds.center-Vector3.Lerp(r.start,r.end,f),Vector3.up).sqrMagnitude;float progress=startAt+r.Length*f;if(sq<best-.0001f||Mathf.Abs(sq-best)<=.0001f&&progress>distance){best=sq;distance=progress;seg=i;}}startAt+=r.Length;}
  Check(seg>=0&&best<25,"Directed goal projects to final authored route");Prop(d,"CurrentSegment",seg);Prop(d,"Distance",distance);d.route.SampleSegment(seg,distance,out var center,out var forward);p.ApplyContinuousRoutePose(center+Vector3.up*d.footOffset,forward,0);Physics.SyncTransforms();p.transform.position+=gc.bounds.center-pc.bounds.center;p.GetComponent<Rigidbody>().position=p.transform.position;Physics.SyncTransforms();Check(!TimeManager.isGameRunning&&!goal.Claimed&&gc.bounds.Intersects(pc.bounds),"Paused physical goal fixture awaits actual resume input");
 }
 static void Branch(string name,bool right){Add(name+" seed",.1,()=>SeedBranch());Gesture(name+" actual direction",new Vector2(right?240:-240,0));Add(name+" selected",3.2,()=>{Check(testedChoice.Selected&&testedChoice.Selection==(right?1:0),name+" actual drag determines branch",new{testedChoice.name,testedChoice.Selection,lane=d.Lane,timeline=d.Timeline.Where(x=>x.Contains("choice committed "+testedChoice.name+"=")).ToArray()});Shot(name+"-selected");});Gesture(name+" reverse after commitment",new Vector2(right?-240:240,0));Add(name+" stable",.3,()=>Check(testedChoice.Selected&&testedChoice.Selection==(right?1:0)&&d.Timeline.Count(x=>x.Contains("choice committed "+testedChoice.name+"="))==1,name+" opposite repeated gesture cannot recommit",new{testedChoice.Selection,entries=d.Timeline.Where(x=>x.Contains("choice committed "+testedChoice.name+"=")).ToArray()}));}
 static void FullFlow(bool right){
  Add("pause lane baseline",.1,()=>pauseLane=d.Lane);Click("pause",()=>c.pauseButton.GetComponent<Button>(),true);Add("pause frozen snapshot",.3,()=>{Check(!TimeManager.isGameRunning&&c.settingsMenuUI.activeInHierarchy,"Actual pause opens menu",State());Check(Mathf.Abs(d.Lane-pauseLane)<.01f,"Pause click does not move player lane",new{before=pauseLane,after=d.Lane});pausedElapsed=cp.Elapsed;pausedDistance=d.Distance;handleBefore=SceneManager.GetActiveScene().handle;Shot("03-pause");});
  Click("cancel continue",()=>ButtonAt("SettingsMenu/Panel/RunActions/Resume"),false,true);Add("continue cancellation",.3,()=>Check(!TimeManager.isGameRunning&&cp.Elapsed==pausedElapsed&&d.Distance==pausedDistance,"Drag outside continue cancels without advancing",State()));
  Click("continue twice",()=>ButtonAt("SettingsMenu/Panel/RunActions/Resume"),true);Add("continued",.5,()=>Check(TimeManager.isGameRunning&&cp.Elapsed>pausedElapsed&&d.Distance>pausedDistance&&SceneManager.GetActiveScene().handle==handleBefore,"Rapid continue resumes same run exactly once",State()));
  Add("retry pause lane baseline",.1,()=>pauseLane=d.Lane);Click("pause for retry",()=>c.pauseButton.GetComponent<Button>());Add("retry pause lane stable",.2,()=>Check(Mathf.Abs(d.Lane-pauseLane)<.01f,"Second pause click preserves lane",new{before=pauseLane,after=d.Lane}));Click("cancel retry",()=>ButtonAt("SettingsMenu/Panel/RunActions/Retry"),false,true);Add("retry cancelled",.3,()=>Check(SceneManager.GetActiveScene().handle==handleBefore&&!TimeManager.isGameRunning,"Retry drag cancellation retains scene",State()));
  Add("retry load baseline",.1,()=>{loadsBefore=sceneLoads.Count;savedCoin=MoneyScript.S.Coin;savedJewel=MoneyScript.S.Jewel;});Click("retry twice",()=>ButtonAt("SettingsMenu/Panel/RunActions/Retry"),true);Add("retry arrives",1.1,()=>{Fresh();Check(sceneLoads.Count==loadsBefore+1&&SceneManager.GetActiveScene().handle!=handleBefore&&MoneyScript.S.Coin==savedCoin&&MoneyScript.S.Jewel==savedJewel,"Rapid retry causes one scene load and preserves wallet",sceneLoads.Skip(loadsBefore).ToArray());Shot("04-retry-lobby");});
  Click("lobby settings",()=>ButtonAt("UI/Top/Setting/Image"));Add("settings lobby",.3,()=>{Check(c.settingsMenuUI.activeInHierarchy&&!c.settingsMenuUI.GetComponent<HarborSettingsPanel>().runActions.activeInHierarchy,"Lobby settings hide run-only controls");Shot("05-lobby-settings");});Gesture("start beneath settings",new Vector2(70,0));Add("settings blocks start",.3,()=>Check(!TimeManager.isGameRunning&&cp.Elapsed==0,"Actual drag under settings cannot start"));Click("cancel settings close",()=>ButtonAt("SettingsMenu/Panel/Close"),false,true);Add("settings close cancelled",.2,()=>Check(c.settingsMenuUI.activeInHierarchy,"Close drag cancellation keeps menu"));Click("settings close twice",()=>ButtonAt("SettingsMenu/Panel/Close"),true);Add("closed lobby",.3,()=>Check(!c.settingsMenuUI.activeInHierarchy&&!TimeManager.isGameRunning,"Rapid close returns to lobby without autostart"));Gesture("start after close",new Vector2(70,0));Add("start accepted",.4,()=>Check(TimeManager.isGameRunning&&cp.Elapsed>0,"Real start works after cancelled menu gestures",State()));
  Branch("ch4-route",right);
  Add("directed load chapter5",.2,()=>pendingScene=SceneManager.LoadSceneAsync("ShoeTower"));Add("chapter5 lobby",1.2,()=>Fresh());Gesture("chapter5 actual start",new Vector2(70,0));Add("chapter5 started",.4,()=>Check(TimeManager.isGameRunning,"Chapter5 actual start accepted",State()));Branch("ch5-floor",!right);Add("separate fresh Ch5 goal fixture",.2,()=>pendingScene=SceneManager.LoadSceneAsync("ShoeTower"));Add("fresh goal lobby",1.2,()=>Fresh());Gesture("goal fixture actual start",new Vector2(70,0));Add("goal fixture started",.3,()=>Check(TimeManager.isGameRunning&&!d.IsTransferring,"Goal scenario starts from real lobby input",State()));
  Click("pause for physical goal fixture",()=>c.pauseButton.GetComponent<Button>());Add("stage physical goal",.3,()=>SeedGoal());Click("resume into physical offering",()=>ButtonAt("SettingsMenu/Panel/RunActions/Resume"));Add("offering result",3.0,()=>{Check(d.GoalClaimed&&cp.Completed&&CanvasScript.isGameOver&&c.youWinUI.activeInHierarchy,"Real resume reaches physical goal and visible result",State());savedCoin=MoneyScript.S.Coin;savedJewel=MoneyScript.S.Jewel;handleBefore=SceneManager.GetActiveScene().handle;InspectButton(ButtonAt("GameOverScreen/VictoryCard/Close"),"result close");Shot("06-physical-offering-result");});Click("cancel result return",()=>ButtonAt("GameOverScreen/VictoryCard/Continue"),false,true);Add("result remains",.3,()=>Check(CanvasScript.isGameOver&&c.youWinUI.activeInHierarchy&&SceneManager.GetActiveScene().handle==handleBefore,"Cancelled result return preserves result"));Add("return load baseline",.1,()=>loadsBefore=sceneLoads.Count);Click("result return twice",()=>ButtonAt("GameOverScreen/VictoryCard/Continue"),true);Add("result lobby",1.2,()=>{Fresh();Check(sceneLoads.Count==loadsBefore+1&&SceneManager.GetActiveScene().handle!=handleBefore&&MoneyScript.S.Coin==savedCoin&&MoneyScript.S.Jewel==savedJewel,"Rapid result return causes one scene load without repeat reward",sceneLoads.Skip(loadsBefore).ToArray());Shot("07-result-return-lobby");});
 }

 static void BurstReleaseAndRepeat(){Guard();var cursor=expectedCursor;var foreground=GetForegroundWindow();var target=WindowFromPoint(cursor);string action=label;burstStarted=burstActive=true;burstHeld=held;new Thread(()=>{try{foreach(uint flags in new uint[]{4,2,4}){if(flags==2||burstHeld)Thread.Sleep(60);GetCursorPos(out var observed);if(GetForegroundWindow()!=foreground||WindowFromPoint(cursor)!=target||Math.Abs(observed.x-cursor.x)>1||Math.Abs(observed.y-cursor.y)>1)throw new Exception("Background burst target ownership changed");uint count=SendInput(1,new[]{new NativeInput{type=0,mouse=new Mouse{flags=flags,extra=new UIntPtr(0xC014)}}},Marshal.SizeOf<NativeInput>());if(count!=1)throw new Exception("Background SendInput failed");burstHeld=flags==2;burstEvents.Enqueue(new{action,flags,inserted=count,utc=DateTime.UtcNow.ToString("O"),desktop=new[]{cursor.x,cursor.y},nativeBackgroundThread=true});}}catch(Exception e){burstErrors.Enqueue(e.ToString());if(burstHeld){try{ReleaseOwnedProbeButton();burstHeld=false;}catch(Exception release){burstErrors.Enqueue(release.Message);}}}finally{burstActive=false;}}){IsBackground=true,Name="Cycle14 owned Unity input burst"}.Start();}
 static void BurstSuite(){Probe();Click("burst pause",()=>c.pauseButton.GetComponent<Button>());Add("burst retry baseline",.3,()=>{Check(c.settingsMenuUI.activeInHierarchy&&!TimeManager.isGameRunning,"Pause before true OS double click");loadsBefore=sceneLoads.Count;handleBefore=SceneManager.GetActiveScene().handle;savedCoin=MoneyScript.S.Coin;savedJewel=MoneyScript.S.Jewel;});Click("burst retry",()=>ButtonAt("SettingsMenu/Panel/RunActions/Retry"),true);Add("retry arrives",1.2,()=>{Fresh();Check(sceneLoads.Count==loadsBefore+1&&MoneyScript.S.Coin==savedCoin&&MoneyScript.S.Jewel==savedJewel,"60ms OS retry double click causes one fresh lobby without Story",sceneLoads.Skip(loadsBefore).ToArray());Shot("08-native-burst-retry");});Add("burst goal fresh scene",.2,()=>pendingScene=SceneManager.LoadSceneAsync("ShoeTower"));Add("burst goal fresh lobby",1.2,()=>Fresh());Gesture("burst goal start",new Vector2(70,0));Click("burst goal pause",()=>c.pauseButton.GetComponent<Button>());Add("burst physical goal",.3,()=>SeedGoal());Click("burst goal resume",()=>ButtonAt("SettingsMenu/Panel/RunActions/Resume"));Add("burst result",3.0,()=>{Check(d.GoalClaimed&&CanvasScript.isGameOver&&c.youWinUI.activeInHierarchy,"Burst scenario reaches physical result");loadsBefore=sceneLoads.Count;handleBefore=SceneManager.GetActiveScene().handle;savedCoin=MoneyScript.S.Coin;savedJewel=MoneyScript.S.Jewel;});Click("burst result return",()=>ButtonAt("GameOverScreen/VictoryCard/Continue"),true);Add("result lobby",1.2,()=>{Fresh();Check(sceneLoads.Count==loadsBefore+1&&MoneyScript.S.Coin==savedCoin&&MoneyScript.S.Jewel==savedJewel,"60ms OS result double click causes one fresh lobby and stable reward",sceneLoads.Skip(loadsBefore).ToArray());Shot("09-native-burst-result-return");});}
 public static object BeginBurst(string output){burstOnly=true;return Begin(output);}
 public static object BeginSlow(string output){slowOnly=true;return Begin(output);}
 public static object Begin(string output){if(!EditorApplication.isPlaying||Directory.Exists(output))throw new Exception("Fresh output and Play required");folder=output;Directory.CreateDirectory(folder);view=Resources.FindObjectsOfTypeAll(typeof(EditorWindow).Assembly.GetType("UnityEditor.GameView")).Cast<EditorWindow>().Single();zoom=Get(view,"m_ZoomArea");view.Focus();GetCursorPos(out expectedCursor);SessionState.SetString("Chapter45.Validation14.Cursor",expectedCursor.x+","+expectedCursor.y);if((GetAsyncKeyState(1)&0x8000)!=0)throw new Exception("Initial mouse button held");Bind();steps.Clear();checks.Clear();inputDeferrals.Clear();observations.Clear();sent.Clear();errors.Clear();step=failed=0;frame=-1;held=mousePrimed=false;calibration=Vector2.zero;began=at=EditorApplication.timeSinceStartup;sceneLoads.Clear();expectedHeight=2340;prefix="tall-";if(burstOnly)BurstSuite();else Probe();if(!slowOnly){if(!burstOnly)FullFlow(true);Add("switch to existing short portrait",.3,()=>{view.GetType().GetProperty("selectedSizeIndex",F).SetValue(view,22);view.Repaint();expectedHeight=1920;calibration=Vector2.zero;prefix="short-";pendingScene=SceneManager.LoadSceneAsync("Jamsil");});Add("short lobby settle",1.2,()=>{Bind();Check(Screen.width==1080&&Screen.height==1920,"Existing short portrait selected",State());});if(burstOnly)BurstSuite();else{Probe();FullFlow(false);}}active=true;SceneManager.sceneLoaded+=SceneLoaded;Application.logMessageReceived+=Log;EditorApplication.update+=Tick;Write("conditions.json",new{directedFixtures="Scene load, branch/goal prerequisite and position seed only; no tested start/menu/branch callbacks invoked; other goal prerequisite choices explicitly committed as fixture",input="Windows SendInput; actual UnityEngine.Input and native EventSystem",testedControlCallbacksInvoked=false,otherGoalPrerequisiteChoiceCallbacks=true,engineKeyWrites=false,desktopScope="Foreground Unity GameView only; abort on cursor/focus interference"});return new{started=true,folder,steps=steps.Count};}
 public static object ReleaseOwnedProbeButton(){GetWindowThreadProcessId(GetForegroundWindow(),out var pid);if(pid!=System.Diagnostics.Process.GetCurrentProcess().Id)throw new Exception("Unity foreground required for owned release");uint n=SendInput(1,new[]{new NativeInput{type=0,mouse=new Mouse{flags=4,extra=new UIntPtr(0xC014)}}},Marshal.SizeOf<NativeInput>());return new{released=n==1};}
 static void Log(string m,string s,LogType t){if(t==LogType.Error||t==LogType.Exception||t==LogType.Assert)errors.Add(m+"\n"+s);}
 static void Tick(){if(!active||!EditorApplication.isPlaying)return;if(burstActive)return;if(burstStarted){held=burstHeld;burstStarted=false;while(burstErrors.TryDequeue(out var error))errors.Add(error);if(errors.Count>0){Finish();return;}}EditorApplication.QueuePlayerLoopUpdate();if(frame==Time.frameCount)return;frame=Time.frameCount;try{var mouse=(Vector2)Input.mousePosition;if(Input.GetMouseButtonDown(0)||Input.GetMouseButtonUp(0)||Vector2.Distance(mouse,lastObserved)>1||Input.GetMouseButton(0)){observations.Add(new{frame,label,mouse=V(mouse),expected=mousePrimed?V(expectedGame):null,down=Input.GetMouseButtonDown(0),held=Input.GetMouseButton(0),up=Input.GetMouseButtonUp(0),state=State()});lastObserved=mouse;}if(EditorApplication.timeSinceStartup-began>170)throw new TimeoutException("OS input probe timed out");if(step>=steps.Count){Finish();return;}var s=steps[step];if(EditorApplication.timeSinceStartup-at<s.delay)return;if(pendingScene!=null&&!pendingScene.isDone)return;if((s.name=="retry arrives"||s.name=="result lobby")&&SceneManager.GetActiveScene().handle==handleBefore)return;if(Screen.width!=1080||Screen.height!=expectedHeight){inputDeferrals.Add(new{step=s.name,frame=Time.frameCount,screen=new[]{Screen.width,Screen.height},age=EditorApplication.timeSinceStartup-at});return;}label=s.name;s.action();step++;at=EditorApplication.timeSinceStartup;Write("status.json",new{step,label,total=steps.Count,state=State()});}catch(Exception e){errors.Add(e.ToString());Finish();}}
 static void Finish(){if(held){try{ReleaseOwnedProbeButton();held=false;}catch(Exception e){errors.Add("Owned button release: "+e.Message);}}active=false;EditorApplication.update-=Tick;Application.logMessageReceived-=Log;SceneManager.sceneLoaded-=SceneLoaded;Write("scene-loads.json",sceneLoads);Write("background-os-bursts.json",burstEvents.ToArray());Write("input-deferrals.json",inputDeferrals);Write("observed-input.json",observations);Write("summary.json",new{complete=true,passed=checks.Count-failed,failed,errors,checks,stepsCompleted=step,stepsTotal=steps.Count,seconds=EditorApplication.timeSinceStartup-began,actualOsInput=true,testedControlCallbackInvocation=false,otherGoalPrerequisiteChoiceCallbacks=true,restorationRequired=true});}
}
