using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Reflection;using UnityEngine;using UnityEditor;using UnityEngine.SceneManagement;using IndianOceanAssets.ShooterSurvival;
public static class ValidationDeath12 {
 const BindingFlags F=BindingFlags.Instance|BindingFlags.NonPublic;
 static Chapter45Director d;static Chapter45Hazard h;static PlayerScript p;static CanvasScript canvas;static ChapterProgression cp;static string folder;static int phase,frame,handle,coin,jewel,rewarded,unlocked;static double began,at;static bool active;static readonly List<object> checks=new();static readonly List<string> errors=new();
 static string Json(object x)=>(string)AppDomain.CurrentDomain.GetAssemblies().First(a=>a.GetName().Name=="Newtonsoft.Json").GetType("Newtonsoft.Json.JsonConvert").GetMethod("SerializeObject",new[]{typeof(object)}).Invoke(null,new[]{x});
 static void Set(object o,string n,object v)=>o.GetType().GetField("<"+n+">k__BackingField",F).SetValue(o,v);
 static void Check(bool pass,string label,object evidence=null)=>checks.Add(new{pass,label,evidence});
 static void Bind(){d=UnityEngine.Object.FindFirstObjectByType<Chapter45Director>();p=d.Player;canvas=UnityEngine.Object.FindFirstObjectByType<CanvasScript>();cp=UnityEngine.Object.FindFirstObjectByType<ChapterProgression>();h=d.hazards.Single(z=>z.name=="4F falling television");}
 static void Next(int n){phase=n;at=EditorApplication.timeSinceStartup;File.WriteAllText(Path.Combine(folder,"status.json"),Json(new{phase,hp=p.currentHealth,h.Contacts,d.Running,CanvasScript.isGameOver}));}
 static void Shot(string name)=>ScreenCapture.CaptureScreenshot(Path.Combine(folder,name+".png"));
 static void Stage(bool fatal){
  foreach(var e in d.encounters){e.Retire();Set(e,"Complete",true);}foreach(var z in d.hazards)if(z!=h){Set(z,"Triggered",true);z.Cancel();}
  foreach(var c in d.choices)if(c.distance<h.distance){Set(d,"CurrentSegment",Array.FindIndex(d.route.segments,s=>s.floor==c.floor));c.Commit(3);}
  Set(d,"CurrentSegment",d.route.SegmentAt(h.distance));Set(d,"Distance",h.distance);d.SampleOnCurrentDeck(h.distance,out var center,out var forward);float lane=Vector3.Dot(h.body.position-center,Vector3.Cross(Vector3.up,forward));p.ApplyContinuousRoutePose(center+Vector3.up*d.footOffset,forward,lane);
  Set(d,"ShieldReady",false);typeof(PlayerScript).GetField("currentForwardMoveSpeed",F).SetValue(p,0f);p.canShoot=false;foreach(var w in p.GetComponentsInChildren<WeaponScript>(true))w.enabled=false;
  if(fatal){p.currentHealth=4;p.UpdateHealth();}Physics.SyncTransforms();coin=MoneyScript.S.Coin;jewel=MoneyScript.S.Jewel;rewarded=PlayerPrefs.GetInt("chapter_rewarded_5");unlocked=PlayerPrefs.GetInt("chapter_unlocked");
 }
 public static object Begin(string output){if(!EditorApplication.isPlaying||Directory.Exists(output))throw new Exception("Fresh Play/output required");folder=output;Directory.CreateDirectory(folder);Bind();canvas.PlayerPressedStartButton();Stage(true);checks.Clear();errors.Clear();frame=-1;began=EditorApplication.timeSinceStartup;active=true;Next(0);Application.logMessageReceived+=Log;EditorApplication.update+=Tick;return new{started=true,seededInitialHealth=4,heldForward=true,weaponsDisabled=true,manualDamageOrHit=false};}
 static void Log(string m,string trace,LogType t){if(t==LogType.Error||t==LogType.Exception||t==LogType.Assert)errors.Add(m);}
 static void Tick(){if(!active||!EditorApplication.isPlaying)return;EditorApplication.QueuePlayerLoopUpdate();if(frame==Time.frameCount)return;frame=Time.frameCount;double age=EditorApplication.timeSinceStartup-at;
  try{if(EditorApplication.timeSinceStartup-began>60)throw new TimeoutException("TV death phase "+phase);
   switch(phase){
    case 0:if(p.currentHealth>0)return;Check(h.Contacts==1&&p.LastDamageWasFatal&&Mathf.Approximately(p.LastDamageAmount,4f)&&p.LastDamageCause==PlayerDamageCause.FallingObject,"Native TV collision kills seeded 4HP player with falling-object cause; reported loss is clamped to remaining HP",new{h.Contacts,p.LastDamageAmount,cause=p.LastDamageCause.ToString(),label=PlayerDamageCauseText.Label(p.LastDamageCause),advice=PlayerDamageCauseText.Advice(p.LastDamageCause)});Shot("01-tv-death");Next(1);return;
    case 1:if(age<3.5)return;Check(!d.Running&&!h.Active&&!h.body.gameObject.activeInHierarchy&&!h.footprint.activeInHierarchy,"Death stops TV body and warning");Check(CanvasScript.isGameOver&&!TimeManager.isGameRunning&&!cp.Completed&&!d.GoalClaimed,"Defeat owns terminal flow without false chapter clear");Check(MoneyScript.S.Coin==coin&&MoneyScript.S.Jewel==jewel&&PlayerPrefs.GetInt("chapter_rewarded_5")==rewarded&&PlayerPrefs.GetInt("chapter_unlocked")==unlocked,"Short failed run grants no progress/clear reward",new{coin,jewel,afterCoin=MoneyScript.S.Coin,afterJewel=MoneyScript.S.Jewel});canvas.YouWin();canvas.YouWin();Check(MoneyScript.S.Coin==coin&&MoneyScript.S.Jewel==jewel&&!cp.Completed,"Late duplicate win UI calls after death cannot pay");Shot("02-defeat");Next(6);return;
    case 6:if(age<.4)return;var texts=UnityEngine.Object.FindObjectsByType<TMPro.TMP_Text>(FindObjectsSortMode.None).Where(x=>x.isActiveAndEnabled&&x.gameObject.activeInHierarchy).Select(x=>x.text).ToArray();File.WriteAllText(Path.Combine(folder,"defeat-visible-text.json"),Json(texts));Check(texts.Any(x=>x.Contains("낙하물에 맞음")),"Visible defeat UI reports falling-object cause before Replay");handle=SceneManager.GetActiveScene().handle;cp.Replay();Next(2);return;
    case 2:if(age<1||SceneManager.GetActiveScene().handle==handle)return;Bind();Check(p.currentHealth==60&&!TimeManager.isGameRunning&&!CanvasScript.isGameOver&&!d.Running&&d.Elapsed==0&&d.LiftCount==0,"Native Replay returns to fresh alive lobby");Check(!h.Triggered&&!h.Active&&!h.Finished&&h.Contacts==0&&!h.body.gameObject.activeInHierarchy&&!h.footprint.activeInHierarchy,"Replay clears TV hit latch/body/warning");Check(MoneyScript.S.Coin==coin&&MoneyScript.S.Jewel==jewel,"Replay preserves earned wallet without duplicate payment");Shot("03-replay-lobby");canvas.PlayerPressedStartButton();Next(3);return;
    case 3:if(age<.4)return;Check(p.MaxHealth==60&&p.currentHealth==60&&p.ResolvedAttackDamage==8&&d.Running,"Replay Start uses authored stats and active fresh run");Stage(false);Next(4);return;
    case 4:if(!h.Finished)return;Check(h.Contacts==1&&Mathf.Approximately(p.currentHealth,55.2f),"Second TV encounter hits exactly once after Replay",new{h.Contacts,p.currentHealth});Check(!h.Active&&!h.body.gameObject.activeInHierarchy&&!h.footprint.activeInHierarchy,"Replayed TV finishes without stale warning");Shot("04-replayed-tv-finish");Next(5);return;
    case 5:if(age<.4)return;Finish();return;
   }
  }catch(Exception e){errors.Add(e.ToString());Finish();}
 }
 static void Finish(){active=false;EditorApplication.update-=Tick;Application.logMessageReceived-=Log;File.WriteAllText(Path.Combine(folder,"summary.json"),Json(new{checks,passed=checks.Count(x=>(bool)x.GetType().GetProperty("pass").GetValue(x)),failed=checks.Count(x=>!(bool)x.GetType().GetProperty("pass").GetValue(x)),errors,directedFixture=true,initialHealth=4,heldForwardSpeedZero=true,otherEncountersRetired=true,actualChapterReplayApi=true,manualDamageOrHitOrTick=false}));}
}
