using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Reflection;using UnityEngine;using UnityEditor;using IndianOceanAssets.ShooterSurvival;using Object=UnityEngine.Object;
public static class ValidationActors17 {
 const BindingFlags F=BindingFlags.Instance|BindingFlags.NonPublic;
 static Chapter45Director d;static PlayerScript p;static CanvasScript canvas;static Chapter45RoleAction role;static Chapter45Encounter encounter;static EnemyScript_space actor;static Chapter45RoleAction[] queue;
 static string folder,kind;static bool active;static int frame,stage,shotIndex;static float stageAt,warningAt,firstFireAt,deathAt,initialHealth,maxObservedStep;static double beganWall,pauseWall,settleWall;static int pauseStage;static string pausedState,pauseLabel;static readonly HashSet<string> paused=new(),captures=new();static readonly HashSet<int> knownShots=new();static readonly Dictionary<int,float> births=new();static readonly List<object> checks=new(),events=new();static readonly List<string> errors=new();static int failures;static Vector3[] queueOrigins;static int timelineIndex;static Vector3 savedActorPosition;
 static string Json(object x)=>(string)AppDomain.CurrentDomain.GetAssemblies().First(a=>a.GetName().Name=="Newtonsoft.Json").GetType("Newtonsoft.Json.JsonConvert").GetMethod("SerializeObject",new[]{typeof(object)}).Invoke(null,new[]{x});
 static void Set(object o,string n,object v)=>o.GetType().GetField("<"+n+">k__BackingField",F).SetValue(o,v);
 static T Get<T>(object o,string n)=>(T)o.GetType().GetField(n,F).GetValue(o);
 static object Call(object o,string n,params object[] args)=>o.GetType().GetMethod(n,F).Invoke(o,args);
 static float[] V(Vector3 v)=>new[]{v.x,v.y,v.z};
 static void Check(bool ok,string name,object evidence=null){checks.Add(new{ok,name,evidence,t=d.Elapsed});if(!ok)failures++;}
 static SimpleProjectile[] Shots()=>Object.FindObjectsByType<SimpleProjectile>(FindObjectsSortMode.None).Where(x=>x.name.StartsWith("PopcornThrower active projectile")).OrderBy(x=>x.GetInstanceID()).ToArray();
 static object Projectile(SimpleProjectile x)=>new{id=x.GetInstanceID(),position=V(x.transform.position),velocity=V(Get<Vector3>(x,"launchVelocity")),bodyVelocity=V(x.GetComponent<Rigidbody>().linearVelocity),remaining=Get<float>(x,"remainingLifetime"),x.damage,canDamage=x.CanDamage(p),collider=x.GetComponent<Collider>().enabled,scale=V(x.transform.lossyScale),radius=x.GetComponent<SphereCollider>().radius};
 static object Actor(Chapter45RoleAction r){var a=r.GetComponent<EnemyScript_space>();var animator=r.GetComponentInChildren<Animator>(true);var state=animator.isInitialized?animator.GetCurrentAnimatorStateInfo(0):default;return new{r.name,r.Phase,r.Actions,r.Contacts,r.callNumber,a.IsDead,a.CurrentHealth,active=a.gameObject.activeInHierarchy,position=V(r.transform.position),age=Get<float>(r,"age"),remaining=Get<float>(r,"remaining"),queueStartedAt=Get<float>(r,"queueStartedAt"),origin=V(Get<Vector3>(r,"origin")),right=V(Get<Vector3>(r,"right")),markerActive=r.warningMarker!=null&&r.warningMarker.gameObject.activeInHierarchy,marker=r.warningMarker==null?null:V(r.warningMarker.position),lockedTarget=V(Get<Vector3>(r,"lockedTarget")),hand=r.heldProp==null?null:V(r.heldProp.position),release=r.projectileOrigin==null?null:V(r.projectileOrigin.position),animator.enabled,animator.speed,state.normalizedTime,state.fullPathHash,animatorCount=r.GetComponentsInChildren<Animator>(true).Length};}
 static string PauseState()=>Json(new{d.Elapsed,d.Distance,hp=p.currentHealth,player=V(p.transform.position),actors=(kind=="queue"?queue:new[]{role}).Select(Actor).ToArray(),shots=Shots().Select(Projectile).ToArray()});
 static void Capture(string label){if(!captures.Add(label))return;ScreenCapture.CaptureScreenshot(Path.Combine(folder,(shotIndex++).ToString("D2")+"-"+label+".png"));}
 static void Note(string label,object details=null){events.Add(new{label,t=d.Elapsed,details});Capture(label);}
 static void Pause(string label){paused.Add(label);pauseLabel=label;canvas.PauseGame();pauseStage=1;pauseWall=EditorApplication.timeSinceStartup;}
 static bool EqualPause(string a,string b,out double drift){const string pattern=@"-?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?";var aa=System.Text.RegularExpressions.Regex.Matches(a,pattern);var bb=System.Text.RegularExpressions.Regex.Matches(b,pattern);drift=0;if(aa.Count!=bb.Count||System.Text.RegularExpressions.Regex.Replace(a,pattern,"#")!=System.Text.RegularExpressions.Regex.Replace(b,pattern,"#"))return false;for(int i=0;i<aa.Count;i++){double x=double.Parse(aa[i].Value,System.Globalization.CultureInfo.InvariantCulture),y=double.Parse(bb[i].Value,System.Globalization.CultureInfo.InvariantCulture);drift=Math.Max(drift,Math.Abs(x-y));}return drift<=.00001;}
 static bool ObservePause(){if(pauseStage==0)return false;double now=EditorApplication.timeSinceStartup;if(pauseStage==1){if(now-pauseWall<.2)return true;pausedState=PauseState();settleWall=now;pauseStage=2;Capture("paused-"+pauseLabel);return true;}if(now-settleWall<.6)return true;string after=PauseState();bool same=EqualPause(pausedState,after,out double drift);Check(same,"Settled pause freezes clocks, actors, rig, hand, shots and HP within1e-5 absolute float tolerance: "+pauseLabel,new{before=pausedState,after,maxAbsoluteNumericDrift=drift,tolerance=.00001});canvas.ResumeGame();pauseStage=0;Note("resumed-"+pauseLabel);return true;}
 static void MoveThrower(float distance){d.SampleOnCurrentDeck(d.Distance,out var center,out var forward);actor.transform.position=p.transform.position+Vector3.ProjectOnPlane(forward,Vector3.up).normalized*distance;var position=actor.transform.position;position.y=center.y+.06f;actor.transform.position=position;Physics.SyncTransforms();}
 public static object Begin(string scenario,string output){
  if(!EditorApplication.isPlaying||active||Directory.Exists(output))throw new Exception("Fresh Play/output required");kind=scenario;if(kind!="queue"&&kind!="popcorn-lifecycle"&&kind!="popcorn-transfer")throw new Exception("Unknown scenario");folder=output;Directory.CreateDirectory(folder);d=Object.FindFirstObjectByType<Chapter45Director>();p=d.Player;canvas=Object.FindFirstObjectByType<CanvasScript>();canvas.PlayerPressedStartButton();var overlay=Object.FindFirstObjectByType<CombatHarness>();if(overlay!=null)overlay.GetType().GetField("overlayVisible",F).SetValue(overlay,false);
  role=d.GetComponentsInChildren<Chapter45RoleAction>(true).SingleOrDefault(r=>r.role==(kind=="queue"?Chapter45RoleAction.Role.CalledQueue:Chapter45RoleAction.Role.PopcornThrower)&&(kind!="queue"||r.name.StartsWith("Actor 23 ")));if(role==null)throw new Exception("Missing unique role");actor=role.GetComponent<EnemyScript_space>();encounter=role.encounter;
  foreach(var e in d.encounters)if(e!=encounter){e.Retire();Set(e,"Complete",true);}foreach(var h in d.hazards){Set(h,"Triggered",true);h.Cancel();}
  foreach(var choice in d.choices){int index=Array.FindIndex(d.route.segments,s=>s.floor==choice.floor);if(index>=0)Set(d,"CurrentSegment",index);choice.Commit(kind=="queue"?-3:3);}
  float distance=encounter.stopDistance;Set(d,"Distance",distance);Set(d,"CurrentSegment",d.route.SegmentAt(distance));d.SampleOnCurrentDeck(distance,out var center,out var forward);p.ApplyContinuousRoutePose(center+Vector3.up*d.footOffset,forward,0);p.canShoot=false;Physics.SyncTransforms();Call(d,"RefreshVisibility");
  queue=encounter.actors.Select(a=>a.GetComponent<Chapter45RoleAction>()).Where(r=>r!=null&&r.role==Chapter45RoleAction.Role.CalledQueue).ToArray();stage=0;frame=-1;shotIndex=0;maxObservedStep=0;pauseStage=0;warningAt=firstFireAt=-1;knownShots.Clear();births.Clear();checks.Clear();events.Clear();errors.Clear();captures.Clear();paused.Clear();failures=0;timelineIndex=0;stageAt=d.Elapsed;beganWall=EditorApplication.timeSinceStartup;active=true;initialHealth=p.currentHealth;EditorApplication.update+=Tick;Application.logMessageReceived+=Log;
  File.WriteAllText(Path.Combine(folder,"conditions.json"),Json(new{scenario=kind,directedFixture=true,fullPlaythrough=false,startingDistance=distance,health=initialHealth,attack=p.ResolvedAttackDamage,clock="Native Update/FixedUpdate1x",disabledPlayerShooting=true,excludedOtherEncountersAndHazards=true,excludedOtherActorsInTargetForPopcorn=true,repositionedPopcornActor="15m, later25m then22.5m for range boundary",manualFire=false,manualLaunch=false,manualRoleTick=false,manualHit=false,manualDamage=false,directedDeath="EnemyDeath callback after second volley or first queue movement; not a weapon-kill claim",directedReset="Encounter.ResetForRun, then native encounter activation",directedTransfer=kind=="popcorn-transfer"?"Invoke existing BeginLift after native volley; eligibility gate deliberately bypassed, subsequent native transfer/cleanup observed":null}));return new{started=true,scenario=kind,folder};
 }
 static void Log(string m,string s,LogType t){if(t==LogType.Error||t==LogType.Exception||t==LogType.Assert)errors.Add(m);}
 static void Tick(){if(!active||!EditorApplication.isPlaying)return;EditorApplication.QueuePlayerLoopUpdate();if(frame==Time.frameCount)return;frame=Time.frameCount;maxObservedStep=Mathf.Max(maxObservedStep,Time.deltaTime);try{if(EditorApplication.timeSinceStartup-beganWall>90)throw new TimeoutException("Directed fixture wall limit");if(ObservePause())return;
  var shots=Shots();var newly=shots.Where(x=>knownShots.Add(x.GetInstanceID())).ToArray();foreach(var x in newly)births[x.GetInstanceID()]=d.Elapsed;
  File.AppendAllText(Path.Combine(folder,"frames.jsonl"),Json(new{frame,t=d.Elapsed,phase=stage,d.Distance,d.CurrentFloor,d.Running,d.IsTransferring,hp=p.currentHealth,cause=p.LastDamageCause.ToString(),player=V(p.transform.position),actor=Actor(role),queue=kind=="queue"?queue.Select(Actor).ToArray():null,shots=shots.Select(Projectile).ToArray(),newIds=newly.Select(x=>x.GetInstanceID()).ToArray()})+"\n");
  while(timelineIndex<d.Timeline.Count){string line=d.Timeline[timelineIndex++];File.AppendAllText(Path.Combine(folder,"timeline.txt"),line+"\n");}
  if(stage==0){if(!encounter.Activated)return;savedActorPosition=actor.transform.position;stageAt=d.Elapsed;if(kind=="queue"){queueOrigins=queue.Select(r=>r.transform.position).ToArray();Check(queue.Length==3&&queue[0]==role,"CH05 remains first of three registered queue actors");Check(role.GetComponentsInChildren<Animator>(true).Length==1,"CH05 owns exactly one resolved Animator");}else{foreach(var a in encounter.actors)if(a!=actor)a.gameObject.SetActive(false);MoveThrower(15);Check(role.heldProp.GetComponentsInChildren<Collider>(true).Length==0,"New held carton adds no physical collider");Check(!role.heldProp.Find("Popcorn paper cup").gameObject.activeSelf,"Old cylinder remains archived inactive");}stage=1;Note("native-activation");return;}
  if(kind=="queue"){QueueTick();return;}
  if(stage==1){
   if(role.Phase==Chapter45RoleAction.ActionPhase.Warning&&warningAt<0){warningAt=d.Elapsed;Note("first-warning");if(!paused.Contains("warning")){Pause("warning");return;}}
   if(newly.Length>0){Check(newly.Length==3,"Native volley has exactly three new projectile IDs",newly.Select(Projectile).ToArray());Check(newly.All(x=>Mathf.Abs(Get<Vector3>(x,"launchVelocity").magnitude-11)<.002f),"Native speed is11m/s");var yaw=newly.Select(x=>Get<Vector3>(x,"launchVelocity")).Select(v=>Mathf.Atan2(v.x,v.z)*Mathf.Rad2Deg).ToArray();float[] gaps={Mathf.Abs(Mathf.DeltaAngle(yaw[0],yaw[1])),Mathf.Abs(Mathf.DeltaAngle(yaw[1],yaw[2])),Mathf.Abs(Mathf.DeltaAngle(yaw[0],yaw[2]))};Array.Sort(gaps);Check(Mathf.Abs(gaps[0]-12)<.02f&&Mathf.Abs(gaps[1]-12)<.02f&&Mathf.Abs(gaps[2]-24)<.02f,"Horizontal fan angles are12/12/24 degrees",gaps);
    foreach(var x in newly){var mesh=x.GetComponent<MeshFilter>().sharedMesh;float max=mesh.vertices.Max(v=>v.magnitude);Check(max<=x.GetComponent<SphereCollider>().radius+.00001f,"Visible popcorn kernel fits unchanged sphere collider",new{max,radius=x.GetComponent<SphereCollider>().radius,scale=V(x.transform.lossyScale)});}
    if(firstFireAt<0){firstFireAt=d.Elapsed;float tolerance=Mathf.Max(.04f,maxObservedStep*2+.02f);Check(Mathf.Abs(d.Elapsed-warningAt-1.1f)<=tolerance,"First warning precedes native volley by1.1 active seconds within measured update tolerance",new{observed=d.Elapsed-warningAt,maxObservedStep,tolerance});Note("first-volley");if(kind=="popcorn-transfer"){var lift=d.lifts.Where(l=>l.afterSegment>=d.CurrentSegment&&d.route.segments[l.afterSegment].floor==d.CurrentFloor).OrderBy(l=>l.afterSegment).First();Call(d,"BeginLift",lift,lift.Destination(lift.afterSegment));Check(d.IsTransferring&&shots.All(x=>!x.CanDamage(p)),"Native transfer immediately blocks same shots from damage");stage=8;stageAt=d.Elapsed;return;}}
    else if(knownShots.Count>=6){actor.EnemyDeath();deathAt=d.Elapsed;Check(actor.IsDead,"Directed shooter death enters native death lifecycle");Note("shooter-death-after-volley");stage=2;stageAt=d.Elapsed;return;}
   }
   if(firstFireAt>=0&&d.Elapsed-firstFireAt>.15f&&!paused.Contains("flight")){Pause("flight");return;}
  }else if(stage==2){if(d.Elapsed-stageAt>.1f&&!captures.Contains("shots-outlive-shooter")){Check(shots.Length>0,"Already fired shots outlive shooter death");Note("shots-outlive-shooter");}if(d.Elapsed-deathAt>4.3f){Check(shots.Length==0&&knownShots.Count==6,"No remaining shots or third volley after dead-shooter4s lifetime");Check(!actor.gameObject.activeSelf,"Native corpse deactivates");encounter.ResetForRun(d);stage=3;stageAt=d.Elapsed;Note("native-encounter-reset");}}
  else if(stage==3&&encounter.Activated){foreach(var a in encounter.actors)if(a!=actor)a.gameObject.SetActive(false);Check(!actor.IsDead&&role.Actions==0&&Vector3.Distance(actor.transform.position,savedActorPosition)<.01f,"Encounter reactivation restores authored actor placement/life/counters");MoveThrower(25);stage=4;stageAt=d.Elapsed;Note("range-outside25m");}
  else if(stage==4&&d.Elapsed-stageAt>2.1f){Check(role.Phase==Chapter45RoleAction.ActionPhase.Moving&&role.Actions==0&&shots.Length==0,"No warning or shot outside23m after native cooldown expires");MoveThrower(22.5f);stage=5;stageAt=d.Elapsed;Note("range-inside22_5m");}
  else if(stage==5){if(role.Phase==Chapter45RoleAction.ActionPhase.Warning&&!captures.Contains("inside-warning"))Note("inside-warning");if(newly.Length>0){Check(captures.Contains("inside-warning")&&newly.Length==3,"Entering23m admits a warned native three-shot action");Call(d,"StopRun");Check(!d.Running&&shots.All(x=>!x.CanDamage(p)),"Native StopRun blocks current shots from damage");stage=6;pauseWall=EditorApplication.timeSinceStartup;Note("stopped-with-live-shots");}}
  else if(stage==6&&EditorApplication.timeSinceStartup-pauseWall>.2){Check(Shots().Length==0,"Native FixedUpdate cleans all stopped-run shots");Finish();}
  else if(stage==8){if(d.Elapsed-stageAt>.15f&&!captures.Contains("transfer-cleanup")){Check(Shots().Length==0,"Native FixedUpdate cleans transfer shots");Note("transfer-cleanup");}if(!d.IsTransferring&&d.Elapsed-stageAt>1){Check(d.CurrentFloor==6&&Shots().Length==0,"Actual transfer lands on6F without old shots");Finish();}}
 }catch(Exception e){errors.Add(e.ToString());Finish();}}
 static void QueueTick(){float qAge=d.Elapsed-Get<float>(role,"queueStartedAt");if(stage==1){if(qAge>1.8f&&!paused.Contains("queue-call")){Pause("queue-call");return;}if(qAge>3.4f&&!paused.Contains("queue-moving")){Pause("queue-moving");return;}if(qAge>4.5f){var deltas=queue.Select((r,i)=>r.transform.position-queueOrigins[i]).ToArray();Check(deltas.All(v=>Mathf.Abs(v.magnitude-2.2f)<.025f)&&deltas.Skip(1).All(v=>Vector3.Distance(v,deltas[0])<.002f),"Whole called queue moves2.2m with shared displacement",deltas.Select(V).ToArray());actor.EnemyDeath();deathAt=d.Elapsed;stage=2;Note("queue-leader-death");}}
  else if(stage==2&&qAge>11.5f){Check(actor.IsDead&&!actor.gameObject.activeSelf,"CH05 native death completes without duplicate Animator");Check(d.Timeline.Any(t=>t.Contains("queue called "+encounter.name+" number=025")),"Followers keep shared call clock after leader death");encounter.ResetForRun(d);stage=3;Note("queue-native-reset");}
  else if(stage==3&&encounter.Activated){Check(!actor.IsDead&&actor.CurrentHealth>0&&role.Actions==0&&role.GetComponentsInChildren<Animator>(true).Length==1,"Native queue reactivation restores life and one own-rig Animator");Check(queue.Select((r,i)=>Vector3.Distance(r.transform.position,queueOrigins[i])).All(v=>v<.02f),"Native reactivation restores authored queue positions");stage=4;stageAt=d.Elapsed;Note("queue-reactivated");}
  else if(stage==4&&d.Elapsed-stageAt>7.1f){Check(d.Timeline.Count(t=>t.Contains("queue called "+encounter.name+" number=024"))==2,"Fresh activation restarts call024 exactly once");Finish();}}
 static void Finish(){if(!active)return;active=false;if(pauseStage!=0){canvas.ResumeGame();pauseStage=0;}EditorApplication.update-=Tick;Application.logMessageReceived-=Log;Capture("final");File.WriteAllText(Path.Combine(folder,"result.json"),Json(new{complete=true,kind,passed=checks.Count-failures,failed=failures,checks,events,errors,elapsed=d.Elapsed,hp=p.currentHealth,knownProjectileIds=knownShots.ToArray(),births,directedFixture=true,manualFire=false,manualLaunch=false,manualRoleTick=false,manualHit=false,manualDamage=false,nativePhysics=true}));}
 public static object Stop(){if(active)Finish();return new{stopped=true};}
}

