using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Reflection;using System.Runtime.InteropServices;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine.SceneManagement;
public static class ValidationState13 {
 const string Selector="NoryangjinMapTool.TestStartStage",Owner="Chapter45.Validation13.Owner";
 static readonly string Root=Path.GetFullPath("outputs/chapter45-detailed-design-2026-10-03/validation-cycle13");
 [StructLayout(LayoutKind.Sequential)]struct InputInfo{public uint size,tick;}
 [DllImport("user32.dll")]static extern bool GetLastInputInfo(ref InputInfo info);
 public sealed class Row{public string key,kind,value;public bool existed;}
 public sealed class State{public int version=1;public string scene,startScene;public Row[] session;public float timeScale,captureDeltaTime;public bool cleanupExists,cleanup;public uint inputTick;}
 static Type JsonType=>AppDomain.CurrentDomain.GetAssemblies().First(a=>a.GetName().Name=="Newtonsoft.Json").GetType("Newtonsoft.Json.JsonConvert");
 static string Json(object o)=>(string)JsonType.GetMethod("SerializeObject",new[]{typeof(object)}).Invoke(null,new[]{o});
 static T Decode<T>(string s)=>(T)JsonType.GetMethod("DeserializeObject",new[]{typeof(string),typeof(Type)}).Invoke(null,new object[]{s,typeof(T)});
 static uint LastInput(){var x=new InputInfo{size=(uint)Marshal.SizeOf<InputInfo>()};if(!GetLastInputInfo(ref x))throw new Exception("Cannot verify desktop input state");return x.tick;}
 static Row Value(string key,string kind){bool exists;string value;if(kind=="bool"){bool a=SessionState.GetBool(key,false),b=SessionState.GetBool(key,true);exists=a==b;value=a.ToString();}else if(kind=="int"){int a=SessionState.GetInt(key,int.MinValue),b=SessionState.GetInt(key,int.MaxValue);exists=a==b;value=a.ToString();}else if(kind=="float"){float a=SessionState.GetFloat(key,float.MinValue),b=SessionState.GetFloat(key,float.MaxValue);exists=a==b;value=a.ToString("R",System.Globalization.CultureInfo.InvariantCulture);}else{string a=SessionState.GetString(key,"missing:a"),b=SessionState.GetString(key,"missing:b");exists=a==b;value=a;}return new Row{key=key,kind=kind,value=value,existed=exists};}
 static State Current()=>new State{scene=SceneManager.GetActiveScene().path,startScene=AssetDatabase.GetAssetPath(EditorSceneManager.playModeStartScene),timeScale=Time.timeScale,captureDeltaTime=Time.captureDeltaTime,cleanupExists=EditorPrefs.HasKey("PT_ResourcesCleanup"),cleanup=EditorPrefs.GetBool("PT_ResourcesCleanup",false),inputTick=LastInput(),session=new[]{Value(Selector,"int"),Value(Selector+".Active","bool"),Value(Selector+".DefaultPath","string"),Value(Selector+".AppliedPath","string"),Value("NoryangjinMapTool.OpeningVideoEnabled","bool"),Value("NoryangjinMapTool.TestPower9999","bool"),Value("NoryangjinMapTool.TestFastLateral","bool"),Value("NoryangjinMapTool.TestTimeScale","float"),Value("SR18.Progression.Active","bool")}};
 static void CleanEdit(){if(EditorApplication.isPlayingOrWillChangePlaymode||EditorApplication.isCompiling||EditorApplication.isUpdating||EditorGUIUtility.editingTextField||GUIUtility.hotControl!=0||PrefabStageUtility.GetCurrentPrefabStage()!=null)throw new Exception("Editor is busy or editing");for(int i=0;i<SceneManager.sceneCount;i++)if(SceneManager.GetSceneAt(i).isDirty)throw new Exception("Unsaved scene must be preserved");}
 static State Original(){var s=Decode<State>(File.ReadAllText(Path.Combine(Root,"original-editor-state.json")));if(s.version!=1||s.session.Length!=9)throw new Exception("Invalid original Editor snapshot");return s;}
 public static object Capture(){CleanEdit();Directory.CreateDirectory(Root);string path=Path.Combine(Root,"original-editor-state.json");if(File.Exists(path))throw new Exception("Preserve original snapshot");var s=Current();string j=Json(s);if(Json(Decode<State>(j))!=j)throw new Exception("Snapshot round trip failed");File.WriteAllText(path,j);return new{captured=true,path,sessionKeys=s.session.Length,scene=s.scene,inputTick=s.inputTick};}
 public static object Configure(string scene){CleanEdit();var original=Original();if(LastInput()!=original.inputTick)throw new Exception("Desktop input changed since preflight; do not interrupt new user work");if(scene!="Jamsil"&&scene!="ShoeTower"&&scene!="RestStop")throw new ArgumentException("Chapter scene required");SessionState.SetBool("NoryangjinMapTool.TestPower9999",false);SessionState.SetBool("NoryangjinMapTool.TestFastLateral",false);SessionState.SetFloat("NoryangjinMapTool.TestTimeScale",1);typeof(ChapterPlaytestPreferences).Assembly.GetType("NoryangjinMapToolTestStartStage").GetMethod("SelectStage",BindingFlags.Static|BindingFlags.NonPublic).Invoke(null,new object[]{scene=="RestStop"?3:scene=="Jamsil"?4:5});SessionState.SetString(Owner,Root);return new{configured=true,scene,ordinaryStats=true,playerPrefsChanged=false};}
 public static object RestoreEditor(){CleanEdit();var s=Original();foreach(var r in s.session){if(!r.existed){if(r.kind=="bool")SessionState.EraseBool(r.key);else if(r.kind=="int")SessionState.EraseInt(r.key);else if(r.kind=="float")SessionState.EraseFloat(r.key);else SessionState.EraseString(r.key);}else if(r.kind=="bool")SessionState.SetBool(r.key,bool.Parse(r.value));else if(r.kind=="int")SessionState.SetInt(r.key,int.Parse(r.value));else if(r.kind=="float")SessionState.SetFloat(r.key,float.Parse(r.value,System.Globalization.CultureInfo.InvariantCulture));else SessionState.SetString(r.key,r.value);}EditorSceneManager.playModeStartScene=string.IsNullOrEmpty(s.startScene)?null:AssetDatabase.LoadAssetAtPath<SceneAsset>(s.startScene);if(SceneManager.GetActiveScene().path!=s.scene)EditorSceneManager.OpenScene(s.scene);Time.timeScale=s.timeScale;Time.captureDeltaTime=s.captureDeltaTime;if(s.cleanupExists)EditorPrefs.SetBool("PT_ResourcesCleanup",s.cleanup);else EditorPrefs.DeleteKey("PT_ResourcesCleanup");SessionState.EraseString(Owner);var actual=Current();var bad=s.session.Where((r,i)=>Json(r)!=Json(actual.session[i])).Select(r=>r.key).ToArray();if(actual.scene!=s.scene||actual.startScene!=s.startScene||actual.timeScale!=s.timeScale||actual.captureDeltaTime!=s.captureDeltaTime||bad.Length!=0)throw new Exception("Editor restoration mismatch: "+string.Join(",",bad));return new{restored=true,mismatches=0,scene=actual.scene,startScene=actual.startScene,sessionKeys=9};}

}
