using System;using System.IO;using System.Linq;using System.Globalization;using System.Security.Cryptography;using System.Reflection;using UnityEngine;using UnityEditor;using UnityEngine.Localization.Settings;
public static class ValidationPrefs16 {
 const string Root="outputs/chapter45-detailed-design-2026-10-03/validation-cycle16/",HashKey="Chapter45.Validation16.GameSnapshotHash";
 static readonly string[] Keys={"coin","jewel","chapter_unlocked","chapter_rewarded_3","chapter_rewarded_4","chapter_rewarded_5","TutorialDone"};
 public sealed class Row{public string key,kind="int";public bool existed;public int value;}
 public sealed class State{public int version=1;public Row[] rows;public string locale;}
 static Type J=>AppDomain.CurrentDomain.GetAssemblies().First(a=>a.GetName().Name=="Newtonsoft.Json").GetType("Newtonsoft.Json.JsonConvert");
 static string Json(object o)=>(string)J.GetMethod("SerializeObject",new[]{typeof(object)}).Invoke(null,new[]{o});
 static string Hash(string s){using var h=SHA256.Create();return Convert.ToBase64String(h.ComputeHash(System.Text.Encoding.UTF8.GetBytes(s)));}
 static State Original(){string s=File.ReadAllText(Root+"original-game-settings.json");if(Hash(s)!=SessionState.GetString(HashKey,""))throw new Exception("Game snapshot checksum mismatch");var state=(State)J.GetMethod("DeserializeObject",new[]{typeof(string),typeof(Type)}).Invoke(null,new object[]{s,typeof(State)});if(state.version!=1||state.rows.Length!=Keys.Length||!state.rows.Select(r=>r.key).SequenceEqual(Keys)||state.rows.Any(r=>r.kind!="int"))throw new Exception("Invalid exact-key snapshot");return state;}
 static void Clean(){if(EditorApplication.isPlayingOrWillChangePlaymode||EditorApplication.isCompiling||EditorApplication.isUpdating)throw new Exception("Clean Edit required");}
 public static object Capture(){Clean();string p=Root+"original-game-settings.json";if(File.Exists(p))throw new Exception("Preserve baseline");var state=new State{locale=LocalizationSettings.SelectedLocale.Identifier.Code,rows=Keys.Select(k=>new Row{key=k,existed=PlayerPrefs.HasKey(k),value=PlayerPrefs.GetInt(k)}).ToArray()};string s=Json(state);File.WriteAllText(p,s);SessionState.SetString(HashKey,Hash(s));Original();return new{captured=Keys.Length,keys=Keys,types="int only",locale=state.locale,directNativeRegistryWrites=false};}
 public static object Prepare(){Clean();var s=Original();if(s.rows.Any(r=>r.existed!=PlayerPrefs.HasKey(r.key)||r.value!=PlayerPrefs.GetInt(r.key)))throw new Exception("Game state changed since snapshot");bool change=!PlayerPrefs.HasKey("TutorialDone")||PlayerPrefs.GetInt("TutorialDone")!=1;if(change){PlayerPrefs.SetInt("TutorialDone",1);PlayerPrefs.Save();}return new{tutorialChanged=change,changedKeys=change?new[]{"TutorialDone"}:Array.Empty<string>(),engineKeysTouched=false};}
 public static object RestoreLocale(){var s=Original();LocalizationSettings.SelectedLocale=LocalizationSettings.AvailableLocales.Locales.Single(l=>l.Identifier.Code==s.locale);return new{locale=s.locale};}
 public static object Restore()=>RestoreTo("game-settings-restoration.json"); public static object RestoreTo(string receiptFile){Clean();if(Path.GetFileName(receiptFile)!=receiptFile||File.Exists(Root+receiptFile))throw new Exception("Preserve restoration receipts");var s=Original();var changed=s.rows.Where(r=>r.existed!=PlayerPrefs.HasKey(r.key)||r.value!=PlayerPrefs.GetInt(r.key)).ToArray();foreach(var r in changed){if(r.existed)PlayerPrefs.SetInt(r.key,r.value);else PlayerPrefs.DeleteKey(r.key);}if(changed.Length>0)PlayerPrefs.Save();var bad=s.rows.Where(r=>r.existed!=PlayerPrefs.HasKey(r.key)||r.value!=PlayerPrefs.GetInt(r.key)).Select(r=>r.key).ToArray();var receipt=new{restored=bad.Length==0,changedKeysRestored=changed.Select(r=>r.key).ToArray(),capturedKeys=Keys.Length,mismatches=bad,directNativeRegistryWrites=false,engineKeysTouched=false};File.WriteAllText(Root+receiptFile,Json(receipt));if(bad.Length!=0)throw new Exception("Exact game setting restoration failed");return receipt;}
}
