using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Reflection;using UnityEngine;using UnityEditor;using IndianOceanAssets.ShooterSurvival;
public static class ValidationTv12 {
 const BindingFlags F=BindingFlags.Instance|BindingFlags.NonPublic;
 static Chapter45Director d;static Chapter45Hazard h;static PlayerScript p;static CanvasScript canvas;static CapsuleCollider capsule;static BoxCollider box;static string folder,mode;static int axis,frame,index;static float begin,wallBegin,next,initialHp,warningAt,activeAt,landingAt,endAt,contactAt,radius,edge,offset;static Vector3 rest;static bool active,returned,paused,pauseDone,pauseActive;static double pauseWall;static float pauseClock;static Vector3 pauseBody;static readonly List<object> samples=new(),frames=new(),checks=new();static readonly List<string> errors=new();
 static string Json(object x)=>(string)AppDomain.CurrentDomain.GetAssemblies().First(a=>a.GetName().Name=="Newtonsoft.Json").GetType("Newtonsoft.Json.JsonConvert").GetMethod("SerializeObject",new[]{typeof(object)}).Invoke(null,new[]{x});
 static float[] V(Vector3 v)=>new[]{v.x,v.y,v.z};
 static void Set(object o,string name,object v)=>o.GetType().GetField("<"+name+">k__BackingField",F).SetValue(o,v);
 static object Mark(){var f=h.footprint.GetComponent<MeshFilter>();return new{active=h.footprint.activeInHierarchy,position=V(h.footprint.transform.position),vertices=f.sharedMesh.vertices.Select(v=>V(f.transform.TransformPoint(v))).ToArray(),mesh=f.sharedMesh.name};}
 static void Check(bool pass,string name,object evidence=null)=>checks.Add(new{pass,name,evidence});
 static void Place(Vector3 root){d.SampleOnCurrentDeck(h.distance,out var c,out var fw);float dis=h.distance+Vector3.Dot(root-c,fw);Set(d,"Distance",dis);d.SampleOnCurrentDeck(dis,out var center,out var forward);float lane=Vector3.Dot(root-center,Vector3.Cross(Vector3.up,forward));p.ApplyContinuousRoutePose(center+Vector3.up*d.footOffset,forward,lane);Physics.SyncTransforms();}
 static Vector3 RootFor(Vector3 center){Vector3 shift=capsule.transform.TransformPoint(capsule.center)-p.transform.position;center-=Vector3.ProjectOnPlane(shift,Vector3.up);center.y=h.transform.position.y+d.footOffset;return center;}
 public static object Begin(string id,string scenario,int axisNumber,float edgeOffset,string output){
  if(!EditorApplication.isPlaying||active||Directory.Exists(output))throw new Exception("Fresh play/output required");Directory.CreateDirectory(output);folder=output;mode=scenario;axis=axisNumber;offset=edgeOffset;
  d=UnityEngine.Object.FindFirstObjectByType<Chapter45Director>();p=d.Player;canvas=UnityEngine.Object.FindFirstObjectByType<CanvasScript>();canvas.PlayerPressedStartButton();h=d.hazards.Single(z=>z.name=="4F falling television");
  foreach(var e in d.encounters){e.Retire();Set(e,"Complete",true);}foreach(var z in d.hazards)if(z!=h){Set(z,"Triggered",true);z.Cancel();}
  foreach(var c in d.choices)if(c.distance<h.distance){int seg=Array.FindIndex(d.route.segments,s=>s.floor==c.floor);Set(d,"CurrentSegment",seg);c.Commit(3);}
  Set(d,"CurrentSegment",d.route.SegmentAt(h.distance));Set(d,"Distance",h.distance);d.SampleOnCurrentDeck(h.distance,out var center,out var forward);p.ApplyContinuousRoutePose(center+Vector3.up*d.footOffset,forward,0);
  Set(d,"ShieldReady",false);p.canShoot=false;typeof(PlayerScript).GetField("currentForwardMoveSpeed",F).SetValue(p,0f);capsule=p.GetComponent<CapsuleCollider>();box=h.body.GetComponentInChildren<BoxCollider>(true);rest=h.body.position;radius=capsule.radius*Mathf.Max(capsule.transform.lossyScale.x,capsule.transform.lossyScale.z);
  var tvCenter=box.transform.TransformPoint(box.center);Vector3 direction=axis==0?h.transform.right:axis==1?-h.transform.right:axis==2?h.transform.forward:-h.transform.forward;
  edge=(axis<2?box.size.x*Mathf.Abs(box.transform.lossyScale.x):box.size.z*Mathf.Abs(box.transform.lossyScale.z))*.5f+radius;
  Vector3 target=tvCenter;if(mode=="edge")target+=direction*(edge+offset);if(mode=="return"||mode=="linger"||mode=="beforeEnd")target-=h.transform.right*(edge+.8f);
  Place(RootFor(target));typeof(Chapter45Director).GetMethod("RefreshVisibility",F).Invoke(d,null);var harness=UnityEngine.Object.FindFirstObjectByType<CombatHarness>();if(harness!=null)typeof(CombatHarness).GetField("overlayVisible",F).SetValue(harness,false);
  initialHp=p.currentHealth;begin=d.Elapsed;wallBegin=Time.realtimeSinceStartup;next=0;frame=-1;index=0;warningAt=activeAt=landingAt=endAt=contactAt=-1;active=true;returned=paused=pauseDone=false;samples.Clear();frames.Clear();checks.Clear();errors.Clear();
  File.WriteAllText(Path.Combine(folder,"conditions.json"),Json(new{id,scenario,axisNumber,edgeOffset,analyticCapsuleCenterEdge=edge,playerRadius=radius,player=V(p.transform.position),capsuleCenter=V(capsule.transform.TransformPoint(capsule.center)),body=V(rest),warning=Mark(),box=EditorJsonUtility.ToJson(box),boxScale=V(box.transform.lossyScale),h.warningSeconds,h.operationSeconds,h.lingerSeconds,heldForwardSpeedZero=true,otherEncountersRetired=true,initialFloorDirected=true,ordinaryRoute=false,manualDamageOrHitOrTick=false,engineSessionWrites=false}));
  Application.logMessageReceived+=Log;EditorApplication.update+=Tick;return new{started=true,id,folder};
 }
 static void Log(string msg,string trace,LogType t){if(t==LogType.Error||t==LogType.Exception||t==LogType.Assert)errors.Add(msg);}
 static void Tick(){if(!active||!EditorApplication.isPlaying)return;EditorApplication.QueuePlayerLoopUpdate();if(frame==Time.frameCount)return;frame=Time.frameCount;
  try{float t=d.Elapsed-begin;float wall=Time.realtimeSinceStartup-wallBegin;if(h.Triggered&&warningAt<0)warningAt=t;if(h.Active&&activeAt<0)activeAt=t;if(h.Active&&(h.body.position-rest).sqrMagnitude<.0001f&&landingAt<0)landingAt=t;if(h.Finished&&endAt<0)endAt=t;if(h.Contacts>0&&contactAt<0)contactAt=t;
   if(((mode=="pause"&&h.Triggered&&!h.Active)||(mode=="fallPause"&&h.Active&&t-activeAt>=.2f))&&!pauseDone&&!paused){canvas.PauseGame();paused=true;pauseWall=EditorApplication.timeSinceStartup;pauseClock=d.Elapsed;pauseBody=h.body.position;pauseActive=h.Active;}
   if(paused&&EditorApplication.timeSinceStartup-pauseWall>.7){Check(d.Elapsed==pauseClock&&h.body.position==pauseBody&&h.Active==pauseActive,"pause freezes TV warning or native fall clock",new{duringFall=pauseActive,clockDrift=d.Elapsed-pauseClock,bodyDrift=Vector3.Distance(h.body.position,pauseBody)});canvas.ResumeGame();paused=false;pauseDone=true;}
   if((mode=="dodge"||mode=="pause")&&warningAt>=0&&t-warningAt>=.35f&&!h.Finished&&d.Lane>-3.8f)typeof(PlayerScript).GetMethod("PlayerMove",F).Invoke(p,new object[]{-15f});
   if(mode=="fallDodge"&&activeAt>=0&&t-activeAt>=.15f&&!h.Finished&&d.Lane>-3.8f)typeof(PlayerScript).GetMethod("PlayerMove",F).Invoke(p,new object[]{-15f});
   if(mode=="fallPause"&&pauseDone&&!h.Finished&&d.Lane>-3.8f)typeof(PlayerScript).GetMethod("PlayerMove",F).Invoke(p,new object[]{-15f});
   if(mode=="return"&&h.Finished&&!returned){Place(RootFor(rest));returned=true;}
   if(mode=="linger"&&landingAt>=0&&t-landingAt>=.2f&&!returned){Place(RootFor(rest));returned=true;}
   if(mode=="beforeEnd"&&h.Active&&!returned&&(float)typeof(Chapter45Hazard).GetField("elapsed",F).GetValue(h)>=(float)typeof(Chapter45Hazard).GetField("resolvedWarning",F).GetValue(h)+(float)typeof(Chapter45Hazard).GetField("resolvedOperation",F).GetValue(h)+h.lingerSeconds-.08f){Place(RootFor(rest));returned=true;}
   Vector3 shift;float depth;bool overlap=Physics.ComputePenetration(capsule,capsule.transform.position,capsule.transform.rotation,box,box.transform.position,box.transform.rotation,out shift,out depth);
   samples.Add(new{t,wall,frame,player=V(p.transform.position),capsuleCenter=V(capsule.transform.TransformPoint(capsule.center)),hp=p.currentHealth,h.Triggered,h.Active,h.Finished,h.Contacts,body=V(h.body.position),bodyActive=h.body.gameObject.activeInHierarchy,marker=Mark(),nativeGeometryOverlap=overlap,penetration=depth,paused,returned,damageCause=p.LastDamageCause.ToString(),damageLabel=PlayerDamageCauseText.Label(p.LastDamageCause)});
   if(wall>=next){next=wall+.16f;string name=(index++).ToString("D3")+".png";ScreenCapture.CaptureScreenshot(Path.Combine(folder,name));frames.Add(new{file=name,t,wall,hp=p.currentHealth,h.Contacts,h.Active,h.Finished});}
   if(wall<7.5f&&p.currentHealth>0)return;Check(warningAt>=0&&activeAt>warningAt,"warning precedes native body activation");Check(landingAt>activeAt&&endAt>=landingAt,"native landing then finish observed");Check(!h.Active&&!h.body.gameObject.activeInHierarchy&&!h.footprint.activeInHierarchy,"body and warning hidden after finish");if(mode=="dodge"||mode=="return"||mode=="pause"||mode=="fallDodge")Check(h.Contacts==0&&p.currentHealth==initialHp,"safe dodge or post-finish return takes no TV damage");if(mode=="linger"||mode=="beforeEnd")Check(returned&&h.Contacts==1&&Mathf.Approximately(p.currentHealth,55.2f),"Visible landed TV still damages before warning ends");Finish();
  }catch(Exception e){errors.Add(e.ToString());Finish();}
 }
 static void Finish(){active=false;EditorApplication.update-=Tick;Application.logMessageReceived-=Log;File.WriteAllText(Path.Combine(folder,"result.json"),Json(new{complete=true,mode,axis,offset,initialHp,health=p.currentHealth,contacts=h.Contacts,warningAt,activeAt,landingAt,endAt,contactAt,checks,samples,frames,errors,timeline=d.Timeline.ToArray(),manualDamageOrHitOrTick=false}));}
 public static object ProbeCompile()=>new{compiled=true};
}
