using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Reflection;using UnityEngine;using UnityEditor;using IndianOceanAssets.ShooterSurvival;
public static class VerifyMovingPreacher {
 const BindingFlags P=BindingFlags.Instance|BindingFlags.NonPublic;static Chapter45Director d;static PlayerScript p;static Chapter45RoleAction r;static string folder;static bool evade,active;static int frame;static float begin,hp,lane,warning=-1,action=-1,minScale=1;static List<object> samples=new();static readonly MethodInfo Move=typeof(PlayerScript).GetMethod("PlayerMove",P);
 static void Set(object o,string n,object v)=>o.GetType().GetField("<"+n+">k__BackingField",P).SetValue(o,v);
 static string Json(object x)=>(string)AppDomain.CurrentDomain.GetAssemblies().First(a=>a.GetName().Name=="Newtonsoft.Json").GetType("Newtonsoft.Json.JsonConvert").GetMethod("SerializeObject",new[]{typeof(object)}).Invoke(null,new[]{x});
 static float[] V(Vector3 v)=>new[]{v.x,v.y,v.z};
 public static object Main(string output,bool safe){folder=output;Directory.CreateDirectory(folder);evade=safe;d=UnityEngine.Object.FindFirstObjectByType<Chapter45Director>();p=d.Player;UnityEngine.Object.FindFirstObjectByType<CanvasScript>().PlayerPressedStartButton();p.canShoot=false;foreach(var w in p.GetComponentsInChildren<WeaponScript>(true))w.enabled=false;var e=d.encounters.First(e=>e.actors.Any(a=>a.GetComponent<Chapter45RoleAction>()?.role==Chapter45RoleAction.Role.Preacher));r=e.actors[0].GetComponent<Chapter45RoleAction>();foreach(var other in d.encounters)if(other!=e){other.Retire();Set(other,"Complete",true);}foreach(var h in d.hazards){h.manualOnly=true;h.Cancel();}float distance=e.activationDistance-1;Set(d,"Distance",distance);Set(d,"CurrentSegment",d.route.SegmentAt(distance));d.Sample(distance,out var center,out var forward);lane=Vector3.Dot(r.transform.position-center,Vector3.Cross(Vector3.up,forward));p.ApplyContinuousRoutePose(center+Vector3.up*d.footOffset,forward,lane);Physics.SyncTransforms();begin=d.Elapsed;hp=p.currentHealth;frame=-1;warning=action=-1;minScale=1;samples.Clear();active=true;EditorApplication.update+=Tick;return new{started=true,folder,safe,initialLane=lane,routeSpeed=d.RouteSpeed,noShot=true,manualDamage=false};}
 static void Tick(){if(!active||!EditorApplication.isPlaying)return;EditorApplication.QueuePlayerLoopUpdate();if(frame==Time.frameCount)return;frame=Time.frameCount;float t=d.Elapsed-begin;if(r.Phase==Chapter45RoleAction.ActionPhase.Warning&&warning<0){warning=t;ScreenCapture.CaptureScreenshot(Path.Combine(folder,"warning.png"));}if(r.Actions>0&&action<0){action=t;ScreenCapture.CaptureScreenshot(Path.Combine(folder,"action.png"));}if(evade&&warning>=0){float desired=lane>0?-3:3;Move.Invoke(p,new object[]{Mathf.Clamp((desired-d.Lane)*12,-15,15)});}minScale=Mathf.Min(minScale,d.CrowdMoveScale);samples.Add(new{t,d.Distance,lane=d.Lane,player=V(p.transform.position),actor=V(r.transform.position),phase=r.Phase.ToString(),r.Actions,r.Contacts,hp=p.currentHealth,scale=d.CrowdMoveScale});if(t<8&&p.currentHealth>0)return;active=false;EditorApplication.update-=Tick;File.WriteAllText(Path.Combine(folder,"result.json"),Json(new{evade,initialHP=hp,health=p.currentHealth,r.Contacts,r.Actions,warning,action,minScale,manualDamage=false,manualRoleTick=false,ordinaryForwardMotion=true,initialPlacementOnly=true,samples,timeline=d.Timeline.ToArray()}));ScreenCapture.CaptureScreenshot(Path.Combine(folder,"end.png"));}
}
