using System;using System.IO;using System.Linq;using System.Reflection;using UnityEngine;using UnityEditor;using IndianOceanAssets.ShooterSurvival;
// Directed spatial setup, followed by untouched game Update/FixedUpdate and
// real collider callbacks. Never calls Hazard.Hit, applies damage or forces death.
public static class VerifyStreetPhysicalHazard {
 static Chapter45Director d;static PlayerScript p;static Chapter45Hazard h;static string output;static bool safe,started,wasActive;static float begin,initialHealth,initialLane;static int frame;const BindingFlags Flags=BindingFlags.Instance|BindingFlags.NonPublic;
 static string Json(object x)=>(string)AppDomain.CurrentDomain.GetAssemblies().First(a=>a.GetName().Name=="Newtonsoft.Json").GetType("Newtonsoft.Json.JsonConvert").GetMethod("SerializeObject",new[]{typeof(object)}).Invoke(null,new[]{x});
 static void Set(object o,string property,object value)=>o.GetType().GetField("<"+property+">k__BackingField",Flags).SetValue(o,value);
 public static object Main(string hazard,bool safeLane,string folder){if(!EditorApplication.isPlaying)throw new Exception("Play required");output=folder;Directory.CreateDirectory(output);safe=safeLane;d=UnityEngine.Object.FindFirstObjectByType<Chapter45Director>();p=d.Player;h=d.hazards.Single(x=>x.name==hazard);UnityEngine.Object.FindFirstObjectByType<CanvasScript>().PlayerPressedStartButton();foreach(var choice in d.choices)choice.Commit(-2.8f);d.GrantShield();initialHealth=p.currentHealth;float distance=h.distance-h.warningDistance-2;initialLane=safe?h.safeLane:hazard=="Open manhole"?1.8f:1.7f;Set(d,"Distance",distance);Set(d,"CurrentSegment",d.route.SegmentAt(distance));d.Sample(distance,out var center,out var forward);p.ApplyContinuousRoutePose(center+Vector3.up*d.footOffset,forward,initialLane);Physics.SyncTransforms();begin=Time.time;frame=-1;started=true;wasActive=false;EditorApplication.update-=Tick;EditorApplication.update+=Tick;File.WriteAllText(Path.Combine(output,"conditions.json"),Json(new{hazard,safe,initialHealth,initialLane,directedSpatialSetup=true,ordinaryPlaythrough=false,manualDamage=false,manualHazardTick=false,physicalContactOnly=true,shieldGranted=d.ShieldReady,startDistance=distance}));ScreenCapture.CaptureScreenshot(Path.Combine(output,"start.png"));return new{started=true,output};}
 static void Tick(){if(!started||!EditorApplication.isPlaying||frame==Time.frameCount)return;frame=Time.frameCount;if(h.Active&&!wasActive){wasActive=true;ScreenCapture.CaptureScreenshot(Path.Combine(output,"physical-body-active.png"));}float elapsed=Time.time-begin;if(p.currentHealth>0&&elapsed<9)return;bool passed=safe?p.currentHealth>0&&h.Contacts==0&&d.Distance>h.distance+8:p.currentHealth<=0&&h.Contacts==1&&p.LastDamageCause==h.damageCause;File.WriteAllText(Path.Combine(output,"result.json"),Json(new{passed,safe,elapsed,health=p.currentHealth,initialHealth,contacts=h.Contacts,triggered=h.Triggered,bodyWasActive=wasActive,distance=d.Distance,lane=d.Lane,cause=p.LastDamageCause.ToString(),expectedCause=h.damageCause.ToString(),timeline=d.Timeline.ToArray(),manualDamage=false,manualHazardHit=false}));ScreenCapture.CaptureScreenshot(Path.Combine(output,"end.png"));started=false;EditorApplication.update-=Tick;}
}
