using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections.Generic;using UnityEngine;using UnityEditor;using IndianOceanAssets.ShooterSurvival;using Object=UnityEngine.Object;
public static class VerifyEscalatorCamera {
 const BindingFlags P=BindingFlags.Instance|BindingFlags.NonPublic;static Chapter45Director d;static PlayerScript player;static Chapter45Lift[] lifts;static string folder;static bool active;static int index,frame,shot;static double start;static List<object> samples=new();static float[] times={0,.1f,.3f,.7f,2.5f,4.7f};
 static string Json(object o)=>(string)AppDomain.CurrentDomain.GetAssemblies().First(a=>a.GetName().Name=="Newtonsoft.Json").GetType("Newtonsoft.Json.JsonConvert").GetMethod("SerializeObject",new[]{typeof(object)}).Invoke(null,new[]{o});
 static void Set(object o,string name,object v)=>o.GetType().GetProperty(name).GetSetMethod(true).Invoke(o,new[]{v});
 static float[] V(Vector3 p)=>new[]{p.x,p.y,p.z};
 public static object Main(string output){if(!EditorApplication.isPlaying)throw new Exception("Fresh Play required");folder=output;Directory.CreateDirectory(folder);d=Object.FindFirstObjectByType<Chapter45Director>();player=Object.FindFirstObjectByType<PlayerScript>();Object.FindFirstObjectByType<CanvasScript>().PlayerPressedStartButton();lifts=d.lifts.Where(l=>l.escalator).ToArray();index=0;frame=-1;active=true;samples.Clear();File.WriteAllText(Path.Combine(folder,"conditions.json"),Json(new{ordinaryRoute=false,directedTransferFixture=true,statOverrides=false,collisionAndSceneryUnchanged=true,description="Place at each authored escalator start and invoke real BeginLift; subsequent transfer advances in actual Unity frames. Capture real screen with HUD."}));StartOne();EditorApplication.update+=Tick;return new{folder,lifts=lifts.Length};}
 static void StartOne(){var l=lifts[index];Set(d,"CurrentSegment",l.afterSegment);Set(d,"Distance",d.route.SegmentEnd(l.afterSegment));d.route.SampleSegment(l.afterSegment,d.Distance,out var pos,out var forward);player.ApplyContinuousRoutePose(pos+Vector3.up*d.footOffset,forward,0);Physics.SyncTransforms();var c=Camera.main.GetComponent<StableGameplayCamera>();var yaw=Quaternion.Euler(0,player.transform.eulerAngles.y,0);c.transform.SetPositionAndRotation(player.transform.position+yaw*c.yawRelativeOffset,yaw*c.yawRelativeRotation);c.enabled=false;c.enabled=true;typeof(Chapter45Director).GetMethod("BeginLift",P).Invoke(d,new object[]{l,l.Destination(l.afterSegment)});start=EditorApplication.timeSinceStartup;shot=0;}
 static void Tick(){if(!active||Time.frameCount==frame)return;frame=Time.frameCount;try{double age=EditorApplication.timeSinceStartup-start;var camera=Camera.main;var target=player.transform.position+Vector3.up*1.5f;var viewport=camera.WorldToViewportPoint(target);var ray=target-camera.transform.position;var obstacles=Physics.RaycastAll(camera.transform.position,ray.normalized,ray.magnitude-.3f).Where(h=>!h.transform.IsChildOf(player.transform)).Where(h=>{var r=h.transform.GetComponent<Renderer>();return r!=null&&r.enabled&&!r.forceRenderingOff&&r.gameObject.activeInHierarchy;}).Select(h=>h.transform.name).Distinct().ToArray();float elapsed=(float)typeof(Chapter45Director).GetField("rideElapsed",P).GetValue(d);samples.Add(new{lift=index,frame=Time.frameCount,elapsed,viewport=V(viewport),camera=V(camera.transform.position),obstacles});if(shot<times.Length&&elapsed>=times[shot]){ScreenCapture.CaptureScreenshot(Path.Combine(folder,$"lift{index}-sample{shot}-{elapsed:F3}.png"));shot++;}if(!d.IsTransferring&&age>1){index++;if(index>=lifts.Length){Finish(new{completed=true,samples});return;}StartOne();}if(age>8)throw new Exception("Transfer did not end");}catch(Exception e){Finish(new{completed=false,error=e.ToString(),samples});}}
 static void Finish(object value){active=false;EditorApplication.update-=Tick;File.WriteAllText(Path.Combine(folder,"result.json"),Json(value));}
}
