using System;using System.IO;using System.Linq;using System.Collections;using System.Collections.Generic;using System.Reflection;using UnityEngine;using UnityEditor;using IndianOceanAssets.ShooterSurvival;using Object=UnityEngine.Object;
// Directed native-Update/physics fixtures. Placement and encounter prerequisites
// are explicit; no manual role Tick/Contact/Fire, Hazard.Hit or player damage.
public static class VerifyPlayabilityCycle03 {
 const BindingFlags P=BindingFlags.Instance|BindingFlags.NonPublic;
 static Chapter45Director d;static PlayerScript p;static CanvasScript canvas;static string output;static List<object> checks=new();static List<string> errors=new();static int failed;
 static string Json(object x)=>(string)AppDomain.CurrentDomain.GetAssemblies().First(a=>a.GetName().Name=="Newtonsoft.Json").GetType("Newtonsoft.Json.JsonConvert").GetMethod("SerializeObject",new[]{typeof(object)}).Invoke(null,new[]{x});
 static void Set(object o,string property,object v)=>o.GetType().GetField("<"+property+">k__BackingField",P).SetValue(o,v);
 static void Check(bool pass,string label,object evidence=null){checks.Add(new{pass,label,evidence});if(!pass)failed++;}
 static float[] V(Vector3 x)=>new[]{x.x,x.y,x.z};
 static void Log(string m,string stack,LogType t){if(t==LogType.Error||t==LogType.Exception||t==LogType.Assert||t==LogType.Warning&&m.Contains("Animator"))errors.Add(m);}
 static void Shot(string label)=>ScreenCapture.CaptureScreenshot(Path.Combine(output,label+".png"));
 public static object Main(string folder){if(!EditorApplication.isPlaying)throw new Exception("Play required");output=folder;Directory.CreateDirectory(output);checks.Clear();errors.Clear();failed=0;d=Object.FindFirstObjectByType<Chapter45Director>();p=d.Player;canvas=Object.FindFirstObjectByType<CanvasScript>();canvas.PlayerPressedStartButton();var overlay=Object.FindFirstObjectByType<CombatHarness>();if(overlay!=null)typeof(CombatHarness).GetField("overlayVisible",P).SetValue(overlay,false);p.enabled=false;p.canShoot=false;foreach(var w in p.GetComponentsInChildren<WeaponScript>(true))w.enabled=false;Application.logMessageReceived+=Log;canvas.StartCoroutine(Guarded(Run()));return new{started=true,output};}
 static void Pump(){EditorApplication.QueuePlayerLoopUpdate();}
 static IEnumerator Guarded(IEnumerator run){EditorApplication.update+=Pump;var stack=new Stack<IEnumerator>();stack.Push(run);while(stack.Count>0){bool next;object current;try{var top=stack.Peek();next=top.MoveNext();current=next?top.Current:null;}catch(Exception ex){errors.Add(ex.ToString());Finish();yield break;}if(!next){stack.Pop();continue;}if(current is IEnumerator nested){stack.Push(nested);continue;}yield return current;}Finish();}
 static void Finish(){EditorApplication.update-=Pump;Application.logMessageReceived-=Log;File.WriteAllText(Path.Combine(output,"summary.json"),Json(new{utc=DateTime.UtcNow.ToString("o"),checks,passed=checks.Count-failed,failed,errors,directedFixture=true,ordinaryPlaythrough=false,manualRoleTick=false,manualRoleContact=false,manualProjectileLaunch=false,manualPlayerDamage=false}));}
 static void Reset(){TimeManager.isGameRunning=true;TimeManager.timeFactor=1;p.Heal(p.MaxHealth);d.BeginRun();p.enabled=false;p.canShoot=false;foreach(var e in d.encounters){e.Retire();Set(e,"Complete",true);}foreach(var h in d.hazards){h.manualOnly=true;h.Cancel();}foreach(var b in Object.FindObjectsByType<SimpleProjectile>(FindObjectsSortMode.None))if(b.gameObject.activeInHierarchy)b.gameObject.SetActive(false);}
 static void Floor(int floor){Set(d,"CurrentSegment",Array.FindIndex(d.route.segments,s=>s.floor==floor));}
 static void Choose(int choice){if(d.choices.Length==0)return;if(d.chapter==5)Floor(4);foreach(var c in d.choices)c.Commit(choice==0?-2:2);}
 static Chapter45RoleAction Stage(Chapter45RoleAction.Role role,bool group=false){Reset();var e=d.encounters.First(e=>e.actors.Any(a=>a.GetComponent<Chapter45RoleAction>()?.role==role));Choose(e.requiredChoice==1?1:0);Floor(e.floor);Set(d,"Distance",e.activationDistance+.1f);e.ResetForRun(d);e.Tick();var r=e.actors.Select(a=>a.GetComponent<Chapter45RoleAction>()).First(r=>r!=null&&r.role==role);if(!group)foreach(var a in e.actors)if(a.gameObject!=r.gameObject)a.gameObject.SetActive(false);Vector3 toward=r.transform.forward;float gap=role==Chapter45RoleAction.Role.Basketball?6:role==Chapter45RoleAction.Role.Promoter||role==Chapter45RoleAction.Role.PlateThrower||role==Chapter45RoleAction.Role.PopcornThrower?9:4;p.ApplyContinuousRoutePose(r.transform.position+toward*gap+Vector3.up*d.footOffset,-toward,0);Physics.SyncTransforms();return r;}
 static IEnumerator Run(){if(d.chapter==4){yield return Role("PhoneShopper",false);yield return Role("Preacher",false);yield return Role("Preacher",true);yield return Role("Promoter",false);yield return Wallet(0);yield return Wallet(1);}else{foreach(string role in new[]{"StudentGrab","Basketball","Golfer","Cleaner","PlateThrower","PopcornThrower","ShoppingBags"})yield return Role(role,false);yield return Role("StudentGrab",true);yield return Queue();yield return QueueLeaderDefeat();yield return FloorClock();yield return WarningReadability();yield return ShoeGate();}}
 static IEnumerator Role(string roleName,bool evade){var type=(Chapter45RoleAction.Role)Enum.Parse(typeof(Chapter45RoleAction.Role),roleName);var r=Stage(type);var actor=r.GetComponent<EnemyScript_space>();var a=r.GetComponentInChildren<Animator>(true);float began=d.Elapsed,hp=p.currentHealth,warning=-1,action=-1,minMove=1;Vector3 start=r.transform.position;bool moved=false,shotWarning=false,shotAction=false;var ids=new HashSet<int>();var samples=new List<object>();float next=0;float duration=type==Chapter45RoleAction.Role.PhoneShopper?3:8;Vector3 lastProjectile=Vector3.zero;float projectileTravel=0;int trackedProjectile=0;bool phoneBoneMoved=false;var hand=r.heldProp;Vector3 handFirst=hand==null?Vector3.zero:hand.position;
  if(type==Chapter45RoleAction.Role.ShoppingBags)p.transform.position=r.transform.position+Vector3.up*.12f;
  while(d.Elapsed-began<duration&&p.currentHealth>0){yield return null;float t=d.Elapsed-began;if(r.Phase==Chapter45RoleAction.ActionPhase.Warning&&warning<0){warning=t;if(type==Chapter45RoleAction.Role.StudentGrab&&!evade)Check(r.warningText.StartsWith("와 머야~!!"),"Student native warning uses requested dialogue",new{r.warningText});Shot(roleName+(evade?"-safe":"-hit")+"-warning");shotWarning=true;if(evade){p.transform.position+=r.transform.right*5;Physics.SyncTransforms();}}if(r.Actions>0&&action<0){action=t;Shot(roleName+(evade?"-safe":"-hit")+"-action");shotAction=true;}minMove=Mathf.Min(minMove,d.CrowdMoveScale);moved|=Vector3.Distance(start,r.transform.position)>.2f;if(hand!=null&&Vector3.Distance(handFirst,hand.position)>.005f)phoneBoneMoved=true;
   foreach(var b in r.encounter.GetComponentsInChildren<SimpleProjectile>(false)){if(!b.name.Contains("active projectile"))continue;ids.Add(b.GetInstanceID());if(trackedProjectile==0){trackedProjectile=b.GetInstanceID();lastProjectile=b.transform.position;}else if(trackedProjectile==b.GetInstanceID()){projectileTravel+=Vector3.Distance(lastProjectile,b.transform.position);lastProjectile=b.transform.position;}}
   if(t>=next){next=t+.1f;samples.Add(new{t,phase=r.Phase.ToString(),r.Actions,r.Contacts,health=p.currentHealth,crowdMoveScale=d.CrowdMoveScale,actor=V(r.transform.position),player=V(p.transform.position),animatorState=a.GetCurrentAnimatorStateInfo(0).shortNameHash,projectiles=ids.Count});}
   if(r.Actions>0&&t-action>1.6f)break;
  }
  if(type==Chapter45RoleAction.Role.PhoneShopper){Check(a.runtimeAnimatorController.animationClips.Any(c=>c.name.ToLowerInvariant().Contains("phone")),"Phone filming uses its own phone clip",new{r.name,handProp=hand?.name,phoneBoneMoved,moved});Shot("PhoneShopper-filming");}
  else if(type==Chapter45RoleAction.Role.ShoppingBags)Check(r.Contacts>0&&minMove<.5f,"Shopping bags crowd physical contact slows player",new{r.Contacts,minMove,damage=hp-p.currentHealth});
  else {Check(shotWarning&&shotAction&&action-warning>=.75f,roleName+" warning precedes native action",new{warning,action,r.Actions,evade});if(type==Chapter45RoleAction.Role.Promoter||type==Chapter45RoleAction.Role.PlateThrower||type==Chapter45RoleAction.Role.PopcornThrower){int expected=type==Chapter45RoleAction.Role.Promoter?5:type==Chapter45RoleAction.Role.PopcornThrower?3:1;Check(ids.Count==expected&&projectileTravel>1,roleName+" native projectile burst and travel",new{expected,count=ids.Count,projectileTravel,damage=hp-p.currentHealth});}else{Check(evade?r.Contacts==0&&p.currentHealth==hp:r.Contacts>0&&p.currentHealth<hp,roleName+(evade?" sidestep avoids actual strike":" actual warned strike damages"),new{r.Contacts,damage=hp-p.currentHealth,moved});if(!evade&&(type==Chapter45RoleAction.Role.StudentGrab||type==Chapter45RoleAction.Role.Preacher))Check(minMove==.35f,roleName+" applies bounded grab slowdown",new{minMove});}}
  File.WriteAllText(Path.Combine(output,roleName+(evade?"-safe":"-hit")+".json"),Json(new{samples,timeline=d.Timeline.ToArray(),nativeUpdatesOnly=true}));yield return new WaitForEndOfFrame();yield return null;
 }
 static IEnumerator Wallet(int choice){Reset();Choose(choice);var c=d.choices.First(x=>x.kind==Chapter45Choice.ChoiceKind.RouteFork);Set(d,"Distance",c.rewardDistance+.1f);int before=MoneyScript.S.Coin;float attack=p.ResolvedAttackDamage;yield return null;yield return null;int paid=MoneyScript.S.Coin-before;float after=p.ResolvedAttackDamage;yield return new WaitForSeconds(.4f);Check(c.Rewarded&&paid==(choice==1?120:0)&&MoneyScript.S.Coin-before==paid&&Mathf.Abs(after-attack*(choice==1?1.1f:1))<.001f,"Route choice actual wallet/attack and duplicate prevention",new{choice,before,afterCoin=MoneyScript.S.Coin,paid,attack,after,resolvedPotential=c.ResolvedCoins});}
 static IEnumerator Queue(){var leader=Stage(Chapter45RoleAction.Role.CalledQueue,true);var rs=leader.encounter.actors.Select(a=>a.GetComponent<Chapter45RoleAction>()).Where(r=>r!=null&&r.role==Chapter45RoleAction.Role.CalledQueue).ToArray();var origins=rs.Select(r=>r.transform.position).ToArray();float start=d.Elapsed,called=-1;float[] moved=rs.Select(_=>-1f).ToArray();var samples=new List<object>();bool paused=false;float drift=0,clockDrift=0;while(d.Elapsed-start<6.8f){yield return null;float t=d.Elapsed-start;if(called<0&&d.Timeline.Any(x=>x.Contains("queue called"))){called=t;Shot("queue-called-still");}for(int i=0;i<rs.Length;i++)if(moved[i]<0&&Vector3.Distance(origins[i],rs[i].transform.position)>.015f)moved[i]=t;if(!paused&&t>2){paused=true;var positions=rs.Select(r=>r.transform.position).ToArray();float before=d.Elapsed;TimeManager.isGameRunning=false;yield return new WaitForSeconds(.8f);clockDrift=d.Elapsed-before;drift=rs.Select((r,i)=>Vector3.Distance(positions[i],r.transform.position)).Max();TimeManager.isGameRunning=true;}if(t>3&&t<3.1f)Shot("queue-moving-after-call");samples.Add(new{t,called,movement=rs.Select((r,i)=>Vector3.Distance(origins[i],r.transform.position)).ToArray()});}Check(called>=1.45f&&moved.All(t=>t-called>=1.15f),"B1 call precedes every queue member by at least1.15 active seconds",new{called,moved,lead=moved.Select(t=>t-called).ToArray()});Check(moved.Max()-moved.Min()<.06f,"B1 group starts together despite authored individual phase offsets",new{moved});Check(drift<.001f&&clockDrift==0,"B1 queue call clock and movement pause together",new{drift,clockDrift});File.WriteAllText(Path.Combine(output,"queue.json"),Json(new{samples,timeline=d.Timeline.ToArray()}));}
 static IEnumerator QueueLeaderDefeat(){var leader=Stage(Chapter45RoleAction.Role.CalledQueue,true);var followers=leader.encounter.actors.Where(a=>a.gameObject!=leader.gameObject).Select(a=>a.GetComponent<Chapter45RoleAction>()).ToArray();var starts=followers.Select(r=>r.transform.position).ToArray();leader.GetComponent<EnemyScript_space>().EnemyDeath();float began=d.Elapsed,called=-1,moved=-1;while(d.Elapsed-began<4){yield return null;float t=d.Elapsed-began;if(called<0&&d.Timeline.Any(x=>x.Contains("queue called")))called=t;if(moved<0&&followers.Any(r=>Vector3.Distance(r.transform.position,starts[Array.IndexOf(followers,r)])>.015f))moved=t;}Check(called>=1.45f&&moved-called>=1.15f&&followers.All(r=>Vector3.Distance(r.transform.position,starts[Array.IndexOf(followers,r)])>1),"Defeated queue leader does not strand followers or remove their call warning",new{called,moved,leaderDead=leader.GetComponent<EnemyScript_space>().IsDead,nativeEnemyDeathFixture=true});Shot("queue-after-leader-defeat");yield return new WaitForEndOfFrame();yield return null;}
 static IEnumerator FloorClock(){Reset();Floor(1);var entranceLift=d.lifts.First(l=>l.minimumFloorSeconds>0);Set(d,"CurrentSegment",entranceLift.afterSegment);Set(d,"Distance",d.route.SegmentEnd(entranceLift.afterSegment));Set(d,"FloorElapsed",24f);Set(d,"Elapsed",24f);yield return new WaitForSeconds(.2f);Check(d.hud.panel.activeInHierarchy&&d.hud.title.text.Contains("준비")&&d.hud.description.text.Contains("초 후"),"Blocked1F exit explains the remaining active-time wait",new{d.hud.title.text,detail=d.hud.description.text});Shot("1F-wait-countdown");yield return new WaitForEndOfFrame();yield return null;float clock=d.FloorElapsed;yield return new WaitForSeconds(.4f);Check(d.FloorElapsed>clock+.3f,"1F active clock advances");clock=d.FloorElapsed;TimeManager.isGameRunning=false;yield return new WaitForSeconds(.8f);Check(d.FloorElapsed==clock,"1F clock freezes while paused");TimeManager.isGameRunning=true;var lift=d.lifts.First(l=>l.minimumFloorSeconds>0);Set(d,"FloorElapsed",29.9f);Check(!lift.Ready(d),"1F escalator locked below30 active seconds");yield return new WaitForSeconds(.2f);Check(lift.Ready(d)&&d.FloorElapsed>=30,"1F escalator opens only after30 active seconds and cleared prerequisites",new{d.FloorElapsed,lift.minimumFloorSeconds});}
 static IEnumerator ShoeGate(){Reset();Choose(0);Floor(7);var es=d.encounters.Where(e=>e.floor==7).ToArray();var all=es.SelectMany(e=>e.actors).ToArray();foreach(var e in es){e.ResetForRun(d);Set(d,"Distance",e.activationDistance+.1f);e.Tick();}foreach(var a in all){a.GetComponent<Chapter45RoleAction>().enabled=false;a.transform.position+=Vector3.right*15;}var goal=d.goals.Single(g=>g.offering);p.transform.position=goal.transform.position+Vector3.up*.2f;Physics.SyncTransforms();int jewel=MoneyScript.S.Jewel;yield return new WaitForSeconds(.25f);Check(!goal.Claimed&&MoneyScript.S.Jewel==jewel,"Physical shoe overlap blocked while all6 managers live",new{alive=all.Count(a=>!a.IsDead),goal.Claimed});Shot("shoe-blocked-six-managers");for(int i=0;i<all.Length-1;i++)all[i].EnemyDeath();yield return new WaitForSeconds(.7f);Check(!goal.Claimed&&MoneyScript.S.Jewel==jewel,"Physical shoe overlap remains blocked while last manager lives",new{alive=all.Count(a=>!a.IsDead),goal.Claimed});Shot("shoe-blocked-last-manager");all.Last().EnemyDeath();yield return new WaitForSeconds(.8f);int delta=MoneyScript.S.Jewel-jewel;Check(goal.Claimed&&d.GoalClaimed&&delta>0,"Same native collider overlap collects once after last manager defeat",new{alive=all.Count(a=>!a.IsDead),goal.Claimed,delta,seededEarlierFloorCompletion=true,nativeEnemyDeathCalls=true});yield return new WaitForSeconds(.5f);Check(MoneyScript.S.Jewel-jewel==delta,"Persistent shoe overlap never duplicates completion reward",new{delta});Shot("shoe-collected");}
 static IEnumerator WarningReadability(){Reset();Floor(8);d.AnnounceWarning("행동 예고","접시 투척 · 옆으로 이동하세요",1.1f);yield return new WaitForSeconds(.1f);d.AnnounceWarning("주문 034번","호출된 대기줄이 이동합니다",1.2f);yield return new WaitForSeconds(.2f);d.hud.description.ForceMeshUpdate();Check(d.hud.description.text.Contains("접시 투척")&&d.hud.description.text.Contains("주문 034번"),"Order call retains the concurrently active attack warning",new{d.hud.description.text});Check(!d.hud.description.isTextOverflowing,"Two concurrent warning lines fit the native HUD",new{d.hud.description.fontSize,d.hud.description.isTextOverflowing,lines=d.hud.description.textInfo.lineCount,rect=d.hud.description.rectTransform.rect.ToString()});Shot("concurrent-plate-call");yield return new WaitForEndOfFrame();yield return new WaitForSeconds(1.2f);d.AnnounceWarning("위험 예고","배식 카트 · 빈 통로로 피하세요",1.5f);d.AnnounceWarning("행동 예고","덩크 준비 · 표시된 자리에서 벗어나세요",1.1f);d.AnnounceWarning("행동 예고","와 머야~!! · 손을 뻗기 전에 옆으로",1.1f);yield return new WaitForSeconds(.2f);d.hud.description.ForceMeshUpdate();Check(!d.hud.description.isTextOverflowing,"Three simultaneous hazard/strike messages fit the native HUD",new{d.hud.description.text,d.hud.description.fontSize,d.hud.description.isTextOverflowing,lines=d.hud.description.textInfo.lineCount});Shot("concurrent-cart-strikes");yield return new WaitForEndOfFrame();yield return null;}
}
