using System;using System.Linq;using System.Collections.Generic;using System.Reflection;using UnityEngine;using UnityEditor;using IndianOceanAssets.ShooterSurvival;
public static class VerifyRoleActions {
 const BindingFlags Private=BindingFlags.Instance|BindingFlags.NonPublic;static List<string> checks=new();static void Check(bool v,string s){if(!v)throw new Exception(s);checks.Add(s);}static void Set(object o,string p,object v)=>o.GetType().GetField("<"+p+">k__BackingField",Private).SetValue(o,v);static void Field(object o,string p,object v)=>o.GetType().GetField(p,Private).SetValue(o,v);static object Call(object o,string p,params object[] args)=>o.GetType().GetMethod(p,Private).Invoke(o,args);
 public static object Main(){
  if(!EditorApplication.isPlaying)throw new Exception("Play required");checks.Clear();var d=UnityEngine.Object.FindFirstObjectByType<Chapter45Director>();var p=UnityEngine.Object.FindFirstObjectByType<PlayerScript>();UnityEngine.Object.FindFirstObjectByType<CanvasScript>().PlayerPressedStartButton();
  var e=d.encounters.First(x=>x.floor==1);var actor=e.actors[0];actor.gameObject.SetActive(true);actor.ApplyStat(2,12,EnemyTier.Normal);Field(actor,"playerScript",p);Set(e,"Activated",true);var role=actor.GetComponent<Chapter45RoleAction>();role.role=Chapter45RoleAction.Role.Guard;Set(role,"Phase",Chapter45RoleAction.ActionPhase.Acting);Field(role,"age",5f);Field(role,"hitThisAction",false);Field(role,"lastContact",-100f);
  Vector3 forward=Vector3.ProjectOnPlane(p.transform.forward,Vector3.up).normalized;Vector3 right=Vector3.Cross(Vector3.up,forward);Vector3 muzzle=p.transform.position+forward*2+Vector3.up*2.2f;actor.transform.position=p.transform.position+forward*8;
  Physics.SyncTransforms();var pitch=d.AimAtRoleHeight(muzzle,forward);Check(pitch.y<-.05f&&Mathf.Abs(Vector3.Dot(pitch,right))<.001f,"human-height aim changes pitch only within firing lane: "+pitch+" collider="+actor.GetComponent<Collider>().bounds+" active="+actor.gameObject.activeInHierarchy+" eligible="+e.Eligible);actor.transform.position+=right*3;Physics.SyncTransforms();Check(Vector3.Distance(d.AimAtRoleHeight(muzzle,forward),forward)<.001f,"off-lane actors receive no horizontal auto-aim");
  float hp=p.currentHealth;d.GrantShield();role.ContactPlayer(p);role.ContactPlayer(p);Check(p.currentHealth==hp&&!d.ShieldReady,"one guarded strike consumes shield once and never repeats damage");
  TimeManager.isGameRunning=false;float age=(float)role.GetType().GetField("age",Private).GetValue(role);role.TickRole(2);Call(role,"Update");Check(p.currentHealth==hp&&(float)role.GetType().GetField("age",Private).GetValue(role)==age&&!actor.GetComponentInChildren<Animator>(true).enabled,"pause freezes damage, role clock and Animator");TimeManager.isGameRunning=true;Call(role,"Update");Check(actor.GetComponentInChildren<Animator>(true).enabled,"resume restores role Animator");
  int floor=e.floor;e.floor=999;role.TickRole(2);role.ContactPlayer(p);Check(p.currentHealth==hp,"wrong floor blocks role motion and damage");e.floor=floor;
  role.transform.position=p.transform.position+Vector3.forward*4;Set(role,"Phase",Chapter45RoleAction.ActionPhase.Moving);Field(role,"remaining",0f);Field(role,"hitThisAction",false);Field(role,"lastContact",-100f);
  for(int i=0;i<250&&p.currentHealth==hp;i++)role.TickRole(.02f);Check(p.currentHealth==hp-role.actionDamage,"guard reaches a stationary player with its warned spatial strike");
  role.gameObject.SetActive(false);actor.transform.position=p.transform.position;actor.gameObject.SetActive(true);actor.ApplyStat(2,12,EnemyTier.Normal);role.enabled=false;actor.GetComponent<Chapter45Deck>().floor=d.CurrentFloor;Field(actor,"playerScript",p);
  var go=new GameObject("Directed cinema contact fixture");var hold=go.AddComponent<RestStopHoldout>();hold.chapter45Owner=d;hold.requiredFloor=d.CurrentFloor;hold.choiceIndex=-1;hold.police=Array.Empty<EnemyEventController>();hold.entrances=Array.Empty<Transform>();hold.entranceSignals=Array.Empty<Renderer>();hold.center=go.transform;hold.center.position=p.transform.position;hold.BeginRun();Call(hold,"BeginEncounter");
  var audience=actor.gameObject.AddComponent<Chapter45AudienceContact>();audience.holdout=hold;audience.damage=2;hp=p.currentHealth;int score=p.playerScore,coins=MoneyScript.S.Coin;
  TimeManager.isGameRunning=false;audience.Contact(p);Check(p.currentHealth==hp&&!actor.IsDead,"paused audience contact cannot retire or damage");TimeManager.isGameRunning=true;
  actor.GetComponent<Chapter45Deck>().floor=999;audience.Contact(p);Check(p.currentHealth==hp&&!actor.IsDead,"other-deck audience contact cannot retire or damage");actor.GetComponent<Chapter45Deck>().floor=d.CurrentFloor;
  audience.Contact(p);audience.Contact(p);Check(p.currentHealth==hp-2&&actor.IsDead,"audience contact applies configured2 once instead of health12");Check(p.playerScore==score&&MoneyScript.S.Coin==coins,"contact retirement grants neither score nor coins");
  hold.police=new[]{actor.GetComponent<EnemyEventController>()};Field(hold,"alive",new[]{true});Call(hold,"CountKills");Check(hold.Killed==0&&audience.RetiredOnContact,"contact retirement does not increment cinema kill HUD");
  actor.gameObject.SetActive(false);actor.gameObject.SetActive(true);actor.ApplyStat(2,12,EnemyTier.Normal);Field(hold,"alive",new[]{true});actor.EnemyDeath();Call(hold,"CountKills");Check(hold.Killed==1&&!audience.RetiredOnContact,"reused audience clears contact reason and normal defeat counts once");
  return new{checks=checks.ToArray(),passed=checks.Count,fixture=true,ordinaryPlaythrough=false,explicitDirectedActivationAndSpatialSetup=true};
 }
}
