using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections.Generic;using UnityEngine;using UnityEditor;using IndianOceanAssets.ShooterSurvival;using Object=UnityEngine.Object;
public static class VerifyReleaseTransfers {
 const BindingFlags P=BindingFlags.Instance|BindingFlags.NonPublic;static Chapter45Director d;static PlayerScript player;static Chapter45Lift[] lifts;static string folder;static bool active,landed;static int index,frame,shot,sideShot,wait;static double start;static List<object> samples=new();static float[] times={0,.3f,2.5f,4.7f};static Vector3 arrival,forward;static readonly float[] offsets={0,-2,2};
 static string Json(object o)=>(string)AppDomain.CurrentDomain.GetAssemblies().First(a=>a.GetName().Name=="Newtonsoft.Json").GetType("Newtonsoft.Json.JsonConvert").GetMethod("SerializeObject",new[]{typeof(object)}).Invoke(null,new[]{o});
 static void Set(object o,string name,object v)=>o.GetType().GetProperty(name).GetSetMethod(true).Invoke(o,new[]{v});static float[] V(Vector3 p)=>new[]{p.x,p.y,p.z};
 public static object Main(string output){if(!EditorApplication.isPlaying)throw new Exception("Fresh Play required");folder=output;Directory.CreateDirectory(folder);d=Object.FindFirstObjectByType<Chapter45Director>();player=Object.FindFirstObjectByType<PlayerScript>();Object.FindFirstObjectByType<CanvasScript>().PlayerPressedStartButton();lifts=d.lifts.Where(l=>l.escalator||d.route.segments[l.afterSegment].floor==5).ToArray();index=0;frame=-1;active=true;samples.Clear();File.WriteAllText(Path.Combine(folder,"conditions.json"),Json(new{ordinaryRoute=false,directedTransferFixture=true,statOverrides=false,description="Three real escalator transfers and cinema elevator; each landing frozen briefly for centre/left/right native HUD captures. No saved scene edits."}));StartOne();EditorApplication.update+=Tick;return new{folder,lifts=lifts.Length};}
 static void StartOne(){TimeManager.isGameRunning=true;player.movement=true;landed=false;var l=lifts[index];Set(d,"CurrentSegment",l.afterSegment);Set(d,"Distance",d.route.SegmentEnd(l.afterSegment));d.route.SampleSegment(l.afterSegment,d.Distance,out var pos,out var direction);player.ApplyContinuousRoutePose(pos+Vector3.up*d.footOffset,direction,0);Physics.SyncTransforms();Camera.main.GetComponent<StableGameplayCamera>().SnapToTarget();typeof(Chapter45Director).GetMethod("BeginLift",P).Invoke(d,new object[]{l,l.Destination(l.afterSegment)});start=EditorApplication.timeSinceStartup;shot=0;}
 static bool capturePending;
 static void PlaceLanding(){player.ApplyContinuousRoutePose(arrival,forward,offsets[sideShot]);Physics.SyncTransforms();Camera.main.GetComponent<StableGameplayCamera>().SnapToTarget();capturePending=false;wait=Time.frameCount+4;}
 static void Tick(){if(!active||Time.frameCount==frame)return;frame=Time.frameCount;try{if(landed){if(frame<wait)return;if(!capturePending){ScreenCapture.CaptureScreenshot(Path.Combine(folder,$"lift{index}-landing-{sideShot}.png"));samples.Add(new{lift=index,landing=true,lateral=offsets[sideShot],player=V(player.transform.position),camera=V(Camera.main.transform.position)});capturePending=true;wait=frame+2;return;}sideShot++;if(sideShot<offsets.Length){PlaceLanding();return;}index++;if(index==lifts.Length){Finish(new{completed=true,transfers=lifts.Length,samples});return;}StartOne();return;}
  double age=EditorApplication.timeSinceStartup-start;var camera=Camera.main;var target=player.transform.position+Vector3.up*1.5f;var viewport=camera.WorldToViewportPoint(target);var ray=target-camera.transform.position;var obstacles=Physics.RaycastAll(camera.transform.position,ray.normalized,ray.magnitude-.3f).Where(h=>!h.transform.IsChildOf(player.transform)).Where(h=>{var r=h.transform.GetComponent<Renderer>();return r!=null&&r.enabled&&!r.forceRenderingOff&&r.gameObject.activeInHierarchy;}).Select(h=>h.transform.name).Distinct().ToArray();float elapsed=(float)typeof(Chapter45Director).GetField("rideElapsed",P).GetValue(d);samples.Add(new{lift=index,landing=false,frame=Time.frameCount,elapsed,viewport=V(viewport),camera=V(camera.transform.position),obstacles});if(shot<times.Length&&elapsed>=times[shot]){ScreenCapture.CaptureScreenshot(Path.Combine(folder,$"lift{index}-sample{shot}.png"));shot++;}if(!d.IsTransferring&&age>1){TimeManager.isGameRunning=false;player.movement=false;d.route.SampleSegment(d.CurrentSegment,d.Distance,out var pos,out forward);arrival=pos+Vector3.up*d.footOffset;landed=true;sideShot=0;PlaceLanding();}if(age>9)throw new Exception("Transfer did not end");}catch(Exception e){Finish(new{completed=false,error=e.ToString(),samples});}}
 static void Finish(object value){active=false;TimeManager.isGameRunning=true;EditorApplication.update-=Tick;File.WriteAllText(Path.Combine(folder,"result.json"),Json(value));}
}
