using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections.Generic;using UnityEngine;using UnityEditor;using IndianOceanAssets.ShooterSurvival;using Object=UnityEngine.Object;
public static class VerifyCoupleLive {
 const BindingFlags P=BindingFlags.Instance|BindingFlags.NonPublic;static Chapter45Director d;static Chapter45CouplePose pose;static string folder;static int frame=-1,shot;static double start;static List<object> rows;static Quaternion pausedArm;static Vector3 pausedRoot;static bool paused,resumed,killed;static float pauseDrift,maxGap;static int validFrames;
 static void Set(object o,string p,object v)=>o.GetType().GetProperty(p).GetSetMethod(true).Invoke(o,new[]{v});
 static string Json(object o)=>(string)AppDomain.CurrentDomain.GetAssemblies().First(a=>a.GetName().Name=="Newtonsoft.Json").GetType("Newtonsoft.Json.JsonConvert").GetMethod("SerializeObject",new[]{typeof(object)}).Invoke(null,new[]{o});
 public static object Main(string output){if(!EditorApplication.isPlaying)throw new Exception("Play required");folder=output;Directory.CreateDirectory(folder);Object.FindFirstObjectByType<CanvasScript>().PlayerPressedStartButton();d=Object.FindFirstObjectByType<Chapter45Director>();pose=d.GetComponentsInChildren<Chapter45CouplePose>(true).First(p=>p.follower.encounter.floor==2);var e=pose.follower.encounter;d.enabled=false;Set(d,"Running",true);Set(d,"Distance",e.activationDistance+.2f);Set(d,"CurrentSegment",d.route.SegmentAt(d.Distance));d.Player.movement=false;foreach(var w in d.Player.GetComponentsInChildren<WeaponScript>())w.enabled=false;var center=(pose.leader.transform.position+pose.follower.transform.position)*.5f;d.Player.transform.position=center-pose.leader.transform.forward*15;e.Tick();typeof(Chapter45Director).GetMethod("RefreshVisibility",P).Invoke(d,null);var cam=Camera.main;cam.GetComponent<StableGameplayCamera>().enabled=false;cam.transform.position=center+pose.leader.transform.forward*5+Vector3.up*2.5f;cam.transform.LookAt(center+Vector3.up*1.0f);cam.fieldOfView=43;start=EditorApplication.timeSinceStartup;rows=new();EditorApplication.update+=Tick;return new{folder,pending=true};}
 static void Tick(){if(frame==Time.frameCount)return;frame=Time.frameCount;try{float age=(float)(EditorApplication.timeSinceStartup-start);if(age>2&&!paused){TimeManager.isGameRunning=false;paused=true;}if(age>2.2f&&age<2.3f){pausedArm=pose.upper.rotation;pausedRoot=pose.follower.transform.position;}if(age>=2.3f&&age<3){pauseDrift=Mathf.Max(pauseDrift,Quaternion.Angle(pausedArm,pose.upper.rotation),Vector3.Distance(pausedRoot,pose.follower.transform.position));}if(age>=3&&!resumed){TimeManager.isGameRunning=true;resumed=true;}if(age>=7&&!killed){pose.follower.GetComponent<EnemyScript_space>().EnemyDeath();killed=true;}float gap=Vector3.Distance(pose.hand.position,pose.partnerElbow.position+pose.leader.transform.forward*.06f);if(age>.3f&&(!paused||resumed)&&!killed){maxGap=Mathf.Max(maxGap,gap);validFrames++;}if(shot<6&&age>=shot+ .45f){ScreenCapture.CaptureScreenshot(Path.Combine(folder,"couple-"+shot+".png"));shot++;}rows.Add(new{age,gap,canLink=pose.follower.CanAct&&pose.leader.CanAct,animatorEnabled=pose.animator.enabled});if(age>=8){Finish(null);}}catch(Exception e){Finish(e.ToString());}}
 static void Finish(string error){EditorApplication.update-=Tick;TimeManager.isGameRunning=true;bool dead=pose.follower.GetComponent<EnemyScript_space>().IsDead;File.WriteAllText(Path.Combine(folder,"result.json"),Json(new{completed=error==null,error,maxHandToElbowGap=maxGap,pauseDrift,validFrames,deadStopsLink=dead&&!pose.follower.CanAct,passed=error==null&&maxGap<.10f&&pauseDrift<.001f&&dead&&!pose.follower.CanAct,samples=rows,conditions="Directed real Play fixture: place player away and activate the authored pair through Encounter.Tick, disable player firing only, run actual role movement/own Animator/arm IK for eight seconds with pause/resume/death. No ordinary-route claim."}));}
}
