using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEngine.Rendering;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine.SceneManagement;using TMPro;using Object=UnityEngine.Object;
// Incremental visual-only Ch5 edit. Existing colliders, route, actors, camera,
// lifts and shared source assets are deliberately never assigned or edited.
public static class ApplyToon19 {
 const string A="Assets/ShooterSurvival/Models/Chapters/Chapters45/Ch5Toon20261004";
 const string Record="outputs/ch5-toon-2026-10-04";
 static readonly Dictionary<string,Material> mats=new();static readonly Dictionary<string,Mesh> meshes=new();static readonly List<object> remaps=new();
 static Material cream,ivory,coral,peach,teal,deep,leaf,gold,glass;static int hidden,shops;static Transform root;
 static string Json(object o)=>(string)AppDomain.CurrentDomain.GetAssemblies().First(a=>a.GetName().Name=="Newtonsoft.Json").GetType("Newtonsoft.Json.JsonConvert").GetMethod("SerializeObject",new[]{typeof(object)}).Invoke(null,new[]{o});
 static Color C(string hex){ColorUtility.TryParseHtmlString("#"+hex,out var c);return c;}
 static Material Mat(string name,string hex){if(mats.TryGetValue(name,out var m))return m;string path=A+"/"+name+".mat";m=AssetDatabase.LoadAssetAtPath<Material>(path);if(m==null){m=new Material(Shader.Find("FlatKit/Stylized Surface")){name=name,enableInstancing=true};m.SetColor("_BaseColor",C(hex));m.SetColor("_ColorDim",new Color(.82f,.78f,.72f,1));m.SetFloat("_CelPrimaryMode",1);m.EnableKeyword("_CELPRIMARYMODE_SINGLE");m.SetFloat("_SelfShadingSize",.5f);m.SetFloat("_ShadowEdgeSize",.12f);m.SetFloat("_Flatness",.6f);m.SetFloat("_LightContribution",.06f);m.SetFloat("_TextureImpact",0);m.SetColor("_EmissionColor",Color.black);m.DisableKeyword("_EMISSION");m.SetFloat("_UnityShadowMode",1);m.EnableKeyword("_UNITYSHADOWMODE_MULTIPLY");m.SetFloat("_UnityShadowPower",.23f);m.SetFloat("_UnityShadowSharpness",1.5f);AssetDatabase.CreateAsset(m,path);}mats[name]=m;return m;}
 static void Palette(){cream=Mat("Cream warm structure","F6DCAF");ivory=Mat("Ivory lit trim","FFF0D1");coral=Mat("Coral signage and floor","DC806B");peach=Mat("Peach floor diamonds","F0B69A");teal=Mat("Teal painted trim","477E7B");deep=Mat("Deep teal recess","244F50");leaf=Mat("Leaf green","628653");gold=Mat("Warm metal satin","DDBA84");glass=Mat("Teal translucent glazing","639B94");if(glass.GetFloat("_Surface")==0){glass.SetColor("_BaseColor",new Color(.35f,.61f,.57f,.52f));glass.SetFloat("_Surface",1);glass.SetInt("_SrcBlend",(int)BlendMode.SrcAlpha);glass.SetInt("_DstBlend",(int)BlendMode.OneMinusSrcAlpha);glass.SetInt("_ZWrite",0);glass.SetInt("_Cull",(int)CullMode.Off);glass.renderQueue=3000;glass.EnableKeyword("_SURFACE_TYPE_TRANSPARENT");EditorUtility.SetDirty(glass);}}
 static Transform Group(Transform p,string name){var t=new GameObject(name).transform;t.SetParent(p,false);return t;}
 static Mesh Mesh(string key,Func<Mesh> create){if(meshes.TryGetValue(key,out var m))return m;m=AssetDatabase.LoadAssetAtPath<Mesh>(A+"/"+key+".asset");if(m==null){m=create();m.name=key;AssetDatabase.CreateAsset(m,A+"/"+key+".asset");}meshes[key]=m;return m;}
 static GameObject MeshObject(Transform p,string name,Mesh mesh,Material mat,Vector3 pos){var g=Group(p,name).gameObject;g.transform.localPosition=pos;g.AddComponent<MeshFilter>().sharedMesh=mesh;var r=g.AddComponent<MeshRenderer>();r.sharedMaterial=mat;r.shadowCastingMode=ShadowCastingMode.Off;r.receiveShadows=true;return g;}
 static GameObject Box(Transform p,string n,Vector3 pos,Vector3 scale,Material mat){var g=GameObject.CreatePrimitive(PrimitiveType.Cube);g.name=n;g.transform.SetParent(p,false);g.transform.localPosition=pos;g.transform.localScale=scale;Object.DestroyImmediate(g.GetComponent<Collider>());g.GetComponent<MeshRenderer>().sharedMaterial=mat;g.GetComponent<MeshRenderer>().shadowCastingMode=ShadowCastingMode.Off;return g;}
 static GameObject Cylinder(Transform p,string n,Vector3 pos,Vector3 scale,Material mat){var g=GameObject.CreatePrimitive(PrimitiveType.Cylinder);g.name=n;g.transform.SetParent(p,false);g.transform.localPosition=pos;g.transform.localScale=scale;Object.DestroyImmediate(g.GetComponent<Collider>());g.GetComponent<MeshRenderer>().sharedMaterial=mat;g.GetComponent<MeshRenderer>().shadowCastingMode=ShadowCastingMode.Off;return g;}
 static Vector3 Polar(float r,float a,float y=0){a*=Mathf.Deg2Rad;return new Vector3(r*Mathf.Cos(a),y,r*Mathf.Sin(a));}
 static List<Vector2> Contour(float w,float h,float rad,bool topOnly=false){var p=new List<Vector2>();for(int q=0;q<4;q++){float r=topOnly&&q>=2?.08f:rad;float cx=q==0||q==3?w/2-r:-w/2+r,cy=q<2?h/2-r:-h/2+r;for(int j=0;j<=8;j++){float a=(q*90+j*90f/8)*Mathf.Deg2Rad;p.Add(new Vector2(cx+r*Mathf.Cos(a),cy+r*Mathf.Sin(a)));}}return p;}
 static Mesh Rounded(float w,float h,float rad,float depth,float border=0,bool topOnly=false){var a=Contour(w,h,rad,topOnly);var v=new List<Vector3>();var tr=new List<int>();Action<Vector3,Vector3,Vector3,Vector3> quad=(p0,p1,p2,p3)=>{int n=v.Count;v.AddRange(new[]{p0,p1,p2,p3});tr.AddRange(new[]{n,n+1,n+2,n,n+2,n+3});};
  if(border>0){var b=Contour(w-2*border,h-2*border,Mathf.Max(.05f,rad-border),topOnly);for(int i=0;i<a.Count;i++){int j=(i+1)%a.Count;Vector3 af=new(a[i].x,a[i].y,depth/2),an=new(a[j].x,a[j].y,depth/2),bf=new(b[i].x,b[i].y,depth/2),bn=new(b[j].x,b[j].y,depth/2);quad(af,an,bn,bf);quad(af-Vector3.forward*depth,bf-Vector3.forward*depth,bn-Vector3.forward*depth,an-Vector3.forward*depth);quad(af-Vector3.forward*depth,an-Vector3.forward*depth,an,af);quad(bf,bn,bn-Vector3.forward*depth,bf-Vector3.forward*depth);}}
  else{for(int i=0;i<a.Count;i++){int j=(i+1)%a.Count;Vector3 x=new(a[i].x,a[i].y,depth/2),y=new(a[j].x,a[j].y,depth/2);int n=v.Count;v.AddRange(new[]{Vector3.forward*depth/2,x,y,-Vector3.forward*depth/2,y-Vector3.forward*depth,x-Vector3.forward*depth});tr.AddRange(new[]{n,n+1,n+2,n+3,n+4,n+5});quad(x-Vector3.forward*depth,y-Vector3.forward*depth,y,x);}}
  var m=new Mesh();m.SetVertices(v);m.SetTriangles(tr,0);m.RecalculateNormals();m.RecalculateBounds();return m;}
 static Mesh Band(float ri,float ro,float y){var v=new List<Vector3>();var tr=new List<int>();for(int i=0;i<=192;i++){v.Add(Polar(ri,i*360f/192,y));v.Add(Polar(ro,i*360f/192,y));}for(int i=0;i<192;i++){int n=i*2;tr.AddRange(new[]{n,n+2,n+1,n+1,n+2,n+3});}var m=new Mesh();m.SetVertices(v);m.SetTriangles(tr,0);m.RecalculateNormals();return m;}
 static Mesh Rail(float radius,float y,float height){var v=new List<Vector3>();var tr=new List<int>();for(int i=0;i<=192;i++){v.Add(Polar(radius,i*360f/192,y));v.Add(Polar(radius,i*360f/192,y+height));}for(int i=0;i<192;i++){int n=i*2;tr.AddRange(new[]{n,n+1,n+2,n+1,n+3,n+2});}var m=new Mesh();m.SetVertices(v);m.SetTriangles(tr,0);m.RecalculateNormals();return m;}
 static Material Remap(Material src,string objectName){if(src==null||src.shader==null||src.shader.name.Contains("TextMeshPro")||src.shader.name.Contains("Sprites")||AssetDatabase.GetAssetPath(src).StartsWith(A))return src;string n=src.name.ToLowerInvariant(),obj=objectName.ToLowerInvariant();if(n.Contains("glass")||n.Contains("glazing"))return glass;if(n.Contains("limestone")||n.Contains("pearl stone"))return cream;if(n.Contains("porcelain")||n=="ceiling"||n.Contains("ivory")||n.Contains("white sole"))return ivory;if(n.Contains("champagne")||n.Contains("bronze mullion")||n.Contains("warm oak"))return gold;if(n.Contains("teal"))return teal;if(n.Contains("graphite"))return deep;if(n.Contains("joint"))return Mat("Soft warm floor joint","D5B98F");if(n.Contains("daylight"))return Mat("Warm skylight diffuser","FFF3D6");if(n.Contains("shop light"))return ivory;if(n.Contains("planter soil"))return Mat("Soil","534D3B");
  string guid=AssetDatabase.AssetPathToGUID(AssetDatabase.GetAssetPath(src));if(string.IsNullOrEmpty(guid))return src;string key="Isolated-"+guid;string path=A+"/"+key+".mat";if(mats.TryGetValue(key,out var cached))return cached;var m=AssetDatabase.LoadAssetAtPath<Material>(path);if(m==null){m=new Material(src){name="Ch5 toon "+src.name,enableInstancing=true};Color old=src.HasProperty("_BaseColor")?src.GetColor("_BaseColor"):Color.white;Texture tex=src.HasProperty("_BaseMap")?src.GetTexture("_BaseMap"):null;m.shader=Shader.Find("FlatKit/Stylized Surface");m.SetColor("_BaseColor",old);m.SetColor("_ColorDim",new Color(.82f,.79f,.73f,1));m.SetFloat("_CelPrimaryMode",1);m.EnableKeyword("_CELPRIMARYMODE_SINGLE");m.SetFloat("_ShadowEdgeSize",.1f);m.SetFloat("_Flatness",.6f);m.SetFloat("_LightContribution",.05f);m.SetFloat("_TextureImpact",tex!=null?.78f:0);if(tex!=null)m.SetTexture("_BaseMap",tex);m.SetFloat("_DetailMapImpact",0);m.SetTexture("_BumpMap",null);m.DisableKeyword("_NORMALMAP");m.SetFloat("_UnityShadowMode",1);m.EnableKeyword("_UNITYSHADOWMODE_MULTIPLY");m.SetFloat("_UnityShadowPower",.22f);AssetDatabase.CreateAsset(m,path);remaps.Add(new{source=AssetDatabase.GetAssetPath(src),clone=path,retainedTexture=AssetDatabase.GetAssetPath(tex)});}mats[key]=m;return m;}
 static void Style(Transform t){foreach(var r in t.GetComponentsInChildren<Renderer>(true)){if(r is SkinnedMeshRenderer||r.GetComponent<TMP_Text>()!=null||r.GetComponent<TMP_SubMesh>()!=null)continue;r.sharedMaterials=r.sharedMaterials.Select(m=>Remap(m,r.name)).ToArray();}}
 static void Hide(Renderer r){if(r.enabled){r.enabled=false;hidden++;}}
 static void BuildShop(Transform shop,int floor,int index){shops++;bool already=shop.Find("Toon rounded storefront 19")!=null;foreach(var r in shop.GetComponentsInChildren<Renderer>(true)){if(new[]{"Brass lintel","Deep ivory storefront fascia","Timber portal left","Timber portal right","Clear display glazing"}.Contains(r.name))Hide(r);}
  var g=Group(shop,already?"Toon rounded storefront 19 revision2":"Toon rounded storefront 19");var arch=Mesh("Portal-top-rounded-v2",()=>Rounded(5.9f,6.6f,1.1f,.52f,.36f,true));var back=Mesh("Window-recess-top-rounded-v2",()=>Rounded(5.25f,5.8f,.85f,.16f,0,true));var header=Mesh("Coral-round-header",()=>Rounded(5.25f,1.65f,.52f,.22f));
  for(int j=-1;j<=1;j++){float x=j*5.85f;MeshObject(g,"Thick rounded cream portal",arch,ivory,new Vector3(x,3.3f,5.65f));MeshObject(g,"Teal recessed window background",back,(index+j)%3==0?teal:deep,new Vector3(x,2.95f,.8f));MeshObject(g,"Coral store sign panel",header,(index+j)%4==0?teal:coral,new Vector3(x,5.35f,5.55f));Box(g,"Deep window soffit",new Vector3(x,4.48f,3),new Vector3(5.2f,.12f,5),teal);Box(g,"Recessed left jamb",new Vector3(x-2.6f,2.3f,3),new Vector3(.12f,4.3f,5),teal);Box(g,"Recessed right jamb",new Vector3(x+2.6f,2.3f,3),new Vector3(.12f,4.3f,5),teal);Box(g,"Cream window sill",new Vector3(x,.2f,5.32f),new Vector3(5.2f,.18f,.4f),cream);
   if(j!=0){var sign=Group(g,"Simple category emblem");sign.localPosition=new Vector3(x,5.3f,5.69f);if(floor==1||floor==4){MeshObject(sign,"Bag silhouette",Mesh("Bag-emblem",()=>Rounded(.7f,.58f,.08f,.015f)),ivory,Vector3.zero);MeshObject(sign,"Bag handle",Mesh("Bag-handle",()=>Rounded(.32f,.32f,.15f,.018f,.035f)),ivory,new Vector3(0,.31f,0));}else if(floor==2){Box(sign,"Shirt body",Vector3.zero,new Vector3(.45f,.65f,.018f),ivory);var sleeves=Box(sign,"Shirt sleeves",new Vector3(0,.21f,0),new Vector3(.85f,.22f,.018f),ivory);}else{MeshObject(sign,"Category label plaque",Mesh("Small-emblem-oval",()=>Rounded(.9f,.4f,.19f,.02f)),ivory,Vector3.zero);}}
  }
  for(int k=0;k<4;k++){float x=-8.8f+k*5.86f;Cylinder(g,"Rounded cream pier",new Vector3(x,2.8f,5.55f),new Vector3(.66f,2.8f,.66f),cream);Cylinder(g,"Pier warm capital",new Vector3(x,4.5f,5.55f),new Vector3(.77f,.13f,.77f),ivory);Cylinder(g,"Pier teal foot",new Vector3(x,.2f,5.55f),new Vector3(.72f,.2f,.72f),teal);}
  var title=shop.Find("Fictional store name")?.GetComponent<TMP_Text>();if(title!=null){title.transform.localPosition=new Vector3(0,5.34f,5.74f);title.fontSize=4.8f;title.color=C("FFF0D1");}
  // Reuse verified goods, promote them into the visible window, without moving gameplay.
  foreach(var t in shop.Cast<Transform>().Where(t=>t.name.StartsWith("RetailTote reused")||t.name.StartsWith("RetailSneaker reused")||t.name=="Fitted retail case base").ToArray()){var p=t.localPosition;if(!already)p.z+=2.1f;if(t.name.StartsWith("RetailTote")||t.name.StartsWith("RetailSneaker")){t.localScale*=1.2f;p.y+=.4f;}else{t.localScale=new Vector3(t.localScale.x,t.localScale.y*1.4f,t.localScale.z);}t.localPosition=p;}
  var plant=shop.GetComponentsInChildren<MeshFilter>(true).FirstOrDefault(t=>t.name=="Reused TRELLIS planter greenery");
  foreach(float x in new[]{-8.25f,8.25f}){Cylinder(g,"Rounded cream planter",new Vector3(x,.5f,6.15f),new Vector3(1.12f,.5f,1.12f),cream);Cylinder(g,"Teal planter foot",new Vector3(x,.12f,6.15f),new Vector3(1.13f,.12f,1.13f),teal);if(plant!=null){var copy=MeshObject(g,"Reused TRELLIS foliage",plant.sharedMesh,plant.GetComponent<Renderer>().sharedMaterial,new Vector3(x,1,6.15f));copy.transform.localRotation=plant.transform.localRotation;copy.transform.localScale=plant.transform.localScale*1.2f;var b=copy.GetComponent<Renderer>().bounds;copy.transform.position+=g.TransformPoint(new Vector3(x,.40f,6.15f))-new Vector3(b.center.x,b.min.y,b.center.z);}}
  foreach(float x in new[]{-5.85f,0,5.85f}){Box(g,"Window slim teal left frame",new Vector3(x-2.5f,2.45f,5.44f),new Vector3(.09f,3.85f,.09f),teal);Box(g,"Window top teal frame",new Vector3(x,4.4f,5.44f),new Vector3(5.1f,.11f,.09f),teal);}

 }
 static void Floor(Transform f,int number){if(f.Find("Toon floor detail 19")!=null)throw new Exception("Floor already applied: "+number);Style(f);var g=Group(f,"Toon floor detail 19");if(number!=6){foreach(var r in f.GetComponentsInChildren<Renderer>(true).Where(r=>r.name=="Curved glass balustrade"||r.name=="Brushed rail"||r.name=="Warm walkway tile seam"))Hide(r);
   MeshObject(g,"Curved continuous teal glass",Mesh("Continuous-balustrade",()=>Rail(20,.08f,1.16f)),glass,Vector3.zero);MeshObject(g,"Cream rounded balcony cap",Mesh("Balcony-cap",()=>Band(19.86f,20.14f,1.28f)),ivory,Vector3.zero);MeshObject(g,"Teal rail foot",Mesh("Balcony-foot",()=>Band(19.90f,20.10f,.06f)),teal,Vector3.zero);
   for(int i=0;i<48;i++)Cylinder(g,"Slender teal rail post",Polar(20,i*7.5f,.63f),new Vector3(.07f,.63f,.07f),teal);
   MeshObject(g,"Coral outer promenade border",Mesh("Promenade-outer",()=>Band(33.4f,35.1f,.045f)),coral,Vector3.zero);MeshObject(g,"Coral inner promenade border",Mesh("Promenade-inner",()=>Band(24,25.6f,.042f)),coral,Vector3.zero);
   var v=new List<Vector3>();var tr=new List<int>();for(int i=0;i<12;i++){int n=v.Count;float a=i*30;v.AddRange(new[]{Polar(25.6f,a,.041f),Polar(33.4f,a+6,.041f),Polar(33.4f,a+12,.041f),Polar(25.6f,a+17,.041f)});tr.AddRange(new[]{n,n+3,n+1,n+1,n+3,n+2});}MeshObject(g,"Warm geometric floor rhythm",Mesh("Promenade-diamonds",()=>{var m=new Mesh();m.SetVertices(v);m.SetTriangles(tr,0);m.RecalculateNormals();return m;}),peach,Vector3.zero);
   int index=0;foreach(var s in f.Cast<Transform>().Where(t=>t.name.Contains(" storefront ")).ToArray())BuildShop(s,number,index++);
  }
  foreach(var s in f.Cast<Transform>().Where(t=>t.name.Contains(" storefront ")).ToArray()){var visual=s.Find("Toon rounded storefront 19");if(visual!=null)Combine(visual,"store"+number+"-"+shops+"-"+s.GetSiblingIndex());}Combine(g,"floor"+number);
 }
 static void Combine(Transform g,string key){var renderers=g.GetComponentsInChildren<MeshRenderer>(true).ToArray();foreach(var group in renderers.GroupBy(r=>r.sharedMaterial)){var parts=group.Select(r=>new CombineInstance{mesh=r.GetComponent<MeshFilter>().sharedMesh,transform=g.worldToLocalMatrix*r.transform.localToWorldMatrix}).ToArray();var combined=new Mesh{name="Toon batched "+key+" "+group.Key.name,indexFormat=IndexFormat.UInt32};combined.CombineMeshes(parts,true,true);string path=A+"/Batch-"+key+"-"+group.Key.name+".asset";if(File.Exists(path))throw new Exception("Do not overwrite earlier mesh batch");AssetDatabase.CreateAsset(combined,path);MeshObject(g,"Batched "+group.Key.name,combined,group.Key,Vector3.zero);}foreach(var r in renderers)Object.DestroyImmediate(r.gameObject);}
 public static object RefineRepresentative(){if(EditorApplication.isPlayingOrWillChangePlaymode||SceneManager.GetActiveScene().isDirty)throw new Exception("Clean Edit only");string snap=Record+"/recovery-before-representative-v2.unity";if(File.Exists(snap))throw new Exception("Already revised");File.Copy(SceneManager.GetActiveScene().path,snap,false);mats.Clear();meshes.Clear();Palette();var f=GameObject.Find("Chapter45_World/DetailedMall_20261003/Scenery").transform.Cast<Transform>().Single(t=>t.name.StartsWith("1F ")&&t.name.Contains(" · "));int i=0;foreach(var shop in f.Cast<Transform>().Where(t=>t.name.Contains(" storefront ")).ToArray()){var old=shop.Find("Toon rounded storefront 19");foreach(var r in old.GetComponentsInChildren<Renderer>(true))r.enabled=false;BuildShop(shop,1,i++);Combine(shop.Find("Toon rounded storefront 19 revision2"),"revision2-store-"+i);}EditorSceneManager.MarkSceneDirty(SceneManager.GetActiveScene());EditorSceneManager.SaveScene(SceneManager.GetActiveScene());return new{revisedShops=i,originalCollidersUntouched=true};}
 public static object Main(string scope){if(EditorApplication.isPlayingOrWillChangePlaymode||EditorApplication.isCompiling||EditorApplication.isUpdating||SceneManager.GetActiveScene().isDirty||PrefabStageUtility.GetCurrentPrefabStage()!=null)throw new Exception("Clean Edit only");if(SceneManager.GetActiveScene().name!="ShoeTower")throw new Exception("Existing ShoeTower only");root=GameObject.Find("Chapter45_World/DetailedMall_20261003").transform;if(root==null)throw new Exception("Expected existing mall");string snapshot=Record+"/recovery-before-"+scope+".unity";if(File.Exists(snapshot))throw new Exception("Preserve recovery and inspect already applied scope");File.Copy(SceneManager.GetActiveScene().path,snapshot,false);Directory.CreateDirectory(A);AssetDatabase.Refresh();mats.Clear();meshes.Clear();remaps.Clear();hidden=shops=0;Palette();var scenery=root.Find("Scenery");var floors=scenery.Cast<Transform>().Where(t=>t.GetComponent<Chapter45SceneryGroup>()!=null&&t.name.Contains(" · ")).ToArray();var selected=scope=="representative"?floors.Where(t=>t.name.StartsWith("1F ")).ToArray():floors.Where(t=>!t.name.StartsWith("1F ")).ToArray();foreach(var f in selected){int number=f.GetComponent<Chapter45SceneryGroup>().floor;Floor(f,number);}
  foreach(var t in scenery.Cast<Transform>().Where(t=>scope=="representative"?t.name.StartsWith("1F curved ceiling"):!t.name.Contains(" · ")&&!t.name.StartsWith("1F curved ceiling")).ToArray())Style(t);
  if(scope!="representative")foreach(var lift in root.GetComponentsInChildren<Chapter45Lift>(true))Style(lift.transform);
  foreach(var m in mats.Values)AssetDatabase.SaveAssetIfDirty(m);EditorSceneManager.MarkSceneDirty(SceneManager.GetActiveScene());if(!EditorSceneManager.SaveScene(SceneManager.GetActiveScene()))throw new Exception("Save failed");var result=new{scope,assets=A,floors=selected.Select(f=>f.name).ToArray(),shops,hiddenOldRenderers=hidden,clonedSourceMaterials=remaps,newGeometry="Native rounded extrusions, cylinder piers, continuous curved glass, shared combined per-material meshes, inlaid floor bands",generatedAIModels=0,newPaidCredits=0,sharedOriginalsEdited=false,cameraOrGameplayChanged=false};File.WriteAllText(Record+"/applied-"+scope+".json",Json(result));return result;}
}
