using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEngine.Rendering;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine.SceneManagement;using Object=UnityEngine.Object;
public static class DressToon19 {
 const string A="Assets/ShooterSurvival/Models/Chapters/Chapters45/Ch5Toon20261004";static int index;static Material ivory,coral,teal;static Transform G(Transform p,string n){var t=new GameObject(n).transform;t.SetParent(p,false);return t;}
 static GameObject Cylinder(Transform p,string n,Vector3 pos,Vector3 scale,Material m){var g=GameObject.CreatePrimitive(PrimitiveType.Cylinder);g.name=n;g.transform.SetParent(p,false);g.transform.localPosition=pos;g.transform.localScale=scale;Object.DestroyImmediate(g.GetComponent<Collider>());g.GetComponent<Renderer>().sharedMaterial=m;g.GetComponent<Renderer>().shadowCastingMode=ShadowCastingMode.Off;return g;}
 static Vector3 P(float r,float a,float y=0){a*=Mathf.Deg2Rad;return new Vector3(r*Mathf.Cos(a),y,r*Mathf.Sin(a));}
 static void Batch(Transform root,string key){var rr=root.GetComponentsInChildren<MeshRenderer>().ToArray();foreach(var group in rr.GroupBy(r=>r.sharedMaterial)){var m=new Mesh{indexFormat=IndexFormat.UInt32};m.CombineMeshes(group.Select(r=>new CombineInstance{mesh=r.GetComponent<MeshFilter>().sharedMesh,transform=root.worldToLocalMatrix*r.transform.localToWorldMatrix}).ToArray());AssetDatabase.CreateAsset(m,A+"/Dressing-"+key+"-"+(index++)+".asset");var g=G(root,"Batched dressing "+group.Key.name);g.gameObject.AddComponent<MeshFilter>().sharedMesh=m;var r=g.gameObject.AddComponent<MeshRenderer>();r.sharedMaterial=group.Key;r.shadowCastingMode=ShadowCastingMode.Off;}foreach(var r in rr)Object.DestroyImmediate(r.gameObject);}
 static void Product(Transform parent,MeshFilter source,Vector3 basePoint,float targetHeight,Material material){var g=G(parent,"Reused verified display good");g.gameObject.AddComponent<MeshFilter>().sharedMesh=source.sharedMesh;var r=g.gameObject.AddComponent<MeshRenderer>();r.sharedMaterial=material;r.shadowCastingMode=ShadowCastingMode.Off;g.localRotation=source.transform.localRotation;g.localScale=source.transform.localScale;var b=r.bounds;g.localScale*=targetHeight/Mathf.Max(.01f,b.size.y);b=r.bounds;g.position+=parent.TransformPoint(basePoint)-new Vector3(b.center.x,b.min.y,b.center.z);}
 static Mesh Ribbon(float inner,float outer,float bottom,float top){var v=new List<Vector3>();var tr=new List<int>();for(int i=0;i<192;i++){float a=i*360f/192,b=(i+1)*360f/192;foreach(var quad in new[]{new[]{P(inner,a,bottom),P(inner,b,bottom),P(outer,b,bottom),P(outer,a,bottom)},new[]{P(inner,a,bottom),P(inner,a,top),P(inner,b,top),P(inner,b,bottom)},new[]{P(outer,a,bottom),P(outer,b,bottom),P(outer,b,top),P(outer,a,top)}}){int n=v.Count;v.AddRange(quad);tr.AddRange(new[]{n,n+2,n+1,n,n+3,n+2,n,n+1,n+2,n,n+2,n+3});}}var m=new Mesh();m.SetVertices(v);m.SetTriangles(tr,0);m.RecalculateNormals();return m;}
 public static object Main(string scope){if(EditorApplication.isPlayingOrWillChangePlaymode||SceneManager.GetActiveScene().isDirty)throw new Exception("Clean Edit only");string rec="outputs/ch5-toon-2026-10-04/recovery-before-dress-"+scope+".unity";if(File.Exists(rec))throw new Exception("Preserve existing dressing");File.Copy(SceneManager.GetActiveScene().path,rec,false);ivory=AssetDatabase.LoadAssetAtPath<Material>(A+"/Ivory lit trim.mat");coral=AssetDatabase.LoadAssetAtPath<Material>(A+"/Coral signage and floor.mat");teal=AssetDatabase.LoadAssetAtPath<Material>(A+"/Teal painted trim.mat");var scenery=GameObject.Find("Chapter45_World/DetailedMall_20261003/Scenery").transform;int stores=0;var floors=scenery.Cast<Transform>().Where(t=>t.name.Contains(" · ")&&(scope=="representative"?t.name.StartsWith("1F "):!t.name.StartsWith("1F "))).ToArray();foreach(var floor in floors){int f=floor.GetComponent<Chapter45SceneryGroup>().floor;foreach(var shop in floor.Cast<Transform>().Where(t=>t.name.Contains(" storefront ")).ToArray()){var g=G(shop,"Toon curated window accents 19");if(f==1||f==7){var goods=shop.Cast<Transform>().Where(t=>t.name.StartsWith(f==1?"RetailTote reused":"RetailSneaker reused")).ToArray();foreach(var t in shop.Cast<Transform>().Where(t=>t.name=="Fitted retail case base"))foreach(var r in t.GetComponentsInChildren<Renderer>())r.enabled=false;int j=0;foreach(var good in goods){var source=good.GetComponentInChildren<MeshFilter>();float x=(j-1)*5.85f,height=j==1?1.6f:1.2f;foreach(var r in good.GetComponentsInChildren<Renderer>())r.enabled=false;Cylinder(g,"Tall rounded cream display",new Vector3(x,height/2,3.8f),new Vector3(1.5f,height/2,1.5f),ivory);Product(g,source,new Vector3(x,height+.02f,3.8f),f==1?.85f:.48f,source.GetComponent<Renderer>().sharedMaterial);Cylinder(g,"Low coral display",new Vector3(x+1.4f,.42f,3.5f),new Vector3(.95f,.42f,.95f),coral);Product(g,source,new Vector3(x+1.4f,.86f,3.5f),f==1?.65f:.38f,source.GetComponent<Renderer>().sharedMaterial);j++;}}
    Batch(g,"floor"+f+"-shop"+(stores++));}
   if(f!=6){var g=G(floor,"Toon curved ceiling cornice 19");foreach(float r in new[]{25.8f,34.7f}){var mesh=Ribbon(r-.18f,r+.18f,7.04f,7.28f);AssetDatabase.CreateAsset(mesh,A+"/Cornice-floor"+f+"-r"+r+".asset");var t=G(g,"Cream curved ceiling reveal");t.gameObject.AddComponent<MeshFilter>().sharedMesh=mesh;t.gameObject.AddComponent<MeshRenderer>().sharedMaterial=ivory;}for(int j=0;j<24;j++){Cylinder(g,"Recessed warm circular ceiling light",P(34,j*15,7.12f),new Vector3(.5f,.035f,.5f),ivory);}Batch(g,"ceiling"+f);}
  }
  if(scope=="representative"){var paths=AssetDatabase.FindAssets("t:Mesh",new[]{A}).Select(AssetDatabase.GUIDToAssetPath).Where(p=>p.Contains("Batch-revision2-store-")&&p.Contains("MallPlant")).ToArray();foreach(var path in paths){var m=AssetDatabase.LoadAssetAtPath<Mesh>(path);m.vertices=m.vertices.Select(v=>v-Vector3.up*.62f).ToArray();m.RecalculateBounds();EditorUtility.SetDirty(m);AssetDatabase.SaveAssetIfDirty(m);}}
  EditorSceneManager.MarkSceneDirty(SceneManager.GetActiveScene());EditorSceneManager.SaveScene(SceneManager.GetActiveScene());return new{scope,floors=floors.Length,stores,geometry="Curated reused goods on varied cylindrical plinths; curved ceiling cornices; duplicate planter base concealed",collidersAdded=0,paidGeneration=0};}
}
